<h1>Affiliate Commission Details for <?php echo amDate($date) ?></h1>

<?php if ($commissions):?>
<h4>Commissions</h4>
<div class="grid-container">
<table class="hedit">
<tr>
    <th class="bold align-right">Amount</th>
    <th class="bold align-right">Record Type</th>
    <th class="bold align-right">Payment#/Receipt#</th>
    <th class="bold align-right">User</th>
    <th class="bold align-right">Product(s)</th>
</tr>
<?php 
foreach ($commissions as $c): 
/* @var $c Aff_Commission */    
    $p = $c->getPayment();
    if ($p) $invoice = $p->getInvoice();
    if ($p) $user = Am_Di::getInstance()->userTable->load($p->user_id);
    
    printf("<tr><td>%.2f</td><td>%s</td><td>%s/%s</td>
            <td>%s</td><td>%s</td>
            </tr>\n",
            $c->amount, 
            $c->record_type,
            $c->payment_id, $c->receipt_id,
            $user ? sprintf('%s : "%s" &lt;%s&gt;', 
                $this->escape($user->login),
                $this->escape($user->name_f . " " . $user->name_l),
                $this->escape($user->email)): "-",
            "---"
            );
endforeach;
?>
</table>
</div>
<?php endif; ?>


<?php if ($clicks):?>
<h4>Clicks</h4>
<div class="grid-container">
<table class="grid">
<tr>
    <th class="bold align-right">Time</th>
    <th class="bold align-right">IP</th>
    <th class="bold align-right">URL</th>
    <th class="bold align-right">Referer</th>
</tr>
<?php 
foreach ($clicks as $c): 
    printf("<tr><td>%s</td><td>%s</td>
            <td><a href='%s' target='blank'>%s</a></td>
            <td><a href='%s' target='blank'>%s</a></td>
            </tr>\n",
            amDateTime($c->time),
            $this->escape($c->remote_addr),
            $this->escape($c->url), $this->escape($c->url),
            $this->escape($c->referrer), $this->escape($c->referrer)
            );
endforeach;
?>
</table>
</div>
<?php endif; ?>
