<?php
/**
 * es.php
 * Spanish Language File
 * @package  aMember_Core
 * @version  $Id: es.php 5320 2010-09-15 06:04:44Z barfly $
 * @license  http://www.amember.com/p/Main/License
 * @copyright Copyright &copy; 2006, Alex Scott
 * DO NOT EDIT THIS FILE FOR CUSTOMIZATION, READ readme.txt for details
 */

defined( 'INCLUDED_AMEMBER_CONFIG' ) or die( 'El acceso directo a este archivo no est&aacute; permitido.' );

define ('_TPL_POWEREDBY', 'Powered by %saMember Pro%s membership software');

define('_TPL_INDEX_IF_YOU_ARE_REGISTERED', 'Si eres un usuario registrado, favor %slogin%s');
define('_TPL_INDEX_IF_YOU_ARE_NOT_REGISTERED', 'Si a&uacute;n no estas registrado, favor %ssignup%s');
define('_TPL_LOGIN_PLEASE_LOGIN', 'Favor iniciar sesi&oacute;n');
define('_TPL_LOGIN_USERNAME', 'Usuario');
define('_TPL_LOGIN_PASSWORD', 'Contrase&ntilde;a');
define('_TPL_LOGIN_REMEMBER_MY_PASSWORD', 'Recordar contrase&ntilde;a?');
define('_TPL_LOGIN_NOT_REGISTERED_YET', 'Sin membres&iacute;a?');
define('_TPL_LOGIN_SIGNUP_HERE', 'Registr&aacute;te aqu&iacute;');
define('_TPL_LOGIN_LOST_PASSWORD', 'Olvid&oacute; la contrase&ntilde;a');
define('_TPL_LOGIN_ENTER_YOUR_EMAIL_OR_USERNAME', 'Introduce tu <b>Direcci&oacute;n de Correo</b> o tu <b>Usuario</b>');
define('_TPL_LOGIN_BTN_LOGIN', 'Iniciar Sesi&oacute;n');
define('_TPL_LOGIN_BTN_BACK', 'Volver');
define('_TPL_LOGIN_BTN_GET_PASSWORD', 'Obtener contrase&ntilde;a');

define ('_TPL_SIGNUP_MEM_TYPE', 'Seleccione un tipo de membres&iacute;a');
define ('_TPL_SIGNUP_TITLE', 'Registr&aacute;te');
define ('_TPL_AFF_SIGNUP_TITLE', 'Registro de Afiliados');
define ('_TPL_SIGNUP_MEMB_TYPE', 'Tipo de membres&iacute;a');
define ('_TPL_SIGNUP_FREE', 'gratis');
define ('_TPL_SIGNUP_SELECT_PSYS', 'Seleccione el sistema de pago');
define ('_TPL_SIGNUP_PAYSYS', 'Sistema de Pago');
define ('_TPL_SIGNUP_NAME', 'Tu nombre');
define ('_TPL_SIGNUP_NAME_1', 'Tus Nombres y Apellidos');
define ('_TPL_SIGNUP_EMAIL', 'Tu direcci&oacute;n de Correo');
define ('_TPL_SIGNUP_EMAIL_1', 'Un correo de confirmaci&oacute;n ser&aacute; enviado');
define ('_TPL_SIGNUP_EMAIL_2', 'a ti a esta direcci&oacute;n');
define ('_TPL_SIGNUP_LOGIN', 'Elije tu Usuario');
define ('_TPL_SIGNUP_LOGIN_1', 'Tiene que ser de %d o mas caracteres y puede');
define ('_TPL_SIGNUP_LOGIN_2', 'solo contener letras peque&ntilde;as, n&uacute;meros y');
define ('_TPL_SIGNUP_LOGIN_3', 'el \'underscore\' \'_\'');
define ('_TPL_SIGNUP_CHECK_UNIQ', 'chequear existencia');
define ('_TPL_SIGNUP_PSWD', 'Elegir una contrase&ntilde;a');
define ('_TPL_SIGNUP_PSWD_1', 'Tiene que ser de %d o m&aacute;s caracteres');
define ('_TPL_SIGNUP_CONF_PSWD', 'Confirmar contrase&ntilde;a');
define ('_TPL_SIGNUP_CONF_PSWD_1', 'Introduzca contrase&ntilde;a de nuevo');
define ('_TPL_SIGNUP_NEWSLETTERS_SUBSCRIBE', 'Suscribir a nuestros NewsLetters');
define ('_TPL_SIGNUP_NEWSLETTERS_SUBSCRIBE_1', '');
define ('_TPL_SIGNUP_ADDR', 'DIRECCION');
define ('_TPL_SIGNUP_STREET', 'Calle');
define ('_TPL_SIGNUP_CITY', 'Ciudad');
define ('_TPL_SIGNUP_STATE', 'Estado');
define ('_TPL_SIGNUP_ZIP', 'ZIP');
define ('_TPL_SIGNUP_COUNTRY', 'Pa&iacute;s');
define ('_TPL_SIGNUP_COUPONS', 'Cupones');
define ('_TPL_SIGNUP_COUPON_CODE', 'Introduzca el n&uacute;mero de cup&oacute;n');
define ('_TPL_SIGNUP_COUPON_1', 'si obtienes un n&uacute;mero de cupon desde publicidad,');
define ('_TPL_SIGNUP_COUPON_2', ' favor intrduzcalo');
define ('_TPL_SIGNUP_SUBMIT_CONTINUE', 'Continuar');

define ('_TPL_AFFILIATE_TITLE', 'Informacion de Afiliado');
define ('_TPL_AFFILIATE_TXT_LINKS', 'Puedes usar el siguiente texto para publicidad de nuestro sitio: ');
define ('_TPL_AFFILIATE_HTML_CODE', 'C&oacute;digo HTML: ');
define ('_TPL_AFFILIATE_BANNERS', 'Puedes utilizar los siguientes banners para publicidad de nuestro sitio:');
define ('_TPL_AFFILIATE_BACK2_INFO', 'Regresar a la p&aacute;gina de membres&iacute;a');

define ('_TPL_AFF_PAYOUT_TITLE', 'Cambiar informaci&oacute;n de pagos');
define ('_TPL_AFF_PAYOUT_METHOD', 'Metodo de pago');
define ('_TPL_AFF_PAYOUT_NOT_SELECTED', 'Ninguno seleccionado');
define ('_TPL_AFF_PAYOUT_PP_EMAIL', 'Tu direcci&oacute;n de correo en PayPal');
define ('_TPL_AFF_PAYOUT_STORM_EMAIL', 'Tu direcci&oacute;n de correo en StormPay');
define ('_TPL_AFF_PAYOUT_IKOBO_EMAIL', 'Tu direcci&oacute;n de correo en iKobo');
define ('_TPL_AFF_PAYOUT_MBKRS_ID', 'Tu usuario en MoneyBookers');
define ('_TPL_AFF_PAYOUT_EGOLD_ACC', 'Tu # cuenta en E-Gold');
define ('_TPL_AFF_PAYOUT_CHECK_PTO', 'Beneficiario del cheque:');

define ('_TPL_AFF_PAYOUT_STREET', 'Calle');
define ('_TPL_AFF_PAYOUT_CITY', 'Ciudad');
define ('_TPL_AFF_PAYOUT_STATE', 'Estado');
define ('_TPL_AFF_PAYOUT_ZIP', 'ZIP');
define ('_TPL_AFF_PAYOUT_COUNTRY', 'Pa&iacute;s');
define ('_TPL_AFF_PAYOUT_SAVE_BUT', 'Guardar');
define ('_TPL_AFF_PAYOUT_BACK_BUT', 'Regresar');

define ('_TPL_AFF_STATS_TITLE', 'Estadísticas de afiliado');
define ('_TPL_AFF_STATS_DISPLAY_BUT', 'Mostrar');
define ('_TPL_AFF_STATS_PERIOD', 'Estadísticas del periodo');
define ('_TPL_AFF_STATS_CLICKS', 'CLICKS');
define ('_TPL_AFF_STATS_COMMISS', 'COMISIONES');
define ('_TPL_AFF_STATS_DATE', 'Fecha');
define ('_TPL_AFF_STATS_RAW', 'Interválo');
define ('_TPL_AFF_STATS_UNIQUE', 'Unica');
define ('_TPL_AFF_STATS_TRANS', 'Transacciones');
define ('_TPL_AFF_STATS_CREDIT', 'Credito');
define ('_TPL_AFF_STATS_DEBIT', 'Debito');
define ('_TPL_AFF_STATS_TOTAL', 'Total');
define ('_TPL_AFF_STATS_TOTAL_H', 'TOTAL');
define ('_TPL_AFF_STATS_TOP20', 'Top 20 Paginas de enlace');
define ('_TPL_AFF_STATS_REFERRER', 'Paginas de enlace');
define ('_TPL_AFF_STATS_BACK', 'Regresar a la pagina de información de membresía');

define ('_TPL_AGREEMENT_TITLE', 'Contrato de usuario');
define ('_TPL_AGREEMENT_REED_AGREE', 'Por favor lea y acepte el siguiente contrato:');
define ('_TPL_AGREEMENT_AGREE', 'Acepto');
define ('_TPL_AGREEMENT_CONTINUE_BUT', 'Continuar');

define ('_TPL_CANCEL_TITLE', 'Fallo en el pago');
define ('_TPL_CANCEL_ERROR', 'Un error ocurrió al efectuar tu pago.');
define ('_TPL_CANCEL_GOTO', 'Favor regresar a la %ssign-up page%s e intenta nuevamente.');

define ('_TPL_EMAIL_VER_TITLE', 'Registro - Correo de Confirmación');
define ('_TPL_EMAIL_VER_TEXT', 'Favor revisa tu correo - un correo de confirmación fue enviado a tu bandeja de entrada. Cuando recibas este mensaje, lea y complete las instrucciones.');
define ('_TPL_EMAIL_VER_POWEREDBY', 'Soportado por %saMember Pro%s sistema de membresía');

define ('_TPL_FATAL_ERROR_TITLE', 'Un error ha ocurrido');
define ('_TPL_FATAL_ERROR_CONTACT', 'Por favor contacte al administrador: ');

define ('_TPL_MEMBER_TITLE', 'Tu información');
define ('_TPL_MEMBER_SUBSCR', 'Tus suscripciones');
define ('_TPL_MEMBER_NO_SUBSCR', 'No tienes suscripciones activas');
define ('_TPL_MEMBER_ADD_RENEW', 'Agregar/Renovar Suscripciones');
define ('_TPL_MEMBER_USE', 'Por favor use el formulario de %sAdd/Renew subscription%s ');
define ('_TPL_MEMBER_ORDER_SUBSCR', 'para ordenar o renovar una suscripción.');
define ('_TPL_MEMBER_USEFUL_LINKS', 'Enlaces correctos');
define ('_TPL_MEMBER_LOGOUT', 'Salir');
define ('_TPL_MEMBER_CH_PSWD', 'Cambiar Contraseña/Editar Perfil');
define ('_TPL_MEMBER_SELECT', '** Seleccionar Producto **');
define ('_TPL_MEMBER_SELECT2', '** Seleccionar metodo de pago **');
define ('_TPL_MEMBER_ORDER_BUT', 'Ordenar');
define ('_TPL_MEMBER_PYMNT_HIST', 'Tu historial de pagos');
define ('_TPL_MEMBER_PRODUCT', 'Producto');
define ('_TPL_MEMBER_PERIOD', 'Periodo');
define ('_TPL_MEMBER_PAYSYS', 'Sistema de pago');
define ('_TPL_MEMBER_AMOUNT', 'Cantidad');
define ('_TPL_MEMBER_CANCEL_SUBSCR', 'De verdad quieres cancelar esta suscripción?');
define ('_TPL_MEMBER_CANCEL', 'Cancelar');
define ('_TPL_MEMBER_CANCELLED', 'CANCELADA');
define ('_TPL_MEMBER_PDF_INVOICE', 'Recibo PDF');
define ('_TPL_MEMBER_INVOICE', 'Recibo');

define ('_TPL_MULT_MEMBER_TITLE', 'Tu información');
define ('_TPL_MULT_MEMBER_SUBSCR', 'Tus suscripciones');
define ('_TPL_MULT_MEMBER_NOACTSUB', 'No tienes suscripciones activas');
define ('_TPL_MULT_MEMBER_ADDREN', 'Favor usar %sAdd/Renew subscription%s form%s para ordernar o renovar suscripciones.');
define ('_TPL_MULT_MEMBER_LOGOUT', 'Salir');
define ('_TPL_MULT_MEMBER_CHPWD', 'Cambiar contraseña/Editar Perfil');
define ('_TPL_MULT_MEMBER_ADDRSUBSCR', 'Agregar/Renovar Suscripciones');
define ('_TPL_MULT_MEMBER_SELECTPM', '** Seleccionar metodo de pago **');
define ('_TPL_MULT_MEMBER_PHIST', 'Tu historial de pagos');
define ('_TPL_MULT_MEMBER_PRODUCT', 'Producto');
define ('_TPL_MULT_MEMBER_PERIOD', 'Periodo');
define ('_TPL_MULT_MEMBER_PSYS', 'Sistema de Pago');
define ('_TPL_MULT_MEMBER_AMOUNT', 'Cantidad');
define ('_TPL_MULT_MEMBER_CANCEL', 'Cancelar');
define ('_TPL_MULT_MEMBER_CANCELLED', 'Cancelada');
define ('_TPL_MULT_MEMBER_ORDERBUT', 'Ordenar');

define ('_TPL_MSGCLOSE_CLOSE', 'Cerrar esta ventana');

define ('_TPL_PROFILE_TITLE', 'Editar perfil');
define ('_TPL_PROFILE_USERNAME', 'Usuario');
define ('_TPL_PROFILE_ANOTHERUSRNM', 'Aquí puedes elegir otro usuario');
define ('_TPL_PROFILE_FLNAME', 'Nombre y Apellido');
define ('_TPL_PROFILE_EMAIL', 'Correo electronico');
define ('_TPL_PROFILE_CHPWD', 'Cambiar contraseña');
define ('_TPL_PROFILE_BLANK', 'Dejar en blanco para no efectuar cambio');
define ('_TPL_PROFILE_CONFPWD', 'Confirmar contraseña');
define ('_TPL_PROFILE_STREET', 'Calle');
define ('_TPL_PROFILE_CITY', 'Ciudad');
define ('_TPL_PROFILE_STATE', 'Estado');
define ('_TPL_PROFILE_ZIP', 'ZIP');
define ('_TPL_PROFILE_COUNTRY', 'País');
define ('_TPL_PROFILE_UNSUBSCR', 'Darme de baja');
define ('_TPL_PROFILE_NOEMAIL', 'No enviarme mensajes periodicos');
define ('_TPL_PROFILE_CHECKBOX', 'Selecciona este campo para darte de baja');
define ('_TPL_PROFILE_SAVEBUT', 'Guardar Perfil');
define ('_TPL_PROFILE_BACKBUT', 'Regresar');

define ('_TPL_PROFILE_SAVED_TITLE', 'Editar Perfil');
define ('_TPL_PROFILE_SAVED_SUCCESS', 'Tu perfil ha sido guardado correctamente.');
define ('_TPL_PROFILE_SAVED_GOBACK', 'Por favor regresa a tu %sMembership Information Page%s.');

define ('_TPL_CHANGEPASSWORD_TITLE', 'Cambiar Contraseña');
define ('_TPL_CHANGEPASSWORD_USERNAME', 'Usuario');
define ('_TPL_CHANGEPASSWORD_SAVEBUT', 'Cambiar');
define ('_TPL_CHANGEPASSWORD_BACKBUT', 'Pagina de entrar');
define ('_TPL_CHANGEPASSWORD_CHPWD', 'Nueva contraseña');
define ('_TPL_CHANGEPASSWORD_CONFPWD', 'Confirmar contraseña');

define ('_TPL_CHANGEPASSWORD_FAILED_TITLE', 'Cambio de contraseña erroneo');
define ('_TPL_CHANGEPASSWORD_FAILED_INCINFO', 'La información suministrada es incorrecta!.');
define ('_TPL_CHANGEPASSWORD_FAILED_USRNOTFOUND', 'Usuario no encontrado en la base de datos.');
define ('_TPL_CHANGEPASSWORD_FAILED_EXPIRED', 'Codigo de seguridad expirado.');
define ('_TPL_CHANGEPASSWORD_FAILED_WRONGPASS', 'Contraseñas no coinciden o son muy cortas.');
define ('_TPL_CHANGEPASSWORD_FAILED_RETURN', 'Regresa y trata de nuevo.');

define ('_TPL_REDIRECT_CLICKHERE', 'Click aqui si no quiere esperar mas (O si tu explorador no te redirecciona automaticamente).');

define ('_SENDPWD_OK_TITLE', 'Enviada la contraseña perdida');
define ('_SENDPWD_OK_TEXT', 'Tu contraseña ha sido enviado ');
define ('_SENDPWD_OK_TEXT_1', 'Favor revisar tu bandeja de entrada');

define ('_SENDPWD_FAILED_TITLE', 'Fallo al enviar el password olvidado');
define ('_SENDPWD_FAILED_TEXT', 'La información introducida es incorrecta.');
define ('_SENDPWD_FAILED_TEXT_1', 'El usuario [%s] no existe enla base de datos');
define ('_TPL_SENDPWD_RETURN', 'Regresar a la pagina de entrada');

define ('_TPL_NEWGUEST_FAILED_TITLE', 'Error de \'Confirmación\'');
define ('_TPL_NEWGUEST_FAILED_INCINFO', 'La información introducida es incorrecta');
define ('_TPL_NEWGUEST_FAILED_RETURN', 'Regrese y trate de nuevo');


define ('_TPL_NEWGUEST_FAILED_EMAIL_TITLE', 'Error de \'Confirmación\'');
define ('_TPL_NEWGUEST_FAILED_EMAIL_INFO', 'El correo introducido ya esta siendo utilizado por otro miembro.');
define ('_TPL_NEWGUEST_FAILED_EMAIL_LINK', 'Siga este link para entrar y subscribirse al sistema de noticias.');


define ('_TPL_NEWGUEST_OK_TITLE', 'Confirmación enviada');
define ('_TPL_NEWGUEST_OK_PWDOK', 'Nueva invitacion a visitante fue enviada a tu bandeja de entrada');
define ('_TPL_NEWGUEST_OK_CHECKEM', 'Por favor revise su bandeja de entrada');
define ('_TPL_NEWGUEST_OK_RETURN', 'Regresar');

define ('_TPL_NEWGUEST_COMPLETE_TITLE', 'Suscripción Añadida');
define ('_TPL_NEWGUEST_COMPLETE', 'Tu dirección de correo ha sido completamente suscrita a nuestro sistema de noticias');


define ('_TPL_NEWSLETTER_SUBSCRIPTIONS', 'Suscripciones a noticias');
define ('_TPL_NEWSLETTER_ARCHIVE', 'Archivo de noticias');
define ('_TPL_NEWSLETTER_SUBSCRIBE', 'Suscripcion a noticias');
define ('_TPL_NEWSLETTER_MEMBER_AREA', 'Control Panel');
define ('_TPL_NEWSLETTER_SUBSCRIBE_TO_NEWSLETTERS', 'Elije sistema de noticias');
define ('_TPL_NEWSLETTER_NAME', 'Nombre');
define ('_TPL_NEWSLETTER_EMAIL', 'Correo Electronico');
define ('_TPL_NEWSLETTER_DO_SUBSCRIBE', 'Suscribir');
define ('_TPL_NEWSLETTER_BACK', 'Regresar');

define ('_TPL_NEWSLETTER_UPDATE_SUBSCRIPTIONS', 'Actualizar suscripciones');
define ('_TPL_NEWSLETTER_INFO_SAVED', 'Información salvada');
define ('_TPL_NEWSLETTER_INFO_UPDATED', 'Informaciones de suscripciones al sistema de noticias, guardadas');

define ('_TPL_NEWSLETTER_REQUIRED_NAME', 'El nombre es un campo obligatorio');
define ('_TPL_NEWSLETTER_REQUIRED_EMAIL', 'El correo electronico es un campo obligatorio');
define ('_TPL_NEWSLETTER_REQUIRED_THREAD', 'No se ha seleccionado noticia');

define ('_TPL_NEWSLETTER_UNSUBSCRIBE', 'Salir de todas las suscripciones por correo electronico');

define ('_TPL_NEWSLETTER_DATE', 'Fecha');
define ('_TPL_NEWSLETTER_SUBJECT', 'Asunto');
define ('_TPL_NEWSLETTER_MESSAGE', 'Mensaje');
define ('_TPL_NEWSLETTER_THREADS', 'Temas');

define ('_TPL_SIGNUP_MULT_TITLE', 'Registrarse');
define ('_TPL_SIGNUP_MULT_SELECTTYPE', 'Seleccionar un tipo de membresía');
define ('_TPL_SIGNUP_MULT_MEMTYPE', 'Tipo de Membresia');
define ('_TPL_SIGNUP_MULT_SELPAYSYS', 'Selecciona un sistema de pago');
define ('_TPL_SIGNUP_MULT_PAYSYS', 'Sistema de Pago');
define ('_TPL_SIGNUP_MULT_NAME', 'Tu nombre');
define ('_TPL_SIGNUP_MULT_FLNAME', 'Tu nombre y apellido');
define ('_TPL_SIGNUP_MULT_EMAIL', 'Tu direccion de Correo');
define ('_TPL_SIGNUP_MULT_CONFIRM', 'será usada para enviar confirmaciones');
define ('_TPL_SIGNUP_MULT_LOGIN', 'Elije un Nombre de Usuario ');
define ('_TPL_SIGNUP_MULT_ENTER', 'introduce el nombre de usuario preferido %s- será usado luego del pago%s para entrar a tu cuenta.%s Tiene que ser %d caracteres o mas de largo %sy puede tener letras minusculas, numeros y \'_\' ');
define ('_TPL_SIGNUP_MULT_CHECK', 'Chequear disponibilidad');
define ('_TPL_SIGNUP_MULT_CHPWD', 'Elije una contraseña');
define ('_TPL_SIGNUP_MULT_MUSTBE', 'Tiene que ser %d caracteres o mas, de largo');
define ('_TPL_SIGNUP_MULT_CONFPWD', 'Confirma contraseña');
define ('_TPL_SIGNUP_MULT_PWDAGAIN', 'introduzca la contraseña de nuevo');
define ('_TPL_SIGNUP_MULT_ADDRESS', 'Información de Dirección');
define ('_TPL_SIGNUP_MULT_STREET', 'Calle');
define ('_TPL_SIGNUP_MULT_CITY', 'Ciudad');
define ('_TPL_SIGNUP_MULT_STATE', 'Estado');
define ('_TPL_SIGNUP_MULT_ZIP', 'ZIP');
define ('_TPL_SIGNUP_MULT_COUNTRY', 'País');
define ('_TPL_SIGNUP_MULT_COUPONS', 'Cupones');
define ('_TPL_SIGNUP_MULT_CCODE', 'Introduzca el numero de cupon');
define ('_TPL_SIGNUP_MULT_GETCOUP', 'Si obtienes un cupon de alguna publicidad,%s favor de introducirlo aqui');
define ('_TPL_SIGNUP_MULT_CONT', 'Continúa');

define ('_TPL_THX_TITLE', 'Gracias por registrarte');
define ('_TPL_THX_ENJOY', 'Disfruta tu membresía. Para entrar, favor haz click %sAquí%s');
define ('_TPL_THX_PAYPROC', 'Tu pago fue correctamente ejecutado.');
define ('_TPL_THX_ORDERREF', 'Referencia de orden: %d / %s');
define ('_TPL_THX_DATETIME', 'Fecha y hora: %s');
define ('_TPL_THX_PRDTITLE', 'Suscripción/Producto');
define ('_TPL_THX_PRICE', 'Preciop');
define ('_TPL_THX_SUBTOTAL', 'Subtotal');
define ('_TPL_THX_DISCOUNT', 'Descuento por cupon');
define ('_TPL_THX_TAX', 'Impuestos');
define ('_TPL_THX_TOTAL', 'Total');
define ('_TPL_THX_YOUR_INVOICE', 'Numero de recibo');
define ('_TPL_THX_FROM', 'desde');

define ('_TPL_THX_ERROR_TITLE', 'Error de registro');
define ('_TPL_THX_ERROR_ERROR', 'Errores obtenidos durante la ejecución');
define ('_TPL_THX_ERROR_CONTACT', 'Favor contactar a un administrador');

define ('_TPL_UNSUBSCRIBE_TITLE', 'Confirmacion de "dada de baja"');
define ('_TPL_UNSUBSCRIBE_CONFIRM', 'De verdad quieres dar de baja a este correo %s%s%s de %s noticias periodicas?');
define ('_TPL_UNSUBSCRIBE_UNSUB_BUT', 'Si, Por favor darme de baja');
define ('_TPL_UNSUBSCRIBE_NO_UNSUB_BUT', 'No, favor mantenerme suscrito');

define ('_TPL_UNSUBSCRIBED_TITLE', 'Baja al correo!');
define ('_TPL_UNSUBSCRIBED_SUCCESS1', 'Tu direccion de correo %s fue dada de baja correctamente.');
define ('_TPL_UNSUBSCRIBED_SUCCESS2', 'No recibiras mas correos de nuestro sitio.');
define ('_TPL_UNSUBSCRIBED_SUCCESS3', 'Sin embargo, tenga pendiente que seguira recibiendo correos sobre nuevos pagos, y si pregunta por su contraseña.');

define ('_UNIQ_LOGIN_EMPTY_TITLE', 'Usuario en blanco');
define ('_UNIQ_LOGIN_EMPTY_TEXT', 'Favor introducir tu usuario.');
define ('_UNIQ_LOGIN_EXSTS_TITLE', 'Nombre de Usuario en USO.');
define ('_UNIQ_LOGIN_EXSTS_TEXT', 'El nombre de usuario %s ya es utilizado por otro usuario.');
define ('_UNIQ_LOGIN_EXSTS_TEXT_1', 'Favor elegir un nombre de usuario diferente');
define ('_UNIQ_LOGIN_EXSTS_TEXT_2', 'Si es tu cuenta, favor ir a %sla pagina de membresias%s y entrar al sistema.');
define ('_UNIQ_LOGIN_FREE_TITLE', 'Usuario disponible');
define ('_UNIQ_LOGIN_FREE_TEXT', 'Nombre de Usuario %s aún no ha sido registrado');
define ('_UNIQ_LOGIN_FREE_TEXT_1', 'Felicidades, está disponible');
define ('_TPL_UNIQ_LOGIN_CLOSE', 'Cerrar');

define('_LOGIN_WAIT_BEFORE_NEXT_ATTEMPT', 'Favor esperar %d minutos hasta el proximo intento de entrada.');
define('_LOGIN_SESSION_EXPIRED', 'Session expirada, favor introducir usuario y contraseña de nuevo');
define('_LOGIN_ACCESS_NOT_ALLOWED', 'Acceso a esta area no está permitido. Favor ir a %s"La pagina de informacion de tu membresía"%s para renovar la suscripcion.');
define('_LOGIN_INCORRECT', "Nombre de usuario y contraseña no coinciden");
define('_LOGIN_ACCOUNT_DISABLED', 'Tu cuenta ha sido deshabilitada. Favor contactar al webmaster para mas informacion.');
define('_LOGIN_MANUAL_VERIFICATION_PENDING', 'Tu cuenta aun no esta habilitada. Recibiras un correo de confirmacion una vez aprobada.');
define('_LOGIN_USERNAME_WRONG_CASE', 'Introduzca el nombre de usuario correctamente. Introdujiste "%s", en vez de "%s"');
define('_LOGIN_PLEASE_LOGIN', 'Favor entrar');

define('_SIGNUP_PLEASE_SELECT_MEMT', 'Favor elegir un tipo de memebresía');
define('_SIGNUP_PLEASE_SELECT_PAYSYS', 'Favor elegir el sistema de pago');
define('_SIGNUP_PLEASE_ENTER_FNAME', 'Favor entrar tu Nombre');
define('_SIGNUP_PLEASE_ENTER_LNAME', 'Favor entrar tu Apellido');
define('_SIGNUP_INVALID_USERNAME', 'El nombre de usuario contiene caracteres prohibidos - favor usar digitos, letras o espacios');
define('_SIGNUP_INVALID_USERNAME_W_SPACES', 'El nombre de usuario contiene caracteres prohibidos - favor usar digitos o letras');
define('_SIGNUP_INVALID_USERNAME_2', 'Favor introducir un usuario valido. Tiene que contener al menos %d caracteres');
define('_SIGNUP_INVALID_USERNAME_3', 'Nombre de usuario %s ya está en uso. Favor elegir otro.');
define('_SIGNUP_PLEASE_ENTER_EMAIL', 'Favor introducir una direccion de correo valida.');
define('_SIGNUP_INVALID_EMAIL_1', 'Una cuenta con la misma direccion de correo ya existe.');
define('_SIGNUP_INVALID_EMAIL_2', 'Favor %sentrar%s a tu cuenta ya existente.%sSi aun no has completado el pago, podras hacerlo luego de entrar.');
define('_SIGNUP_PLEASE_ENTER_PSWD', 'Favor introducir contraseña');
define('_SIGNUP_INVALID_PASS_1', 'La contraseña debe contener al menos %d letras y digitos');
define('_SIGNUP_INVALID_PASS_2', 'La contraseña y su confirmacion, no coinciden. Favor introducirlos nuevamente.');
define('_SIGNUP_SCRIPT_ERROR', 'Error de configuracion - Tienes que agregar al menos un producto (Tipo de Membresía)');
define('_SIGNUP_PAYMENT_NOT_FOUND', 'Pago: %d no encontrado');
define('_SIGNUP_PAYMENT_COMPLETED', 'Pago %d completado, favor entrar a tu cuenta ');
define('_SIGNUP_PAYMENT_COMPLETED_1', 'aqui');
define('_SIGNUP_INCORRECT_LINK', 'Enlace incorrecto - asegurese que lo copio correctamente desde su correo.');
define('_SIGNUP_USER_AGREEMENT', 'Tienes que aceptar los terminos de uso antes de continuar');
define('_SIGNUP_INCORRECT_PRODID', 'ID del producto incorrecto');
define('_SIGNUP_LOGIN_EXISTS', 'Entrada ya existe. Error de sistema');
define('_SIGNUP_ENTER_STREET', 'Calle');
define('_SIGNUP_ENTER_CITY', 'Ciudad');
define('_SIGNUP_ENTER_STATE', 'Estado');
define('_SIGNUP_ENTER_ZIP', 'Codigo ZIP');
define('_SIGNUP_ENTER_COUNTRY', 'País');

define('_AFF_MEMBER_TITLE', 'Informacion de afiliado');
define('_AFF_INTERNAL_ERROR', 'Error Interno - el id de miembro está en blanco');
define('_AFF_ERROR_1', 'Favor entrar una direccion de correo para tus pagos');
define('_AFF_ERROR_2', 'Favor entrar un nombre de beneficiario');
define('_AFF_ERROR_3', 'Favor entrar tu cuenta de StormPay');
define('_AFF_ERROR_4', 'Favor introducir tu cuenta de iKobo');
define('_AFF_ERROR_5', 'Favor introducir tu cuenta de MoneyBookers');
define('_AFF_ERROR_6', 'Favor introducir tu cuenta de E-Gold');
define('_AFF_ERROR_7', 'Tipo de pago desconocido');
define('_AFF_ERROR_8', 'Accion desconocida: %s');
define('_AFF_AFFILIATES', 'Afiliados');
define('_AFF_PROGR_CONF', 'Configuracion del programa de afiliados');
define('_AFF_PAYOUT_MTHDS', 'Metodos aceptados de pago');
define('_AFF_MTHD4_PAYOUT', 'el afiliado puede elegir un metodo de pago.');
define('_AFF_NOTHING_SELECTED', 'Si nada es seleccionado, las comisiones no seran enviadas automaticamente.');
define('_AFF_REPORT', 'payout report.');
define('_AFF_CONFIG_F1_1', 'Comision de afiliado para el primer pago');
define('_AFF_CONFIG_F1_2', 'Comision de afiliado para el primer pago, ej: 1.5 o 2.5%');
define('_AFF_CONFIG_F2_1', 'Comision de afiliado para los proximos pagos');
define('_AFF_CONFIG_F2_2', 'Comision de afiliado apra los proximos pagos, ej: 1.5 o 2.5%');
define('_AFF_CONFIG_F3_1', 'Tiempo de vida de la Cookie');
define('_AFF_CONFIG_F3_2', 'Cuanto tiempo (en dias) guardar cookies sobre referidos.');
define('_AFF_CONFIG_F3_3', 'entonces si el afiliado regresa al sitio, las comisiones serán');
define('_AFF_CONFIG_F3_4', 'pagar al afiliado referido.');
define('_AFF_CONFIG_F4_1', 'Pagar solo la primera comision');
define('_AFF_CONFIG_F4_2', 'el afiliado solo recibira comision por la primera compra.');
define('_AFF_CONFIG_F4_3', 'en caso de pagos recurrentes, solo la primera comision sera ');
define('_AFF_CONFIG_F4_4', 'generada.');
define('_AFF_CONFIG_F5_1', 'No ofrecer comision por cuentas gratis');
define('_AFF_CONFIG_F5_2', 'comision de venta no sera creditada a la cuenta del afiliado');
define('_AFF_CONFIG_F5_3', 'si el usuario se registra por una cuenta gratis. Claro, solo afecta a');
define('_AFF_CONFIG_F5_4', 'a comisiones \"arregladas\" de afiliados.');
define('_AFF_ARRAY_1ELEM', 'Give Commission even for free subscriptions');
define('_AFF_ARRAY_2ELEM', 'No ofrecer comisiones por cuentas gratis');
define('_AFF_CONFIG_F6_1', 'Tipo de suscripcion de afiliado');
define('_AFF_CONFIG_F6_2', 'Afiliado solo recibira comision por la primera compra.');
define('_AFF_CONFIG_F6_3', 'en caso de pagos recurrentes, solo la primera comision sera ');
define('_AFF_CONFIG_F6_4', 'generada.');
define('_AFF_ARRAY_2_ELEM_1', 'Defecto - el usuario tiene que click el enlace para ser un afiliado');
define('_AFF_ARRAY_2_ELEM_2', 'Todo los nuevos miembros seran afiliados');
define('_AFF_ARRAY_2_ELEM_3', 'Solo miembros pueden agregar y modificar afiliados');
define('_AFF_CONFIG_F7_1', 'Comisiones de correo, al administrador');
define('_AFF_CONFIG_F7_2', 'Cuando una comision de nueva venta sea acreditada a un afiliado');
define('_AFF_CONFIG_F7_3', 'enviar un correo al administraodr');
define('_AFF_CONFIG_F8_1', 'enviar un correo al afiliado');
define('_AFF_CONFIG_F8_2', 'Cuando una comision de nueva venta sea acreditada a un afiliado');
define('_AFF_CONFIG_F8_3', 'enviar un correo al afiliado');
define('_AFF_ADVERTISE_SITE', 'Publica nuestro sitio a tus amigos y recibe dinero');
define('_AFF_MEMBER_AREA', 'Area de Afiliados');
define('_AFF_GET_BANS_LINKS', 'Ver banners de afiliados y enlaces');
define('_AFF_REVIEW_STAT', 'Ver mis estadisticas de afiliado');
define('_AFF_UPDATE_PAYOUT', 'Actualizar la informacion de pago');
define('_AFF_MEMBER_F1_1', 'Direccion Paypal para pago de afiliado');
define('_AFF_MEMBER_F2_1', 'Direccion StormPay para pago de afiliado');
define('_AFF_MEMBER_F3_1', 'Direccion iKobo para pago de afiliado');
define('_AFF_MEMBER_F4_1', 'ID de MoneyBookers para pago de afiliado');
define('_AFF_MEMBER_F5_1', 'Numero de cuenta de E-Gold para pago de afiliado');
define('_AFF_MEMBER_F6_1', 'Beneficiario');
define('_AFF_MEMBER_THANK_YOU', 'Gracias por registrarse');
define('_AFF_MEMBER_REDIRECTING', 'Redireccionando...');
define('_AFF_DISABLED_MESSAGE', 'El programa de afiliaciones no esta habilitado. Ir al aMember CP -> Setup');

define('_AFF_PAYOUT_TYPE', 'Tipo de Afiliacion');
define('_AFF_SIGNUP_PLEASE_PAYOUT_TYPE', 'Elige tu tipo de pago');

define('_MEMBER_VF_INTEGER', 'Favor introducir un valor decimal para [%s]');
define('_MEMBER_VF_NUMERIC', 'Favor introducir un valor entero para [%s]');
define('_MEMBER_VF_REQUIRE', 'Favor introducir un valor entero para [%s]');
define('_MEMBER_VF_EMAIL', 'Favor introducir una direccion de correo al campo [%s] ');

define('_MEMBER_ERROR_1', 'Tu no has verificado tu cuenta de correo, por esto no estas permitido a entrar al sistema. Favor revisar tu bandeja de entrada para el mensaje de verificacion. Si no has recibido el mensaje %sFavor Click %s este link%s y reenviaremos tu mensaje de confirmación.');
define('_MEMBER_REDIRECTING', 'Redireccionando a tu pagina de membresía');
define('_MEMBER_ONLY4_PAID', 'Este producto esta solo disponible para miembros premium');
define('_MEMBER_ONLY4_NEW', 'Este producto esta solo disponible para miembros nuevos');
define('_MEMBER_NOT4_ORDER', 'Este producto no esta disponible');
define('_MEMBER_SELECT_PRODUCT', 'Favor seleccionar un tipo de suscripcion a renovar');
define('_MEMBER_SELECT_PAYMENT', 'Favor seleccionar el tipo de pago');
define('_MEMBER_ID_NOT_MATCH', 'member_id no coincide con el pago');
define('_MEMBER_SUBSCR_CANCELLED', 'Suscripcion cancelada');
define('_MEMBER_RSUB_CANCELLED', 'La suscripcion recurrente ha sido cancelada.');
define('_MEMBER_MAIL_ADMIN', 'Suscripcion recurrente cancelada: Nombre de Usuario: %s Pago #: %d');
define('_MEMBER_MAIL_THEME', '*** Suscripcion Cancelada');
define('_MEMBER_ERROR', 'Tienes que aceptar los terminos de uso para continuar');

define('_MEMBER_PROFILE_CORRECTLOG', 'Favor introducir el Usuario correcto. Tiene que contener al menos %d letras, digitos o _');
define('_MEMBER_PROFILE_NAMEEXISTS', 'El nombre de usuario %s ya está tomado. Favor elegir otro.');
define('_MEMBER_PROFILE_ERROR1', 'Favor introducir un nombre de usuario correcto: %s');
define('_MEMBER_PROFILE_ERROR2', 'Favor introducir una direccion de correo correcta');
define('_MEMBER_PROFILE_ERROR3', 'Esta direccion de correo ya esta siendo utilizada');
define('_MEMBER_PROFILE_ERROR4', 'Favor introducir Nombres');
define('_MEMBER_PROFILE_ERROR5', 'Favor introducir Apellidos');
define('_MEMBER_PROFILE_ERROR6', 'La contraseña debe contener al menos %d caracteres');
define('_MEMBER_PROFILE_ERROR7', 'La contraseña debe contener menos de %d caracteres');
define('_MEMBER_PROFILE_ERROR8', 'Contraseña y su confirmación NO coinciden. Favor reintroducirlas');
define('_MEMBER_PROFILE_ERROR9', 'Tipo de campo desconocido %s : %s');

define('_CRON_ERROR', 'Cron externo deshabilitado en el Setup');

define('_COMMON_LANGUAGE', 'Lenguaje');
define('_COMMON_LIFETIME', 'Tiempo de Vida');
define('_COMMON_RECURRING', 'Recurrente');

define('_INDEX_ERROR', 'Sin configuracion ve a la  %spagina de configuracion%s.');

define('_LOGIN_REDIRECT', 'Serás redirigido a un area protegida');

define('_RESEND_ERROR', 'Tu direccion de correo ya esta verificada');
define('_RESEND_ERROR2', 'No puedes pedir mas verificaciones de correo, favor solicitar una %scuenta nueva%s o mejor contactenos en Soporte para una ayuda instantanea.');
define('_RESEND_ERROR3', 'Error #1265.');

define('_NEWSLETTER_SUBSCRIPTION', 'Suscripcion de noticias');
define('_NEWSLETTER_NO_GUEST_THREADS', 'Lo siento, pero no hay sistemas de noticias configurados para visitantes');

define('_SETUP_ERROR', 'Version de PHP %s o mayor para correr aMember. La tuya es : %s%sfavor actualizar tu hosting%s.');
define('_SETUP_ERROR2', 'PHP ha sido compilado con soporta MYSQL.%sentonces aMember no puede ser instalado en tu sistema, Favor contactar%s a tu sistema de hosting para resolver este inconvenicente');
define('_SETUP_FATAL_ERROR', 'Error Fatal: %s');
define('_SETUP_HEADER', 'aMember - Instalacion');
define('_SETUP_CONF_EXISTS', 'Archivo %s ya existe y no se encuentra en blanco. Favor de removerlo o de borrar su contenido');
define('_SETUP_AFTER_FIX', 'Despues de resolver estos problemas, haga click %saqui%s para refrescar la pagina.');
define('_SETUP_CONF_CHMOD', 'Archivo %s existe y no es "writable". favor %sresolver%s');
define('_SETUP_DIRECTORY_CHMOD', 'Directorio %s no es "writeable". Se necesita escribir el archivo de configuracion %s. favor %sresolver%s');
define('_SETUP_ENTER_PARAM', 'Paramatros de configuracion');
define('_SETUP_MODIFY_LATER', 'Puede modificar estos valores luego mediante el Panel de Control');
define('_SETUP_ROOT_URL', 'Direccion Raiz del script');
define('_SETUP_TRAILING_SLASH', '%sNo se puede%s poner slash ( %s/%s )en el final!');
define('_SETUP_LICENSE_NOTE', 'Favor recordar que la direccion debe coincidir con la de la licencia.');
define('_SETUP_HTTPS_URL', '(HTTPS) URL segura del SCRIPT');
define('_SETUP_KEEP_DEFAULT', 'Favor dejar por defecto (not-secure) si no está seguro.');
define('_SETUP_NO_TRSLASH', 'No SLASH ( %s/%s ) por favor!');
define('_SETUP_ADMIN_EMAIL', 'Correo del Administrador');
define('_SETUP_SENT_TO', 'La direccion y otras alertas deben ser enviadas a');
define('_SETUP_ADMIN_LOGIN', 'Usuario del Admin');
define('_SETUP_USERNAME', 'Usuario para entrar a la interface administrativa');
define('_SETUP_ADMIN_PASS', 'Contraseña del Admin');
define('_SETUP_PASS', 'Contraseña para entrar a la interface administrativa');
define('_SETUP_LICENSE_HEAD', 'Licensia');
define('_SETUP_LICENSE', 'Entra la licensia %sCOMPLETA%s, incluyendo las lineas de igualdad ( == ) arriba y abajo!');
define('_SETUP_NEXT_BUT', 'Proximo');
define('_SETUP_ERROR3', 'Favor insertar la Direccion Raiz del Script');
define('_SETUP_ERROR4', 'Favor insertar la direccion Raiz Segura del Script');
define('_SETUP_ERROR5', 'Favor insertar el correo del Admin');
define('_SETUP_ERROR6', 'Favor insertar el usuario del admin');
define('_SETUP_ERROR7', 'Favor insertar la contraseña del admin');
define('_SETUP_ERROR8', 'Favor insertar el codigo de la licensia');
define('_SETUP_ERROR9', 'Entra la licensia %sCOMPLETA%s, incluyendo las lineas de igualdad ( == ) arriba y abajo!');
define('_SETUP_ERROR10', 'URL no coincide con la URL de la licensia');
define('_SETUP_ERROR11', 'URL no coincide con la URL de la licensia');
define('_SETUP_RETURN', 'Favor %sregresar%s y resolver estos errores.');
define('_SETUP_MYSQL_PARAM', 'Parametros de configuracion del MySQL');
define('_SETUP_CONF_EDIT', 'Debes editar %sconfig.inc.php%s si quieres hacer cambios despues de la instalacion');
define('_SETUP_MYSQL_HOST', 'MySQL Host');
define('_SETUP_LOCALHOST', 'Mayoria de veces \'localhost\'');
define('_SETUP_MYSQL_DB', 'MySQL Database');
define('_SETUP_MYSQL_NOTE', 'Nota: La instalacion no crea la base de datos por ti.');
define('_SETUP_USE_DEFAULT', 'Usar la base de datos creada por tu compañia de hosting %s o crea una base de datos por ejemplo \'amember\'');
define('_SETUP_MYSQL_USER', 'MySQL Username');
define('_SETUP_MYSQL_PWD', 'MySQL Password');
define('_SETUP_TABLE_PREFIX', 'MySQL Prefijo de tablas');
define('_SETUP_UNSURE', 'Si no esta seguro, usar por defecto %samember_%s');
define('_SETUP_MYSQL_ERROR1', 'MYSQL - Favor introducir  database name');
define('_SETUP_MYSQL_ERROR2', 'MYSQL - Favor introducir  username');
define('_SETUP_MYSQL_ERROR3', 'MYSQL - Favor introducir  hostname');
define('_SETUP_MYSQL_ERROR4', 'MYSQL - Favor introducir  password');
define('_SETUP_MYSQL_ERROR5', 'No se puede conectar a la base de datos (%s)');
define('_SETUP_MYSQL_ERROR6', 'No se selecciono base de datos \'%s\' ( %s )');
define('_SETUP_MYSQL_INSTALL', 'Instalar aMember a esta base de datos?');
define('_SETUP_MYSQL_CREATE_TABLES', 'Crear tablas');
define('_SETUP_MYSQL_INSTALL2', 'Selecciona y cliquea \'Siguiente\' Para crear las tablas%s%s');
define('_SETUP_MYSQL_ERROR7', 'No se puede seleccionar bases de datos \' %s \' ( %s )');
define('_SETUP_MYSQL_FIX_ERROR', 'Favor resolver y %srefrescar la pagina%s.');
define('_SETUP_ERROR12', 'No se puede abrir %s . favor subir este archivo');
define('_SETUP_ERROR13', 'No se puede salvar el archivo de configuracion');
define('_SETUP_ERROR14', 'No se puede salvar este archivo %s%s%s');
define('_SETUP_NEW_CONFIG', 'Para una nueva instalacion completa descargue los archivos.');
define('_SETUP_UPLOAD_CONFIG', 'Archivo %sconfig.inc.php%s. subirlo a ');
define('_SETUP_DOWNLOAD_BUT', 'Descargar a config.inc.php');
define('_SETUP_IE_RENAME', 'Internet Expolorer a veces renombra %sarchivos cuando los salva. Por ejemplo, puede que se llame %sconfig.inc.php y cambiarlo a config[1].inc.php, it may rename%s.');
define('_SETUP_THANK_YOU1', 'Gracias por usar aMember. El manual de usuario lo puede encontrar %saquí%s.');
define('_SETUP_THANK_YOU2', 'Sientase libre de contactar %sCGI-Central%s.');
define('_SETUP_THANK_YOU3', 'Favor revisar lo siguiente:');
define('_SETUP_THANK_YOU4', '(Puede agregar esta pagina a sus favoritos)');
define('_SETUP_THANK_YOU_LINK1', 'Control Admin (aMember Control Panel)');
define('_SETUP_THANK_YOU_LINK2', 'Pagina de registro');
define('_SETUP_THANK_YOU_LINK3', 'Panel de Usuarios');
define('_SETUP_THANK_YOU_LINK4', 'Pagina de Entrada');
define('_SETUP_THANK_YOU_BEFOREUSE', 'Antes de que aMember este listo para usarse, debe hacer lo siguiente)');
define('_SETUP_THANK_YOU_GOTOCP', 'Ir a la  %sPagina de administracion%s y entrar. Seleccionar %sUtilities>Setup/Configuration%s y configura tu instalacion.');
define('_SETUP_THANK_YOU_ADDPRODUCTS', 'Ir a la  %sPagina de administracion%s  y agrega tus productos.');
define('_SETUP_THANK_YOU_REMEMBER', 'Recuerda , U \'Producto\' o un \'Tipo de Subscripcion \' son sinonimos');
define('_SETUP_THANK_YOU_SUBSCRTYPE', 'Puedes especificar los tipos de suscripciones.');
define('_SETUP_THANK_YOU_PAYCONF', 'Determinar la configuracion para que los pagos se procesen correctamente ');
define('_SETUP_THANK_YOU_CHECKINSTL', 'Chequear tu instalacion, probandola a su totalidad.');
define('_SETUP_THANK_YOU_READMORE', 'Para templates y configuraciones dirijase %saquí%s.');
define('_SETUP_THANK_YOU_FEELFREE', 'Sientase libre de contactar %sal Soporte de CGI-Central%s si necesita alguna configuracion de su script.');
define('_SETUP_THANK_YOU_INFO', 'Puede encontrar monton de cosas importantes en el  %sFORO%s.');
define('_SETUP_HEADER1', 'Instalacion: Paso %d de 6');

define('_UNSUBSCRIBE_ERROR', 'Direccion URL erronea, favor contactar al administrador');

define('_PLUG_PAY_REDIRECT_WAIT', 'Espere...');
define('_PLUG_PAY_REDIRECT_REDIRECT', 'Redireccionandote a una pagina segura de pago...');

define('_TPL_CC_INFO_TITLE', 'Informacion de la Tarjeta de Credito');
define('_TPL_CC_INFO_CCTYPE', 'Tipo de tarjeta');
define('_TPL_CC_INFO_SELECT1', 'Favor seleccionar');
define('_TPL_CC_INFO_CHOOSE', '*** Favor Elegir ***');
define('_TPL_CC_INFO_HOLDERNAME', 'Nombre del tarjeta habiente');
define('_TPL_CC_INFO_ASONCARD', 'Nombre del Tarjeta Habiente, exactamente como se encuentra en la tarjeta');
define('_TPL_CC_INFO_HOLDERNAME2', 'Nombre del Tarjeta Habiente');
define('_TPL_CC_INFO_FLNAME', 'Nombre y Apellido del Tarjeta habiente,  %sexactamente como se encuentra en la tarjeta');
define('_TPL_CC_INFO_CNAME', 'Compañia');
define('_TPL_CC_INFO_COMPNAME', 'el nombre de la compañia asociada con la %sla direccion de la transaccion');
define('_TPL_CC_INFO_CCNUM', 'Número de la Tarjeta');
define('_TPL_CC_INFO_EXAMPLE', 'Por Ejemplo: 1111-2222-3333-4444');
define('_TPL_CC_INFO_EXPIRE', 'Expira:');
define('_TPL_CC_INFO_EXPDATE', 'Fecha de Expiracion - mes y año');
define('_TPL_CC_INFO_CCCODE', 'Codigo de la tarjeta');
define('_TPL_CC_INFO_CCCODEDESC', 'El codigo de la tarjeta es de 3 a 4 digitos seguros %scuales estan impresos en la parte trasera de la tarjeta de credito %s');
define('_TPL_CC_INFO_ADDRINFO', 'Dirección');
define('_TPL_CC_INFO_STRADDR', 'Calle');
define('_TPL_CC_INFO_HNUMB', 'Numero');
define('_TPL_CC_INFO_CITY', 'Ciudad');
define('_TPL_CC_INFO_STATE', 'Estado');
define('_TPL_CC_INFO_ZIP', 'ZIP');
define('_TPL_CC_INFO_COUNTRY', 'País');
define('_TPL_CC_INFO_PHONE', 'Telefono');
define('_TPL_CC_INFO_PHONENUM', 'Introduzca el numero de telefono en el siguiente %sformato: %s999-999-9999%s');
define('_TPL_CC_INFO_MUSTMATCH', '(Tiene que coincidir con el de tu tarjeta de credito)');
define('_TPL_CC_INFO_SUBMIT_BUT', 'Actualizar informacion');
define('_TPL_CC_INFO_BACK_BUT', 'Regresar');
define('_TPL_CC_INFO_SUBMIT_BUT2', 'Subscribir');
define('_TPL_CC_INFO_SUBMIT_BUT_3', 'Subscribir y pagar');

define('_TPL_CC_DECLINED_TITLE', 'Error en el pago');
define('_TPL_CC_DECLINED_TRYAGAIN', 'Vuelva a intentar');



define('_TPL_CC_INFO_BANK_IDENTIFICATION', 'Identificacion del Banco');
define('_TPL_CC_INFO_BIN_NAME', 'Nombre del Banco');
define('_TPL_CC_INFO_BIN_NAME_MORE', 'Nombre del Banco que hizo la tarjeta');
define('_TPL_CC_INFO_BIN_PHONE', 'Telefono del Banco');
define('_TPL_CC_INFO_BIN_PHONE_MORE', 'Telefono del servicio al cliente, impreso en tu tarjeta de credito');

define('_TPL_CC_VERIFY_CODE', 'Formulario de verificacion via telefonica');
define('_TPL_CC_INFO_CALLING', 'Estamos llamando al numero telefonico introducido');
define('_TPL_CC_INFO_VERIFY_CODE', 'Codigo de verificacion');
define('_TPL_CC_INFO_VERIFY_CODE_MORE', 'Introduzca el codigo dado por el sistema');
define('_TPL_CC_INFO_SUBMIT_VERIFY', 'Continuar');

define('_TPL_WRONG_VERIFY_CODE', 'Codigo de verificacion erroneo. Favor volver a intentar.');

define('_TPL_CC_ERROR_TNI', 'Error durante la verificacion via telefonica');
define('_TPL_CC_ERROR_TV',  'Error durante la verificacion via telefonica');
define('_TPL_CC_ERROR_CARDEREMAIL', 'Error. El correo se encuentra en nuestra lista negra');
define('_TPL_CC_ERROR_COUNTRYNOTMATCH', 'Error. La direccion IP no coincide con el pais suministrado');
define('_TPL_CC_ERROR_HIGHRISKCOUNTRY', 'Error. El IP o la direccion se encuentran en nuestra lista negra');
define('_TPL_CC_ERROR_ANONYMOUSPROXY', 'Error. Proxys anonimos no son permitidos');
define('_TPL_CC_ERROR_FREEMAIL', 'Error. Email desde cuentas gratis, no son aceptados');

define('_TPL_CC_ERROR_BIN', 'Error. Pais del Banco y el BIN no coinciden');
define('_TPL_CC_ERROR_BIN_NAME', 'Error. El nombre del Banco no coincide con el BIN');
define('_TPL_CC_ERROR_BIN_PHONE', 'Error. El numero de servicio al cliente no coincide con el del BIN');

define('_TPL_CC_DECLINED', 'Tarjeta de Credito Invalida - Declinada');


define('_TPL_JSVAL_ERR_FORM', 'Favor introducir o seleccionar los valores de los siguientes campos:');
define('_TPL_JSVAL_ERR_SELECT', 'Favor elegir un [%FIELDNAME%] valido');
define('_TPL_JSVAL_ERR_ENTER', 'Favor elegir un [%FIELDNAME%] valido');

define('_TPL_COMMON_SELECT_STATE', '[Seleccione el estado]');
define('_TPL_COMMON_SELECT_COUNTRY', '[Seleccione el pais]');






define('_PLUG_PAY_ANYLINK_REDIR_ERROR', '"AnyLink URL" esta vacio para el producto#%d. favor contactar al administrador');
define('_PLUG_PAY_ANYLINK_TITLE', 'Pago por tarjeta de Credito');
define('_PLUG_PAY_ANYLINK_CCACCEPTED', 'Mayoria de tarjetas de creditos aceptadas');





define('_PLUG_PAY_AUTHORIZE_TITLE', 'Authorize.Net Pago via Web');
define('_PLUG_PAY_AUTHORIZE_DESCR', 'Tarjeta de credito via %sauthorize.net%s');
define('_PLUG_PAY_AUTHORIZE_ERROR', 'Error de Autorizacion %s (Detalles: PNREF:%s, Recibo:%s)%s%s');
define('_PLUG_PAY_AUTHORIZE_ERR_ARR', 'Error al procesar pago:');
define('_PLUG_PAY_AUTHORIZE_ERR_ARR2', 'Favor intentar de nuevo.');
define('_PLUG_PAY_AUTHORIZE_USER_ERR', 'Monto en Cero');
define('_PLUG_PAY_AUTHORIZE_ERROR2', 'Incorrecto: MD5 hash');
define('_PLUG_PAY_AUTHORIZE_ERROR3', 'Transaccion de prueba procesada.');
define('_PLUG_PAY_AUTHORIZE_ERROR4', 'Error de espera finalizado: %s');





define('_PLUG_PAY_AUTHORIZE_AIM_TITLE', 'Autorizar AIM');
define('_PLUG_PAY_AUTHORIZE_AIM_DESC', 'Pago de Tarjeta de Credito');

















define('_PLUG_PAY_BEANSTREAM_TITLE', 'BeanStream');
define('_PLUG_PAY_BEANSTREAM_DESC', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_BEANSTREAM_PFAILED', 'Payment failed: ');





define('_PLUG_PAY_BEANSTREAM_REM_ERROR', 'beanstream_remote ERROR: %s (Detalles: PNREF:%s, recibo:%d)%s%s');
define('_PLUG_PAY_BEANSTREAM_REM_DEBUG', 'beanstream_remote DEBUG: ');
define('_PLUG_PAY_BEANSTREAM_REM_TITLE', 'BeanStream');
define('_PLUG_PAY_BEANSTREAM_REM_DESC', 'Pago de Tarjeta de Credito');

define('_PLUG_PAY_BEANSTREAM_REM_HTML_TITLE', 'Pagina Pago de Tarjeta de Credito');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CNAME', 'Nombre de la Tarjeta');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CNAME2', '%sexactamente%s  como en la tarjeta');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CCNUM', 'Número de la tarjeta de credito');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CCEXP', 'Expira:');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JAN', 'Enero');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_FEB', 'Febrero');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_MAR', 'Marzo');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_APR', 'Abril');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_MAY', 'Mayo');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JUN', 'Junio');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JUL', 'Julio');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_AUG', 'Augosto');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_SEP', 'Septiembre');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_OCT', 'Octubre');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_NOV', 'Noviembre');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_DEC', 'Deciembre');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ADDR', 'Direccion');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ADDR2', '%sexactamentet%s como en la tarjeta');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CITY', 'Ciudad');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CITY2', '%sexactamente%s como en la tarjeta');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_COUNTRY', 'Pais');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_COUNTRY2', '%sexactamente%s como en la tarjeta');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_STATE', 'Estado');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_STATE2', '%sexactamente%s como en la tarjeta');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ZIP', 'ZIP');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_PHONE', 'Telefono');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_PROCEED', 'Proceder');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_FSUMB', 'Este formulario sera enviado por medio de un servidor seguro');





define('_PLUG_PAY_PAYCOM_FERROR', ' ERROR PayCom IPN: %s (Detalles: Recibo:%d)%s');
define('_PLUG_PAY_PAYCOM_ERROR', 'Error al procesar el pago: %s');
define('_PLUG_PAY_PAYCOM_ERROR2', '%s Favor regresar e intentar de nuevo.');
define('_PLUG_PAY_PAYCOM_ERROR3', 'Contraseña de PostBack Incorrecta: ');
define('_PLUG_PAY_PAYCOM_ERROR4', 'Paycom IPN:  Error en el Pago(Detalles: Recibo:%d)%s');
define('_PLUG_PAY_PAYCOM_ERROR5', 'Modo de prueba deshabilitado, abortando');
define('_PLUG_PAY_PAYCOM_ERROR6', 'Codigo de Producto Erroneo: [%d] en vez de [%d]');
define('_PLUG_PAY_PAYCOM_ERROR7', 'IP incorrecto: %s , mascaras de IP aceptadas: ');
define('_PLUG_PAY_PAYCOM_ERROR8', 'co_code Incorrecto');

define('_PLUG_PAY_PAYCOM_TITLE', 'PayCom');
define('_PLUG_PAY_PAYCOM_DESC', 'Tarjeta de Credito PayCom');

define('_PLUG_PAY_PAYCOM_ERROR9', 'ERROR paycom: %s');
define('_PLUG_PAY_PAYCOM_ERROR10', 'Modo prueba deshabilidado');

define('_PLUG_PAY_PAYCOM_HTML_TITLE', 'Pago Paycom');
define('_PLUG_PAY_PAYCOM_HTML_TEXT1', 'Favor hacer click en "Proceder" para continuar con el pago a %sPaycom.net%s, nuestros vendedores autorizados.');
define('_PLUG_PAY_PAYCOM_HTML_SUBMBUT', 'Proceder');





define('_PLUG_PAY_CC_CORE_FERROR1', '\'v\' tiene un valor invalido');
define('_PLUG_PAY_CC_CORE_FERROR2', 'El ID del miembro está vacio');
define('_PLUG_PAY_CC_CORE_FERROR3', 'ID del Pago esta vacio');
define('_PLUG_PAY_CC_CORE_FERROR4', 'El dueño del pago es incorrecto');
define('_PLUG_PAY_CC_CORE_FERROR5', 'El pago ya está siendo procesado, Favor ir a la %sPagina de la Membresía%s');
define('_PLUG_PAY_CC_CORE_FERROR6', 'Ya te has registrado por esta muestra Gratis  - Favor regresar a la <a href=\'%s/signup.php\'>pagina de registro</a> y elige otro producto');
define('_PLUG_PAY_CC_CORE_SBSCNCL', 'Suscripcion cancelada');
define('_PLUG_PAY_CC_CORE_SBSCNCL2', 'La suscripcion recurrente ha sido cancelada.');
define('_PLUG_PAY_CC_CORE_CCINFOCHNG', 'Informacion sobre la tarjeta de credito actualizada');
define('_PLUG_PAY_CC_CORE_REDIR', 'Redireccionando al sistema de pago');
define('_PLUG_PAY_CC_CORE_FERROR7', 'Accion en blanco');

define('_TPL_CC_INFO_PROVINCE', 'Provincia Internacional Que manda la cuenta');
define('_TPL_CC_INFO_PROVINCE_DESC', 'Para las provincias internacionales fuera de los E.E.U.U. y de Canada incluya el nombre de la provincia aqui');
define('_TPL_CC_INFO_ISSUENUM', 'La edicion de la tarjeta #');
define('_TPL_CC_INFO_ISSUENUM_DESC', 'se requiere para las tarjetas de credito de Maestro/Solo/Switch solamente');
define('_TPL_CC_INFO_STARTDATE', 'Fecha Del Comienzo De la Tarjeta');
define('_TPL_CC_INFO_STARTDATE_DESC', 'se requiere para las tarjetas de credito de Maestro/Solo/Switch solamente');


define('_PLUG_PAY_CC_CORE_REDIR', 'Redireccionando al sistema de pago');
define('_PLUG_PAY_CC_CORE_REDIRDESC', 'Seras redireccionado automaticamente en 2 segundos a una pagina segura para el pago');
define('_PLUG_PAY_CC_CORE_ERROR1', 'Favor introducir su Número de la tarjeta de credito');
define('_PLUG_PAY_CC_CORE_ERROR2', 'Número de tarjeta de credito invalido');
define('_PLUG_PAY_CC_CORE_ERROR3', 'Número de la tarjeta de credito invalido: ');
define('_PLUG_PAY_CC_CORE_ERROR4', 'Inválido : Expiración - Mes');
define('_PLUG_PAY_CC_CORE_ERROR5', 'Inválido : Expiración - Año');
define('_PLUG_PAY_CC_CORE_ERROR6', 'Favor seleccionar un tipo de tarjeta de credito');
define('_PLUG_PAY_CC_CORE_ERROR7', 'Favor introducir el codigo de la tarjeta de credito');
define('_PLUG_PAY_CC_CORE_ERROR8', 'Favor introducir el tarjetahabiente');
define('_PLUG_PAY_CC_CORE_ERROR9', 'Favor introducir el Nombre');
define('_PLUG_PAY_CC_CORE_ERROR10', 'Favor introducir el apellido');
define('_PLUG_PAY_CC_CORE_ERROR11', 'Favor introducir la compañia de la tarjeta');
define('_PLUG_PAY_CC_CORE_ERROR12', 'Favor introducir un numero telefonico');
define('_PLUG_PAY_CC_CORE_ERROR13', 'Favor introducir el numero de casa');
define('_PLUG_PAY_CC_CORE_ERROR14', 'Favor introducir la calle');
define('_PLUG_PAY_CC_CORE_ERROR15', 'Favor introducir Ciudad');
define('_PLUG_PAY_CC_CORE_ERROR16', 'Favor introducir Estado');
define('_PLUG_PAY_CC_CORE_ERROR17', 'Favor introducir el Codigo Postal');
define('_PLUG_PAY_CC_CORE_ERROR18', 'Favor introducir el País');

define('_PLUG_PAY_CC_CORE_ERROR19', 'Fecha Invalida Del Comienzo - Mes');
define('_PLUG_PAY_CC_CORE_ERROR20', 'Fecha Invalida Del Comienzo - Ano');





define('_PLUG_PAY_CC_BILL_TITLE', 'Tarjeta de Credito');
define('_PLUG_PAY_CC_BILL_DESCR', 'Paga con MasterCard, Checkcards, Discover, JCB, Electronic via www.ccbill.com');
define('_PLUG_PAY_CC_BILL_CHECK_DESCR', 'Paga con cheques virtuales en www.ccbill.com');
define('_PLUG_PAY_CC_BILL_TEL_DESCR', 'Recibo del telefono via www.ccbill.com');
define('_PLUG_PAY_CC_BILL_ERROR', 'Usuario y Contraseña no pueden ser los mismos, Favor elegir otra contraseña');





define('_PLUG_PAY_CDG_TITLE', 'CDG');
define('_PLUG_PAY_CDG_DESCR', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_CENTIP_TITLE', 'Centipaid ');
define('_PLUG_PAY_CENTIP_DESC', '%sDigital Stored Value Cards%s');
define('_PLUG_PAY_CENTIP_FERROR', 'centipaid ERROR: %s (Detalles: PNREF:%s, recibo:%s)%s');
define('_PLUG_PAY_CENTIP_ERROR', 'Error al procesar el pago: ');
define('_PLUG_PAY_CENTIP_ERROR2', ' Favor regresar e intentar nuevamente');
define('_PLUG_PAY_CENTIP_ERROR3', 'Monto en Cero');
define('_PLUG_PAY_CENTIP_ERROR4', 'Transaccion de prueba procesada, Cuando aMember este configurado para trabajar en linea');
define('_PLUG_PAY_CENTIP_ERROR5', 'Espera del proceso de pago dió error: %s');





define('_PLUG_PAY_CLICKBANK_TITLE', 'Clickbank');
define('_PLUG_PAY_CLICKBANK_DESC', 'Ir %swww.clickbank.com%s para la descripcion');
define('_PLUG_PAY_CLICKBANK_INCORRECT', 'Proceso incorrecto #%d. Contactar al webmaster');
define('_PLUG_PAY_CLICKBANK_ERROR', 'Espera del proceso de pago dió error: ');





define('_PLUG_PAY_DIRECTONE_TITLE', 'DirectOne');
define('_PLUG_PAY_DIRECTONE_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_DIRECTONEREM_TITLE', 'Pago de Tarjeta de Credito (DirectOne)');
define('_PLUG_PAY_DIRECTONEREM_DESC', 'ir %swww.directone_remote.com%s para la descripcion');
define('_PLUG_PAY_DIRECTONEREM_RETLNK', 'Regresar a la pagina de la membresía');
define('_PLUG_PAY_DIRECTONEREM_ERROR', 'directone ERROR: %s (Detalles: PNREF:%s, Recibo:%d)%s');





define('_PLUG_PAY_PAYMENOW_TITLE', 'PayMeNow');
define('_PLUG_PAY_PAYMENOW_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_PAYMONDE_TITLE', 'PayMonde');
define('_PLUG_PAY_PAYMONDE_DESC', 'Ir %swww.paymonde.com%s para la descripcion');

define('_PLUG_PAY_PAYMONDE_FERROR', 'paymonde ERROR: %s (Detalles: payment_id:%d, recibo:%d)');
define('_PLUG_PAY_PAYMONDE_ERROR', 'Respuesta incorrecta desde el servidor de PayMonde.  Posible intento de hack.');





define('_PLUG_PAY_CC_DEMO_TITLE', 'CCDemo');
define('_PLUG_PAY_CC_DEMO_DESCR', 'Demo - Pago de Tarjeta de Credito - usar 4111-1111-1111-1111 como el # de la tarjeta de credito');
define('_PLUG_PAY_CC_DEMO_CCNUM', 'Favor introducir el # de tarjeta de credito : 4111-1111-1111-1111 Para completar la demostracion');





define('_PLUG_PAY_ECHO_TITLE', 'ECHO');
define('_PLUG_PAY_ECHO_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_EFSNET_TITLE', 'EFSNet');
define('_PLUG_PAY_EFSNET_DESC', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_EFSNET_ERROR', 'Pago no encontrado: #%d');
define('_PLUG_PAY_EFSNET_ERROR2', 'Pago ya completado: #%d');
define('_PLUG_PAY_EFSNET_ERROR3 ', 'Pago creado para otro sistema de pagos: %d (#%d)');
define('_PLUG_PAY_EFSNET_ERROR4', 'Pago creado para otro miembro: #%d');
define('_PLUG_PAY_EFSNET_ERROR5', 'Miembro no encontrado: #%d');
define('_PLUG_PAY_EFSNET_ERROR6', 'aMember: Valor neutro para la transaccion, El sistema dió error');





define('_PLUG_PAY_EGOLD_TITLE', 'E-Gold');
define('_PLUG_PAY_EGOLD_DESC', 'Paga con e-gold (ir %swww.e-gold.com%s para la descripcion)');
define('_PLUG_PAY_EGOLD_ERROR', 'EGOLD ERROR: %s (Detalles: PAYMENT_BATCH_NUM:%d, recibo:%d)%s');
define('_PLUG_PAY_EGOLD_ERROR2', 'El pago va a nombre de %s en vez de mi: ');
define('_PLUG_PAY_EGOLD_ERROR3', 'Unidades diferentes: %s en vez de %s');
define('_PLUG_PAY_EGOLD_ERROR4', 'V2_HASH error %s en vez de: %s');





define('_PLUG_PAY_EMATTERS_TITLE', 'eMatters.com.au');
define('_PLUG_PAY_EMATTERS_DESC', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_EMATTERS_ERROR', 'Transacción Decilnada%s. Favor intentar de nuevo');
define('_PLUG_PAY_EMATTERS_CODE0', 'Transacción Aprobada.');
define('_PLUG_PAY_EMATTERS_CODE1', 'Transacción Decilnada. Ver el banco de la tarjeta.');
define('_PLUG_PAY_EMATTERS_CODE2', 'Transacción Decilnada. Llamada al centro de autorizacion.');
define('_PLUG_PAY_EMATTERS_CODE3', 'Transacción Aprobada. Favor firmar recibo.');
define('_PLUG_PAY_EMATTERS_CODE4', 'Transacción Decilnada. Tipo de transaccion invalido.');
define('_PLUG_PAY_EMATTERS_CODE5', 'Transacción Decilnada. Ver el banco de la tarjeta.');
define('_PLUG_PAY_EMATTERS_CODE6', 'Transacción Decilnada. No cuenta de CREDITO.');
define('_PLUG_PAY_EMATTERS_CODE7', 'Transacción Decilnada. Fondos insuficientes.');
define('_PLUG_PAY_EMATTERS_CODE8', 'Transacción Decilnada. Sobre limite.');
define('_PLUG_PAY_EMATTERS_CODE9', 'Transacción Decilnada. Banco no disponible.');
define('_PLUG_PAY_EMATTERS_CODE10', 'Non-Unique UID - Ya aceptado');
define('_PLUG_PAY_EMATTERS_CODE11', 'Transacción Aprobada - Tipo de tarjeta erroneo');
define('_PLUG_PAY_EMATTERS_CODE12', 'Monto de compra invalido');
define('_PLUG_PAY_EMATTERS_CODE13', 'Numero de tarjeta no aceptado');
define('_PLUG_PAY_EMATTERS_CODE14', 'Formato de fecha en la expiracion invalido');
define('_PLUG_PAY_EMATTERS_CODE15', 'Tarjeta Expirada');
define('_PLUG_PAY_EMATTERS_CODE16', 'Host no encontrado, El sistema del banco fuera de linea');
define('_PLUG_PAY_EMATTERS_CODE17', 'Camino perdido, La linea del banco no encontrada');
define('_PLUG_PAY_EMATTERS_ERROR', 'Transacción Decilnada%s. Favor intentar de nuevo');

define('_PLUG_PAY_EMATTERS_HTML_TITLE', 'Confirmacion de Pago');
define('_PLUG_PAY_EMATTERS_HTML_SELECTC', 'Seleccionar tarjeta');
define('_PLUG_PAY_EMATTERS_HTML_CCNUM', 'Número de la tarjeta de credito');
define('_PLUG_PAY_EMATTERS_HTML_CCEXP', 'Expiracion');
define('_PLUG_PAY_EMATTERS_HTML_CCHNAME', 'Nombre del Tarjeta-habiente');
define('_PLUG_PAY_EMATTERS_HTML_GOTOSITE', 'Ir a un sitio seguro');
define('_PLUG_PAY_EMATTERS_HTML_FORMSUBM', 'Este formulario sera dirigido a un sitio seguro.');
define('_PLUG_PAY_EMATTERS_HTML_CCTYPE', 'Tipo de Tarjeta de Credito');





define('_PLUG_PAY_EPASSPORT_TITLE', 'Epassporte');
define('_PLUG_PAY_EPASSPORT_DESC', 'Epassporte Procesando pago');
define('_PLUG_PAY_EPASSPORT_HTML_TITLE', 'Pago Paycom');
define('_PLUG_PAY_EPASSPORT_HTML_CLICKPAY', 'Favor ir a "Pagar con ePassporte" Para continuar tu pago con ePassporte, Nuestro agente de ventas autorizado.');
define('_PLUG_PAY_EPASSPORT_ERROR', 'epassporte ERROR:');
define('_PLUG_PAY_EPASSPORT_ERROR2', 'Error al procesar el pago: ');
define('_PLUG_PAY_EPASSPORT_ERROR3', ' Favor regresar e intentar nuevamente.');

define('_PLUG_PAY_EPASSPORT_ERROR4', 'Epassporte IPN ERROR: %s (Detalles: recibo:%d)%s');
define('_PLUG_PAY_EPASSPORT_ERROR5', 'Epassporte IPN: Pago Fallido (Detalles: recibo:%d)%s');
define('_PLUG_PAY_EPASSPORT_ERROR6', '# de cuenta incorrecto');
define('_PLUG_PAY_EPASSPORT_ERROR7', 'Error en Direccion IP: %s , Mascara de ip permitida: ');
define('_PLUG_PAY_EPASSPORT_ERROR8', 'Postback Contraseña incorrecta: %s');
define('_PLUG_PAY_EPASSPORT_ERROR9', 'La transaccion fue denegada: ');
define('_PLUG_PAY_EPASSPORT_ERROR10', 'Gracias por tu compra!');
define('_PLUG_PAY_EPASSPORT_ERROR11', 'Verificacion del proceso de la transaccion (TVP) obtuvo un error: ');
define('_PLUG_PAY_EPASSPORT_ERROR12', 'ePassporte IPN: la transaccion por el pago %d fue aceptada y verificada');





define('_PLUG_PAY_EPROCESSING_TITLE', 'eProcessingNetwork');
define('_PLUG_PAY_EPROCESSING_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_EWAY_TITLE', 'E-Way');
define('_PLUG_PAY_EWAY_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_FREE_ID', 'gratis');
define('_PLUG_PAY_FREE_TITLE', 'Registro Gratis');
define('_PLUG_PAY_FREE_DESC', 'Totalmente Gratis');
define('_PLUG_PAY_FREE_NOTFORFREE', 'No se puede usar el sistema gratis con productos que el costos sea mayor a 0.0');
define('_PLUG_PAY_FREE_ERROR', 'Codigo de verificacion incorrecto. Contactar al webmaster si cree que esto  es un error.');
define('_PLUG_PAY_FREE_MAILSENT', 'Correo ya habia sido enviado al Administrador. Favor esperar por la aprobacion.');
define('_PLUG_PAY_FREE_SIGNEDUP', 'Ya estas inscrito. Favor %sEntrar%s aqui');





define('_PLUG_PAY_GLOBILL_ID', 'globill');
define('_PLUG_PAY_GLOBILL_TITLE', 'Glo-Bill Tarjeta de Credito');
define('_PLUG_PAY_GLOBILL_DESC', 'Paga con Visa, Mastercard, Checkcards, Discover, Eurocard, JCB, Diners cards, Electronic  vía  %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_PH_ID', 'globill_phone');
define('_PLUG_PAY_GLOBILL_PH_TITLE', 'Telefono de Glo-Bill');
define('_PLUG_PAY_GLOBILL_PH_DESC', 'Paga facil via telefono por %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_CH_ID', 'globill_check');
define('_PLUG_PAY_GLOBILL_CH_TITLE', 'Cheque Glo-Bill');
define('_PLUG_PAY_GLOBILL_CH_DESC', 'Paga con cheques virtuales via %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_CANNOTORDER', 'Este producto no puede ser ordenado con la tarjeta de credito de GloBill');
define('_PLUG_PAY_GLOBILL_CANNOTORDER2', 'Este producto no puede ser ordenado con el recibo del telefono de GloBill');
define('_PLUG_PAY_GLOBILL_CANNOTORDER3', 'Este producto no puede ser ordenado con cheque virtual de GloBill');
define('_PLUG_PAY_GLOBILL_ERROR', 'Error INTERNO: paysys_id desconocido: %d');
define('_PLUG_PAY_GLOBILL_FERROR', 'GLOBILL ERROR: %s (Detalles: PNREF:%s, recibo:%d)%s');
define('_PLUG_PAY_GLOBILL_ERROR2', 'Nombre de usuario del webmaster erroneo: %s!');





define('_PLUG_PAY_IKOBO_TITLE', 'ikobo');
define('_PLUG_PAY_IKOBO_DESC', 'Pago seguro de Tarjeta de Credito');
define('_PLUG_PAY_IKOBO_ERROR', 'Postback Contraseña incorrecta');





define('_PLUG_PAY_INTERSEC_TITLE', 'InternetSecure');
define('_PLUG_PAY_INTERSEC_DESC', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_INTERSEC_ERROR', 'Submision incorrecta. Favor contactar al webmaster');





define('_PLUG_PAY_IPAYMENT_TITLE', 'IPayment.DE');
define('_PLUG_PAY_IPAYMENT_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_LINKPOINT_TITLE', 'LinkPoint');
define('_PLUG_PAY_LINKPOINT_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_MANCC_FERROR', 'Tienes que estar autorizado a hacerlo');
define('_PLUG_PAY_MANCC_FERROR2', 'ID del pago no fue especificado');
define('_PLUG_PAY_MANCC_FERROR3', 'El historial del miembro no puede ser cargado #%d (%d)');
define('_PLUG_PAY_MANCC_ERROR', 'Número de la tarjeta de credito invalido');
define('_PLUG_PAY_MANCC_ERROR2', 'Fecha de Expiracion incorrecto (Mes)');
define('_PLUG_PAY_MANCC_ERROR3', 'Fecha de Expiracion incorrecto (Año)');
define('_PLUG_PAY_MANCC_ERROR4', 'Calle');
define('_PLUG_PAY_MANCC_ERROR5', 'Ciudad');
define('_PLUG_PAY_MANCC_ERROR6', 'Estado');
define('_PLUG_PAY_MANCC_ERROR7', 'Codigo Postal');
define('_PLUG_PAY_MANCC_ERROR8', 'País');
define('_PLUG_PAY_MANCC_ID', 'manual_cc');
define('_PLUG_PAY_MANCC_TITLE', 'Tarjeta de Credito');
define('_PLUG_PAY_MANCC_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_LOGICCOM_TITLE', 'LogicCommerce');
define('_PLUG_PAY_LOGICCOM_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_MONEYBOOK_ERROR', 'Incorrecto MD5: obtuvimos %s, pero calculado es %s (desde %s)');
define('_PLUG_PAY_MONEYBOOK_ERROR2', 'moneybookers ERROR: %s (Detalles: txn_id:%d, recibo:%d)%s');
define('_PLUG_PAY_MONEYBOOK_ERROR3', 'Esta pagina no puede ser accesada desde un Explorador');
define('_PLUG_PAY_MONEYBOOK_ERROR4', 'Recibidor del pago debe ser %s en vez de: ');
define('_PLUG_PAY_MONEYBOOK_ERROR5', 'Pago no procesado, Estado: ');

define('_PLUG_PAY_MONEYBOOK_TITLE', 'MoneyBookers');
define('_PLUG_PAY_MONEYBOOK_DESC', 'Ir %swww.moneybookers.com%s para la descripcion');





define('_PLUG_PAY_MULTICARD_ERROR', 'multicards ERROR: %s (Detalles: PNREF:%s, recibo:%d)%s');
define('_PLUG_PAY_MULTICARD_ERROR2', 'Error al procesar el pago: ');
define('_PLUG_PAY_MULTICARD_ERROR3', 'Favor regresar e intentar de nuevo.');
define('_PLUG_PAY_MULTICARD_ERROR4', 'Pago Fallido');
define('_PLUG_PAY_MULTICARD_ERROR5', 'Monto recibido en Cero');
define('_PLUG_PAY_MULTICARD_ERROR6', 'Direccion de IP incorrecta');
define('_PLUG_PAY_MULTICARD_ERROR7', 'ID del negociante incorrecto');

define('_PLUG_PAY_MULTICARD_TITLE', 'Multi-Cards');
define('_PLUG_PAY_MULTICARD_DESCR', 'Multi-Cards Procesando la tarjeta de credito');

define('_PLUG_PAY_MULTICARD_HTML_TITLE', 'MultiCards Pagina de Pagos');
define('_PLUG_PAY_MULTICARD_HTML_CNAME', 'Tarjetahabiente');
define('_PLUG_PAY_MULTICARD_HTML_4CONT', 'para contactar');
define('_PLUG_PAY_MULTICARD_HTML_EMAIL', 'Correo de contacto');
define('_PLUG_PAY_MULTICARD_HTML_4CONTE', 'para contactar');
define('_PLUG_PAY_MULTICARD_HTML_CNAME', 'Tarjetahabiente');
define('_PLUG_PAY_MULTICARD_HTML_ASONCC', '%sexactamente%s como en la tarjeta');
define('_PLUG_PAY_MULTICARD_HTML_ADDRESS', 'Direccion');
define('_PLUG_PAY_MULTICARD_HTML_ADDOFCC', '%sexactamente%s como en la tarjeta');
define('_PLUG_PAY_MULTICARD_HTML_CITY', 'Ciudad');
define('_PLUG_PAY_MULTICARD_HTML_EXCITY', '%sexactamente%s Ciudad + Codigo Postal (No residentes de USA) del %starjetahabiente, ej. %sLondon E12 6HB%s');
define('_PLUG_PAY_MULTICARD_HTML_COUNTRY', 'Pais');
define('_PLUG_PAY_MULTICARD_HTML_EXCOUNTRY', '%sexactamente%s el del tarjetahabiente');
define('_PLUG_PAY_MULTICARD_HTML_STATE', 'Estado');
define('_PLUG_PAY_MULTICARD_HTML_EXSTATE', '%sexactamente%s el del tarjetahabiente');
define('_PLUG_PAY_MULTICARD_HTML_ZIP', 'ZIP');
define('_PLUG_PAY_MULTICARD_HTML_EXZIP', '%sexactamente%s el del tarjetahabiente ');
define('_PLUG_PAY_MULTICARD_HTML_IFNOTUSA', '(SI no esta en USA, digitar %s99999%s)');
define('_PLUG_PAY_MULTICARD_HTML_SUB_BUT', 'Proceder');





define('_PLUG_PAY_NETBILLING_FERROR', 'ID del miembro no especificado');
define('_PLUG_PAY_NETBILLING_FERROR2', 'Tienes que estar autorizado');
define('_PLUG_PAY_NETBILLING_FERROR3', 'ID de pago no especificado');
define('_PLUG_PAY_NETBILLING_FERROR4', 'No se puede cargar el historial del miembro #%d (%d)');
define('_PLUG_PAY_NETBILLING_ERROR', 'Número de la tarjeta de credito invalido');
define('_PLUG_PAY_NETBILLING_ERROR2', 'Fecha de Expiracion incorrecto (Mes)');
define('_PLUG_PAY_NETBILLING_ERROR3', 'Fecha de Expiracion incorrecto (año)');
define('_PLUG_PAY_NETBILLING_ERROR4', 'Favor introducir el Codigo de la Tarjeta');
define('_PLUG_PAY_NETBILLING_ERROR5', 'Calle');
define('_PLUG_PAY_NETBILLING_ERROR6', 'Ciudad');
define('_PLUG_PAY_NETBILLING_ERROR7', 'Seleccionar Estado');
define('_PLUG_PAY_NETBILLING_ERROR8', 'Código Postal');
define('_PLUG_PAY_NETBILLING_ERROR9', 'Seleccionar País');

define('_PLUG_PAY_NETBILLING_TITLE', 'NetBilling');
define('_PLUG_PAY_NETBILLING_CC_PAYMENT', 'Pago de Tarjeta de Credito');

define('_PLUG_PAY_NETBILLING_FERROR5', 'No hay usuario definido con NetBilling');
define('_PLUG_PAY_NETBILLING_PNOTFOUND', 'Pago no encontrado: #%d');
define('_PLUG_PAY_NETBILLING_PCOMPLETED', 'Pago ya completado: #%d');
define('_PLUG_PAY_NETBILLING_ANOTHERPSYS', 'Pago creado para otro sistema de pago:');
define('_PLUG_PAY_NETBILLING_ANOTHERMEMBER', 'Pago creado para otro Miembro: #%d');
define('_PLUG_PAY_NETBILLING_MEMNOTFOUND', 'Miembro no encontrado: #%d');
define('_PLUG_PAY_NETBILLING_EMPTYRES', 'aMember: El pago tubo errores en su proceso. El resultado obtenido fue en blanco');





define('_PLUG_PAY_NOCHEX_FERROR', 'nochex ERROR: %s (Detalles: txn_id:%d, Recibo:%d)%s');
define('_PLUG_PAY_NOCHEX_ERROR', 'pagina IPN debe ser accesada solamente por nochex, no por los clientes');
define('_PLUG_PAY_NOCHEX_ERROR2', 'El pago recibido es %s en vez de: ');
define('_PLUG_PAY_NOCHEX_ERROR3', 'DECLINADA, por el servidor de nochex. Posible intento de hack(%s)');
define('_PLUG_PAY_NOCHEX_ERROR4', 'No se encontrar letras Verificadas o denegadas en el resultado (%s)');

define('_PLUG_PAY_NOCHEX_TITLE', 'NoChex');
define('_PLUG_PAY_NOCHEX_DESC', 'Pago seguro de Tarjeta de Credito');





define('_PLUG_PAY_OFFLINE_TITLE', 'Pago Offline');
define('_PLUG_PAY_OFFLINE_DESC', 'Pago Offline');

define('_PLUG_PAY_OFFLINE_HTML_HEAD', 'Cambiar este archivo');
define('_PLUG_PAY_OFFLINE_HTML_HEAD2', 'para conocer tus necesidades y pagar offline.');
define('_PLUG_PAY_OFFLINE_HTML_PUSR', 'Pago # / Usuario: ');
define('_PLUG_PAY_OFFLINE_HTML_PRICE', 'Precio:     ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT1', 'Aquí las instrucciones para los clientes.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT2', 'Asegurese de que el cliente introducirá el # de pago y el Usuario');
define('_PLUG_PAY_OFFLINE_HTML_TEXT3', 'a la descripcion del pago. Entonces sera facil pra encontrarlo ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT4', 'odernar despues.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT5', 'Cuando recibas el pago completo, Ponga el pago como "Completado"');
define('_PLUG_PAY_OFFLINE_HTML_TEXT6', 'en el panel de Control. El usuario recibirá la informacion para entrar');
define('_PLUG_PAY_OFFLINE_HTML_TEXT7', 'entonces estara disponible para interactuar en el sitio.');





define('_PLUG_PAY_OGONE_TITLE', 'Ogone');
define('_PLUG_PAY_OGONE_DESC', 'Pago seguro con tarjetas de credito');
define('_PLUG_PAY_OGONE_ERROR', 'Codigo de estado desconocido: [%s]');
define('_PLUG_PAY_OGONE_ERROR2', 'El monto obtenido es neutro!');





define('_PLUG_PAY_PSWDCALL_FERROR', 'passwordcall ERROR: %s (Detalles: txn_id:%d, recibo:%d)%s');
define('_PLUG_PAY_PSWDCALL_ERROR', 'Webmaster falso: %d');
define('_PLUG_PAY_PSWDCALL_TITLE', 'PasswordCall');
define('_PLUG_PAY_PSWDCALL_DESC', 'Ir %swww.passwordcall.de%s para mas detalles');





define('_PLUG_PAY_BLUEPAY_TITLE', 'BluePay');
define('_PLUG_PAY_BLUEPAY_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_PAYFLINK_FERROR', 'PAYFLOW ERROR: %s (Detalles: PNREF:%s, recibo:%d)%s');
define('_PLUG_PAY_PAYFLINK_ERROR', 'Monto obtenido en CERO');

define('_PLUG_PAY_PAYFLINK_TITLE', 'Enlace a PayFlow');
define('_PLUG_PAY_PAYFLINK_DESC', 'Ir %swww.verisign.com%s para la descripcion');





define('_PLUG_PAY_PAYFLPRO_TITLE', 'PayFlow Pro');
define('_PLUG_PAY_PAYFLPRO_DESC', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_PAYFLPRO_ERROR', 'PayFlow plugin Error de configuracion: Archivo %s%s%s no encontrado');
define('_PLUG_PAY_PAYFLPRO_ERROR2', 'PayFlow plugin Error de configuracion: Archivo %s%s%s no ejecutable. chmod 755');
define('_PLUG_PAY_PAYFLPRO_FERROR', 'No se puede correro el script de pago');
define('_PLUG_PAY_PAYFLPRO_ERROR3', 'Error al correr el script pfpro, Resultado: %s');
define('_PLUG_PAY_PAYFLPRO_CCDECL', 'Tarjeta Declinada. Asegurate que la direccion suministrada coincida con la direccion donde recibes los estados de cuenta.');





define('_PLUG_PAY_PYMGTWAY_TITLE', 'PaymentsGateway');
define('_PLUG_PAY_PYMGTWAY_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_EGSPAY_TITLE', 'AC Pay');
define('_PLUG_PAY_EGSPAY_DESC', 'Ir <a href="http://www.egspay.com" target=_blank>www.egspay.com</a> para la descripcion');
define('_PLUG_PAY_EGSPAY_ERROR', 'egspay ERROR: %s (Detalles: recibo:%d)%s');





define('_PLUG_PAY_PAYPALR_INVEMAIL', 'Correo invalido: $email, saltado');
define('_PLUG_PAY_PAYPALR_IDEMPTY', 'Id de suscripcion en blanco %s');
define('_PLUG_PAY_PAYPALR_NOPAYMENTS', 'No historial de pagos encontrados para');
define('_PLUG_PAY_PAYPALR_2MUCHREC', 'Demasiado (>1) records de pagos encontrados');

define('_PLUG_PAY_PAYPALR_TITLE', 'PayPal');
define('_PLUG_PAY_PAYPALR_DESC', 'Pago de Tarjeta de Credito Seguro');
define('_PLUG_PAY_PAYPALR_FERROR', 'El periodo se tiene que encontrar en elintervalo de 1-5 años');
define('_PLUG_PAY_PAYPALR_FERROR2', 'El periodo se tiene que encontrar en elintervalo de 1-24 Meses');
define('_PLUG_PAY_PAYPALR_FERROR3', 'El periodo se tiene que encontrar en elintervalo de 1-52 Semanas');
define('_PLUG_PAY_PAYPALR_FERROR4', 'El periodo se tiene que encontrar en elintervalo de 1-90 Dias');
define('_PLUG_PAY_PAYPALR_FERROR5', 'Unidad de Periodo desconocida: %s');
define('_PLUG_PAY_PAYPALR_FERROR6', 'Valor incorrecto para la fecha de expiracion: ');
define('_PLUG_PAY_PAYPALR_FERROR7', 'La siguiente combinacion de productos (recurrentes y no recurrentes) no pueden ser ordenadas a la vez.');
define('_PLUG_PAY_PAYPALR_FERROR8', 'La siguiente combinacion de productos no pueden ser ordenadas a la vez.');
define('_PLUG_PAY_PAYPALR_FERROR9', 'Hay demasiados productos con diferentes tipos de monedas. Favor elegir otro conjunto de productos');
define('_PLUG_PAY_PAYPALR_ERROR', 'No se pudo validar el IPN de PayPal: FOPEN [%s] resultados a [%s (%s)]');
define('_PLUG_PAY_PAYPALR_ERROR2', 'Reclamacion de Paypal no tienen un # de transaccion IPN : [%s]');
define('_PLUG_PAY_PAYPALR_ERROR3', 'IPN Error al validar: %s');
define('_PLUG_PAY_PAYPALR_ERROR4', 'Recibidor del pago [%s] es desconocido, pPago ignorado.<br />');
define('_PLUG_PAY_PAYPALR_ERROR5', 'Si esta incorrecto, favor agregar una direccion de correo %s En el aMember CP -> Setup -> PayPal');
define('_PLUG_PAY_PAYPALR_ERROR6', 'El estado del Pago por PayPal es [%s], Mensajes del IPN seran ignorados<br />');
define('_PLUG_PAY_PAYPALR_ERROR7', 'No es un error o un problema, Es solo un mensaje para su informacion');
define('_PLUG_PAY_PAYPALR_ERROR8', 'La moneda de PayPal es [%s] en vez de la esperada: [%s]');
define('_PLUG_PAY_PAYPALR_ERROR9', 'Monto pasado es [%d], deberia ser [%d]');
define('_PLUG_PAY_PAYPALR_ERROR11', 'No se ha encontrado historial para este pago');
define('_PLUG_PAY_PAYPALR_ERROR12', 'Cupones no deben ser usado con pruebas de PayPal, Favor contactar al administrador');





define('_PLUG_PAY_PAYRDY_FERROR', 'Debes estar autorizado.');
define('_PLUG_PAY_PAYRDY_FERROR2', 'ID del pago no especificado');
define('_PLUG_PAY_PAYRDY_FERROR3', 'No se puede cargar el historial del miembro #%d (%d)');
define('_PLUG_PAY_PAYRDY_ERROR', 'Favor seleccionar un tipo de Tarjeta');
define('_PLUG_PAY_PAYRDY_ERROR2', 'Número de la tarjeta de credito Invalido');
define('_PLUG_PAY_PAYRDY_ERROR3', 'Fecha de Expiracion incorrecto (Mes)');
define('_PLUG_PAY_PAYRDY_ERROR4', 'Fecha de Expiracion incorrecto (año)');
define('_PLUG_PAY_PAYRDY_ERROR5', 'Calle');
define('_PLUG_PAY_PAYRDY_ERROR6', 'Ciudad');
define('_PLUG_PAY_PAYRDY_ERROR7', 'Seleccionar Estado');
define('_PLUG_PAY_PAYRDY_ERROR8', 'Código Postal');
define('_PLUG_PAY_PAYRDY_ERROR9', 'Seleccionar País');

define('_PLUG_PAY_PAYRDY_ERROR10', 'Pago no encontrado: #%d');
define('_PLUG_PAY_PAYRDY_ERROR11', 'Pago ya encontrado: #%d');
define('_PLUG_PAY_PAYRDY_ERROR12', 'Pago creado para otro sistema de pago: ');
define('_PLUG_PAY_PAYRDY_ERROR13', 'aMember: Resultado en blanco. Pago fallido.');
define('_PLUG_PAY_PAYRDY_ERROR14', 'Payment processor error: ');

define('_PLUG_PAY_PAYRDY_TITLE', 'PayReady');
define('_PLUG_PAY_PAYRDY_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_PAYZIP_TITLE', 'PayZIP');
define('_PLUG_PAY_PAYZIP_DESC', 'secure Pago de Tarjeta de Credito');
define('_PLUG_PAY_PAYZIP_ERROR', 'Mala Conneccion ');
define('_PLUG_PAY_PAYZIP_FERROR', 'No hay respuesta desde PayZIP - Transaccion abortada. Intentar mas tarde.');





define('_PLUG_PAY_PLUGNPAY_FERROR', 'ID del miembro no fue especificado');
define('_PLUG_PAY_PLUGNPAY_FERROR2', 'Tienes que estar autorizado');
define('_PLUG_PAY_PLUGNPAY_FERROR3', 'ID del pago no especificado');
define('_PLUG_PAY_PLUGNPAY_FERROR4', 'No se puede cargar el historial del miembro #%d (%d)');
define('_PLUG_PAY_PLUGNPAY_ERROR', 'No devolucion desde plugnpay, pago #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR2', 'Fecha de Expiracion incorrecto (Mes)');
define('_PLUG_PAY_PLUGNPAY_ERROR3', 'Fecha de Expiracion incorrecto (año)');
define('_PLUG_PAY_PLUGNPAY_ERROR4', 'Favor introducir el Codigo de la Tarjeta');
define('_PLUG_PAY_PLUGNPAY_ERROR5', 'Calle');
define('_PLUG_PAY_PLUGNPAY_ERROR6', 'Ciudad');
define('_PLUG_PAY_PLUGNPAY_ERROR7', 'Seleccionar Estado');
define('_PLUG_PAY_PLUGNPAY_ERROR8', 'Código Postal');
define('_PLUG_PAY_PLUGNPAY_ERROR9', 'Seleccionar País');
define('_PLUG_PAY_PLUGNPAY_ERROR10', 'Pago no encontrado: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR11', 'Pago ya encontrado: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR12', 'Pago creado para otro sistema de pago');
define('_PLUG_PAY_PLUGNPAY_ERROR13', 'Miembro no encontrado: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR14', 'Resultado neutro. Pago fallido: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR15', 'aMember: Resultado en blanco. Pago fallido.');

define('_PLUG_PAY_PLUGNPAY_TITLE', 'PlugNPay');
define('_PLUG_PAY_PLUGNPAY_DESC', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_PLUGNPAY_ERROR', 'No devolucion desde plugnpay, pago #%d');





define('_PLUG_PAY_PROBILLING_FERROR', 'PROBILLING ERROR: %s (Detalles: PNREF:%s, recibo:%d)<br />');
define('_PLUG_PAY_PROBILLING_ERROR', 'Estado no es nuevo o ya fué pagado');
define('_PLUG_PAY_PROBILLING_TITLE', 'ProBilling');
define('_PLUG_PAY_PROBILLING_DESC', 'Aceptamos tarjetas de credito, e-checks y soportamos 900 billing');





define('_PLUG_PAY_PROTX_TITLE', 'Protx');
define('_PLUG_PAY_PROTX_DESC', 'Pagado por Tarjeta de Credito/Debito - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');

define('_PLUG_PAY_PROTX_HTML_TITLE', 'Proceder a la pagina seguro y realizar el pago');





define('_PLUG_PAY_PSIGATE_TITLE', 'PsiGate');
define('_PLUG_PAY_PSIGATE_DESC', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_PSIGATE_ERROR', 'Error Interno');

define('_PLUG_PAY_PSIGATE_HTML_TITLE', 'Pago de Tarjeta de Credito Page');
define('_PLUG_PAY_PSIGATE_HTML_CNAME', 'Nombre');
define('_PLUG_PAY_PSIGATE_HTML_ASONCC', '%sexactamente%s como en la tarjeta');
define('_PLUG_PAY_PSIGATE_HTML_CCNUM', 'Número de la tarjeta de credito');
define('_PLUG_PAY_PSIGATE_HTML_CCEXP', 'Expira en:');
define('_PLUG_PAY_PSIGATE_HTML_JAN', 'Enero');
define('_PLUG_PAY_PSIGATE_HTML_FEB', 'Febrero');
define('_PLUG_PAY_PSIGATE_HTML_MAR', 'Marzo');
define('_PLUG_PAY_PSIGATE_HTML_APR', 'Abril');
define('_PLUG_PAY_PSIGATE_HTML_MAY', 'Mayo');
define('_PLUG_PAY_PSIGATE_HTML_JUN', 'Junio');
define('_PLUG_PAY_PSIGATE_HTML_JUL', 'Julio');
define('_PLUG_PAY_PSIGATE_HTML_AUG', 'Augosto');
define('_PLUG_PAY_PSIGATE_HTML_SEP', 'Septiembre');
define('_PLUG_PAY_PSIGATE_HTML_OCT', 'Octubre');
define('_PLUG_PAY_PSIGATE_HTML_NOV', 'Noviembre');
define('_PLUG_PAY_PSIGATE_HTML_DEC', 'Diciembre');
define('_PLUG_PAY_PSIGATE_HTML_ADDR', 'Direccion');
define('_PLUG_PAY_PSIGATE_HTML_ADOFCC', '%sexactamente%s como en la informacion de la tarjeta');
define('_PLUG_PAY_PSIGATE_HTML_CITY', 'Ciudad');
define('_PLUG_PAY_PSIGATE_HTML_CTOFCC', '%sexactamente%s como en la informacion de la tarjeta');
define('_PLUG_PAY_PSIGATE_HTML_COUNTRY', 'Pais');
define('_PLUG_PAY_PSIGATE_HTML_CNOFCC', '%sexactamente%s como en la informacion de la tarjeta');
define('_PLUG_PAY_PSIGATE_HTML_STATE', 'Estado');
define('_PLUG_PAY_PSIGATE_HTML_STOFCC', '%sexactamente%s como en la informacion de la tarjeta');
define('_PLUG_PAY_PSIGATE_HTML_ZIP', 'Codigo Postal');
define('_PLUG_PAY_PSIGATE_HTML_SUBBUT', 'Proceder');
define('_PLUG_PAY_PSIGATE_HTML_DESCR', 'Este formulario sera enviado a un servidor seguro');





define('_PLUG_PAY_QCHEX_TITLE', 'QChex');
define('_PLUG_PAY_QCHEX_DESC', 'Paga con cheque (ir %swww.qchex.com%s para la descripcion)');





define('_PLUG_PAY_SECURTRD_FERROR', 'securetrading ERROR: %s (Detalles: txn_id:%d, recibo:%d)%s');
define('_PLUG_PAY_SECURTRD_TITLE', 'SecureTrading');
define('_PLUG_PAY_SECURTRD_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_STORMPAY_FERROR', 'StormPay ERROR: %s (Detalles: txn_id:%d, recibo:%d)%s');
define('_PLUG_PAY_STORMPAY_ERROR', 'Codigo secreto es falso: %s');
define('_PLUG_PAY_STORMPAY_ERROR2', 'Recibidor del pago es %s en vez de: ');
define('_PLUG_PAY_STORMPAY_ERROR3', 'Pago no procesado, estado: %s');

define('_PLUG_PAY_STORMPAY_TITLE', 'StormPay');
define('_PLUG_PAY_STORMPAY_DESC', 'Ir %swww.stormpay.com%s para la descripcion');





define('_PLUG_PAY_INETCOM_FERROR', 'ID del miembro no fue especificado');
define('_PLUG_PAY_INETCOM_FERROR2', 'Tienes que estar autorizado');
define('_PLUG_PAY_INETCOM_FERROR3', 'ID del pago no especificado');
define('_PLUG_PAY_INETCOM_FERROR4', 'No se puede cargar el historial del miembro #%d (%d)');
define('_PLUG_PAY_INETCOM_ERROR', 'Número de la tarjeta de credito inválido');
define('_PLUG_PAY_INETCOM_ERROR2', 'Fecha de Expiracion incorrecto (Mes)');
define('_PLUG_PAY_INETCOM_ERROR3', 'Fecha de Expiracion incorrecto (año)');
define('_PLUG_PAY_INETCOM_ERROR4', 'Favor introducir el Codigo de la Tarjeta');
define('_PLUG_PAY_INETCOM_ERROR5', 'Calle');
define('_PLUG_PAY_INETCOM_ERROR6', 'Ciudad');
define('_PLUG_PAY_INETCOM_ERROR7', 'Seleccionar Estado');
define('_PLUG_PAY_INETCOM_ERROR8', 'Código Postal');
define('_PLUG_PAY_INETCOM_ERROR9', 'Seleccionar País');
define('_PLUG_PAY_INETCOM_ERROR10', 'Pago no encontrado: #%d');
define('_PLUG_PAY_INETCOM_ERROR11', 'Pago ya encontrado: #%d');
define('_PLUG_PAY_INETCOM_ERROR12', 'Pago creado para otro sistema de pago: %s (#%d)');
define('_PLUG_PAY_INETCOM_ERROR13', 'Miembro no encontrado: #%d');

define('_PLUG_PAY_INETCOM_TITLE', 'TheInternetCommerce');
define('_PLUG_PAY_INETCOM_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_24eKOUT_TITLE', '2Checkout');
define('_PLUG_PAY_24eKOUT_DESC', 'comprar desde 2Checkout');
define('_PLUG_PAY_24eKOUT_ERROR', 'Se trato de usar el modo DEMO, pero no esta habilitado');
define('_PLUG_PAY_24eKOUT_ERROR2', 'La tarjeta de credito no pudo ser procesada');
define('_PLUG_PAY_24eKOUT_ERROR3', 'Imposible de validar si pagó, favor contactar al webmaster');





define('_PLUG_PAY_WORLDPAY_FERROR', 'WORLDPAY ERROR: %s (Detalles: PNREF:%s, recibo:%d)%s');
define('_PLUG_PAY_WORLDPAY_ERROR', 'Direccion IP incorrecta para el envio de WorldPay');
define('_PLUG_PAY_WORLDPAY_ERROR2', 'Transacción Declinada (%s)');
define('_PLUG_PAY_WORLDPAY_ERROR3', 'Modo prueba deshabilitado');
define('_PLUG_PAY_WORLDPAY_ERROR4', 'ID de instalacion incorrecto: no es nuestro pago');
define('_PLUG_PAY_WORLDPAY_ERROR5', 'el monto devuelto es neutro');
define('_PLUG_PAY_WORLDPAY_ERROR6', 'Pago ya procesado (recibo#: %d) en pago #%d');

define('_PLUG_PAY_WORLDPAY_TITLE', 'WorldPay');
define('_PLUG_PAY_WORLDPAY_DESC', 'Paga con Tarjeta de Credito/Debito - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');
define('_PLUG_PAY_WORLDPAY_FERROR2', 'Unidad de periodo invalida expire_days. Tendria que ser d|m|w|y');
define('_PLUG_PAY_WORLDPAY_FERROR3', 'Valor incorrecto para $s: %s');
define('_PLUG_PAY_WORLDPAY_FERROR4', 'Valor incorrecto para %s en el producto #');





define('_PLUG_PAY_VEROTEL_FERROR', 'VEROTEL ERROR: %s (Detalles: recibo:%d)%s');

define('_PLUG_PAY_VEROTEL_TITLE', 'VeroTel');
define('_PLUG_PAY_VEROTEL_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_PAYPALPRO_TITLE', 'Pagar con PayPal');
define('_PLUG_PAY_PAYPALPRO_DESC', 'Rapido y seguro pago con PayPal.<br />Ahorra tiempo. Paga seguro. Paga sin compartir<br />informacion financiera.');
define('_PLUG_PAY_PAYPALPRO_FERROR', 'Hay muchos productos con diferentes moendas. Esta orden es imposible de procesar.');
define('_PLUG_PAY_PAYPALPRO_FERROR2', 'Error Interno (get_caller): ');
define('_PLUG_PAY_PAYPALPRO_FERROR3', 'Moneda devuelta en blanco');
define('_PLUG_PAY_PAYPALPRO_REDIRECT', 'Redireccionando al portal de PayPal');
define('_PLUG_PAY_PAYPALPRO_REDIRECT2', 'Estas siendo transferido al portal de PayPal para finalizar el pago');
define('_PLUG_PAY_PAYPALPRO_FERROR4', 'Error Interno : ');
define('_PLUG_PAY_PAYPALPRO_FERROR5', 'Error Interno: ');
define('_PLUG_PAY_PAYPALPRO_FERROR6', 'Estado del pago incompleto, favor contactar el soporte tecnico de nuestro portal');
define('_PLUG_PAY_PAYPALPRO_FERROR7', 'Favor seguir los %spasos para registro nuevamente%s');
define('_PLUG_PAY_PAYPALPRO_ERROR', 'Moneda devuelta en blanco');
define('_PLUG_PAY_PAYPALPRO_ERROR2', 'Pago #%d no encontrado');
define('_PLUG_PAY_PAYPALPRO_FERROR8', 'txn_id devuelto en blanco');
define('_PLUG_PAY_PAYPALPRO_TITLE2', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_PAYPALPRO_DESC2', 'Paga con Tarjetas de Credito : Visa, MC, Discover o Amex ');

define('_PLUG_PAY_PAYPALPRO_HTML_TITLE', 'Confirmar tu pago');
define('_PLUG_PAY_PAYPALPRO_HTML_SPTITLE', 'Subscripcion/Producto');
define('_PLUG_PAY_PAYPALPRO_HTML_PRICE', 'Precio');
define('_PLUG_PAY_PAYPALPRO_HTML_SUBTOTAL', 'Subtotal');
define('_PLUG_PAY_PAYPALPRO_HTML_CPDSC', 'Descuento por cupon');
define('_PLUG_PAY_PAYPALPRO_HTML_TAXAM', 'Impuestos:');
define('_PLUG_PAY_PAYPALPRO_HTML_TOTAL', 'Total');
define('_PLUG_PAY_PAYPALPRO_HTML_SBBUT', 'Confirmar Pago ');





define('_PLUG_PAY_FIRSTPAY_TITLE', 'FirstPay.Net');
define('_PLUG_PAY_FIRSTPAY_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_MERCANYW_TITLE', 'MerchantAnyWhere');
define('_PLUG_PAY_MERCANYW_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_SECPAY_TITLE', 'SecPay');
define('_PLUG_PAY_SECPAY_DESC', 'Pago de Tarjeta de Credito');
define('_PLUG_PAY_SECPAY_ERROR', 'Error de Constructor: %s');
define('_PLUG_PAY_SECPAY_ERROR2', 'SOAP llamada incorrecta: ');
define('_PLUG_PAY_SECPAY_ERROR3', 'SOAP error: %s');





define('_PLUG_PAY_PROTXDIR_TITLE', 'Protx');
define('_PLUG_PAY_PROTXDIR_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_SAFEPAY_TITLE', 'SafePay');
define('_PLUG_PAY_SAFEPAY_DESC', 'Ir %swww.safepaysolutions.com%s para la descripcion');
define('_PLUG_PAY_SAFEPAY_ERROR', 'Error en la passphrase');
define('_PLUG_PAY_SAFEPAY_ERROR2', 'Error en el monto (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR3', 'Error en Cantidad de itemes (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR4', 'Error en el ID de transaccion (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR5', 'Transaccion no confirmada, el dinero no esta en tu cuenta SPS');
define('_PLUG_PAY_SAFEPAY_ERROR6', 'Resultado %s: Error de Pago');





define('_PLUG_PAY_SECUREPAY_TITLE', 'SecurePay');
define('_PLUG_PAY_SECUREPAY_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_GOOGLE_CHECKOUT_TITLE', 'Google Checkout');
define('_PLUG_PAY_GOOGLE_CHECKOUT_DESC', 'Pago de Tarjeta de Credito');





define('_PLUG_PAY_MANUAL_TITLE', 'Pago manual');





define('_PLUG_PAY_ALERTPAY_TITLE', 'AlertPay');
define('_PLUG_PAY_ALERTPAY_DESC', 'Pay by credit card');
define('_PLUG_PAY_ALERTPAY_FERROR2', 'Unknown period unit in expire_days. Should be d|m|w|y');
define('_PLUG_PAY_ALERTPAY_FERROR3', 'Incorrect value for $s: %s');
define('_PLUG_PAY_ALERTPAY_FERROR4', 'Incorrect value for %s in product #');
define('_PLUG_PAY_ALERTPAY_ERROR', 'Incorrect secret code');
define('_PLUG_PAY_ALERTPAY_FERROR', 'ALERTPAY ERROR: %s (Details: PNREF:%s, invoice:%d)%s');
define('_PLUG_PAY_ALERTPAY_ERROR2', 'Transaction declined (%s)');
define('_PLUG_PAY_ALERTPAY_ERROR3', 'Test mode disabled');
define('_PLUG_PAY_ALERTPAY_ERROR4', 'Incorrect merchant account: it is not our payment');
define('_PLUG_PAY_ALERTPAY_ERROR5', 'returned amount empty or = 0');
define('_PLUG_PAY_ALERTPAY_ERROR6', 'Payment is already processed (alertpay invoice#: %d) in payment #%d');







define('_PLUG_PAY_METACHARGE_TITLE', 'Metacharge');
define('_PLUG_PAY_METACHARGE_DESC', 'Pay by credit card/debit card - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');

define('_PLUG_PAY_METACHARGE_FERROR', 'METACHARGE ERROR: %s (Details: PNREF:%s, invoice:%d)%s');

define('_PLUG_PAY_METACHARGE_ERROR2', 'Transaction declined (%s)');
define('_PLUG_PAY_METACHARGE_ERROR3', 'Test mode disabled');
define('_PLUG_PAY_METACHARGE_ERROR4', 'Incorrect Installation ID: it is not our payment');
define('_PLUG_PAY_METACHARGE_ERROR5', 'returned amount empty or = 0');
define('_PLUG_PAY_METACHARGE_ERROR6', 'Payment is already processed (metacharge invoice#: %d) in payment #%d');

define('_PLUG_PAY_METACHARGE_FERROR2', 'Unknown period unit in expire_days. Should be d|m|w|y');
define('_PLUG_PAY_METACHARGE_FERROR3', 'Incorrect value for $s: %s');
define('_PLUG_PAY_METACHARGE_HTML_SUB_BUT', 'Click here if your browser does not automatically forward you');
define('_PLUG_PAY_METACHARGE_HTML_TITLE', 'Metacharge Payment');













//missed rows
define ('_TPL_SIGNUP_CAPTCHA', 'Enter Verification Text');
define ('_TPL_SIGNUP_CAPTCHA_1', 'Please type text from image');
define ('_TPL_AFF_PAYOUT_SAFEPAY_EMAIL', 'Your SafePaySolutions E-Mail address');
define ('_TPL_EMAIL_VER_TITLE_PROFILE', 'Email verification required');
define ('_TPL_EMAIL_VER_TEXT_PROFILE', 'Please check your email - verification email message has been just emailed to you. Once you receive this message, read it and follow instructions in this email to complete your email verification.');
define ('_TPL_MEMBER_MAIN_PAGE', 'Main Page');
define ('_TPL_PROFILE_EMAIL_NOT_VERIFIED', 'Email address is not verified!');
define ('_TPL_PROFILE_EMAIL_RESEND_VERIFICATION_EMAIL', 'Resend verification email');
define ('_TPL_NEWSLETTER_ARCHIVE_DATE', 'Date');
define ('_TPL_NEWSLETTER_ARCHIVE_SUBJECT', 'Subject');
define ('_TPL_NEWSLETTER_ARCHIVE_NO_ARCHIVE', 'You have no archive messages');
define('_SIGNUP_CAPTCHA_ERROR', 'Verification image entered incorrectly, please re-enter it carefully');
define('_AFF_ERROR_9', 'Please enter an email address for payouts');
define('_AFF_MEMBER_F7_1', 'SafePaySolutions address for affiliate payout');
define('_SETUP_THANK_YOU_PROTECTION', 'Setup your protection for protected areas. You can use .htaccess or PHP included files. To use the Cookie-Based login capability all of your protected files must be PHP! ');
define('_PLUG_PAY_AUTHORIZE_CIM_TITLE', 'Authorize CIM');
define('_PLUG_PAY_AUTHORIZE_CIM_DESC', 'Credit card payment');
define('_PLUG_PAY_ESOLUTIONS_TITLE', 'Merchant e-Solutions');
define('_PLUG_PAY_ESOLUTIONS_DESC', 'Credit card payment');
define('_TPL_SKYPAY_ADDRESS_TITLE', 'Billing address');
define('_TPL_SKYPAY_ADDRESS_CHOOSE', '*** Please choose ***');
define('_TPL_SKYPAY_ADDRESS_HOLDERNAME', 'Cardholder Name');
define('_TPL_SKYPAY_ADDRESS_ASONCARD', 'cardholder name, exactly as on the card');
define('_TPL_SKYPAY_ADDRESS_FLNAME', 'cardholder first and last name, exactly as%son the card');
define('_TPL_SKYPAY_ADDRESS_ADDRINFO', 'Please specify your billing address details');
define('_TPL_SKYPAY_ADDRESS_STRADDR', 'Address');
define('_TPL_SKYPAY_ADDRESS_STRADDR2', 'Address (2)');
define('_TPL_SKYPAY_ADDRESS_CITY', 'City');
define('_TPL_SKYPAY_ADDRESS_ZIP', 'Postal code / Zip code');
define('_TPL_SKYPAY_ADDRESS_COUNTRY', 'Country');
define('_TPL_SKYPAY_ADDRESS_PHONE', 'Phone');
define('_TPL_SKYPAY_ADDRESS_MUSTMATCH', '(must match your credit card statement delivery address)');
define('_TPL_SKYPAY_ADDRESS_BACK_BUT', 'Back');
define('_TPL_SKYPAY_ADDRESS_SUBMIT_BUT', 'Continue');
define('_TPL_SKYPAY_ADDRESS_SUBMIT_BUT_3', 'Subscribe and Pay');
define('_TPL_SKYPAY_PAY_TITLE', 'Confirm payment details');
define('_TPL_SKYPAY_PAY_SUBMIT', 'Continue to the Skypay Payment page');
define('_TPL_SKYPAY_ADDRESS_BILLING', 'Billing address details:');
define('_TPL_SKYPAY_PRODUCT_BILLING', 'Product details:');
define('_PLUG_PAY_SKYPAY_FERROR1', 'skypay ERROR: %s (Details: txn_id:%d, invoice:%d)%s');
define('_PLUG_PAY_SKYPAY_FERROR2', 'You are not logged in.');
define('_PLUG_PAY_SKYPAY_FERROR3', 'It seems to be not your payment, please go back and try again.');
define('_PLUG_PAY_SKYPAY_TITLE', 'Skypay');
define('_PLUG_PAY_SKYPAY_DESC', 'Pay by credit card/debit card');
define ('_TPL_SKYPAY_CANCEL_TITLE', 'Payment Cancelled');
define ('_TPL_SKYPAY_CANCEL_ERROR', 'Your payment has been cancelled.');
define ('_TPL_SKYPAY_CANCEL_GOTO', 'To see your subscription details please go to %sMembership page%s.');
?>