<?php
/**
 * hr.php
 * Croatian Lanuage file
 * @author   Alex Scott <alex@cgi-central.net>
 * @package  aMember_Core
 * @translated by   Sanjin Barac <update.soft.sanjin@gmail.com>
 * @version  $Id: hr.php 3200 2008-08-20 13:28:07Z caesar $
 * @license  http://www.amember.com/p/Main/License
 * @copyright Copyright &copy; 2006, Alex Scott
 * DO NOT EDIT THIS FILE FOR CUSTOMIZATION, READ readme.txt for details
 */

defined( 'INCLUDED_AMEMBER_CONFIG' ) or die( 'Direktan pristup nije dozvoljen' );

define ('_TPL_POWEREDBY', 'Powered by %saMember Pro%s membership software');

define('_TPL_INDEX_IF_YOU_ARE_REGISTERED', 'Ako ste registriran èlan, molimo %slogin%s');
define('_TPL_INDEX_IF_YOU_ARE_NOT_REGISTERED', 'Ako još niste registrirani, molimo %ssignup%s');
define('_TPL_LOGIN_PLEASE_LOGIN', 'Molimo da se logirate');
define('_TPL_LOGIN_USERNAME', 'Korisnièko ime');
define('_TPL_LOGIN_PASSWORD', 'Lozinka');
define('_TPL_LOGIN_REMEMBER_MY_PASSWORD', 'Zapamti moju lozinku?');
define('_TPL_LOGIN_NOT_REGISTERED_YET', 'Niste još registrirani?');
define('_TPL_LOGIN_SIGNUP_HERE', 'Registrirajte se ovdje');
define('_TPL_LOGIN_LOST_PASSWORD', 'Izgubljena lozinka');
define('_TPL_LOGIN_ENTER_YOUR_EMAIL_OR_USERNAME', 'Unesite vašu <b>Email adresu</b> ili <b>Korisnièko ime</b>');
define('_TPL_LOGIN_BTN_LOGIN', 'Prijava');
define('_TPL_LOGIN_BTN_BACK', 'Natrag');
define('_TPL_LOGIN_BTN_GET_PASSWORD', 'Uzmi lozinku');

define ('_TPL_SIGNUP_MEM_TYPE', 'Odredite vrstu èlanstva');
define ('_TPL_SIGNUP_TITLE', 'Registracija');
define ('_TPL_AFF_SIGNUP_TITLE', 'Registracija affiliate èlanova');
define ('_TPL_SIGNUP_MEMB_TYPE', 'Vrsta èlanstva');
define ('_TPL_SIGNUP_FREE', 'besplatno');
define ('_TPL_SIGNUP_SELECT_PSYS', 'Odredite sistem za plaæanje');
define ('_TPL_SIGNUP_PAYSYS', 'Sistem za plaæanje');
define ('_TPL_SIGNUP_NAME', 'Vaše ime');
define ('_TPL_SIGNUP_NAME_1', 'Vaše ime &amp; prezime');
define ('_TPL_SIGNUP_EMAIL', 'Vaša Email adresa');
define ('_TPL_SIGNUP_EMAIL_1', 'Jedna email poruka bit æe vam poslana za potvrdu');
define ('_TPL_SIGNUP_EMAIL_2', 'na ovu adresu');
define ('_TPL_SIGNUP_LOGIN', 'Izaberite Korisnièko ime (User ID)');
define ('_TPL_SIGNUP_LOGIN_1', 'Mora sadržavati %d ili više znakova i može');
define ('_TPL_SIGNUP_LOGIN_2', 'sadržavati samo mala slova, brojeve, i');
define ('_TPL_SIGNUP_LOGIN_3', 'podvlaku \'_\'');
define ('_TPL_SIGNUP_CHECK_UNIQ', 'provjeri da li veä postoji');
define ('_TPL_SIGNUP_PSWD', 'Izaberite Lozinku');
define ('_TPL_SIGNUP_PSWD_1', 'Mora sadržavati %d ili više znakova');
define ('_TPL_SIGNUP_CAPTCHA', 'Unesite verifikacijski tekst');
define ('_TPL_SIGNUP_CAPTCHA_1', 'Molimo da upišete tekst iz slike');
define ('_TPL_SIGNUP_CONF_PSWD', 'Potvrdite svoju lozinku');
define ('_TPL_SIGNUP_CONF_PSWD_1', 'Unesite lozinku ponovo');
define ('_TPL_SIGNUP_NEWSLETTERS_SUBSCRIBE', 'Prijavite se na naš Newsletter');
define ('_TPL_SIGNUP_NEWSLETTERS_SUBSCRIBE_1', '');
define ('_TPL_SIGNUP_ADDR', 'ADRESA');
define ('_TPL_SIGNUP_STREET', 'Ulica');
define ('_TPL_SIGNUP_CITY', 'Grad');
define ('_TPL_SIGNUP_STATE', 'Regija / država');
define ('_TPL_SIGNUP_ZIP', 'Poštanski broj / zip');
define ('_TPL_SIGNUP_COUNTRY', 'Država');
define ('_TPL_SIGNUP_COUPONS', 'KUPON');
define ('_TPL_SIGNUP_COUPON_CODE', 'Unesite kupon kod');
define ('_TPL_SIGNUP_COUPON_1', 'ako ste dobili kupon od oglašavaèa,');
define ('_TPL_SIGNUP_COUPON_2', ' molimo da ga unesete ovdje');
define ('_TPL_SIGNUP_SUBMIT_CONTINUE', 'Nastavi');

define ('_TPL_AFFILIATE_TITLE', 'Affiliate info');
define ('_TPL_AFFILIATE_TXT_LINKS', 'Možete koristiti slijedeæi tekst da reklamirate našu web stranicu:');
define ('_TPL_AFFILIATE_HTML_CODE', 'HTML kod:');
define ('_TPL_AFFILIATE_BANNERS', 'Možete koristiti slijedeæe bannere da reklamirate našu web stranicu:');
define ('_TPL_AFFILIATE_BACK2_INFO', 'Natrag na stranicu sa Èlanskim podacima');

define ('_TPL_AFF_PAYOUT_TITLE', 'Promijenite podatke za isplatu');
define ('_TPL_AFF_PAYOUT_METHOD', 'NAÈIN ISPLATE');
define ('_TPL_AFF_PAYOUT_NOT_SELECTED', 'Nije odabrano');
define ('_TPL_AFF_PAYOUT_PP_EMAIL', 'Vaša PayPal email adresa');
define ('_TPL_AFF_PAYOUT_STORM_EMAIL', 'Vaša StormPay email adresa');
define ('_TPL_AFF_PAYOUT_IKOBO_EMAIL', 'Vaša iKobo email adresa');
define ('_TPL_AFF_PAYOUT_MBKRS_ID', 'Vaš MoneyBookers Account ID');
define ('_TPL_AFF_PAYOUT_EGOLD_ACC', 'Vaš E-Gold account#');
define ('_TPL_AFF_PAYOUT_CHECK_PTO', 'Èek isplatiti na');
define ('_TPL_AFF_PAYOUT_SAFEPAY_EMAIL', 'Vaša SafePaySolutions email adresa');

define ('_TPL_AFF_PAYOUT_STREET', 'Ulica');
define ('_TPL_AFF_PAYOUT_CITY', 'Grad');
define ('_TPL_AFF_PAYOUT_STATE', 'Regija / država');
define ('_TPL_AFF_PAYOUT_ZIP', 'Poštanski broj / zip');
define ('_TPL_AFF_PAYOUT_COUNTRY', 'Država');
define ('_TPL_AFF_PAYOUT_SAVE_BUT', 'Spremi');
define ('_TPL_AFF_PAYOUT_BACK_BUT', 'Natrag');

define ('_TPL_AFF_STATS_TITLE', 'Affiliate statistika');
define ('_TPL_AFF_STATS_DISPLAY_BUT', 'Prikaži');
define ('_TPL_AFF_STATS_PERIOD', 'Statistiku za razdoblje');
define ('_TPL_AFF_STATS_CLICKS', 'Klikova');
define ('_TPL_AFF_STATS_COMMISS', 'PROVIZIJE');
define ('_TPL_AFF_STATS_DATE', 'Datum');
define ('_TPL_AFF_STATS_RAW', 'Neostvareno');
define ('_TPL_AFF_STATS_UNIQUE', 'Unikatno');
define ('_TPL_AFF_STATS_TRANS', 'Transakcije');
define ('_TPL_AFF_STATS_CREDIT', 'Dobit');
define ('_TPL_AFF_STATS_DEBIT', 'Stavljeno na raèun');
define ('_TPL_AFF_STATS_TOTAL', 'Ukupno');
define ('_TPL_AFF_STATS_TOTAL_H', 'UKUPNO');
define ('_TPL_AFF_STATS_TOP20', 'Glavnih 20 preporuèivaèa');
define ('_TPL_AFF_STATS_REFERRER', 'PREPORUÈIVAÈ');
define ('_TPL_AFF_STATS_BACK', 'Natrag na stranicu sa Èlanskim podacima');

define ('_TPL_AGREEMENT_TITLE', 'Ugovor o korištenju');
define ('_TPL_AGREEMENT_REED_AGREE', 'Molimo da proèitate i složite se sa slijedeæim ugovorom o korištenju:');
define ('_TPL_AGREEMENT_AGREE', 'Slažem se');
define ('_TPL_AGREEMENT_CONTINUE_BUT', 'Nastavi');

define ('_TPL_CANCEL_TITLE', 'Plaæanje nije uspjelo');
define ('_TPL_CANCEL_ERROR', 'Dogodila se greška za vrijeme vašeg plaæanja.');
define ('_TPL_CANCEL_GOTO', 'Molimo da vratite na %ssign-up page%s i pokušate ponovo.');

define ('_TPL_EMAIL_VER_TITLE', 'Registracija - email potvrda');
define ('_TPL_EMAIL_VER_TEXT', 'Molimo provjerite vašu dolaznu email poštu - poslana vam je email poruka koju trebate potvrditi. Nakon što primite ovu email poruku, proèitajte i slijedite upute u ovoj poruci da biste dovršili svoju prijavu.');
define ('_TPL_EMAIL_VER_POWEREDBY', 'Powered by %saMember Pro%s membership software');

define ('_TPL_FATAL_ERROR_TITLE', 'Dogodila se Greška');
define ('_TPL_FATAL_ERROR_CONTACT', 'Molimo da kontaktirate administratora stranice: ');

define ('_TPL_MEMBER_TITLE', 'Vaši èlanski podaci');
define ('_TPL_MEMBER_SUBSCR', 'Vaše pretplate');
define ('_TPL_MEMBER_NO_SUBSCR', 'Vi nemate aktivnih pretplata');
define ('_TPL_MEMBER_ADD_RENEW', 'Dodaj/Obnovi pretplatu');
define ('_TPL_MEMBER_USE', 'Molimo da koristite formular %sDodaj/Obnovi pretplatu%s');
define ('_TPL_MEMBER_ORDER_SUBSCR', 'da biste se pretplatili ili obnovili pretplatu.');
define ('_TPL_MEMBER_USEFUL_LINKS', 'Korisni linkovi');
define ('_TPL_MEMBER_LOGOUT', 'Odjava');
define ('_TPL_MEMBER_CH_PSWD', 'Promijeni lozinku/Editiraj profil');
define ('_TPL_MEMBER_SELECT', '** Odaberite proizvod **');
define ('_TPL_MEMBER_SELECT2', '** Odaberite naèin plaæanja **');
define ('_TPL_MEMBER_ORDER_BUT', 'Naruèujem');
define ('_TPL_MEMBER_PYMNT_HIST', 'Povijest vaših plaæanja');
define ('_TPL_MEMBER_PRODUCT', 'Proizvod');
define ('_TPL_MEMBER_PERIOD', 'Razdoblje');
define ('_TPL_MEMBER_PAYSYS', 'Sistem plaæanja');
define ('_TPL_MEMBER_AMOUNT', 'Iznos');
define ('_TPL_MEMBER_CANCEL_SUBSCR', 'Da li stvarno želite otkazati pretplatu?');
define ('_TPL_MEMBER_CANCEL', 'Otkazujem');
define ('_TPL_MEMBER_CANCELLED', 'OTKAZANO');
define ('_TPL_MEMBER_PDF_INVOICE', 'PDF Raèun');
define ('_TPL_MEMBER_INVOICE', 'Izdati raèun');

define ('_TPL_MULT_MEMBER_TITLE', 'Vaši èlanski podaci');
define ('_TPL_MULT_MEMBER_SUBSCR', 'Vaše pretplate');
define ('_TPL_MULT_MEMBER_NOACTSUB', 'Vi nemate aktivnih pretplata');
define ('_TPL_MULT_MEMBER_ADDREN', 'Molimo da koristite formular%s %sDodaj/Obnovi pretplatu%s da biste se pretplatili ili obnovili pretplatu.');
define ('_TPL_MULT_MEMBER_LOGOUT', 'Odjava');
define ('_TPL_MULT_MEMBER_CHPWD', 'Promijeni lozinku/Editiraj profil');
define ('_TPL_MULT_MEMBER_ADDRSUBSCR', 'Dodaj/Obnovi pretplatu');
define ('_TPL_MULT_MEMBER_SELECTPM', '** Odaberi naèin plaæanja **');
define ('_TPL_MULT_MEMBER_PHIST', 'Povijest vaših plaæanja');
define ('_TPL_MULT_MEMBER_PRODUCT', 'Proizvod');
define ('_TPL_MULT_MEMBER_PERIOD', 'Razdoblje');
define ('_TPL_MULT_MEMBER_PSYS', 'Sistem plaæanja');
define ('_TPL_MULT_MEMBER_AMOUNT', 'Iznos');
define ('_TPL_MULT_MEMBER_CANCEL', 'Otkazujem');
define ('_TPL_MULT_MEMBER_CANCELLED', 'OTKAZANO');
define ('_TPL_MULT_MEMBER_ORDERBUT', 'Naruèujem');

define ('_TPL_MSGCLOSE_CLOSE', 'Zatvori ovaj prozor');

define ('_TPL_PROFILE_TITLE', 'Editiraj Profil');
define ('_TPL_PROFILE_USERNAME', 'Korisnièko ime');
define ('_TPL_PROFILE_ANOTHERUSRNM', 'vi možete ovdje izabrati drugo korisnièko ime');
define ('_TPL_PROFILE_FLNAME', 'Ime & Prezime');
define ('_TPL_PROFILE_EMAIL', 'Email adresa');
define ('_TPL_PROFILE_CHPWD', 'Promjena lozinke');
define ('_TPL_PROFILE_BLANK', 'Ostavite prazno da zadržite bez promjena');
define ('_TPL_PROFILE_CONFPWD', 'Potvrdi lozinku');
define ('_TPL_PROFILE_STREET', 'Ulica');
define ('_TPL_PROFILE_CITY', 'Grad');
define ('_TPL_PROFILE_STATE', 'Regija / država');
define ('_TPL_PROFILE_ZIP', 'Poštanski broj / zip');
define ('_TPL_PROFILE_COUNTRY', 'Država');
define ('_TPL_PROFILE_UNSUBSCR', 'Odjava');
define ('_TPL_PROFILE_NOEMAIL', 'ne šaljite mi povremene email poruke');
define ('_TPL_PROFILE_CHECKBOX', 'oznaèite ovaj okvir za odjavu');
define ('_TPL_PROFILE_SAVEBUT', 'Spremi Profil');
define ('_TPL_PROFILE_BACKBUT', 'Natrag');

define ('_TPL_PROFILE_SAVED_TITLE', 'Editiraj Profil');
define ('_TPL_PROFILE_SAVED_SUCCESS', 'Vaš èlanski profil je uspješno spremljen.');
define ('_TPL_PROFILE_SAVED_GOBACK', 'Molimo da se vratite na vašu stranicu%s sa %sèlanskim informacijama.');

define ('_TPL_CHANGEPASSWORD_TITLE', 'Promjena lozinke');
define ('_TPL_CHANGEPASSWORD_USERNAME', 'Korisnièko ime');
define ('_TPL_CHANGEPASSWORD_SAVEBUT', 'Promijeni');
define ('_TPL_CHANGEPASSWORD_BACKBUT', 'Stranica za Prijavu');
define ('_TPL_CHANGEPASSWORD_CHPWD', 'Nova lozinka');
define ('_TPL_CHANGEPASSWORD_CONFPWD', 'Potvrdi lozinku');

define ('_TPL_CHANGEPASSWORD_FAILED_TITLE', 'Greška prilikom promjene lozinke');
define ('_TPL_CHANGEPASSWORD_FAILED_INCINFO', 'Podatak koji ste unijeli je pogrešan');
define ('_TPL_CHANGEPASSWORD_FAILED_USRNOTFOUND', 'Korisnik nije naðen u bazi podataka.');
define ('_TPL_CHANGEPASSWORD_FAILED_EXPIRED', 'Sigurnosni kod je istekao.');
define ('_TPL_CHANGEPASSWORD_FAILED_WRONGPASS', 'Lozinke nisu jednake ili su prekratke.');
define ('_TPL_CHANGEPASSWORD_FAILED_RETURN', 'Vratite se i pokušajte ponovo');

define ('_TPL_REDIRECT_CLICKHERE', 'Kliknite ovdje ako ne želite duže èekati (ali ako vas vaš preglednik neæe automatski preusmjeriti).');

define ('_SENDPWD_OK_TITLE', 'Izgubljena Lozinka je poslana');
define ('_SENDPWD_OK_TEXT', 'Lozinka je poslana na vaš email');
define ('_SENDPWD_OK_TEXT_1', 'Molimo da provjerite svoju dolaznu email poštu');

define ('_SENDPWD_FAILED_TITLE', 'Greška prilikom slanja izgubljene lozinke');
define ('_SENDPWD_FAILED_TEXT', 'Podatak koji ste unijeli je pogrešan');
define ('_SENDPWD_FAILED_TEXT_1', 'Korisnièko ime [%s] ne postoji u bazi podataka');
define ('_TPL_SENDPWD_RETURN', 'Vratite se na stranicu za ulaz');

define ('_TPL_NEWGUEST_FAILED_TITLE', 'Greška prilikom potvrde');
define ('_TPL_NEWGUEST_FAILED_INCINFO', 'Podatak koji ste unijeli je pogrešan');
define ('_TPL_NEWGUEST_FAILED_RETURN', 'Vratite se i pokušajte ponovo');


define ('_TPL_NEWGUEST_FAILED_EMAIL_TITLE', 'Greška prilikom potvrde');
define ('_TPL_NEWGUEST_FAILED_EMAIL_INFO', 'Email adresu koju ste naveli veæ koristi jedan od naših registriranih èlanova.');
define ('_TPL_NEWGUEST_FAILED_EMAIL_LINK', 'Slijedite ovaj link za Prijavu i pretplatu na newslettere');


define ('_TPL_NEWGUEST_OK_TITLE', 'Potvrda je poslana');
define ('_TPL_NEWGUEST_OK_PWDOK', 'Potvrda za novu pretplatu poslana je na vašu email adresu');
define ('_TPL_NEWGUEST_OK_CHECKEM', 'Molimo provjerite vašu dolaznu email poštu');
define ('_TPL_NEWGUEST_OK_RETURN', 'Povratak');

define ('_TPL_NEWGUEST_COMPLETE_TITLE', 'Pretplata je dodana');
define ('_TPL_NEWGUEST_COMPLETE', 'Vaša email adresa je uspješno dodana na newslettere web stranice');


define ('_TPL_NEWSLETTER_SUBSCRIPTIONS', 'Newsletter pretplate');
define ('_TPL_NEWSLETTER_ARCHIVE', 'Newsletter arhiva');
define ('_TPL_NEWSLETTER_SUBSCRIBE', 'Pretplata na Newsletter');
define ('_TPL_NEWSLETTER_MEMBER_AREA', 'Zona èlanova');
define ('_TPL_NEWSLETTER_SUBSCRIBE_TO_NEWSLETTERS', 'Izaberite Newslettere');
define ('_TPL_NEWSLETTER_NAME', 'Ime i Prezime');
define ('_TPL_NEWSLETTER_EMAIL', 'Email');
define ('_TPL_NEWSLETTER_DO_SUBSCRIBE', 'Prijava');
define ('_TPL_NEWSLETTER_BACK', 'Natrag');

define ('_TPL_NEWSLETTER_UPDATE_SUBSCRIPTIONS', 'Izmijeni pretplate');
define ('_TPL_NEWSLETTER_INFO_SAVED', 'Podaci su spremljeni');
define ('_TPL_NEWSLETTER_INFO_UPDATED', 'Podaci pretplata na Newsletter su izmijenjeni');

define ('_TPL_NEWSLETTER_REQUIRED_NAME', 'Ime i Prezime je obavezno polje za unos');
define ('_TPL_NEWSLETTER_REQUIRED_EMAIL', 'Email je obavezno polje za unos');
define ('_TPL_NEWSLETTER_REQUIRED_THREAD', 'Tema newslettera nije odabrana');

define ('_TPL_NEWSLETTER_UNSUBSCRIBE', 'Odjava od svih email poruka');

define ('_TPL_NEWSLETTER_DATE', 'Datum');
define ('_TPL_NEWSLETTER_SUBJECT', 'Predmet');
define ('_TPL_NEWSLETTER_MESSAGE', 'Poruka');
define ('_TPL_NEWSLETTER_THREADS', 'Tema(e)');

define ('_TPL_SIGNUP_MULT_TITLE', 'Prijava');
define ('_TPL_SIGNUP_MULT_SELECTTYPE', 'Odaberite vrstu èlanstva');
define ('_TPL_SIGNUP_MULT_MEMTYPE', 'Vrsta èlanstva');
define ('_TPL_SIGNUP_MULT_SELPAYSYS', 'Odaberite sistem plaæanja');
define ('_TPL_SIGNUP_MULT_PAYSYS', 'Sistem plaæanja');
define ('_TPL_SIGNUP_MULT_NAME', 'Vaše ime');
define ('_TPL_SIGNUP_MULT_FLNAME', 'vaše ime i prezime');
define ('_TPL_SIGNUP_MULT_EMAIL', 'Vaša email adresa');
define ('_TPL_SIGNUP_MULT_CONFIRM', 'æe biti korištena za slanje potvrde');
define ('_TPL_SIGNUP_MULT_LOGIN', 'Izaberite ime za prijavu (User ID)');
define ('_TPL_SIGNUP_MULT_ENTER', 'odabrano ime za prijavu %s- æe biti korišteno nakon plaæanja%sza prijavu u vaš raèun.%s Mora biti %d ili više znakova%si može sadržavati mala slova, brojeve i _');
define ('_TPL_SIGNUP_MULT_CHECK', 'provjerite da li je u upotrebi');
define ('_TPL_SIGNUP_MULT_CHPWD', 'Izaberite lozinku');
define ('_TPL_SIGNUP_MULT_MUSTBE', 'Mora biti %d ili više znakova');
define ('_TPL_SIGNUP_MULT_CONFPWD', 'Potvrdite svoju lozinku');
define ('_TPL_SIGNUP_MULT_PWDAGAIN', 'unesite lozinku ponovo');
define ('_TPL_SIGNUP_MULT_ADDRESS', 'ADRESA - PODACI');
define ('_TPL_SIGNUP_MULT_STREET', 'Ulica');
define ('_TPL_SIGNUP_MULT_CITY', 'Grad');
define ('_TPL_SIGNUP_MULT_STATE', 'Regija / država');
define ('_TPL_SIGNUP_MULT_ZIP', 'Poštanski broj / zip');
define ('_TPL_SIGNUP_MULT_COUNTRY', 'Država');
define ('_TPL_SIGNUP_MULT_COUPONS', 'KUPONI');
define ('_TPL_SIGNUP_MULT_CCODE', 'Unesite kod Kupona');
define ('_TPL_SIGNUP_MULT_GETCOUP', 'ako ste uzeli neki kod kupona od oglašivaèa,%s molimo da ga unesete ovdje');
define ('_TPL_SIGNUP_MULT_CONT', 'Nastavi');

define ('_TPL_THX_TITLE', 'Zahvaljujemo na registraciji');
define ('_TPL_THX_ENJOY', 'Uživajte u èlanstvu. Za ulaz kliknite na %sPrijava%s');
define ('_TPL_THX_PAYPROC', 'Vaša uplata je uspješno obraðena.');
define ('_TPL_THX_ORDERREF', 'Oznaka naloga: %d / %s');
define ('_TPL_THX_DATETIME', 'Datum i vrijeme plaæanja: %s');
define ('_TPL_THX_PRDTITLE', 'Naslov Pretplate/Proizvoda');
define ('_TPL_THX_PRICE', 'Cijena');
define ('_TPL_THX_SUBTOTAL', 'Ukupno');
define ('_TPL_THX_DISCOUNT', 'Kupon popust');
define ('_TPL_THX_TAX', 'Iznos poreza');
define ('_TPL_THX_TOTAL', 'Sveukupno');
define ('_TPL_THX_YOUR_INVOICE', 'Vaš raèun broj');
define ('_TPL_THX_FROM', 'od');

define ('_TPL_THX_ERROR_TITLE', 'Greška prilikom prijave');
define ('_TPL_THX_ERROR_ERROR', 'Dogodila se greška prilikom procedure Prijave');
define ('_TPL_THX_ERROR_CONTACT', 'Molimo da kontaktirate administratora web stranice');

define ('_TPL_UNSUBSCRIBE_TITLE', 'Potvrda odjave');
define ('_TPL_UNSUBSCRIBE_CONFIRM', 'Da li stvarno želite odjaviti email adresu %s%s%s iz %s povremenih email poruka?');
define ('_TPL_UNSUBSCRIBE_UNSUB_BUT', 'Da, molim odjavu');
define ('_TPL_UNSUBSCRIBE_NO_UNSUB_BUT', 'Ne, molim da me zadržite prijavljenog');

define ('_TPL_UNSUBSCRIBED_TITLE', 'Email je odjavljen');
define ('_TPL_UNSUBSCRIBED_SUCCESS1', 'Vaša email adresa %s je uspješno odjavljena.');
define ('_TPL_UNSUBSCRIBED_SUCCESS2', 'Vi više neæete primati povremene email poruke od naše web stranice.');
define ('_TPL_UNSUBSCRIBED_SUCCESS3', 'Meðutim, imajte na umu da æe vam biti poslana poruka o novom plaæanju, i ako zatražite izgubljenu lozinku za vaš raèun.');

define ('_UNIQ_LOGIN_EMPTY_TITLE', 'Prazno Korisnièko ime');
define ('_UNIQ_LOGIN_EMPTY_TEXT', 'Molimo, unesite vaše korisnièko ime.');
define ('_UNIQ_LOGIN_EXSTS_TITLE', 'Korisnièko ime se veæ koristi');
define ('_UNIQ_LOGIN_EXSTS_TEXT', 'Korisnièko ime %s je izabrao neki drugi korisnik');
define ('_UNIQ_LOGIN_EXSTS_TEXT_1', 'Molimo da odaberete neko drugo ime za prijavu');
define ('_UNIQ_LOGIN_EXSTS_TEXT_2', 'Ako je to vaš raèun, molimo da odete na %svašu èlansku stranicu%s da biste se prijavili u vašu pretplatu.');
define ('_UNIQ_LOGIN_FREE_TITLE', 'Korisnièko ime je dostupno');
define ('_UNIQ_LOGIN_FREE_TEXT', 'Korisnièko ime %s još nije registrirano');
define ('_UNIQ_LOGIN_FREE_TEXT_1', 'Èestitamo, to je dostupno!');
define ('_TPL_UNIQ_LOGIN_CLOSE', 'Zatvori');

define('_LOGIN_WAIT_BEFORE_NEXT_ATTEMPT', 'Molimo da saèekate %d minuta prije nego što se ponovo pokušate prijaviti');
define('_LOGIN_SESSION_EXPIRED', 'Povezanost je istekla, molimo da unesete korisnièko ime i lozinku ponovo');
define('_LOGIN_ACCESS_NOT_ALLOWED', 'Pristup ovoj èlanskoj zoni nije dopušten. Molimo da odete na %s"Stranicu sa Èlanskim podacima"%s da obnovite ili dodate pretplatu');
define('_LOGIN_INCORRECT', "Neispravno korisnièko ime ili lozinka");
define('_LOGIN_ACCOUNT_DISABLED', 'Vaš raèun je deaktiviran. Kontaktirajte webmastera za pojedinosti');
define('_LOGIN_MANUAL_VERIFICATION_PENDING', 'Vaš raèun još nije aktiviran. Vi æete primiti email poruku kada potvrda bude dovršena');
define('_LOGIN_USERNAME_WRONG_CASE', 'Unesite korisnièko ime u ispravnom obliku. Vi unosite "%s", molimo da umjesto toga unesete "%s" ');
define('_LOGIN_PLEASE_LOGIN', 'Molim prijavu');

define('_SIGNUP_PLEASE_SELECT_MEMT', 'Molimo da izaberete vrstu èlanstva');
define('_SIGNUP_PLEASE_SELECT_PAYSYS', 'Molimo da izaberete sistem plaæanja');
define('_SIGNUP_PLEASE_ENTER_FNAME', 'Molimo da unesete svoje Ime');
define('_SIGNUP_PLEASE_ENTER_LNAME', 'Molimo da unesete svoje Prezime');
define('_SIGNUP_INVALID_USERNAME', 'Korisnièko ime sadrži nedozvoljene znakove - molimo da koristite brojke, slova ili prazna mjesta');
define('_SIGNUP_INVALID_USERNAME_W_SPACES', 'Korisnièko ime sadrži nedozvoljene znakove - molimo da koristite brojke i slova');
define('_SIGNUP_INVALID_USERNAME_2', 'Molimo da koristite ispravno ime za prijavu. To mora sadržavati najmanje %d znakova');
define('_SIGNUP_INVALID_USERNAME_3', 'Korisnièko ime %s je veæ zauzeto. Molimo da izaberete drugo korisnièko ime.');
define('_SIGNUP_PLEASE_ENTER_EMAIL', 'Molimo da unesete ispravan email');
define('_SIGNUP_INVALID_EMAIL_1', 'Jedan raèun sa istom email adresom veæ postoji.');
define('_SIGNUP_INVALID_EMAIL_2', 'Molimo da se %sprijavite%s u vaš postojeæi raèun.%sAko još nemate dovršeno plaæanje, bit æete u moguænosti dovršiti ga nakon prijave');
define('_SIGNUP_PLEASE_ENTER_PSWD', 'Molimo da unesete Lozinku');
define('_SIGNUP_INVALID_PASS_1', 'Lozinka mora sadržavati najmanje %d znakova ili brojki');
define('_SIGNUP_INVALID_PASS_2', 'Lozinka i Potvrda lozinke se razlikuju. Molimo da ponovo unesete oboje');
define('_SIGNUP_SCRIPT_ERROR', 'Greška u konfiguraciji skripte - trebate dodati najmanje jedan proizvod (Vrsta èlanstva) iz aMember Control Panela');
define('_SIGNUP_PAYMENT_NOT_FOUND', 'Plaæanje %d nije naðeno');
define('_SIGNUP_PAYMENT_COMPLETED', 'Plaæanje %d je veæ izvršeno, molimo da uðete u vaš raèun ');
define('_SIGNUP_PAYMENT_COMPLETED_1', 'ovdje');
define('_SIGNUP_INCORRECT_LINK', 'Netoèan link - provjerite jeste li toèno kopirali link iz vašeg email programa');
define('_SIGNUP_USER_AGREEMENT', 'Vi se morate složiti sa Ugovorom o korištenju za nastavak');
define('_SIGNUP_INCORRECT_PRODID', 'Netoèan ID proizvoda za stranicu za registriranje');
define('_SIGNUP_LOGIN_EXISTS', 'Vi ste veæ prijavljeni. Interna greška');
define('_SIGNUP_ENTER_STREET', 'Molimo da unesete Ulicu');
define('_SIGNUP_ENTER_CITY', 'Molimo da unesete Grad');
define('_SIGNUP_ENTER_STATE', 'Molimo da unesete Regiju / državu');
define('_SIGNUP_ENTER_ZIP', 'Molimo da unesete Poštanski broj / zip');
define('_SIGNUP_ENTER_COUNTRY', 'Molimo da unesete Državu');
define('_SIGNUP_CAPTCHA_ERROR', 'Potvrdna slika je unešena netoèno, molimo da to unesete pažljivije');

define('_AFF_MEMBER_TITLE', 'Podaci Affiliate partnera');
define('_AFF_INTERNAL_ERROR', 'Interna greška - member_id je prazan');
define('_AFF_ERROR_1', 'Molimo da unesete email adresu za isplatu');
define('_AFF_ERROR_2', 'Molimo da unesete ime primatelja èeka');
define('_AFF_ERROR_3', 'Molimo da unesete email StormPay raèuna');
define('_AFF_ERROR_4', 'Molimo da unesete email iKobo raèuna');
define('_AFF_ERROR_5', 'Molimo da unesete ID MoneyBookers raèuna');
define('_AFF_ERROR_6', 'Molimo da unesete E-Gold raèun#');
define('_AFF_ERROR_7', 'Nepoznata vrsta isplate');
define('_AFF_ERROR_8', 'Nepoznata akcija: %s');
define('_AFF_ERROR_9', 'Molimo da unesete email adresu za isplatu');
define('_AFF_AFFILIATES', 'Affiliate partneri');
define('_AFF_PROGR_CONF', 'konfiguracija affiliate programa');
define('_AFF_PAYOUT_MTHDS', 'Prihvaæeni naèini plaæanja');
define('_AFF_MTHD4_PAYOUT', 'affiliate partner može izabrati naèin isplate provizije.');
define('_AFF_NOTHING_SELECTED', 'Ako ništa nije odabrano, provizije neæe biti ukljuèene automatski');
define('_AFF_REPORT', 'izvještaj isplate.');
define('_AFF_CONFIG_F1_1', 'Affiliate provizija za prvo plaæanje');
define('_AFF_CONFIG_F1_2', 'affiliate provizije za prvo plaæanje, npr.: 1.5 ili 2.5%');
define('_AFF_CONFIG_F2_1', 'Affiliate provizija za slijedeæa plaæanja');
define('_AFF_CONFIG_F2_2', 'affiliate provizije za slijedeæa plaæanja, npr.: 1.5 ili 2.5%');
define('_AFF_CONFIG_F3_1', 'Affiliate cookie trajanje');
define('_AFF_CONFIG_F3_2', 'koliko dugo (u danima) spremiti cookies o preporuèivaèu.');
define('_AFF_CONFIG_F3_3', 'Tako ako se kupac vrati na stranicu kasnije, provizija æe biti');
define('_AFF_CONFIG_F3_4', 'plaæena upuæivajuæem affiliate partneru.');
define('_AFF_CONFIG_F4_1', 'Plati samo prvu proviziju');
define('_AFF_CONFIG_F4_2', 'affiliate partner æe dobiti proviziju samo za prvu kupovinu.');
define('_AFF_CONFIG_F4_3', 'U sluèaju ponavljajuæeg plaæanja, samo jedna (prva) provizija æe');
define('_AFF_CONFIG_F4_4', 'biti ostvarena.');
define('_AFF_CONFIG_F5_1', 'Ne davati proviziju za besplatne pretplatnike');
define('_AFF_CONFIG_F5_2', 'provizija za prodaju neæe biti doznaèena na raèun affiliate partnera');
define('_AFF_CONFIG_F5_3', 'ako je korisnik pretplaæen za besplatnu pretplatu. Naravno, to se odnosi samo na');
define('_AFF_CONFIG_F5_4', '\'fixed\' affiliate provizije.');
define('_AFF_ARRAY_1ELEM', 'Davati proviziju èak i za besplatne pretplate');
define('_AFF_ARRAY_2ELEM', 'Ne davati provizije za besplatne provizije');
define('_AFF_CONFIG_F6_1', 'Vrsta Affiliate registracije');
define('_AFF_CONFIG_F6_2', 'affiliate partner æe dobiti proviziju samo za prvu kupovinu.');
define('_AFF_CONFIG_F6_3', 'U sluèaju ponavljajuæih plaæanja, samo jedna (prva) provizija æe');
define('_AFF_CONFIG_F6_4', 'biti ostvarena.');
define('_AFF_ARRAY_2_ELEM_1', 'Default - korisnik treba kliknuti na link da postane affiliate partner');
define('_AFF_ARRAY_2_ELEM_2', 'Svi novi èlanovi automatski postaju affiliate partneri');
define('_AFF_ARRAY_2_ELEM_3', 'Samo admin može aktivirati korisnika kao affiliate partnera');
define('_AFF_CONFIG_F7_1', 'Obavijesti admina o proviziji');
define('_AFF_CONFIG_F7_2', 'kada se provizija od nove prodaje doznaèi na raèun affiliate partnera');
define('_AFF_CONFIG_F7_3', 'pošalji email poruku administratoru');
define('_AFF_CONFIG_F8_1', 'Obavijesti affiliate partnera o proviziji');
define('_AFF_CONFIG_F8_2', 'kada se provizija od nove prodaje doznaèi na raèun affiliate partnera');
define('_AFF_CONFIG_F8_3', 'pošalji email poruku affiliate partneru');
define('_AFF_ADVERTISE_SITE', 'Reklamirajte našu web stranicu prijateljima i zaradite novac');
define('_AFF_MEMBER_AREA', 'Zona affiliate partnera');
define('_AFF_GET_BANS_LINKS', 'Uzmite affiliate bannere i linkove');
define('_AFF_REVIEW_STAT', 'Pregledajte svoju affiliate statistiku');
define('_AFF_UPDATE_PAYOUT', 'Obnovite svoje informacije za isplatu provizije');
define('_AFF_MEMBER_F1_1', 'Paypal adresa za affiliate isplatu');
define('_AFF_MEMBER_F2_1', 'StormPay adresa za affiliate isplatu');
define('_AFF_MEMBER_F3_1', 'iKobo adresa za affiliate isplatu');
define('_AFF_MEMBER_F4_1', 'MoneyBookers account ID za affiliate isplatu');
define('_AFF_MEMBER_F5_1', 'E-Gold account# za affiliate isplatu');
define('_AFF_MEMBER_F6_1', 'Èek isplatiti na');
define('_AFF_MEMBER_F7_1', 'SafePaySolutions adresa za affiliate isplatu');
define('_AFF_MEMBER_THANK_YOU', 'Hvala vam za registraciju');
define('_AFF_MEMBER_REDIRECTING', 'Biti æete preusmjereni na stranicu sa affiliate profilom');
define('_AFF_DISABLED_MESSAGE', 'Affiliate program nije aktiviran. Molimo omoguæite to na aMember CP -> Setup');

define('_AFF_PAYOUT_TYPE', 'Vrsta Affiliate isplate');
define('_AFF_SIGNUP_PLEASE_PAYOUT_TYPE', 'Molimo izaberite vrstu isplate');

define('_MEMBER_VF_INTEGER', 'Molimo unesite cijeli broj vrijednost za [%s]');
define('_MEMBER_VF_NUMERIC', 'Molimo unesite numerièku brojèanu vrijednost za [%s]');
define('_MEMBER_VF_REQUIRE', 'Molimo unesite vrijednost za polje [%s]');
define('_MEMBER_VF_EMAIL', 'Molimo unesite valjanu email adresu u polje [%s] ');

define('_MEMBER_ERROR_1', 'Vi još niste potvrdili svoju email adresu, tako da ulaz nije%sdozvoljen. Molimo da provjerite svoju dolaznu email poštu i naðete verifikacijsku email poruku i%skliknete na link za potvrdu. Ukoliko niste primili verifikacijsku poruku,%smolimo da kliknete na %sovaj link%s i mi æemo vam ponovo poslati verifikacijsku poruku.');
define('_MEMBER_REDIRECTING', 'Preusmjeravanje na vašu stranicu sa èlanskim podacima');
define('_MEMBER_ONLY4_PAID', 'Ovaj proizvod je dostupan samo za plaæeno èlanstvo');
define('_MEMBER_ONLY4_NEW', 'Ovaj proizvod je dostupan samo za nove èlanove');
define('_MEMBER_NOT4_ORDER', 'Ovaj proizvod nije dostupan za naruèivanje');
define('_MEMBER_SELECT_PRODUCT', 'Molimo da odaberete proizvod (vrsta pretplate) za obnavljanje');
define('_MEMBER_SELECT_PAYMENT', 'Molimo da odaberete sistem plaæanja za plaæanje');
define('_MEMBER_ID_NOT_MATCH', 'member_id (èlanski broj) se ne podudara za plaæanje');
define('_MEMBER_SUBSCR_CANCELLED', 'Otkazivanje pretplate');
define('_MEMBER_RSUB_CANCELLED', 'Ponavljajuæa pretplata je otkazana.');
define('_MEMBER_MAIL_ADMIN', 'Ponavljajuæa pretplata je otkazana: Korisnièko ime: %s Plaæanje#: %d');
define('_MEMBER_MAIL_THEME', '*** Otkazivanje pretplate');
define('_MEMBER_ERROR', 'Vi se morate složiti sa Ugovorom o korištenju za nastavak');

define('_MEMBER_PROFILE_CORRECTLOG', 'Molimo da unesete ispravan podatak za prijavu. To mora sadržavati najmanje %d slova, brojki ili _');
define('_MEMBER_PROFILE_NAMEEXISTS', 'Korisnièko ime %s je veæ zauzeto. Molimo da izaberete drugo korisnièko ime.');
define('_MEMBER_PROFILE_ERROR1', 'Molimo da unesete ispravno Korisnièko ime: %s');
define('_MEMBER_PROFILE_ERROR2', 'Molimo da unesete valjanu Email adresu');
define('_MEMBER_PROFILE_ERROR3', 'Email adresa se veæ koristi');
define('_MEMBER_PROFILE_ERROR4', 'Molimo da unesete Ime');
define('_MEMBER_PROFILE_ERROR5', 'Molimo da unesete Prezime');
define('_MEMBER_PROFILE_ERROR6', 'Lozinka mora imati najmanje %d znakova');
define('_MEMBER_PROFILE_ERROR7', 'Lozinka mora imati manje od %d znakova');
define('_MEMBER_PROFILE_ERROR8', 'Lozinka i potvrda se razlikuju. Molimo da unesete ponovo');
define('_MEMBER_PROFILE_ERROR9', 'Nepoznata vrsta polja za %s : %s');

define('_CRON_ERROR', 'Vanjski cron je deaktiviran u setup-u');

define('_COMMON_LANGUAGE', 'Jezik');
define('_COMMON_LIFETIME', 'TRAJANJE');
define('_COMMON_RECURRING', 'PONAVLJANJE');

define('_INDEX_ERROR', 'aMember još nije konfiguiran. Odite na %sstranicu za konfiguraciju%s.');

define('_LOGIN_REDIRECT', 'Vi æete biti preusmjereni u zaštiæeno podruèje');

define('_RESEND_ERROR', 'Vaša email adresa je veæ verificirana');
define('_RESEND_ERROR2', 'Vi više ne možete tražiti verifikacijski email, molimo da se nanovo %sregistrirate%s ili još bolje, kontarktirajte podršku stranice za pomoæ');
define('_RESEND_ERROR3', 'Interna greška #1265.');

define('_NEWSLETTER_SUBSCRIPTION', 'Newsletter pretplate');
define('_NEWSLETTER_NO_GUEST_THREADS', 'Žao nam je, ali ovdje nema konfiguiranih newslettera koji su dostupni za posjetitelje');

define('_SETUP_ERROR', 'PHP verzija %s (ili veæa) je potrebna za pokretanje aMember. Vaša PHP-Verzija je : %s%sMolimo da nadogradite ili zatražite od vašeg hostinga za nadogradnju. PHP prije %s ima greške i ranjiva je.');
define('_SETUP_ERROR2', 'PHP na vašem webhostingu je instaliran bez MySQL podrške.%stako da aMember ne može biti instaliran na vaš hosting, molimo da kontaktirate podršku vašeg%shostinga da otklone ovaj problem.');
define('_SETUP_FATAL_ERROR', 'Fatalna Greška: %s');
define('_SETUP_HEADER', 'aMember Instalacija');
define('_SETUP_CONF_EXISTS', 'Datoteka %s veæ postoji i nije prazna. Molimo da uklonite ili obrišete sav sadržaj ako trebate ponovo napraviti punu konfiguraciju');
define('_SETUP_AFTER_FIX', 'Nakon što otklonite ove probleme, kliknite %sovdje%s da osvježite stranicu.');
define('_SETUP_CONF_CHMOD', 'Datoteka %s veæ postoji i ne dozvoljava zapisivanje. Molimo %spopravite ovo%s');
define('_SETUP_DIRECTORY_CHMOD', 'Direktorij %s ne dozvoljava zapisivanje. Potrebno je zapisati config datoteku %s. Molimo %spopravite ovo%s');
define('_SETUP_ENTER_PARAM', 'Unesite parametre konfiguracije');
define('_SETUP_MODIFY_LATER', 'Vi možete izmijeniti ove vrijednosti kasnije kroz aMember Kontrol Panel');
define('_SETUP_ROOT_URL', 'Root URL od skripte');
define('_SETUP_TRAILING_SLASH', '%sNemojte%s stavljati kosu crtu ( %s/%s ) na kraju!');
define('_SETUP_LICENSE_NOTE', 'Molimo da imate na umu da url mora odgovarati vašoj licenci.');
define('_SETUP_HTTPS_URL', 'Sigurnosni (HTTPS) Root URL od skripte');
define('_SETUP_KEEP_DEFAULT', 'Molimo da ostavite default (ne-sigurno) vrijednost ako niste sigurni.');
define('_SETUP_NO_TRSLASH', 'Bez kose crte ( %s/%s ) molimo!');
define('_SETUP_ADMIN_EMAIL', 'Admin Email');
define('_SETUP_SENT_TO', 'Adresa na koju se šalju obavijesti, upozorenja i druge poruke');
define('_SETUP_ADMIN_LOGIN', 'Admin Login');
define('_SETUP_USERNAME', 'Korisnièko ime za ulaz u suèelje Administratora');
define('_SETUP_ADMIN_PASS', 'Admin Lozinka');
define('_SETUP_PASS', 'Lozinka za ulaz u suèelje Administratora');
define('_SETUP_LICENSE_HEAD', 'Licenca');
define('_SETUP_LICENSE', 'Unesite %sPuni%s licenèni kljuè, ukljuèujuæi iscrtkane crte ( == ) iznad i ispod!');
define('_SETUP_NEXT_BUT', 'Slijedeæe');
define('_SETUP_ERROR3', 'Molimo da unesete root url od skripte');
define('_SETUP_ERROR4', 'Molimo da unesete sigurnosni root url od skripte (ili ostavite DEFAULT VRIJEDNOST - postavka kao Ne-siguran root URL - to æe ipak raditi)');
define('_SETUP_ERROR5', 'Molimo da unesete admin email');
define('_SETUP_ERROR6', 'Molimo da unesete admin login');
define('_SETUP_ERROR7', 'Molimo da unesete admin lozinku');
define('_SETUP_ERROR8', 'Molimo da unesete licenèni kljuè');
define('_SETUP_ERROR9', 'Molimo da unesete puni licenèni kod (treba poèinjati i završavati sa ======)');
define('_SETUP_ERROR10', 'Root URL %s ne odgovara domeni licence');
define('_SETUP_ERROR11', 'Sigurnosni Root URL %s ne odgovara domeni licence');
define('_SETUP_RETURN', 'Molimo %svratite se%s i popravite ove greške.');
define('_SETUP_MYSQL_PARAM', 'Unesite MySQL parametre konfiguracije');
define('_SETUP_CONF_EDIT', 'Vi možete editirati %sconfig.inc.php%s ako trebate napraviti izmjene nakon Setup-a');
define('_SETUP_MYSQL_HOST', 'MySQL Host');
define('_SETUP_LOCALHOST', 'Najèešæe \'localhost\'');
define('_SETUP_MYSQL_DB', 'MySQL Database');
define('_SETUP_MYSQL_NOTE', 'Napomena: Setup ne kreira bazu podataka za vas.');
define('_SETUP_USE_DEFAULT', 'Koristite default bazu podataka kreiranu od strane vašeg hosta ili%skreirajte novu bazu podataka, na primjer \'amember\'');
define('_SETUP_MYSQL_USER', 'MySQL Korisnièko ime');
define('_SETUP_MYSQL_PWD', 'MySQL Lozinka');
define('_SETUP_TABLE_PREFIX', 'MySQL Tables Prefix');
define('_SETUP_UNSURE', 'Ako niste sigurni, koristite default vrijednost %samember_%s');
define('_SETUP_MYSQL_ERROR1', 'Molimo da unesete ime mysql baze podataka');
define('_SETUP_MYSQL_ERROR2', 'Molimo da unesete mysql korisnièko ime');
define('_SETUP_MYSQL_ERROR3', 'Molimo da unesete mysql hostname');
define('_SETUP_MYSQL_ERROR4', 'Molimo da unesete mysql lozinku');
define('_SETUP_MYSQL_ERROR5', 'Ne mogu se spojiti na mysql (%s)');
define('_SETUP_MYSQL_ERROR6', 'Ne mogu odrediti bazu podataka \'%s\' ( %s )');
define('_SETUP_MYSQL_INSTALL', 'Instalirati aMember na ovu MySQL bazu podataka?');
define('_SETUP_MYSQL_CREATE_TABLES', 'Kreiranje aMember tablica baze podataka');
define('_SETUP_MYSQL_INSTALL2', 'Oznaèite okviriæ i kliknite \'Slijedeæe\' da biste kreirali aMember tablice u naznaèenoj MySQL bazi podataka%sUkoliko veæ imate aMember veæ instaliran u bazi podataka, setup neæe ukloniti sve%sto æe samo nadograditi strukturu tablice');
define('_SETUP_MYSQL_ERROR7', 'Ne mogu odrediti bazu podataka \' %s \' ( %s )');
define('_SETUP_MYSQL_FIX_ERROR', 'Molimo da popravite ove greške i %sponovo uèitate%s ovu stranicu.');
define('_SETUP_ERROR12', 'Ne mogu otvoriti %s . Molimo da uèitate ovu datoteku');
define('_SETUP_ERROR13', 'Ne mogu spremiti config datoteku');
define('_SETUP_ERROR14', 'Ne mogu spremiti %s%s%s');
define('_SETUP_NEW_CONFIG', 'Da dovršite setup vi možete napraviti download nove config datoteke u vaš kompjuter i otuda ju uèitati na vaš server.');
define('_SETUP_UPLOAD_CONFIG', 'Datoteka %sconfig.inc.php%s. Uèitati to u:');
define('_SETUP_DOWNLOAD_BUT', 'Download config.inc.php');
define('_SETUP_IE_RENAME', 'Internet Expolorer ponekad promjeni ime %sdatotekama kada se spremaju. Na primjer, to može preimenovati %sconfig.inc.php%s%su %sconfig[1].inc.php%s. Nemojte to zaboraviti popraviti prije uèitavanja!');
define('_SETUP_THANK_YOU1', 'Zahvaljujemo što ste izabrali aMember Pro. Vi možete naæi aMember Pro Korisnièki vodiè %sovdje%s.');
define('_SETUP_THANK_YOU2', 'Slobodno kontaktirajte %sCGI-Central%s u bilo koje vrijeme ako vam treba nešto u vezi skripte.');
define('_SETUP_THANK_YOU3', 'Molimo da provjerite slijedeæe:');
define('_SETUP_THANK_YOU4', '(Vi možete oznaèiti ovu stranicu)');
define('_SETUP_THANK_YOU_LINK1', 'Admin stranica (aMember Control Panel)');
define('_SETUP_THANK_YOU_LINK2', 'Stranica za registraciju');
define('_SETUP_THANK_YOU_LINK3', 'Stranica registriranih èlanova');
define('_SETUP_THANK_YOU_LINK4', 'Login stranica (preusmjeravanje na zaštiæeno podruèje)');
define('_SETUP_THANK_YOU_BEFOREUSE', 'Prije nego što aMember bude spreman za korištenje vi æete takoðer trebati uèiniti slijedeæe:)');
define('_SETUP_THANK_YOU_GOTOCP', 'Odite na %sAdmin stranicu%s i logirajte se. Iz glavnog menija koji je na lijevoj strani odaberite %sUtilities>Setup/Configuration%s Ove postavke mogu biti korištene da fino podesite vašu instalaciju. Omoguæite neki plugins koji vam je potreban za dodatno plaæanje, zatim posjetite plugins konfiguraciju i unesite vaše postavke.');
define('_SETUP_THANK_YOU_ADDPRODUCTS', 'Odite na %sAdmin stranicu%s i dodajte vaše proizvode ili vrste pretplata.%s%sVi æete možda željeti nazivati ih kao \'Proizvodi\' ili \'Vrste pretplata\' ovisno o vrsti posla kojeg obavljate. Na primjer, vi možete izabrati da nazovete nevsletter kao \'Pretplata,\' dok æete možda željeti nazvati kompjuterski software ili hardware kao \'Proizvod.\' Ovisi samo o vama kako æete nazvati ove zapise u aMember bazi podataka.');
define('_SETUP_THANK_YOU_REMEMBER', 'Zapamtite, jedan \'Proizvod\' ili \'Vrsta pretplate\' su samo razlièiti nazivi koji se odnose na istu stvar, koja je zapisana u jednoj aMember bazi podataka.');
define('_SETUP_THANK_YOU_SUBSCRTYPE', 'Vi možete pobliže oznaèiti vrstu pretplate (besplatna ili plaæena registracija, itd.) kada unesete proizvod.%sVažno je da postavite najmanje jedan proizvod!%s');
define('_SETUP_THANK_YOU_PAYCONF', 'Odredite da li vaš sistem(i) plaæanja zahtjeva neku posebnu konfiguraciju. Ako je tako onda možete pogledati %sInstallation Manual%s za više informacija, ili kontaktirati CGI-Central za usluge prilagoðavanja skripte.');
define('_SETUP_THANK_YOU_PROTECTION', 'Postavite svoju zaštitu za zaštiæena podruèja. Vi možete koristiti .htaccess ili PHP included datoteke. Da biste koristili moguænost logiranja na bazi Cookie-ja sve vaše zaštiæene datoteke moraju biti PHP! ');
define('_SETUP_THANK_YOU_CHECKINSTL', 'Provjerite vašu instalaciju taro što æete testirati vašu%s%sSignup Page%s.%sNakon što ste sve podesili i sve radi ispravno vi æete možda željeti da prilagodite neke od HTML predložaka. Vi trebate razmisliti o prilagoðavanju barem ovih predložaka:');
define('_SETUP_THANK_YOU_READMORE', 'Više o prilagoðavanju predložaka možete proèitati %sovdje%s.%sSavjet:%s 90% izgleda skripte aMember može biti prilagoðeno izgledu vaše web stranice tako što æete editirati CSS stylesheet u datoteci %sheader.html%s');
define('_SETUP_THANK_YOU_FEELFREE', 'Slobodno kontaktirajte %sCGI-Central Support%s ako trebate nešto prilagoditi u skripti.');
define('_SETUP_THANK_YOU_INFO', 'Takoðer, puno korisnih informacija možete naæi u %saMember Forum%s.');
define('_SETUP_HEADER1', 'aMember Setup: Korak %d od 6');

define('_UNSUBSCRIBE_ERROR', 'Pogrešno naznaèen URL, molimo da kontaktirate administratora stranice');

define('_PLUG_PAY_REDIRECT_WAIT', 'Molimo saèekajte...');
define('_PLUG_PAY_REDIRECT_REDIRECT', 'Preusmjeravanje na sigurnosnu stranicu za plaæanje');

define('_TPL_CC_INFO_TITLE', 'Podaci o Kreditnoj kartici');
define('_TPL_CC_INFO_CCTYPE', 'Vrsta kreditne kartice');
define('_TPL_CC_INFO_SELECT1', 'molimo da oznaèite jednu');
define('_TPL_CC_INFO_CHOOSE', '*** Molimo izaberite ***');
define('_TPL_CC_INFO_HOLDERNAME', 'Ime vlasnika kartice');
define('_TPL_CC_INFO_ASONCARD', 'ime vlasnika kartice, toèno kao na kartici');
define('_TPL_CC_INFO_HOLDERNAME2', 'Ime vlasnika kartice');
define('_TPL_CC_INFO_FLNAME', 'ime i prezime vlasnika kartice, toèko kao%što je na kartici');
define('_TPL_CC_INFO_CNAME', 'Naziv poduzeæa');
define('_TPL_CC_INFO_COMPNAME', 'naziv poduzeæa vezano uz%sadresu raèuna za transakciju');
define('_TPL_CC_INFO_CCNUM', 'Broj Kreditne kartice');
define('_TPL_CC_INFO_EXAMPLE', 'na primjer: 1111-2222-3333-4444');
define('_TPL_CC_INFO_EXPIRE', 'Kartica istjeèe');
define('_TPL_CC_INFO_EXPDATE', 'Oznaèite datum isteka kartice - mjesec i godina');
define('_TPL_CC_INFO_CCCODE', 'Kod Kreditne kartice');
define('_TPL_CC_INFO_CCCODEDESC', ' "Kod Kartice" je tro- ili èetvero-znamenkasti sigurnosni kod%skoji je otisnut na pozadini kreditne kartice\'s%straka za potpis (ili na prednjem dijelu za American Express kartice).');
define('_TPL_CC_INFO_ADDRINFO', 'Adresa - Podaci');
define('_TPL_CC_INFO_STRADDR', 'Ulica');
define('_TPL_CC_INFO_HNUMB', 'Kuæni broj');
define('_TPL_CC_INFO_CITY', 'Grad');
define('_TPL_CC_INFO_STATE', 'Regija / država');
define('_TPL_CC_INFO_ZIP', 'Poštanski broj / zip');
define('_TPL_CC_INFO_COUNTRY', 'Država');
define('_TPL_CC_INFO_PHONE', 'Telefon');
define('_TPL_CC_INFO_PHONENUM', 'unesite telefonski broj u slijedeæem%sformatu: %s999-999-9999%s');
define('_TPL_CC_INFO_MUSTMATCH', '(mora odgovarati adresi na koju vam se šalju izvještaji o kreditnoj kartici)');
define('_TPL_CC_INFO_SUBMIT_BUT', 'Update Info');
define('_TPL_CC_INFO_BACK_BUT', 'Natrag');
define('_TPL_CC_INFO_SUBMIT_BUT2', 'Naruèi');
define('_TPL_CC_INFO_SUBMIT_BUT_3', 'Naruèi i plati');

define('_TPL_CC_DECLINED_TITLE', 'Greška prilikom plaæanja');
define('_TPL_CC_DECLINED_TRYAGAIN', 'Pokušajte ponovo');



define('_TPL_CC_INFO_BANK_IDENTIFICATION', 'Identifikacija banke');
define('_TPL_CC_INFO_BIN_NAME', 'Naziv banke');
define('_TPL_CC_INFO_BIN_NAME_MORE', 'naziv banke koja je izdala kreditnu karticu');
define('_TPL_CC_INFO_BIN_PHONE', 'Telefon banke');
define('_TPL_CC_INFO_BIN_PHONE_MORE', 'Telefonski broj korisnièkog servisa napisan na pozadini vaše kreditne kartice');

define('_TPL_CC_VERIFY_CODE', 'Formular telefonske verifikacije');
define('_TPL_CC_INFO_CALLING', 'Mi smo nazvali telefonski broj kojeg ste unijeli');
define('_TPL_CC_INFO_VERIFY_CODE', 'Verifikacijski kod');
define('_TPL_CC_INFO_VERIFY_CODE_MORE', 'unesite kod kojeg ste dobili od automatskog sistema');
define('_TPL_CC_INFO_SUBMIT_VERIFY', 'Nastaviti');

define('_TPL_WRONG_VERIFY_CODE', 'Pogrešan verifikacijski kod. Molimo da pokušate ponovo.');

define('_TPL_CC_ERROR_TNI', 'Greška prilikom identifikacije telefonskog broja');
define('_TPL_CC_ERROR_TV',  'Greška prilikom telefonske verifikacije');
define('_TPL_CC_ERROR_CARDEREMAIL', 'Greška. Email u bazi podataka je visoko rizièna email poruka');
define('_TPL_CC_ERROR_COUNTRYNOTMATCH', 'Greška. IP adresa države ne poklapa se sa državom u adresi raèuna');
define('_TPL_CC_ERROR_HIGHRISKCOUNTRY', 'Greška. IP adresa ili država adrese raèuna je na popisu visokoriziènih država');
define('_TPL_CC_ERROR_ANONYMOUSPROXY', 'Greška. Anonimni proxy nije dozvoljen');
define('_TPL_CC_ERROR_FREEMAIL', 'Greška. Email od besplatnog davatelja email usluga nije dozvoljen');

define('_TPL_CC_ERROR_BIN', 'Greška. Država banke izdavatelja na temelju BIN broja ne podudara se sa državom u adresi primanja raèuna');
define('_TPL_CC_ERROR_BIN_NAME', 'Greška. Naziv banke izdavatelja ne podudara se sa unešenim binName');
define('_TPL_CC_ERROR_BIN_PHONE', 'Greška. Telefonski broj korisnièkog servisa ne podudara se sa unešenim binPhone');

define('_TPL_CC_DECLINED', 'Nevažeæi podaci o kreditnoj kartici. Vaša kreditna kartica je odbijena');


define('_TPL_JSVAL_ERR_FORM', 'Molimo unesite/odredite vrijednosti za slijedeæa polja:');
define('_TPL_JSVAL_ERR_SELECT', 'Molimo da odaberete valjano [%FIELDNAME%]');
define('_TPL_JSVAL_ERR_ENTER', 'Molimo da unesete valjano [%FIELDNAME%]');

define('_TPL_COMMON_SELECT_STATE', '[Odaberite regiju]');
define('_TPL_COMMON_SELECT_COUNTRY', '[Odaberite državu]');






define('_PLUG_PAY_ANYLINK_REDIR_ERROR', '"AnyLink URL" je prazan za proizvod#%d. Molimo da kontaktirate administratora stranice');
define('_PLUG_PAY_ANYLINK_TITLE', 'Plaæanje Kreditnom karticom');
define('_PLUG_PAY_ANYLINK_CCACCEPTED', 'sve glavne kreditne kartice su prihvaæene');





define('_PLUG_PAY_AUTHORIZE_TITLE', 'Authorize.Net Web Payment');
define('_PLUG_PAY_AUTHORIZE_DESCR', 'kreditna kartica via %sauthorize.net%s');
define('_PLUG_PAY_AUTHORIZE_ERROR', 'authorize GREŠKA: %s (Detalji: PNREF:%s, raèun:%s)%s%s');
define('_PLUG_PAY_AUTHORIZE_ERR_ARR', 'Greška prilikom procesiranja plaæanja:');
define('_PLUG_PAY_AUTHORIZE_ERR_ARR2', 'Molimo da se vratite natrag i pokušate ponovo.');
define('_PLUG_PAY_AUTHORIZE_USER_ERR', 'vraæeni iznos je prazan ili = 0');
define('_PLUG_PAY_AUTHORIZE_ERROR2', 'MD5 hash neispravan');
define('_PLUG_PAY_AUTHORIZE_ERROR3', 'Test transakcija je podnesena, kada je aMember configuiran za procesiranje uživo');
define('_PLUG_PAY_AUTHORIZE_ERROR4', 'finish_waiting_payment greška: %s');





define('_PLUG_PAY_AUTHORIZE_AIM_TITLE', 'Authorize AIM');
define('_PLUG_PAY_AUTHORIZE_AIM_DESC', 'Plaæanje kreditnom karticom');






define('_PLUG_PAY_AUTHORIZE_CIM_TITLE', 'Authorize CIM');
define('_PLUG_PAY_AUTHORIZE_CIM_DESC', 'Plaæanje kreditnom karticom');






define('_PLUG_PAY_ESOLUTIONS_TITLE', 'Merchant e-Solutions');
define('_PLUG_PAY_ESOLUTIONS_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_BEANSTREAM_TITLE', 'BeanStream');
define('_PLUG_PAY_BEANSTREAM_DESC', 'Plaæanje kreditnom karticom');
define('_PLUG_PAY_BEANSTREAM_PFAILED', 'Plaæanje nije uspjelo: ');





define('_PLUG_PAY_BEANSTREAM_REM_ERROR', 'beanstream_remote GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)%s%s');
define('_PLUG_PAY_BEANSTREAM_REM_DEBUG', 'beanstream_remote UKLONITI GREŠKE: ');
define('_PLUG_PAY_BEANSTREAM_REM_TITLE', 'BeanStream');
define('_PLUG_PAY_BEANSTREAM_REM_DESC', 'plaæanje kreditnom karticom');

define('_PLUG_PAY_BEANSTREAM_REM_HTML_TITLE', 'Stranica za plaæanje Kreditnom karicom');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CNAME', 'Naziv kartice');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CNAME2', '%stoèno%s kao na kreditnoj kartici');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CCNUM', 'Broj kreditne kartice');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CCEXP', 'Kreditna kartica istjeèe');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JAN', '1-Sijeèanj-Januar');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_FEB', '2-Veljaèa-Februar');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_MAR', '3-Ožujak-Mart');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_APR', '4-Travanj-April');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_MAY', '5-Svibanj-Maj');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JUN', '6-Lipanj-Juni');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JUL', '7-Srpanj-Juli');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_AUG', '8-Kolovoz-August');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_SEP', '9-Rujan-Septembar');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_OCT', '10-Listopad-Oktobar');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_NOV', '11-Studeni-Novembar');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_DEC', '12-Prosinac-Decembar');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ADDR', 'Adresa');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ADDR2', '%stoèna%s adresa kreditne kartice');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CITY', 'Grad');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CITY2', '%stoèan%s grad vlasnika kreditne kartice');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_COUNTRY', 'Država');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_COUNTRY2', '%stoèna%s država vlasnika kreditne kartice');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_STATE', 'Regija');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_STATE2', '%stoèna%s regija-država vlasnika kreditne kartice');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ZIP', 'Poštanski broj / zip');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_PHONE', 'Telefon');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_PROCEED', 'Proslijedi');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_FSUMB', 'ovaj formular æe biti podnešen na sigurnosnom serveru');





define('_PLUG_PAY_PAYCOM_FERROR', 'PayCom IPN GREŠKA: %s (Detalji: raèun:%d)%s');
define('_PLUG_PAY_PAYCOM_ERROR', 'Greška prilikom procesiranja plaæanja: %s');
define('_PLUG_PAY_PAYCOM_ERROR2', '%s Molimo da se vratite natrag i pokušate ponovo.');
define('_PLUG_PAY_PAYCOM_ERROR3', 'Postback lozinka neispravna: ');
define('_PLUG_PAY_PAYCOM_ERROR4', 'Paycom IPN: plaæanje nije uspjelo (Detalji: raèun:%d)%s');
define('_PLUG_PAY_PAYCOM_ERROR5', 'Test naèin je onemoguæen, prekidanje');
define('_PLUG_PAY_PAYCOM_ERROR6', 'Pogrešan kod proizvoda: [%d] umjesto [%d]');
define('_PLUG_PAY_PAYCOM_ERROR7', 'Pogrešna IP adresa: %s , dozvoljena IP maska je: ');
define('_PLUG_PAY_PAYCOM_ERROR8', 'Neispravan co_code');

define('_PLUG_PAY_PAYCOM_TITLE', 'PayCom');
define('_PLUG_PAY_PAYCOM_DESC', 'PayCom Procesiranje kreditne kartice');

define('_PLUG_PAY_PAYCOM_ERROR9', 'paycom GREŠKA: %s');
define('_PLUG_PAY_PAYCOM_ERROR10', 'Test naèin je onemoguæen');

define('_PLUG_PAY_PAYCOM_HTML_TITLE', 'Paycom plaæanje');
define('_PLUG_PAY_PAYCOM_HTML_TEXT1', 'Molimo da kliknete na dugme "Proslijedi" dugme da nastavite vaše plaæanje sa %sPaycom.net%s, našim ovlaštenim prodajnim agentom.');
define('_PLUG_PAY_PAYCOM_HTML_SUBMBUT', 'Proslijedi');





define('_PLUG_PAY_CC_CORE_FERROR1', '\'v\' je neispravna vrijednost');
define('_PLUG_PAY_CC_CORE_FERROR2', 'Member id je prazno');
define('_PLUG_PAY_CC_CORE_FERROR3', 'Payment_id je prazno');
define('_PLUG_PAY_CC_CORE_FERROR4', 'Netoèan vlasnik plaæanja');
define('_PLUG_PAY_CC_CORE_FERROR5', 'Plaæanje je veæ procesirano, molimo da odete na %sÈlansku stranicu%s');
define('_PLUG_PAY_CC_CORE_FERROR6', 'Vi ste veæ registrirani za ovu probnu pretplatu  - molimo da se vratite natrag na <a href=\'%s/signup.php\'>stranicu za registraciju</a> i izaberete drugi proizvod');
define('_PLUG_PAY_CC_CORE_SBSCNCL', 'Pretplata je otkazana');
define('_PLUG_PAY_CC_CORE_SBSCNCL2', 'Ponavljajuæa pretplata je otkazana.');
define('_PLUG_PAY_CC_CORE_CCINFOCHNG', 'Podaci o kreditnoj kartici su promjenjeni');
define('_PLUG_PAY_CC_CORE_REDIR', 'Preusmjeravamo vas na sistem plaæanja');
define('_PLUG_PAY_CC_CORE_FERROR7', 'Postupak je prazan');

define('_TPL_CC_INFO_PROVINCE', 'Billing International Province');
define('_TPL_CC_INFO_PROVINCE_DESC', 'za internacionalne provincije izvan USA i Kanade ukljuèuju ime provincije ovdje');
define('_TPL_CC_INFO_ISSUENUM', 'Kartica izdanje #');
define('_TPL_CC_INFO_ISSUENUM_DESC', 'je obavezno samo za Maestro/Solo/Switch kreditne kartice');
define('_TPL_CC_INFO_STARTDATE', 'Datum poèetka kartice');
define('_TPL_CC_INFO_STARTDATE_DESC', 'je obavezno samo za Maestro/Solo/Switch kreditne kartice');


define('_PLUG_PAY_CC_CORE_REDIR', 'Preusmjeravamo vas na sistem plaæanja');
define('_PLUG_PAY_CC_CORE_REDIRDESC', 'Vi æete biti automatski preusmjereni na stranicu za sigurnosno plaæanje za oko 2 sekunde');
define('_PLUG_PAY_CC_CORE_ERROR1', 'Molimo da unesete broj Kreditne kartice');
define('_PLUG_PAY_CC_CORE_ERROR2', 'Nevažeæi broj Kreditne kartice');
define('_PLUG_PAY_CC_CORE_ERROR3', 'Nevažeæi broj Kreditne kartice: ');
define('_PLUG_PAY_CC_CORE_ERROR4', 'Nevažeæi datum - mjesec isticanja');
define('_PLUG_PAY_CC_CORE_ERROR5', 'Nevažeæi datum - godina isticanja');
define('_PLUG_PAY_CC_CORE_ERROR6', 'Molimo da odaberete vrstu Kreditne kartice');
define('_PLUG_PAY_CC_CORE_ERROR7', 'Molimo da unesete kod Kreditne kartice');
define('_PLUG_PAY_CC_CORE_ERROR8', 'Molimo da unesete ime vlasnika Kreditne kartice');
define('_PLUG_PAY_CC_CORE_ERROR9', 'Molimo da unesete ime vlasnika Kreditne kartice');
define('_PLUG_PAY_CC_CORE_ERROR10', 'Molimo da unesete prezime vlasnika Kreditne kartice');
define('_PLUG_PAY_CC_CORE_ERROR11', 'Molimo da unesete poduzeæe kreditne kartice');
define('_PLUG_PAY_CC_CORE_ERROR12', 'Molimo da unesete telefonski broj');
define('_PLUG_PAY_CC_CORE_ERROR13', 'Molimo da unesete kuæni broj');
define('_PLUG_PAY_CC_CORE_ERROR14', 'Molimo da unesete ulicu');
define('_PLUG_PAY_CC_CORE_ERROR15', 'Molimo da unesete grad');
define('_PLUG_PAY_CC_CORE_ERROR16', 'Molimo da unesete regiju-državu');
define('_PLUG_PAY_CC_CORE_ERROR17', 'Molimo da unesete poštanski broj / zip code');
define('_PLUG_PAY_CC_CORE_ERROR18', 'Molimo da unesete državu');

define('_PLUG_PAY_CC_CORE_ERROR19', 'Nevažeæi datum poèetka - mjesec');
define('_PLUG_PAY_CC_CORE_ERROR20', 'Nevažeæi datum poèetka - godina');





define('_PLUG_PAY_CC_BILL_TITLE', 'Credit Card');
define('_PLUG_PAY_CC_BILL_DESCR', 'Plati sa Mastercard, Checkcards, Discover, JCB, Electronic via www.ccbill.com');
define('_PLUG_PAY_CC_BILL_CHECK_DESCR', 'Online plaæanje èekom via www.ccbill.com');
define('_PLUG_PAY_CC_BILL_TEL_DESCR', 'Telefonski raèun via www.ccbill.com');
define('_PLUG_PAY_CC_BILL_ERROR', 'Korisnièko ime i lozinka ne mogu biti jednaki, molimo da izaberete drugu lozinku');





define('_PLUG_PAY_CDG_TITLE', 'CDG');
define('_PLUG_PAY_CDG_DESCR', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_CENTIP_TITLE', 'Centipaid ');
define('_PLUG_PAY_CENTIP_DESC', '%sDigital Stored Value Cards%s');
define('_PLUG_PAY_CENTIP_FERROR', 'centipaid GREŠKA: %s (Detalji: PNREF:%s, raèun:%s)%s');
define('_PLUG_PAY_CENTIP_ERROR', 'Greška prilikom procesiranja plaæanja: ');
define('_PLUG_PAY_CENTIP_ERROR2', ' Molimo da se vratite natrag i pokušate ponovo');
define('_PLUG_PAY_CENTIP_ERROR3', 'vraæeni iznos je prazan ili = 0');
define('_PLUG_PAY_CENTIP_ERROR4', 'Test transakcija je podnesena, kada je aMember configuiran za procesiranje uživo');
define('_PLUG_PAY_CENTIP_ERROR5', 'finish_waiting_payment greška: %s');





define('_PLUG_PAY_CLICKBANK_TITLE', 'Clickbank');
define('_PLUG_PAY_CLICKBANK_DESC', 'Vidi %swww.clickbank.com%s za opis');
define('_PLUG_PAY_CLICKBANK_INCORRECT', 'Netoèno podnošenje #%d. Kontaktirajte webmastera');
define('_PLUG_PAY_CLICKBANK_ERROR', 'finish_waiting_payment greška: ');





define('_PLUG_PAY_DIRECTONE_TITLE', 'DirectOne');
define('_PLUG_PAY_DIRECTONE_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_DIRECTONEREM_TITLE', 'Plaæanje Kreditnom karticom (DirectOne)');
define('_PLUG_PAY_DIRECTONEREM_DESC', 'Vidi %swww.directone_remote.com%s za opis');
define('_PLUG_PAY_DIRECTONEREM_RETLNK', 'Povratak na stranicu sa èlanskim podacima');
define('_PLUG_PAY_DIRECTONEREM_ERROR', 'directone GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)%s');





define('_PLUG_PAY_PAYMENOW_TITLE', 'PayMeNow');
define('_PLUG_PAY_PAYMENOW_DESC', 'Plaæanje Kreditnom karticom');





define('_PLUG_PAY_PAYMONDE_TITLE', 'PayMonde');
define('_PLUG_PAY_PAYMONDE_DESC', 'Vidi %swww.paymonde.com%s za opis');

define('_PLUG_PAY_PAYMONDE_FERROR', 'paymonde GREŠKA: %s (Detalji: payment_id:%d, raèun:%d)');
define('_PLUG_PAY_PAYMONDE_ERROR', 'NEVAŽEÆI odgovor od PayMonde servera.  Vjerojatan pokušaj hakera.');





define('_PLUG_PAY_CC_DEMO_TITLE', 'CCDemo');
define('_PLUG_PAY_CC_DEMO_DESCR', 'Demo plaæanje Kreditnom karticom - koristite 4111-1111-1111-1111 kao broj Kreditne kartice');
define('_PLUG_PAY_CC_DEMO_CCNUM', 'Molimo da unesete broj Kreditne kartice 4111-1111-1111-1111 da dobijete uspješnu transakciju');





define('_PLUG_PAY_ECHO_TITLE', 'ECHO');
define('_PLUG_PAY_ECHO_DESC', 'Plaæanje Kreditnom karticom');





define('_PLUG_PAY_EFSNET_TITLE', 'EFSNet');
define('_PLUG_PAY_EFSNET_DESC', 'Plaæanje Kreditnom karticom');
define('_PLUG_PAY_EFSNET_ERROR', 'Plaæanje nije naðeno: #%d');
define('_PLUG_PAY_EFSNET_ERROR2', 'Plaæanje je veæ izvršeno: #%d');
define('_PLUG_PAY_EFSNET_ERROR3 ', 'Plaæanje je kreirano za drugi sistem plaæanja: %d (#%d)');
define('_PLUG_PAY_EFSNET_ERROR4', 'Plaæanje je kreirano za drugog èlana: #%d');
define('_PLUG_PAY_EFSNET_ERROR5', 'Èlan nije naðen: #%d');
define('_PLUG_PAY_EFSNET_ERROR6', 'aMember: Prazan rezultat od procesora, plaæanje nije uspjelo');





define('_PLUG_PAY_EGOLD_TITLE', 'E-Gold');
define('_PLUG_PAY_EGOLD_DESC', 'Plati sa e-gold (vidi %swww.e-gold.com%s za opis)');
define('_PLUG_PAY_EGOLD_ERROR', 'EGOLD GREŠKA: %s (Detalji: PAYMENT_BATCH_NUM:%d, raèun:%d)%s');
define('_PLUG_PAY_EGOLD_ERROR2', 'Primatelj uplate je %s umjesto mene: ');
define('_PLUG_PAY_EGOLD_ERROR3', 'Plaæanje je u drugoj valuti: %s umjesto zahtjevanih %s');
define('_PLUG_PAY_EGOLD_ERROR4', 'V2_HASH greška %s umjesto: %s');





define('_PLUG_PAY_EMATTERS_TITLE', 'eMatters.com.au');
define('_PLUG_PAY_EMATTERS_DESC', 'plaæanje kreditnom karticom');
define('_PLUG_PAY_EMATTERS_ERROR', 'Transakcija odbijena%s. Molimo pokušajte ponovo');
define('_PLUG_PAY_EMATTERS_CODE0', 'Transakcija je odobrena.');
define('_PLUG_PAY_EMATTERS_CODE1', 'Transakcija je odbijena. Vidi izdavatelja kartice.');
define('_PLUG_PAY_EMATTERS_CODE2', 'Transakcija je odbijena. Nazovite autorizacijski centar.');
define('_PLUG_PAY_EMATTERS_CODE3', 'Transakcija je odobrena. Molimo da potvrdite.');
define('_PLUG_PAY_EMATTERS_CODE4', 'Transakcija je odbijena. Nevažeæa vrsta transakcije.');
define('_PLUG_PAY_EMATTERS_CODE5', 'Transakcija je odbijena. Vidi izdavatelja kartice.');
define('_PLUG_PAY_EMATTERS_CODE6', 'Transakcija je odbijena. Nema CREDIT raèuna.');
define('_PLUG_PAY_EMATTERS_CODE7', 'Transakcija je odbijena. Nedovoljan iznos sredstava.');
define('_PLUG_PAY_EMATTERS_CODE8', 'Transakcija je odbijena. Prekoraèen limit kartice.');
define('_PLUG_PAY_EMATTERS_CODE9', 'Transakcija je odbijena. Izdavatelj nije dostupan.');
define('_PLUG_PAY_EMATTERS_CODE10', 'Non-Unique UID - Veæ prihvaæeno');
define('_PLUG_PAY_EMATTERS_CODE11', 'Transakcija je odobrena - Pogrešna vrsta kartice');
define('_PLUG_PAY_EMATTERS_CODE12', 'Nevažeæi iznos plaæanja');
define('_PLUG_PAY_EMATTERS_CODE13', 'Neprihvatljiv broj kartice');
define('_PLUG_PAY_EMATTERS_CODE14', 'Nevažeæi format datuma isticanja');
define('_PLUG_PAY_EMATTERS_CODE15', 'Kartica je istekla');
define('_PLUG_PAY_EMATTERS_CODE16', 'Host nije naðen, Bankovni sistem izvan rada');
define('_PLUG_PAY_EMATTERS_CODE17', 'Prijenos izgubljen, linija sa bankom prekinuta');
define('_PLUG_PAY_EMATTERS_ERROR', 'Transakcija odbijena%s. Molimo pokušajte ponovo');

define('_PLUG_PAY_EMATTERS_HTML_TITLE', 'Potvrda plaæanja');
define('_PLUG_PAY_EMATTERS_HTML_SELECTC', 'odaberite karticu');
define('_PLUG_PAY_EMATTERS_HTML_CCNUM', 'Broj kreditne kartice');
define('_PLUG_PAY_EMATTERS_HTML_CCEXP', 'Kreditna kartica istièe');
define('_PLUG_PAY_EMATTERS_HTML_CCHNAME', 'Ime vlasnika kreditne kartice');
define('_PLUG_PAY_EMATTERS_HTML_GOTOSITE', 'Odi na sigurnosnu stranicu');
define('_PLUG_PAY_EMATTERS_HTML_FORMSUBM', 'Ovaj formular æe biti podnesen na sigurnosnom serveru.');
define('_PLUG_PAY_EMATTERS_HTML_CCTYPE', 'Vrsta kreditne kartice');





define('_PLUG_PAY_EPASSPORT_TITLE', 'Epassporte');
define('_PLUG_PAY_EPASSPORT_DESC', 'Epassporte procesiranje plaæanja');
define('_PLUG_PAY_EPASSPORT_HTML_TITLE', 'Paycom plaæanje');
define('_PLUG_PAY_EPASSPORT_HTML_CLICKPAY', 'Molimo kliknite na dugme "Plati kroz ePassporte" da nastavite s vašim plaæanjem kroz ePassporte, našim autoriziranim prodajnim agentom.');
define('_PLUG_PAY_EPASSPORT_ERROR', 'epassporte GREŠKA:');
define('_PLUG_PAY_EPASSPORT_ERROR2', 'Greška prilikom procesiranja plaæanja: ');
define('_PLUG_PAY_EPASSPORT_ERROR3', ' Molimo da se vratite natrag i pokušate ponovo.');

define('_PLUG_PAY_EPASSPORT_ERROR4', 'Epassporte IPN GREŠKA: %s (Detalji: raèun:%d)%s');
define('_PLUG_PAY_EPASSPORT_ERROR5', 'Epassporte IPN: plaæanje nije uspjelo (Detalji: raèun:%d)%s');
define('_PLUG_PAY_EPASSPORT_ERROR6', 'Netoèan broj raèuna');
define('_PLUG_PAY_EPASSPORT_ERROR7', 'Netoèna IP adresa: %s , dozvoljena IP maska je: ');
define('_PLUG_PAY_EPASSPORT_ERROR8', 'Postback lozinka je netoèna: %s');
define('_PLUG_PAY_EPASSPORT_ERROR9', 'Ova transakcija je odbijena: ');
define('_PLUG_PAY_EPASSPORT_ERROR10', 'Zahvaljujemo na vašoj kupovini!');
define('_PLUG_PAY_EPASSPORT_ERROR11', 'Greška postupka verifikacije transakcije (TVP): ');
define('_PLUG_PAY_EPASSPORT_ERROR12', 'ePassporte IPN: transakcija za plaæanje %d je prihvaæena i verificirana');





define('_PLUG_PAY_EPROCESSING_TITLE', 'eProcessingNetwork');
define('_PLUG_PAY_EPROCESSING_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_EWAY_TITLE', 'E-Way');
define('_PLUG_PAY_EWAY_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_FREE_ID', 'besplatno');
define('_PLUG_PAY_FREE_TITLE', 'Besplatna registracija');
define('_PLUG_PAY_FREE_DESC', 'Potpuno besplatno');
define('_PLUG_PAY_FREE_NOTFORFREE', 'Ne možete koristiti plugin za BESPLATNO plaæanje sa proizvodom koji košta više od 0.0');
define('_PLUG_PAY_FREE_ERROR', 'Verifikacijski kod je netoèan. Molimo da kontaktirate administratora stranice ako je ovo pogrešno.');
define('_PLUG_PAY_FREE_MAILSENT', 'Mail je poslan administratoru. Molimo saèekajte dok on ne odobri.');
define('_PLUG_PAY_FREE_SIGNEDUP', 'Vi ste veæ registrirani. Molimo da se logirate %sovdje%s');





define('_PLUG_PAY_GLOBILL_ID', 'globill');
define('_PLUG_PAY_GLOBILL_TITLE', 'Glo-Bill Creditna kartica');
define('_PLUG_PAY_GLOBILL_DESC', 'Plati sa Visa, Mastercard, Checkcards, Discover, Eurocard, JCB, Diners cards, Electronic  via  %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_PH_ID', 'globill_phone');
define('_PLUG_PAY_GLOBILL_PH_TITLE', 'Glo-Bill telefon');
define('_PLUG_PAY_GLOBILL_PH_DESC', 'Plati s lakoæom putem Telefonske naplate #900 via  %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_CH_ID', 'globill_check');
define('_PLUG_PAY_GLOBILL_CH_TITLE', 'Glo-Bill èek');
define('_PLUG_PAY_GLOBILL_CH_DESC', 'Plati sa online èekom via %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_CANNOTORDER', 'Ovaj proizvod ne može biti naruèen sa GloBill Kreditnom karticom');
define('_PLUG_PAY_GLOBILL_CANNOTORDER2', 'Ovaj proizvod ne može biti naruèen sa GloBill telefonskom naplatom');
define('_PLUG_PAY_GLOBILL_CANNOTORDER3', 'Ovaj proizvod ne može biti naruèen sa GloBill Online èekom');
define('_PLUG_PAY_GLOBILL_ERROR', 'Interna Greška: nepoznat paysys_id: %d');
define('_PLUG_PAY_GLOBILL_FERROR', 'GLOBILL GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)%s');
define('_PLUG_PAY_GLOBILL_ERROR2', 'Netoèno donešeno korisnièko ime webmastera: %s!');





define('_PLUG_PAY_IKOBO_TITLE', 'ikobo');
define('_PLUG_PAY_IKOBO_DESC', 'Sigurnosno plaæanje kreditnom karticom');
define('_PLUG_PAY_IKOBO_ERROR', 'Postback lozinka netoèna');





define('_PLUG_PAY_INTERSEC_TITLE', 'InternetSecure');
define('_PLUG_PAY_INTERSEC_DESC', 'Plaæanje kreditnom karticom');
define('_PLUG_PAY_INTERSEC_ERROR', 'Netoèno podnošenje. Molimo da kontaktirate webmastera');





define('_PLUG_PAY_IPAYMENT_TITLE', 'IPayment.DE');
define('_PLUG_PAY_IPAYMENT_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_LINKPOINT_TITLE', 'LinkPoint');
define('_PLUG_PAY_LINKPOINT_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_MANCC_FERROR', 'Vi morate biti ovlašteni da to uradite');
define('_PLUG_PAY_MANCC_FERROR2', 'ID plaæanja nije naznaèen');
define('_PLUG_PAY_MANCC_FERROR3', 'Ne mogu uèitati èlanski zapis #%d (%d)');
define('_PLUG_PAY_MANCC_ERROR', 'Nevažeæi broj kreditne kartice');
define('_PLUG_PAY_MANCC_ERROR2', 'Nevažeæi datum isteka - mjesec');
define('_PLUG_PAY_MANCC_ERROR3', 'Nevažeæi datum isteka - godina');
define('_PLUG_PAY_MANCC_ERROR4', 'Molimo da unesete ulicu');
define('_PLUG_PAY_MANCC_ERROR5', 'Molimo da unesete grad');
define('_PLUG_PAY_MANCC_ERROR6', 'Molimo da unesete regiju-državu');
define('_PLUG_PAY_MANCC_ERROR7', 'Molimo da unesete poštanski broj / zip code');
define('_PLUG_PAY_MANCC_ERROR8', 'Molimo da oznaèite državu');
define('_PLUG_PAY_MANCC_ID', 'manual_cc');
define('_PLUG_PAY_MANCC_TITLE', 'Kreditna kartica');
define('_PLUG_PAY_MANCC_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_LOGICCOM_TITLE', 'LogicCommerce');
define('_PLUG_PAY_LOGICCOM_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_MONEYBOOK_ERROR', 'MD5 je netoèan: mi dobivamo %s, ali izraèun je %s (od %s)');
define('_PLUG_PAY_MONEYBOOK_ERROR2', 'moneybookers GREŠKA: %s (Detalji: txn_id:%d, raèun:%d)%s');
define('_PLUG_PAY_MONEYBOOK_ERROR3', 'Ovoj stranici ne bi trebalo biti pristupljeno iz browsera');
define('_PLUG_PAY_MONEYBOOK_ERROR4', 'Primatelj uplate je %s umjesto moj posao: ');
define('_PLUG_PAY_MONEYBOOK_ERROR5', 'Plaæanje nije procesirano, status: ');

define('_PLUG_PAY_MONEYBOOK_TITLE', 'MoneyBookers');
define('_PLUG_PAY_MONEYBOOK_DESC', 'Vidi %swww.moneybookers.com%s za opis');





define('_PLUG_PAY_MULTICARD_ERROR', 'multicards GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)%s');
define('_PLUG_PAY_MULTICARD_ERROR2', 'Greška prilikom procesiranja plaæanja: ');
define('_PLUG_PAY_MULTICARD_ERROR3', 'Molimo vratite se natrag i pokušajte ponovo.');
define('_PLUG_PAY_MULTICARD_ERROR4', 'Plaæanje nije uspjelo');
define('_PLUG_PAY_MULTICARD_ERROR5', 'vraæeni iznos je prazan ili = 0');
define('_PLUG_PAY_MULTICARD_ERROR6', 'Netoèna IP adresa');
define('_PLUG_PAY_MULTICARD_ERROR7', 'Netoèan merchant id');

define('_PLUG_PAY_MULTICARD_TITLE', 'Multi-Cards');
define('_PLUG_PAY_MULTICARD_DESCR', 'Multi-Cards Credit Card Processing');

define('_PLUG_PAY_MULTICARD_HTML_TITLE', 'MultiCards stranica za plaæanje');
define('_PLUG_PAY_MULTICARD_HTML_CNAME', 'Naziv kartice');
define('_PLUG_PAY_MULTICARD_HTML_4CONT', 'za kontakt');
define('_PLUG_PAY_MULTICARD_HTML_EMAIL', 'Kontakt EMail');
define('_PLUG_PAY_MULTICARD_HTML_4CONTE', 'za kontakt');
define('_PLUG_PAY_MULTICARD_HTML_CNAME', 'Naziv kartice');
define('_PLUG_PAY_MULTICARD_HTML_ASONCC', '%stoèno%s kao na kreditnoj kartici');
define('_PLUG_PAY_MULTICARD_HTML_ADDRESS', 'Adresa');
define('_PLUG_PAY_MULTICARD_HTML_ADDOFCC', '%stoèna%s adresa iz kreditne kartice');
define('_PLUG_PAY_MULTICARD_HTML_CITY', 'Grad');
define('_PLUG_PAY_MULTICARD_HTML_EXCITY', '%stoèan%s grad + poštanski broj (iskljuèivo USA) vlasnika%skreditne kartice, npr. %sLondon E12 6HB%s');
define('_PLUG_PAY_MULTICARD_HTML_COUNTRY', 'Država');
define('_PLUG_PAY_MULTICARD_HTML_EXCOUNTRY', '%stoèna%s država vlasnika kreditne kartice');
define('_PLUG_PAY_MULTICARD_HTML_STATE', 'Regija-država');
define('_PLUG_PAY_MULTICARD_HTML_EXSTATE', '%stoèna%s regija-država vlasnika kreditne kartice');
define('_PLUG_PAY_MULTICARD_HTML_ZIP', 'Poštanski broj / zip');
define('_PLUG_PAY_MULTICARD_HTML_EXZIP', '%stoèan%s Poštanski broj / zip od USA vlasnika %skreditne kartice ');
define('_PLUG_PAY_MULTICARD_HTML_IFNOTUSA', '(ako nije u USA, unesite %s99999%s)');
define('_PLUG_PAY_MULTICARD_HTML_SUB_BUT', 'Nastavi');





define('_PLUG_PAY_NETBILLING_FERROR', 'Èlanski ID nije naveden');
define('_PLUG_PAY_NETBILLING_FERROR2', 'Vi morate biti ovlašteni da to uradite');
define('_PLUG_PAY_NETBILLING_FERROR3', 'Platni ID nije naveden');
define('_PLUG_PAY_NETBILLING_FERROR4', 'Ne mogu uèitati èlanski zapis #%d (%d)');
define('_PLUG_PAY_NETBILLING_ERROR', 'Nevažeæi broj kreditne kartice');
define('_PLUG_PAY_NETBILLING_ERROR2', 'Nevažeæi datum isteka - mjesec');
define('_PLUG_PAY_NETBILLING_ERROR3', 'Nevažeæi datum isteka - godina');
define('_PLUG_PAY_NETBILLING_ERROR4', 'Molimo da unesete kod kreditne kartice');
define('_PLUG_PAY_NETBILLING_ERROR5', 'Molimo da unesete ulicu');
define('_PLUG_PAY_NETBILLING_ERROR6', 'Molimo da unesete grad');
define('_PLUG_PAY_NETBILLING_ERROR7', 'Molimo da unesete regiju-državu');
define('_PLUG_PAY_NETBILLING_ERROR8', 'Molimo da unesete Poštanski broj / zip code');
define('_PLUG_PAY_NETBILLING_ERROR9', 'Molimo da unesete državu');

define('_PLUG_PAY_NETBILLING_TITLE', 'NetBilling');
define('_PLUG_PAY_NETBILLING_CC_PAYMENT', 'Plaæanje kreditnom karticom');

define('_PLUG_PAY_NETBILLING_FERROR5', 'Korisnièko ime nije konfiguirano za NetBilling');
define('_PLUG_PAY_NETBILLING_PNOTFOUND', 'Plaæanje nije naðeno: #%d');
define('_PLUG_PAY_NETBILLING_PCOMPLETED', 'Plaæanje je veæ izvršeno: #%d');
define('_PLUG_PAY_NETBILLING_ANOTHERPSYS', 'Plaæanje je kreirano za drugi sistem plaæanja:');
define('_PLUG_PAY_NETBILLING_ANOTHERMEMBER', 'Plaæanje je kreirano za drugog èlana: #%d');
define('_PLUG_PAY_NETBILLING_MEMNOTFOUND', 'Èlan nije naðen: #%d');
define('_PLUG_PAY_NETBILLING_EMPTYRES', 'aMember: Prazan rezultat od procesora, plaæanje nije uspjelo');





define('_PLUG_PAY_NOCHEX_FERROR', 'nochex GREŠKA: %s (Detalji: txn_id:%d, raèun:%d)%s');
define('_PLUG_PAY_NOCHEX_ERROR', 'IPN stranici treba biti pristupljeno samo kroz nochex, ne od korisnika');
define('_PLUG_PAY_NOCHEX_ERROR2', 'Primatelj uplate je %s umjesto moj posao: ');
define('_PLUG_PAY_NOCHEX_ERROR3', 'ODBIJEN odgovor iz nochex servera. Vjerojatan pokušaj hakera (%s)');
define('_PLUG_PAY_NOCHEX_ERROR4', 'Nešto nije VERIFICIRANO ili su naðene NEVAŽEÆE rijeèi u odgovoru (%s)');

define('_PLUG_PAY_NOCHEX_TITLE', 'NoChex');
define('_PLUG_PAY_NOCHEX_DESC', 'Sigurno plaæanje kreditnom karticom');





define('_PLUG_PAY_OFFLINE_TITLE', 'Offline plaæanje');
define('_PLUG_PAY_OFFLINE_DESC', 'Offline plaæanje');

define('_PLUG_PAY_OFFLINE_HTML_HEAD', 'Izmijeni ovu datoteku');
define('_PLUG_PAY_OFFLINE_HTML_HEAD2', 'tako da odgovara vašim potrebama za offline plaæanje.');
define('_PLUG_PAY_OFFLINE_HTML_PUSR', 'Plaæanje#/Korisnièko ime: ');
define('_PLUG_PAY_OFFLINE_HTML_PRICE', 'Cijena:     ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT1', 'Ovdje stavite upute za kupca kako da izvrši plaæanje.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT2', 'Pobrinite se da kupac ukljuèi korisnièko ime(login) i platni#');
define('_PLUG_PAY_OFFLINE_HTML_TEXT3', 'u opis plaæanja. Nakon toga æe vam biti lako da naðete ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT4', 'narudžbu kasnije.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT5', 'Kada vi primite izvršenu uplatu, oznaèite plaæanje kao "Izvršeno"');
define('_PLUG_PAY_OFFLINE_HTML_TEXT6', 'u aMember control panelu. Korisnik æe primiti email sa login podacima');
define('_PLUG_PAY_OFFLINE_HTML_TEXT7', 'i moæi æe uæi u stranicu.');





define('_PLUG_PAY_OGONE_TITLE', 'Ogone');
define('_PLUG_PAY_OGONE_DESC', 'sigurno plaæanje kreditnom karticom');
define('_PLUG_PAY_OGONE_ERROR', 'Nepoznat STATUS kod: [%s]');
define('_PLUG_PAY_OGONE_ERROR2', 'vraæeni iznos prazan ili = 0');





define('_PLUG_PAY_PSWDCALL_FERROR', 'passwordcall GREŠKA: %s (Detalji: txn_id:%d, raèun:%d)%s');
define('_PLUG_PAY_PSWDCALL_ERROR', 'Pogrešan webmaster id: %d');
define('_PLUG_PAY_PSWDCALL_TITLE', 'PasswordCall');
define('_PLUG_PAY_PSWDCALL_DESC', 'Vidi %swww.passwordcall.de%s za opis');





define('_PLUG_PAY_BLUEPAY_TITLE', 'BluePay');
define('_PLUG_PAY_BLUEPAY_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_PAYFLINK_FERROR', 'PAYFLOW GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)%s');
define('_PLUG_PAY_PAYFLINK_ERROR', 'vraæeni iznos prazan ili = 0');

define('_PLUG_PAY_PAYFLINK_TITLE', 'PayFlow Link');
define('_PLUG_PAY_PAYFLINK_DESC', 'Vidi %swww.verisign.com%s za opis');





define('_PLUG_PAY_PAYFLPRO_TITLE', 'PayFlow Pro');
define('_PLUG_PAY_PAYFLPRO_DESC', 'Plaæanje kreditnom karticom');
define('_PLUG_PAY_PAYFLPRO_ERROR', 'PayFlow plugin konfiguracijska greška: datoteka %s%s%s ne postoji');
define('_PLUG_PAY_PAYFLPRO_ERROR2', 'PayFlow plugin konfiguracijska greška: datoteka %s%s%s nije izvršna. Molimo da postavite chmod za ovu datoteku na 755');
define('_PLUG_PAY_PAYFLPRO_FERROR', 'Ne mogu pokrenuti skriptu za plaæanje');
define('_PLUG_PAY_PAYFLPRO_ERROR3', 'Greška prilikom pokretanja pfpro skripte, vraæen rezultat: %s');
define('_PLUG_PAY_PAYFLPRO_CCDECL', 'Kartica je odbijena. Provjerite da li unešena adresa odgovara adresi za isporuku izvještaja kreditne kartice');





define('_PLUG_PAY_PYMGTWAY_TITLE', 'PaymentsGateway');
define('_PLUG_PAY_PYMGTWAY_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_EGSPAY_TITLE', 'AC Pay');
define('_PLUG_PAY_EGSPAY_DESC', 'Vidi <a href="http://www.egspay.com" target=_blank>www.egspay.com</a> za opis');
define('_PLUG_PAY_EGSPAY_ERROR', 'egspay GREŠKA: %s (Detalji: raèun:%d)%s');





define('_PLUG_PAY_PAYPALR_INVEMAIL', 'Nevažeæi email: $email, skipped');
define('_PLUG_PAY_PAYPALR_IDEMPTY', 'ID pretplate je prazan za %s');
define('_PLUG_PAY_PAYPALR_NOPAYMENTS', 'Nije naðen zapis plaæanja za');
define('_PLUG_PAY_PAYPALR_2MUCHREC', 'Previše (>1) zapisa o plaæanju je naðeno za');

define('_PLUG_PAY_PAYPALR_TITLE', 'PayPal');
define('_PLUG_PAY_PAYPALR_DESC', 'sigurno plaæanje kreditnom karticom');
define('_PLUG_PAY_PAYPALR_FERROR', 'Razdoblje treba biti u intervalu od 1-5 godina');
define('_PLUG_PAY_PAYPALR_FERROR2', 'Razdoblje treba biti u intervalu od 1-24 mjeseci');
define('_PLUG_PAY_PAYPALR_FERROR3', 'Razdoblje treba biti u intervalu od 1-52 tjedana');
define('_PLUG_PAY_PAYPALR_FERROR4', 'Razdoblje treba biti u intervalu od 1-90 dana');
define('_PLUG_PAY_PAYPALR_FERROR5', 'Nepoznata jedinica razdoblja: %s');
define('_PLUG_PAY_PAYPALR_FERROR6', 'Netoèna vrijednost za istek u danima: ');
define('_PLUG_PAY_PAYPALR_FERROR7', 'Slijedeæe kombinacije proizvoda (ponavljajuæe i ne-ponavljajuæe) ne mogu biti naruèene odjednom. Molimo da naruèite prvi proizvod, zatim odite u èlansko podruèje i naruèite drugi proizvod');
define('_PLUG_PAY_PAYPALR_FERROR8', 'Slijedeæe kombinacije proizvoda ne mogu biti naruèene odjednom. Molimo da naruèite prvi proizvod, zatim odite u èlansko podruèje i naruèite drugi proizvod');
define('_PLUG_PAY_PAYPALR_FERROR9', 'Ovdje je izabrano nekoliko proizvoda sa razlièitom valutom za naplatu. Nemoguæe je dovršiti ovu narudžbu - molimo da izaberete drugu grupu proizvoda');
define('_PLUG_PAY_PAYPALR_ERROR', 'Nije moguæe ovjeriti PayPal IPN post: FOPEN [%s] results to [%s (%s)]');
define('_PLUG_PAY_PAYPALR_ERROR2', 'Paypal tvrdi da to nije valjana IPN transakcija: [%s]');
define('_PLUG_PAY_PAYPALR_ERROR3', 'IPN validation greška: %s');
define('_PLUG_PAY_PAYPALR_ERROR4', 'Email primatelja uplate [%s] je nepoznat, plaæanje je odbaèeno.<br />');
define('_PLUG_PAY_PAYPALR_ERROR5', 'Ako je to pogrešno, molimo da dodate email adresu %s na aMember CP -> Setup -> PayPal');
define('_PLUG_PAY_PAYPALR_ERROR6', 'Paypal status plaæanja je [%s], IPN poruka æe biti ignorirana<br />');
define('_PLUG_PAY_PAYPALR_ERROR7', 'To nije greška ili problem, samo poruka o statusu za vašu informaciju');
define('_PLUG_PAY_PAYPALR_ERROR8', 'Paypal valuta za plaæanje je [%s] umjesto oèekivanih [%s]');
define('_PLUG_PAY_PAYPALR_ERROR9', 'odobren iznos je [%d], treba biti [%d]');
define('_PLUG_PAY_PAYPALR_ERROR11', 'Ne mogu naæi pripadajuæi aMember platni zapis za ovu uplatu');
define('_PLUG_PAY_PAYPALR_ERROR12', 'Kuponi ne mogu biti korišteni sa PayPal isprobavanjima, molimo da kontaktirate administratora');





define('_PLUG_PAY_PAYRDY_FERROR', 'Vi morate biti ovlašteni da to uradite');
define('_PLUG_PAY_PAYRDY_FERROR2', 'Platni ID nije naveden');
define('_PLUG_PAY_PAYRDY_FERROR3', 'Ne mogu uèitati èlanski zapis #%d (%d)');
define('_PLUG_PAY_PAYRDY_ERROR', 'Molimo da odaberete vrstu kreditne kartice');
define('_PLUG_PAY_PAYRDY_ERROR2', 'Nevažeæi broj kreditne kartice');
define('_PLUG_PAY_PAYRDY_ERROR3', 'Nevažeæi datum isteka - mjesec');
define('_PLUG_PAY_PAYRDY_ERROR4', 'Nevažeæi datum isteka - godina');
define('_PLUG_PAY_PAYRDY_ERROR5', 'Molimo da unesete ulicu');
define('_PLUG_PAY_PAYRDY_ERROR6', 'Molimo da unesete grad');
define('_PLUG_PAY_PAYRDY_ERROR7', 'Molimo da unesete regiju-državu');
define('_PLUG_PAY_PAYRDY_ERROR8', 'Molimo da unesete Poštanski broj / zip code');
define('_PLUG_PAY_PAYRDY_ERROR9', 'Molimo da unesete državu');

define('_PLUG_PAY_PAYRDY_ERROR10', 'Plaæanje nije naðeno: #%d');
define('_PLUG_PAY_PAYRDY_ERROR11', 'Plaæanje je veæ izvršeno: #%d');
define('_PLUG_PAY_PAYRDY_ERROR12', 'Plaæanje je kreirano za drugi sistem plaæanja: ');
define('_PLUG_PAY_PAYRDY_ERROR13', 'aMember: Prazan rezultat iz procesora, plaæanje nije uspjelo');
define('_PLUG_PAY_PAYRDY_ERROR14', 'Greška platnog procesora: ');

define('_PLUG_PAY_PAYRDY_TITLE', 'PayReady');
define('_PLUG_PAY_PAYRDY_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_PAYZIP_TITLE', 'PayZIP');
define('_PLUG_PAY_PAYZIP_DESC', 'sigurno plaæanje kreditnom karticom');
define('_PLUG_PAY_PAYZIP_ERROR', 'Loša povezanost ');
define('_PLUG_PAY_PAYZIP_FERROR', 'Nema odgovora od PayZIP - transakcija prekinuta. Molimo pokušajte ponovo kasnije.');





define('_PLUG_PAY_PLUGNPAY_FERROR', 'Èlanski ID nije naveden');
define('_PLUG_PAY_PLUGNPAY_FERROR2', 'Vi morate biti ovlašteni da to uradite');
define('_PLUG_PAY_PLUGNPAY_FERROR3', 'Platni ID nije naveden');
define('_PLUG_PAY_PLUGNPAY_FERROR4', 'Ne mogu uèitati èlanski zapis #%d (%d)');
define('_PLUG_PAY_PLUGNPAY_ERROR', 'nema izvještaja od plugnpay, plaæanje #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR2', 'Nevažeæi datum isteka - mjesec');
define('_PLUG_PAY_PLUGNPAY_ERROR3', 'Nevažeæi datum isteka - godina');
define('_PLUG_PAY_PLUGNPAY_ERROR4', 'Molimo da unesete kod kreditne kartice');
define('_PLUG_PAY_PLUGNPAY_ERROR5', 'Molimo da unesete ulicu');
define('_PLUG_PAY_PLUGNPAY_ERROR6', 'Molimo da unesete grad');
define('_PLUG_PAY_PLUGNPAY_ERROR7', 'Molimo da unesete regiju-državu');
define('_PLUG_PAY_PLUGNPAY_ERROR8', 'Molimo da unesete Poštanski broj / zip code');
define('_PLUG_PAY_PLUGNPAY_ERROR9', 'Molimo da unesete državu');
define('_PLUG_PAY_PLUGNPAY_ERROR10', 'Plaæanje nije naðeno: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR11', 'Plaæanje je veæ izvršeno: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR12', 'Plaæanje je kreirano za drugi sistem plaæanja');
define('_PLUG_PAY_PLUGNPAY_ERROR13', 'Èlan nije naðen: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR14', 'Prazan rezultat, plaæanje nije uspjelo #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR15', 'aMember: Prazan rezultat iz procesora, plaæanje nije uspjelo');

define('_PLUG_PAY_PLUGNPAY_TITLE', 'PlugNPay');
define('_PLUG_PAY_PLUGNPAY_DESC', 'plaæanje kreditnom karticom');
define('_PLUG_PAY_PLUGNPAY_ERROR', 'nema izvještaja od plugnpay, plaæanje #%d');





define('_PLUG_PAY_PROBILLING_FERROR', 'PROBILLING GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)<br />');
define('_PLUG_PAY_PROBILLING_ERROR', 'Status nije NOVO ili PLAÆENO');
define('_PLUG_PAY_PROBILLING_TITLE', 'ProBilling');
define('_PLUG_PAY_PROBILLING_DESC', 'Prihvaæa kreditne kartice, e-èekove i podržava 900 naplatu');





define('_PLUG_PAY_PROTX_TITLE', 'Protx');
define('_PLUG_PAY_PROTX_DESC', 'Plati sa kreditnom karticom/debitnom karticom - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');

define('_PLUG_PAY_PROTX_HTML_TITLE', 'Proslijediti na stranicu za sigurno plaæanje');





define('_PLUG_PAY_PSIGATE_TITLE', 'PsiGate');
define('_PLUG_PAY_PSIGATE_DESC', 'Credit Card Payment');
define('_PLUG_PAY_PSIGATE_ERROR', 'Interna greška');

define('_PLUG_PAY_PSIGATE_HTML_TITLE', 'Stranica za plaæanje kreditnom karticom');
define('_PLUG_PAY_PSIGATE_HTML_CNAME', 'Naziv kartice');
define('_PLUG_PAY_PSIGATE_HTML_ASONCC', '%stoèno%s kao na kreditnoj kartici');
define('_PLUG_PAY_PSIGATE_HTML_CCNUM', 'Broj kreditne kartice');
define('_PLUG_PAY_PSIGATE_HTML_CCEXP', 'Kreditna kartica istièe');
define('_PLUG_PAY_PSIGATE_HTML_JAN', '1-Sijeèanj-Januar');
define('_PLUG_PAY_PSIGATE_HTML_FEB', '2-Veljaèa-Februar');
define('_PLUG_PAY_PSIGATE_HTML_MAR', '3-Ožujak-Mart');
define('_PLUG_PAY_PSIGATE_HTML_APR', '4-Travanj-April');
define('_PLUG_PAY_PSIGATE_HTML_MAY', '5-Svibanj-Maj');
define('_PLUG_PAY_PSIGATE_HTML_JUN', '6-Lipanj-Juni');
define('_PLUG_PAY_PSIGATE_HTML_JUL', '7-Srpanj-Juli');
define('_PLUG_PAY_PSIGATE_HTML_AUG', '8-Kolovoz-August');
define('_PLUG_PAY_PSIGATE_HTML_SEP', '9-Rujan-Septembar');
define('_PLUG_PAY_PSIGATE_HTML_OCT', '10-Listopad-Oktobar');
define('_PLUG_PAY_PSIGATE_HTML_NOV', '11-Studeni-Novembar');
define('_PLUG_PAY_PSIGATE_HTML_DEC', '12-Prosinac-Decembar');
define('_PLUG_PAY_PSIGATE_HTML_ADDR', 'Adresa');
define('_PLUG_PAY_PSIGATE_HTML_ADOFCC', '%stoèna%s adresa vlasnika kreditne kartice');
define('_PLUG_PAY_PSIGATE_HTML_CITY', 'Grad');
define('_PLUG_PAY_PSIGATE_HTML_CTOFCC', '%stoèan%s grad vlasnika%skreditne kartice');
define('_PLUG_PAY_PSIGATE_HTML_COUNTRY', 'Država');
define('_PLUG_PAY_PSIGATE_HTML_CNOFCC', '%stoèna%s država vlasnika kreditne kartice');
define('_PLUG_PAY_PSIGATE_HTML_STATE', 'Regija-država');
define('_PLUG_PAY_PSIGATE_HTML_STOFCC', '%stoèna%s regija-država kreditne kartice');
define('_PLUG_PAY_PSIGATE_HTML_ZIP', 'Poštanski broj / zip');
define('_PLUG_PAY_PSIGATE_HTML_SUBBUT', 'Nastavi');
define('_PLUG_PAY_PSIGATE_HTML_DESCR', 'ovaj formular æe biti podnešen na sigurnom serveru');





define('_PLUG_PAY_QCHEX_TITLE', 'QChex');
define('_PLUG_PAY_QCHEX_DESC', 'Plati sa èekom (vidi %swww.qchex.com%s za opis)');





define('_PLUG_PAY_SECURTRD_FERROR', 'securetrading GREŠKA: %s (Detalji: txn_id:%d, raèun:%d)%s');
define('_PLUG_PAY_SECURTRD_TITLE', 'SecureTrading');
define('_PLUG_PAY_SECURTRD_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_STORMPAY_FERROR', 'StormPay GREŠKA: %s (Detalji: txn_id:%d, raèun:%d)%s');
define('_PLUG_PAY_STORMPAY_ERROR', 'Netoèan tajni kod: %s');
define('_PLUG_PAY_STORMPAY_ERROR2', 'Primatelj uplate je %s umjesto moj posao: ');
define('_PLUG_PAY_STORMPAY_ERROR3', 'Plaæanje nije procesirano, status: %s');

define('_PLUG_PAY_STORMPAY_TITLE', 'StormPay');
define('_PLUG_PAY_STORMPAY_DESC', 'Vidi %swww.stormpay.com%s za opis');





define('_PLUG_PAY_INETCOM_FERROR', 'Èlanski ID nije naveden');
define('_PLUG_PAY_INETCOM_FERROR2', 'Vi morate biti ovlašteni da to uradite');
define('_PLUG_PAY_INETCOM_FERROR3', 'Platni ID nije naveden');
define('_PLUG_PAY_INETCOM_FERROR4', 'Ne mogu uèitati èlanski zapis #%d (%d)');
define('_PLUG_PAY_INETCOM_ERROR', 'Nevažeæi broj kreditne kartice');
define('_PLUG_PAY_INETCOM_ERROR2', 'Nevažeæi datum isteka - mjesec');
define('_PLUG_PAY_INETCOM_ERROR3', 'Nevažeæi datum isteka - godina');
define('_PLUG_PAY_INETCOM_ERROR4', 'Molimo da unesete kod kreditne kartice');
define('_PLUG_PAY_INETCOM_ERROR5', 'Molimo da unesete ulicu');
define('_PLUG_PAY_INETCOM_ERROR6', 'Molimo da unesete grad');
define('_PLUG_PAY_INETCOM_ERROR7', 'Molimo da unesete regiju-državu');
define('_PLUG_PAY_INETCOM_ERROR8', 'Molimo da unesete Poštanski broj / zip code');
define('_PLUG_PAY_INETCOM_ERROR9', 'Molimo da unesete državu');
define('_PLUG_PAY_INETCOM_ERROR10', 'Plaæanje nije naðeno: #%d');
define('_PLUG_PAY_INETCOM_ERROR11', 'Plaæanje je veæ izvršeno: #%d');
define('_PLUG_PAY_INETCOM_ERROR12', 'Plaæanje je kreirano za drugi sistem plaæanja: %s (#%d)');
define('_PLUG_PAY_INETCOM_ERROR13', 'Èlan nije naðen: #%d');

define('_PLUG_PAY_INETCOM_TITLE', 'TheInternetCommerce');
define('_PLUG_PAY_INETCOM_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_24eKOUT_TITLE', '2Checkout');
define('_PLUG_PAY_24eKOUT_DESC', 'Kupite od 2Checkout');
define('_PLUG_PAY_24eKOUT_ERROR', 'Pokušavate koristiti demo naèin, ali demo naèin nije omoguæen');
define('_PLUG_PAY_24eKOUT_ERROR2', 'Kreditna kartica ne može biti procesirana');
define('_PLUG_PAY_24eKOUT_ERROR3', 'Nije moguæe potvrditi da ste platili, molimo da kontaktirate webmastera');





define('_PLUG_PAY_WORLDPAY_FERROR', 'WORLDPAY GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)%s');
define('_PLUG_PAY_WORLDPAY_ERROR', 'Netoèna IP adresa za WorldPay podnošenje');
define('_PLUG_PAY_WORLDPAY_ERROR2', 'Transakcija odbijena (%s)');
define('_PLUG_PAY_WORLDPAY_ERROR3', 'Test naèin onemoguæen');
define('_PLUG_PAY_WORLDPAY_ERROR4', 'Netoèan instalacijski ID: to nije naše plaæanje');
define('_PLUG_PAY_WORLDPAY_ERROR5', 'vraæeni iznos prazan ili = 0');
define('_PLUG_PAY_WORLDPAY_ERROR6', 'Plaæanje je veæ procesirano (worldpay raèun#: %d) u plaæanju #%d');

define('_PLUG_PAY_WORLDPAY_TITLE', 'WorldPay');
define('_PLUG_PAY_WORLDPAY_DESC', 'Plati sa kreditnom karticom/debitnom karticom - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');
define('_PLUG_PAY_WORLDPAY_FERROR2', 'Nepoznata jedinica razdoblja u expire_days. Treba biti d|m|w|y');
define('_PLUG_PAY_WORLDPAY_FERROR3', 'Neispravna vrijednost za $s: %s');
define('_PLUG_PAY_WORLDPAY_FERROR4', 'Neispravna vrijednost za %s u proizvodu #');





define('_PLUG_PAY_VEROTEL_FERROR', 'VEROTEL GREŠKA: %s (Detalji: raèun:%d)%s');

define('_PLUG_PAY_VEROTEL_TITLE', 'VeroTel');
define('_PLUG_PAY_VEROTEL_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_PAYPALPRO_TITLE', 'Checkout sa PayPal');
define('_PLUG_PAY_PAYPALPRO_DESC', 'Brza, sigurna blagajna sa PayPal.<br />Štedi vrijeme. Sigurna naplata. Plati bez razmjene<br />vaših financijskih podataka.');
define('_PLUG_PAY_PAYPALPRO_FERROR', 'Ovdje je izabrano nekoliko proizvoda sa razlièitom valutom za naplatu. Nemoguæe je dovršiti ovu narudžbu - molimo da izaberete drugu grupu proizvoda');
define('_PLUG_PAY_PAYPALPRO_FERROR2', 'Interna greška tijekom procesiranja (get_caller): ');
define('_PLUG_PAY_PAYPALPRO_FERROR3', 'Vraæeni token je prazan');
define('_PLUG_PAY_PAYPALPRO_REDIRECT', 'Preusmjeravamo vas na PayPal WebSite');
define('_PLUG_PAY_PAYPALPRO_REDIRECT2', 'Vi ste sada prešli na PayPal web stranicu za login i izvršenje plaæanja');
define('_PLUG_PAY_PAYPALPRO_FERROR4', 'Interna greška procesiranja : ');
define('_PLUG_PAY_PAYPALPRO_FERROR5', 'Interna greška: ');
define('_PLUG_PAY_PAYPALPRO_FERROR6', 'Platni status nije dovršen, molimo da kontartirate podršku na stranici');
define('_PLUG_PAY_PAYPALPRO_FERROR7', 'Molimo da %sslijedite korake registracije ponovo%s');
define('_PLUG_PAY_PAYPALPRO_ERROR', 'Vraæeni token je prazan');
define('_PLUG_PAY_PAYPALPRO_ERROR2', 'Plaæanje #%d nije naðeno');
define('_PLUG_PAY_PAYPALPRO_FERROR8', 'Vraæen je prazan txn_id');
define('_PLUG_PAY_PAYPALPRO_TITLE2', 'Plaæanje kreditnom karticom');
define('_PLUG_PAY_PAYPALPRO_DESC2', 'Plati sa Visa, MC, Discover ili Amex kreditnom karticom');

define('_PLUG_PAY_PAYPALPRO_HTML_TITLE', 'Potvrdite vašu uplatu');
define('_PLUG_PAY_PAYPALPRO_HTML_SPTITLE', 'Naslov pretplate/Proizvoda');
define('_PLUG_PAY_PAYPALPRO_HTML_PRICE', 'Cijena');
define('_PLUG_PAY_PAYPALPRO_HTML_SUBTOTAL', 'Ukupno');
define('_PLUG_PAY_PAYPALPRO_HTML_CPDSC', 'Kupon popust');
define('_PLUG_PAY_PAYPALPRO_HTML_TAXAM', 'Iznos poreza');
define('_PLUG_PAY_PAYPALPRO_HTML_TOTAL', 'Sveukupno');
define('_PLUG_PAY_PAYPALPRO_HTML_SBBUT', 'Potvrdi plaæanje ');





define('_PLUG_PAY_FIRSTPAY_TITLE', 'FirstPay.Net');
define('_PLUG_PAY_FIRSTPAY_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_MERCANYW_TITLE', 'MerchantAnyWhere');
define('_PLUG_PAY_MERCANYW_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_SECPAY_TITLE', 'SecPay');
define('_PLUG_PAY_SECPAY_DESC', 'Plaæanje kreditnom karticom');
define('_PLUG_PAY_SECPAY_ERROR', 'Constructor greška: %s');
define('_PLUG_PAY_SECPAY_ERROR2', 'SOAP call fault: ');
define('_PLUG_PAY_SECPAY_ERROR3', 'SOAP greška: %s');





define('_PLUG_PAY_PROTXDIR_TITLE', 'Protx');
define('_PLUG_PAY_PROTXDIR_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_SAFEPAY_TITLE', 'SafePay');
define('_PLUG_PAY_SAFEPAY_DESC', 'Vidi %swww.safepaysolutions.com%s za opis');
define('_PLUG_PAY_SAFEPAY_ERROR', 'Tajna lozinka-fraza greška');
define('_PLUG_PAY_SAFEPAY_ERROR2', 'Iznos greška (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR3', 'Stavka kolièina greška (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR4', 'Transakcija ID greška (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR5', 'Transakcija nije potvrðena, novac nije na vašem SPS raèunu');
define('_PLUG_PAY_SAFEPAY_ERROR6', 'Rezultat kod %s: Plaæanje Greška');





define('_PLUG_PAY_SECUREPAY_TITLE', 'SecurePay');
define('_PLUG_PAY_SECUREPAY_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_GOOGLE_CHECKOUT_TITLE', 'Google Checkout');
define('_PLUG_PAY_GOOGLE_CHECKOUT_DESC', 'Plaæanje kreditnom karticom');





define('_PLUG_PAY_MANUAL_TITLE', 'Ruèno plaæanje');





define('_PLUG_PAY_ALERTPAY_TITLE', 'AlertPay');
define('_PLUG_PAY_ALERTPAY_DESC', 'Plati sa kreditnom karticom');
define('_PLUG_PAY_ALERTPAY_FERROR2', 'Nepoznata jedinica razdoblja u expire_days. Treba biti d|m|w|y');
define('_PLUG_PAY_ALERTPAY_FERROR3', 'Netoèna vrijednost za $s: %s');
define('_PLUG_PAY_ALERTPAY_FERROR4', 'Netoèna vrijednost za %s u proizvodu #');
define('_PLUG_PAY_ALERTPAY_ERROR', 'Netoèan tajni kod');
define('_PLUG_PAY_ALERTPAY_FERROR', 'ALERTPAY GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)%s');
define('_PLUG_PAY_ALERTPAY_ERROR2', 'Transakcija odbijena (%s)');
define('_PLUG_PAY_ALERTPAY_ERROR3', 'Test naèin nije omoguæen');
define('_PLUG_PAY_ALERTPAY_ERROR4', 'Neispravan trgovaèki raèun: to nije naše plaæanje');
define('_PLUG_PAY_ALERTPAY_ERROR5', 'vraæeni iznos je prazan ili = 0');
define('_PLUG_PAY_ALERTPAY_ERROR6', 'Plaæanje je veæ procesirano (alertpay raèun#: %d) u plaæanju #%d');







define('_PLUG_PAY_METACHARGE_TITLE', 'Metacharge');
define('_PLUG_PAY_METACHARGE_DESC', 'Plati sa kreditnom karticom/debitnom karticom - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');

define('_PLUG_PAY_METACHARGE_FERROR', 'METACHARGE GREŠKA: %s (Detalji: PNREF:%s, raèun:%d)%s');

define('_PLUG_PAY_METACHARGE_ERROR2', 'Transakcija odbijena (%s)');
define('_PLUG_PAY_METACHARGE_ERROR3', 'Test naèin nije omoguæen');
define('_PLUG_PAY_METACHARGE_ERROR4', 'Neispravan instalacijski ID: to nije naše plaæanje');
define('_PLUG_PAY_METACHARGE_ERROR5', 'vraæeni iznos je prazan ili = 0');
define('_PLUG_PAY_METACHARGE_ERROR6', 'Plaæanje je veæ procesirano (metacharge raèun#: %d) u plaæanju #%d');

define('_PLUG_PAY_METACHARGE_FERROR2', 'Nepoznata jedinica razdoblja u expire_days. Treba biti d|m|w|y');
define('_PLUG_PAY_METACHARGE_FERROR3', 'Neispravna vrijednost za $s: %s');
define('_PLUG_PAY_METACHARGE_HTML_SUB_BUT', 'Kliknite ovdje ako vas vaš preglednik ne proslijedi automatski');
define('_PLUG_PAY_METACHARGE_HTML_TITLE', 'Metacharge Payment');













//missed rows
define ('_TPL_EMAIL_VER_TITLE_PROFILE', 'Email verification required');
define ('_TPL_EMAIL_VER_TEXT_PROFILE', 'Please check your email - verification email message has been just emailed to you. Once you receive this message, read it and follow instructions in this email to complete your email verification.');
define ('_TPL_MEMBER_MAIN_PAGE', 'Main Page');
define ('_TPL_PROFILE_EMAIL_NOT_VERIFIED', 'Email address is not verified!');
define ('_TPL_PROFILE_EMAIL_RESEND_VERIFICATION_EMAIL', 'Resend verification email');
define ('_TPL_NEWSLETTER_ARCHIVE_DATE', 'Date');
define ('_TPL_NEWSLETTER_ARCHIVE_SUBJECT', 'Subject');
define ('_TPL_NEWSLETTER_ARCHIVE_NO_ARCHIVE', 'You have no archive messages');
define('_TPL_SKYPAY_ADDRESS_TITLE', 'Billing address');
define('_TPL_SKYPAY_ADDRESS_CHOOSE', '*** Please choose ***');
define('_TPL_SKYPAY_ADDRESS_HOLDERNAME', 'Cardholder Name');
define('_TPL_SKYPAY_ADDRESS_ASONCARD', 'cardholder name, exactly as on the card');
define('_TPL_SKYPAY_ADDRESS_FLNAME', 'cardholder first and last name, exactly as%son the card');
define('_TPL_SKYPAY_ADDRESS_ADDRINFO', 'Please specify your billing address details');
define('_TPL_SKYPAY_ADDRESS_STRADDR', 'Address');
define('_TPL_SKYPAY_ADDRESS_STRADDR2', 'Address (2)');
define('_TPL_SKYPAY_ADDRESS_CITY', 'City');
define('_TPL_SKYPAY_ADDRESS_ZIP', 'Postal code / Zip code');
define('_TPL_SKYPAY_ADDRESS_COUNTRY', 'Country');
define('_TPL_SKYPAY_ADDRESS_PHONE', 'Phone');
define('_TPL_SKYPAY_ADDRESS_MUSTMATCH', '(must match your credit card statement delivery address)');
define('_TPL_SKYPAY_ADDRESS_BACK_BUT', 'Back');
define('_TPL_SKYPAY_ADDRESS_SUBMIT_BUT', 'Continue');
define('_TPL_SKYPAY_ADDRESS_SUBMIT_BUT_3', 'Subscribe and Pay');
define('_TPL_SKYPAY_PAY_TITLE', 'Confirm payment details');
define('_TPL_SKYPAY_PAY_SUBMIT', 'Continue to the Skypay Payment page');
define('_TPL_SKYPAY_ADDRESS_BILLING', 'Billing address details:');
define('_TPL_SKYPAY_PRODUCT_BILLING', 'Product details:');
define('_PLUG_PAY_SKYPAY_FERROR1', 'skypay ERROR: %s (Details: txn_id:%d, invoice:%d)%s');
define('_PLUG_PAY_SKYPAY_FERROR2', 'You are not logged in.');
define('_PLUG_PAY_SKYPAY_FERROR3', 'It seems to be not your payment, please go back and try again.');
define('_PLUG_PAY_SKYPAY_TITLE', 'Skypay');
define('_PLUG_PAY_SKYPAY_DESC', 'Pay by credit card/debit card');
define ('_TPL_SKYPAY_CANCEL_TITLE', 'Payment Cancelled');
define ('_TPL_SKYPAY_CANCEL_ERROR', 'Your payment has been cancelled.');
define ('_TPL_SKYPAY_CANCEL_GOTO', 'To see your subscription details please go to %sMembership page%s.');
?>