<?php
/**
 * hu.php
 * Hungarian Language file
 * @author   Alex Scott <alex@cgi-central.net>
 * @translator Robert Zoltan Bakos & Richard Soti <support@ebookpublisher.biz>
 * @package  aMember_Core
 * @version  $Id: hu.php 3017 2009-04-28 10:15:21Z sirius $
 * @license  http://www.amember.com/p/Main/License
 * @copyright Copyright &copy; 2006, Alex Scott
 * DO NOT EDIT THIS FILE FOR CUSTOMIZATION, READ readme.txt for details
 */

defined('INCLUDED_AMEMBER_CONFIG') or die('Közvetlen belépés letiltva');

define ('_TPL_POWEREDBY', 'Powered by %saMember Pro%s membership software');

define('_TPL_INDEX_IF_YOU_ARE_REGISTERED', 'Ha már regisztrált tag vagy, kérlek %sjelentkezz be%s');
define('_TPL_INDEX_IF_YOU_ARE_NOT_REGISTERED', 'Ha még nem regisztráltál, ide kattintva %scsatlakozhatsz%s');
define('_TPL_LOGIN_PLEASE_LOGIN', 'Belépés');
define('_TPL_LOGIN_USERNAME', 'Felhasználónév');
define('_TPL_LOGIN_PASSWORD', 'Jelszó');
define('_TPL_LOGIN_REMEMBER_MY_PASSWORD', 'Emlékezz a jelszavamra');
define('_TPL_LOGIN_NOT_REGISTERED_YET', 'Nem regisztrált?');
define('_TPL_LOGIN_SIGNUP_HERE', 'Regisztrálj!');
define('_TPL_LOGIN_LOST_PASSWORD', 'Elfelejtetted a jelszavadat?');
define('_TPL_LOGIN_ENTER_YOUR_EMAIL_OR_USERNAME', 'Add meg az email címed<br />vagy a felhasználóneved');
define('_TPL_LOGIN_BTN_LOGIN', 'Belépés');
define('_TPL_LOGIN_BTN_BACK', 'Vissza');
define('_TPL_LOGIN_BTN_GET_PASSWORD', 'Jelszó küldése levélben');

define ('_TPL_SIGNUP_MEM_TYPE', 'Válassz tagsági típust');
define ('_TPL_SIGNUP_TITLE', 'Regisztráció');
define ('_TPL_AFF_SIGNUP_TITLE', ' Viszonteladói (affiliate) regisztráció');
define ('_TPL_SIGNUP_MEMB_TYPE', 'Tagság típusa');
define ('_TPL_SIGNUP_FREE', 'ingyenes');
define ('_TPL_SIGNUP_SELECT_PSYS', 'Válassz fizetési módszert');
define ('_TPL_SIGNUP_PAYSYS', 'Fizetési módszer');
define ('_TPL_SIGNUP_NAME', 'Neved');
define ('_TPL_SIGNUP_NAME_1', 'Keresztnév és Vezetéknév');
define ('_TPL_SIGNUP_EMAIL', 'E-Mail Cím');
define ('_TPL_SIGNUP_EMAIL_1', 'Igazoló e-mailt küldünk');
define ('_TPL_SIGNUP_EMAIL_2', 'számodra erre a címre');
define ('_TPL_SIGNUP_LOGIN', 'Válassz felhasználónevet');
define ('_TPL_SIGNUP_LOGIN_1', 'Legalább %d karakter hosszúságunak kell lennie, és ');
define ('_TPL_SIGNUP_LOGIN_2', 'csak kis betûket, számokat, és');
define ('_TPL_SIGNUP_LOGIN_3', 'aláhúzás jelet \'_\' tartalmazhat');
define ('_TPL_SIGNUP_CHECK_UNIQ', 'foglalt ez a felhasználónév?');
define ('_TPL_SIGNUP_PSWD', 'Válassz jelszót');
define ('_TPL_SIGNUP_PSWD_1', 'Minimum %d vagy több karakter');
define ('_TPL_SIGNUP_CAPTCHA', 'Írd be a képen látható biztonsági kódot');
define ('_TPL_SIGNUP_CAPTCHA_1', '(ügyelj a nagybetûkre)');
define ('_TPL_SIGNUP_CONF_PSWD', 'Jelszó mégegyszer');
define ('_TPL_SIGNUP_CONF_PSWD_1', 'Ismételd meg a jelszót');
define ('_TPL_SIGNUP_NEWSLETTERS_SUBSCRIBE', 'Hírlevelekre feliratkozás');
define ('_TPL_SIGNUP_NEWSLETTERS_SUBSCRIBE_1', '');
define ('_TPL_SIGNUP_ADDR', 'Cím');
define ('_TPL_SIGNUP_STREET', 'Utca és házszám');
define ('_TPL_SIGNUP_CITY', 'Település');
define ('_TPL_SIGNUP_STATE', 'Állam / Megye');
define ('_TPL_SIGNUP_ZIP', 'Irányítószám');
define ('_TPL_SIGNUP_COUNTRY', 'Ország');
define ('_TPL_SIGNUP_COUPONS', 'KUPONOK');
define ('_TPL_SIGNUP_COUPON_CODE', 'Add meg a kuponod kódját');
define ('_TPL_SIGNUP_COUPON_1', 'Ha van kuponkódod, itt add meg.');
define ('_TPL_SIGNUP_COUPON_2', '');
define ('_TPL_SIGNUP_SUBMIT_CONTINUE', 'Regisztráció folytatása');

define ('_TPL_AFFILIATE_TITLE', 'Viszonteladói (affiliate) információ');
define ('_TPL_AFFILIATE_TXT_LINKS', 'A következõ szövegeket használhatod linkként oldalaink hirdetésére:');
define ('_TPL_AFFILIATE_HTML_CODE', 'HTML kód:');
define ('_TPL_AFFILIATE_BANNERS', 'A következõ bannereket használhatod oldalaink hirdetésére:');
define ('_TPL_AFFILIATE_BACK2_INFO', 'Vissza az affiliate információ oldalra');

define ('_TPL_AFF_PAYOUT_TITLE', 'Viszonteladó kifizetésének módosítása');
define ('_TPL_AFF_PAYOUT_METHOD', 'KIFIZETÉS MÓDJA');
define ('_TPL_AFF_PAYOUT_NOT_SELECTED', 'Nincs bejelölve');
define ('_TPL_AFF_PAYOUT_PP_EMAIL', 'PayPal email címed');
define ('_TPL_AFF_PAYOUT_STORM_EMAIL', 'StormPay email címed');
define ('_TPL_AFF_PAYOUT_IKOBO_EMAIL', 'iKobo email címed');
define ('_TPL_AFF_PAYOUT_MBKRS_ID', 'MoneyBookers számla azonosító');
define ('_TPL_AFF_PAYOUT_EGOLD_ACC', 'E-Gold számla szám');
define ('_TPL_AFF_PAYOUT_CHECK_PTO', 'Csekk kiállítandó:');
define ('_TPL_AFF_PAYOUT_SAFEPAY_EMAIL', 'SafePaySolutions email címed');

define ('_TPL_AFF_PAYOUT_STREET', 'Utca, házszám');
define ('_TPL_AFF_PAYOUT_CITY', 'Település');
define ('_TPL_AFF_PAYOUT_STATE', 'Állam / Megye');
define ('_TPL_AFF_PAYOUT_ZIP', 'Irányítószám');
define ('_TPL_AFF_PAYOUT_COUNTRY', 'Ország');
define ('_TPL_AFF_PAYOUT_SAVE_BUT', 'Mentés');
define ('_TPL_AFF_PAYOUT_BACK_BUT', 'Vissza');

define ('_TPL_AFF_STATS_TITLE', 'Viszonteladói statisztika');
define ('_TPL_AFF_STATS_DISPLAY_BUT', 'Megjelenít');
define ('_TPL_AFF_STATS_PERIOD', 'Statisztika periodusra');
define ('_TPL_AFF_STATS_CLICKS', 'KLIKKEK');
define ('_TPL_AFF_STATS_COMMISS', 'KIFIZETÉSEK');
define ('_TPL_AFF_STATS_DATE', 'Dátum');
define ('_TPL_AFF_STATS_RAW', 'Gyors');
define ('_TPL_AFF_STATS_UNIQUE', 'Egyedi');
define ('_TPL_AFF_STATS_TRANS', 'Tranzakciók');
define ('_TPL_AFF_STATS_CREDIT', 'Jóváírás');
define ('_TPL_AFF_STATS_DEBIT', 'Terhelés');
define ('_TPL_AFF_STATS_TOTAL', 'Totál');
define ('_TPL_AFF_STATS_TOTAL_H', 'TOTÁL');
define ('_TPL_AFF_STATS_TOP20', 'Top 20 referáló');
define ('_TPL_AFF_STATS_REFERRER', 'REFERÁLÓ');
define ('_TPL_AFF_STATS_BACK', 'Vissza a viszonteladói információkhoz');

define ('_TPL_AGREEMENT_TITLE', 'Felhasználási Feltételek');
define ('_TPL_AGREEMENT_REED_AGREE', 'Olvasd végig és fogadd el a következõ felhasználási feltételeket:');
define ('_TPL_AGREEMENT_AGREE', 'Egyetértek');
define ('_TPL_AGREEMENT_CONTINUE_BUT', 'Tovább');

define ('_TPL_CANCEL_TITLE', 'Fizetési muvelet sikertelen');
define ('_TPL_CANCEL_ERROR', 'Fizetési muvelet kezelése közben hiba történt.');
define ('_TPL_CANCEL_GOTO', 'Kérlek, lépj vissza a %sregisztrációs oldalra%s és próbálkozz újra!');

define ('_TPL_EMAIL_VER_TITLE', 'Regisztráció - email ellenõrzés');
define ('_TPL_EMAIL_VER_TEXT', 'A megerõsítõ email kiküldésre került. Kérlek, ellenõrizd le az email fiókodat. A regisztráció véglegesítéséhez kövesd az email utasításait. Köszönöm!');
define ('_TPL_EMAIL_VER_POWEREDBY', 'Powered by %saMember Pro%s membership software');

define ('_TPL_FATAL_ERROR_TITLE', 'Hiba történt');
define ('_TPL_FATAL_ERROR_CONTACT', 'Lépj kapcsolatba a honlap adminisztrátorával: ');

define ('_TPL_MEMBER_TITLE', 'Tagsági információk');
define ('_TPL_MEMBER_SUBSCR', 'Aktív tagságaid:');
define ('_TPL_MEMBER_NO_SUBSCR', 'Nincs érvényben lévõ tagságod!');
define ('_TPL_MEMBER_ADD_RENEW', 'Tagság hozzáadása / megújítása');
define ('_TPL_MEMBER_USE', 'Használd a tagság megújítása menüpontot');
define ('_TPL_MEMBER_ORDER_SUBSCR', 'A tagsági elõfizetés megrendelésére vagy megújítására.');
define ('_TPL_MEMBER_USEFUL_LINKS', 'Hasznos linkek');
define ('_TPL_MEMBER_LOGOUT', 'Kilép');
define ('_TPL_MEMBER_CH_PSWD', 'Jelszavad vagy adataid módosítása');
define ('_TPL_MEMBER_SELECT', '** Válassz terméket **');
define ('_TPL_MEMBER_SELECT2', '** Válassz fiztési módot **');
define ('_TPL_MEMBER_ORDER_BUT', 'Megrendel');
define ('_TPL_MEMBER_PYMNT_HIST', 'Legutóbbi rendelések:');
define ('_TPL_MEMBER_PRODUCT', 'Termék');
define ('_TPL_MEMBER_PERIOD', 'Idõtartam');
define ('_TPL_MEMBER_PAYSYS', 'Fizetési rendszer');
define ('_TPL_MEMBER_AMOUNT', 'Összeg');
define ('_TPL_MEMBER_CANCEL_SUBSCR', 'Biztos, hogy törölni akarod az elõfiztést?');
define ('_TPL_MEMBER_CANCEL', 'Mégse');
define ('_TPL_MEMBER_CANCELLED', 'ÉRVÉNYTELENÍTVE');
define ('_TPL_MEMBER_PDF_INVOICE', 'PDF Számla');
define ('_TPL_MEMBER_INVOICE', 'Számla');

define ('_TPL_MULT_MEMBER_TITLE', 'Tagsági információk');
define ('_TPL_MULT_MEMBER_SUBSCR', 'Aktív tagságaid:');
define ('_TPL_MULT_MEMBER_NOACTSUB', 'Nincs érvényben lévõ elõfizetésed');
define ('_TPL_MULT_MEMBER_ADDREN', 'Használd a %sTagsági elõfizetés hozzáadása / megújítása%s ûrlapot%s elõfizetés megrendelésére vagy megújítására.');
define ('_TPL_MULT_MEMBER_LOGOUT', 'Kilép');
define ('_TPL_MULT_MEMBER_CHPWD', 'Jelszavad vagy adataid módosítása');
define ('_TPL_MULT_MEMBER_ADDRSUBSCR', 'Tagsági elõfizetés hozzáadása / megújítása');
define ('_TPL_MULT_MEMBER_SELECTPM', '** Válassz fiztési módot **');
define ('_TPL_MULT_MEMBER_PHIST', 'Legutóbbi rendelések:');
define ('_TPL_MULT_MEMBER_PRODUCT', 'Termék');
define ('_TPL_MULT_MEMBER_PERIOD', 'Idõtartam');
define ('_TPL_MULT_MEMBER_PSYS', 'Fizetési rendszer');
define ('_TPL_MULT_MEMBER_AMOUNT', 'Összeg');
define ('_TPL_MULT_MEMBER_CANCEL', 'Mégse');
define ('_TPL_MULT_MEMBER_CANCELLED', 'ÉRVÉNYTELENÍTVE');
define ('_TPL_MULT_MEMBER_ORDERBUT', 'Megrendel');

define ('_TPL_MSGCLOSE_CLOSE', 'Ablakot bezár');

define ('_TPL_PROFILE_TITLE', 'Adatmódosítás');
define ('_TPL_PROFILE_USERNAME', 'Felhasználónév');
define ('_TPL_PROFILE_ANOTHERUSRNM', 'itt új fehasználónevet választhatsz');
define ('_TPL_PROFILE_FLNAME', 'Keresztnév és vezetéknév');
define ('_TPL_PROFILE_EMAIL', 'Email cím');
define ('_TPL_PROFILE_CHPWD', 'Jelszó megváltoztatása');
define ('_TPL_PROFILE_BLANK', 'Hagyd üresen, ha nem akarod megváltoztatni');
define ('_TPL_PROFILE_CONFPWD', 'Jelszó mégegyszer');
define ('_TPL_PROFILE_STREET', 'Utca, házszám');
define ('_TPL_PROFILE_CITY', 'Település');
define ('_TPL_PROFILE_STATE', 'Állam / Megye');
define ('_TPL_PROFILE_ZIP', 'Irányítószám');
define ('_TPL_PROFILE_COUNTRY', 'Ország');
define ('_TPL_PROFILE_UNSUBSCR', 'Leiratkozás');
define ('_TPL_PROFILE_NOEMAIL', 'ne küldj ismétlõdõ email üzeneteket');
define ('_TPL_PROFILE_CHECKBOX', 'Jelöld be, ha le akarsz iratkozni');
define ('_TPL_PROFILE_SAVEBUT', 'Adatok mentése');
define ('_TPL_PROFILE_BACKBUT', 'Vissza');

define ('_TPL_PROFILE_SAVED_TITLE', 'Adatmódosítás');
define ('_TPL_PROFILE_SAVED_SUCCESS', 'Adataidat sikeresen módosítottad.');
define ('_TPL_PROFILE_SAVED_GOBACK', 'Lépj vissza a %sTagsági Információ oldalra%s.');

define ('_TPL_CHANGEPASSWORD_TITLE', 'Jelszó módosítása');
define ('_TPL_CHANGEPASSWORD_USERNAME', 'Felhasználónév');
define ('_TPL_CHANGEPASSWORD_SAVEBUT', 'Módosít');
define ('_TPL_CHANGEPASSWORD_BACKBUT', 'Belépési oldal');
define ('_TPL_CHANGEPASSWORD_CHPWD', 'Új jelszó');
define ('_TPL_CHANGEPASSWORD_CONFPWD', 'Jelszó mégegyszer');

define ('_TPL_CHANGEPASSWORD_FAILED_TITLE', 'Jelszó módosítási hiba');
define ('_TPL_CHANGEPASSWORD_FAILED_INCINFO', 'A beírt információ helytelen');
define ('_TPL_CHANGEPASSWORD_FAILED_USRNOTFOUND', 'A felhasználó nem szerepel az adatbázisunkban.');
define ('_TPL_CHANGEPASSWORD_FAILED_EXPIRED', 'Biztonsági kód lejárt.');
define ('_TPL_CHANGEPASSWORD_FAILED_WRONGPASS', 'Jelszó nem egyezik vagy túl rövid.');
define ('_TPL_CHANGEPASSWORD_FAILED_RETURN', 'Lépj vissza, próbálkozz újra');

define ('_TPL_REDIRECT_CLICKHERE', 'Kattints ide, ha nem akarsz tovább várakozni, vagy ha a böngészõd nem irányít át automatikusan.');

define ('_SENDPWD_OK_TITLE', 'Elvesztett jelszó elküldve');
define ('_SENDPWD_OK_TEXT', 'Jelszavadat emailben elküldtük');
define ('_SENDPWD_OK_TEXT_1', 'Ellenõrizd az email fiókodat');

define ('_SENDPWD_FAILED_TITLE', 'A jelszót elküldése sikertelen!');
define ('_SENDPWD_FAILED_TEXT', 'Hibás információkat adtál meg');
define ('_SENDPWD_FAILED_TEXT_1', 'Felhasználónév [%s] nem szerepel az adatbázisban!');
define ('_TPL_SENDPWD_RETURN', 'Vissza a bejelentkezési oldalra');

define ('_TPL_NEWGUEST_FAILED_TITLE', 'Hiba a megerõsítésben');
define ('_TPL_NEWGUEST_FAILED_INCINFO', 'Hibás információkat adtál meg');
define ('_TPL_NEWGUEST_FAILED_RETURN', 'Lépj vissza, próbálkozz újra');


define ('_TPL_NEWGUEST_FAILED_EMAIL_TITLE', 'Hiba a megerõsítésben');
define ('_TPL_NEWGUEST_FAILED_EMAIL_INFO', 'Az email cím amit megadtál, már egy másik felhasználó által használt.');
define ('_TPL_NEWGUEST_FAILED_EMAIL_LINK', 'Kattints erre a linkre a belépéshez és elõfizetéshez');


define ('_TPL_NEWGUEST_OK_TITLE', 'Megerõsítés elküldve');
define ('_TPL_NEWGUEST_OK_PWDOK', 'Új vendég elõfizetésének visszaigazolását emailben elküdtük');
define ('_TPL_NEWGUEST_OK_CHECKEM', 'Ellenõrizd az email fiókodat');
define ('_TPL_NEWGUEST_OK_RETURN', 'Vissza');

define ('_TPL_NEWGUEST_COMPLETE_TITLE', 'Elõfizetés hozzáadva');
define ('_TPL_NEWGUEST_COMPLETE', 'Sikeresen feliratkoztál a hírlevélre');


define ('_TPL_NEWSLETTER_SUBSCRIPTIONS', 'Hírlevél Elõfizetés');
define ('_TPL_NEWSLETTER_ARCHIVE', 'Hírlevel Archívum');
define ('_TPL_NEWSLETTER_SUBSCRIBE', 'Hírlevél Feliratkozás');
define ('_TPL_NEWSLETTER_MEMBER_AREA', 'Tagság oldalai');
define ('_TPL_NEWSLETTER_SUBSCRIBE_TO_NEWSLETTERS', 'Válassz Hírlevelet');
define ('_TPL_NEWSLETTER_NAME', 'Név');
define ('_TPL_NEWSLETTER_EMAIL', 'Email');
define ('_TPL_NEWSLETTER_DO_SUBSCRIBE', 'Feliratkozom');
define ('_TPL_NEWSLETTER_BACK', 'Vissza');

define ('_TPL_NEWSLETTER_UPDATE_SUBSCRIPTIONS', 'Regisztrálás felújítása');
define ('_TPL_NEWSLETTER_INFO_SAVED', 'Információ elmentve');
define ('_TPL_NEWSLETTER_INFO_UPDATED', 'Hírlevél feliratkozási adatok frissítve');

define ('_TPL_NEWSLETTER_REQUIRED_NAME', 'Név ûrlapmezõ kitöltendõ');
define ('_TPL_NEWSLETTER_REQUIRED_EMAIL', 'Email ûrlapmezõ kitöltendõ');
define ('_TPL_NEWSLETTER_REQUIRED_THREAD', 'Hirlevél csoport kiválasztandó');

define ('_TPL_NEWSLETTER_UNSUBSCRIBE', 'Leiratkozom a hírlevélrol, és nem kívánok több email üzenetet kapni');

define ('_TPL_NEWSLETTER_DATE', 'Dátum');
define ('_TPL_NEWSLETTER_SUBJECT', 'Tárgy');
define ('_TPL_NEWSLETTER_MESSAGE', 'Üzenet');
define ('_TPL_NEWSLETTER_THREADS', 'Csoport(ok)');

define ('_TPL_SIGNUP_MULT_TITLE', 'Regisztráció');
define ('_TPL_SIGNUP_MULT_SELECTTYPE', 'Válassz tagsági típust');
define ('_TPL_SIGNUP_MULT_MEMTYPE', 'Tagság típus');
define ('_TPL_SIGNUP_MULT_SELPAYSYS', 'Válassz fizetési módszert');
define ('_TPL_SIGNUP_MULT_PAYSYS', 'Fizetési módszer');
define ('_TPL_SIGNUP_MULT_NAME', 'Neved');
define ('_TPL_SIGNUP_MULT_FLNAME', 'Keresztnév és Vezetéknév');
define ('_TPL_SIGNUP_MULT_EMAIL', 'Email cím');
define ('_TPL_SIGNUP_MULT_CONFIRM', 'visszaigazolás céljára fogjuk használni');
define ('_TPL_SIGNUP_MULT_LOGIN', 'Válassz felhasználónevet');
define ('_TPL_SIGNUP_MULT_ENTER', 'Írd be a kívánt felhasznalónevet, hogy a%s sikeres fizetést követõen%s be tudj lépni. %s Legalább %d karakter hosszúságunak kell lennie, csak kis betûket, számokat, és aláhúzás jelet \'_\' tartalmazhat!');
define ('_TPL_SIGNUP_MULT_CHECK', 'ellenõrizd nem foglalt-e');
define ('_TPL_SIGNUP_MULT_CHPWD', 'Válassz jelszót');
define ('_TPL_SIGNUP_MULT_MUSTBE', 'Minimum %d vagy több karakter');
define ('_TPL_SIGNUP_MULT_CONFPWD', 'Ismételd meg a jelszót');
define ('_TPL_SIGNUP_MULT_PWDAGAIN', 'Jelszó mégegyszer');
define ('_TPL_SIGNUP_MULT_ADDRESS', 'Cím');
define ('_TPL_SIGNUP_MULT_STREET', 'Utca, házszám');
define ('_TPL_SIGNUP_MULT_CITY', 'Település');
define ('_TPL_SIGNUP_MULT_STATE', 'Állam vagy megye');
define ('_TPL_SIGNUP_MULT_ZIP', 'Irányítószám');
define ('_TPL_SIGNUP_MULT_COUNTRY', 'Ország');
define ('_TPL_SIGNUP_MULT_COUPONS', 'KUPONOK');
define ('_TPL_SIGNUP_MULT_CCODE', 'Add meg a kuponod kódját');
define ('_TPL_SIGNUP_MULT_GETCOUP', 'Ha van kuponkódod, itt add meg.');
define ('_TPL_SIGNUP_MULT_CONT', 'Regisztráció folytatása');

define ('_TPL_THX_TITLE', 'Köszönjük a regisztrációt!');
define ('_TPL_THX_ENJOY', 'Élvezd a tagság elõnyeit, belépéshez kattints ide: %sBelépés%s');
define ('_TPL_THX_PAYPROC', 'A befizetés mûvelete sikeresen végrehajtva.');
define ('_TPL_THX_ORDERREF', 'Megrendelés referencia száma: %d / %s');
define ('_TPL_THX_DATETIME', 'Fizetés dátuma, ideje: %s');
define ('_TPL_THX_PRDTITLE', 'Elõfizetés/Termék Megnevezés');
define ('_TPL_THX_PRICE', 'Ár');
define ('_TPL_THX_SUBTOTAL', 'Alap összeg');
define ('_TPL_THX_DISCOUNT', 'Kupon kedvezmény');
define ('_TPL_THX_TAX', 'Adó');
define ('_TPL_THX_TOTAL', 'Totál');
define ('_TPL_THX_YOUR_INVOICE', 'Számla száma');
define ('_TPL_THX_FROM', 'tól');

define ('_TPL_THX_ERROR_TITLE', 'Regisztrációs hiba');
define ('_TPL_THX_ERROR_ERROR', 'Hiba történt a regisztrálás alatt');
define ('_TPL_THX_ERROR_CONTACT', 'Kérjuk, lépj kapcsolatba a honlap adminisztrátorával');

define ('_TPL_UNSUBSCRIBE_TITLE', 'Leiratkozás megerõsítése');
define ('_TPL_UNSUBSCRIBE_CONFIRM', 'Biztos, hogy törölni akarod az email címet: %s%s%s a %s körlevelek listájáról?');
define ('_TPL_UNSUBSCRIBE_UNSUB_BUT', 'Igen, kérném törölni');
define ('_TPL_UNSUBSCRIBE_NO_UNSUB_BUT', 'Nem, kérném a listán tartani');

define ('_TPL_UNSUBSCRIBED_TITLE', 'Email leiratkozva');
define ('_TPL_UNSUBSCRIBED_SUCCESS1', 'Email címed: %s sikeresen törölve a listáról');
define ('_TPL_UNSUBSCRIBED_SUCCESS2', 'Nem fogsz több hírlevelet kapni a honlapunkról.');
define ('_TPL_UNSUBSCRIBED_SUCCESS3', 'Új befizetések, vagy elfelejtett jelszó esetén továbbra is küldünk email értesítõt.');

define ('_UNIQ_LOGIN_EMPTY_TITLE', 'Nincs felhasználónév');
define ('_UNIQ_LOGIN_EMPTY_TEXT', 'Elõször a felhasználónevedet írd be.');
define ('_UNIQ_LOGIN_EXSTS_TITLE', 'A felhasználónév már foglalt.');
define ('_UNIQ_LOGIN_EXSTS_TEXT', 'Felhasználónév %s foglalt valaki más által');
define ('_UNIQ_LOGIN_EXSTS_TEXT_1', 'Kérlek válasz másik felhasználónévet.');
define ('_UNIQ_LOGIN_EXSTS_TEXT_2', 'Ha ez a te fiókod, kérlek %s a belépõ odalon %s jelentkezz be');
define ('_UNIQ_LOGIN_FREE_TITLE', 'A felhasználónév szabad');
define ('_UNIQ_LOGIN_FREE_TEXT', 'A %s felhasználónév még nincs regisztrálva.');
define ('_UNIQ_LOGIN_FREE_TEXT_1', 'Gratulálunk, még nem foglalt!');
define ('_TPL_UNIQ_LOGIN_CLOSE', 'Bezárás');

define('_LOGIN_WAIT_BEFORE_NEXT_ATTEMPT', 'Kérlek, várj %d percet a következõ bejelentkezés elõtt!');
define('_LOGIN_SESSION_EXPIRED', 'A munkamenet lejárt! Kérlek, írd be újra a felhasználó neved és a jelszót');
define('_LOGIN_ACCESS_NOT_ALLOWED', 'Nincs érvényes tagságot. Kérlek, a "%sTagsági információ oldalon%s" újítsd meg vagy válasz új tagságot.');
define('_LOGIN_INCORRECT', "Hibás felhasználónév vagy jelszó");
define('_LOGIN_ACCOUNT_DISABLED', 'Tagságod ideiglenesen felfüggesztve! Részletes információkért lépj kapcsolatba a honlap adminisztrátorával.');
define('_LOGIN_MANUAL_VERIFICATION_PENDING', 'Tagságod még nincs érvényesítve. Az ellenõrzõ folyamat befejeztérõl emailben értesítünk. Köszönjük a türelmet.');
define('_LOGIN_USERNAME_WRONG_CASE', 'Kis és nagy betûk különböznek. "%s" helyett, kérlek inkább ezt "%s" írd');
define('_LOGIN_PLEASE_LOGIN', 'Kérlek, jelentkezz be');

define('_SIGNUP_PLEASE_SELECT_MEMT', 'Válassz tagsági típust');
define('_SIGNUP_PLEASE_SELECT_PAYSYS', 'Válassz fizetési módszert');
define('_SIGNUP_PLEASE_ENTER_FNAME', 'Írd be a keresztneved');
define('_SIGNUP_PLEASE_ENTER_LNAME', 'Írd be a vezetékneved');
define('_SIGNUP_INVALID_USERNAME', 'A felhasználónév nem engedélyezett karaktereket tartalmaz - használj csak számokat, betüket és üres helyet');
define('_SIGNUP_INVALID_USERNAME_W_SPACES', 'A felhasználónév nem engedélyezett karaktereket tartalmaz - használj csak számokat és betüket');
define('_SIGNUP_INVALID_USERNAME_2', 'Érvényes felhasználónevet kell választanod. Legalább %d karaktert kell tartalmaznia');
define('_SIGNUP_INVALID_USERNAME_3', 'A %s felhasználónév már foglalt, kérlek, válassz másikat!');
define('_SIGNUP_PLEASE_ENTER_EMAIL', 'Írj be az érvényes email címed');
define('_SIGNUP_INVALID_EMAIL_1', 'Ezzel az email címmel már feliratkozott valaki.');
define('_SIGNUP_INVALID_EMAIL_2', 'Kérlek, %slépj be%s a jelenlegi tagsági oldaladra.%s Ha függõben lévõ befizetéssel rendelkezel, a belépést követõen tudod rendezni.');
define('_SIGNUP_PLEASE_ENTER_PSWD', 'Írd be jelszavad');
define('_SIGNUP_INVALID_PASS_1', 'Jelszóban legalabb %d betûnek vagy számnak kell lennie');
define('_SIGNUP_INVALID_PASS_2', 'Jelszó és megerõsítõ jelszó nem egyezik. Írd be mindkét helyre mégegyszer');
define('_SIGNUP_SCRIPT_ERROR', 'Program konfigurációs hiba - Legalább egy terméket (tagsági típust) hozzá kell adnod a vezérlõpultban');
define('_SIGNUP_PAYMENT_NOT_FOUND', 'Fizetési mûvelet nem található');
define('_SIGNUP_PAYMENT_COMPLETED', 'Sikeres fizetési mûvelet! Kérlek, lépj be ');
define('_SIGNUP_PAYMENT_COMPLETED_1', 'itt');
define('_SIGNUP_INCORRECT_LINK', 'Hibás link – javasolt az emailbõl átmásolni a szintaxis hibák kizárása érdekében');
define('_SIGNUP_USER_AGREEMENT', 'A továbblépeshez el kell fogadnod a felhasználói feltételeket');
define('_SIGNUP_INCORRECT_PRODID', 'Hibás termékazonosító a regisztrációhoz');
define('_SIGNUP_LOGIN_EXISTS', 'Felhasználónév már foglalt. belsõ hiba');
define('_SIGNUP_ENTER_STREET', 'Írd be az utcát és házszámot');
define('_SIGNUP_ENTER_CITY', 'Írd be a települést');
define('_SIGNUP_ENTER_STATE', 'Írd be az államot vagy megyét');
define('_SIGNUP_ENTER_ZIP', 'Írd be a irányítószámot');
define('_SIGNUP_ENTER_COUNTRY', 'Írd be az országot');
define('_SIGNUP_CAPTCHA_ERROR', 'A biztonsági szám a képrõl helytelen. Kérlek, írd be újra pontosan');

define('_AFF_MEMBER_TITLE', 'Tágsági információ');
define('_AFF_INTERNAL_ERROR', 'Belsõ hiba - member_id üresen hagyva');
define('_AFF_ERROR_1', 'Írd be az email címet a kifizetéshez');
define('_AFF_ERROR_2', 'Írd be a nevet, aki számára csekk kiállítandó');
define('_AFF_ERROR_3', 'Írd be a StormPay emailt');
define('_AFF_ERROR_4', 'Írd be az iKobo emailt');
define('_AFF_ERROR_5', 'Írd be a MoneyBookers számlaazonosítót');
define('_AFF_ERROR_6', 'Írd be az E-Gold számla számot');
define('_AFF_ERROR_7', 'Ismeretlen fizetési mód');
define('_AFF_ERROR_8', 'Ismeretlen mûvelet: %s');
define('_AFF_ERROR_9', 'Írd be az email címet a kifizetéshez');
define('_AFF_AFFILIATES', 'Viszonteladói tagok');
define('_AFF_PROGR_CONF', 'Viszonteladói konfiguráció');
define('_AFF_PAYOUT_MTHDS', 'Elfogadott kifizetési módok');
define('_AFF_MTHD4_PAYOUT', 'viszonteladói tag választhat a kifizetési módok között.');
define('_AFF_NOTHING_SELECTED', 'Javasolt a kifizetési mód megadása, mert alapértelmezett fizetési mód nem adott');
define('_AFF_REPORT', 'Kifizetések listája.');
define('_AFF_CONFIG_F1_1', 'Viszonteladói részesedés elsõ kifizetés');
define('_AFF_CONFIG_F1_2', 'Viszonteladói részesedés elsõ kifizetése, pl.: 1.5 vagy 2.5%');
define('_AFF_CONFIG_F2_1', 'Viszonteladói részesedéseket kovetõ kifizetések');
define('_AFF_CONFIG_F2_2', 'Viszonteladói részesedéseket kovetõ kifizetések, pl.: 1.5 vagy 2.5%');
define('_AFF_CONFIG_F3_1', 'Viszonteladói sütik (cookie) "örökös tartamra"');
define('_AFF_CONFIG_F3_2', 'Mennyi ideig (napokban) tároljuk a cookie-kat a referálóról?');
define('_AFF_CONFIG_F3_3', 'Tehát, ha a kliens késõbb visszatér a honlapra, a kifizetés');
define('_AFF_CONFIG_F3_4', 'a referáló viszonteladónak lesz elküldve.');
define('_AFF_CONFIG_F4_1', 'Csak az elsõ kifizetést küldd');
define('_AFF_CONFIG_F4_2', 'viszonteladó csak az elsõ vásárlásért kap részesedést.');
define('_AFF_CONFIG_F4_3', 'Ismétlõdõ fizetések esetén is csak az elsõ után jár részesedés');
define('_AFF_CONFIG_F4_4', 'kifizetés.');
define('_AFF_CONFIG_F5_1', 'Ingyenes regisztrációk esetén nem jár részesedés');
define('_AFF_CONFIG_F5_2', 'részesedés nem kerül elszámolásra a viszonteladó számára');
define('_AFF_CONFIG_F5_3', 'ha a kliens ingyenes tagságra regisztrált. Természetesen ez csak a ');
define('_AFF_CONFIG_F5_4', '\'fix\' viszonteladói részesedéseket érinti.');
define('_AFF_ARRAY_1ELEM', 'Ingyenes regisztrációkra is adj részesedést');
define('_AFF_ARRAY_2ELEM', 'Ingyenes regisztrációk esetén ne adj részesedést');
define('_AFF_CONFIG_F6_1', 'Viszonteladói regisztráció típusa');
define('_AFF_CONFIG_F6_2', 'viszonteladó csak az elsõ vásárlásért kap részesedést.');
define('_AFF_CONFIG_F6_3', 'Ismétlõdõ fizetések esetén csak a legelsõ részesedés');
define('_AFF_CONFIG_F6_4', 'lesz kalkulálva.');
define('_AFF_ARRAY_2_ELEM_1', 'Alapértelmezett - kliensnek egy linkre kell kattintania, ha viszonteladói taggá szeretne válni');
define('_AFF_ARRAY_2_ELEM_2', 'Minden kliens automatikusan viszonteladói taggá is válik');
define('_AFF_ARRAY_2_ELEM_3', 'Csak az adminisztrátor jelölhet ki valakit viszonteladói taggá');
define('_AFF_CONFIG_F7_1', 'Részesedés kifizetésekrõl küldj emailt az adminisztrátornak');
define('_AFF_CONFIG_F7_2', 'új részesedés teljesítése esetén');
define('_AFF_CONFIG_F7_3', 'küldj egy emailt az adminisztrátornak');
define('_AFF_CONFIG_F8_1', 'Küldj emailt a részesedésrõl a viszonteladói tagnak');
define('_AFF_CONFIG_F8_2', 'új részesedés teljesítése esetén');
define('_AFF_CONFIG_F8_3', 'küldj neki errõl értesítést');
define('_AFF_ADVERTISE_SITE', 'Hirdesd a honlapunkat ismerõseid körében, és keress ezzel pénzt');
define('_AFF_MEMBER_AREA', 'Viszonteladói felület');
define('_AFF_GET_BANS_LINKS', 'Gyûjts össze a viszonteladói bannereket és linkeket');
define('_AFF_REVIEW_STAT', 'Nézd át viszonteladói statisztikádat');
define('_AFF_UPDATE_PAYOUT', 'Frissítsd a részesedés kifizetésének adatait');
define('_AFF_MEMBER_F1_1', 'Paypal cím a viszonteladói részesedésekhez');
define('_AFF_MEMBER_F2_1', 'StormPay cím a viszonteladói részesedésekhez');
define('_AFF_MEMBER_F3_1', 'iKobo cím a viszonteladói részesedésekhez');
define('_AFF_MEMBER_F4_1', 'MoneyBookers azonosító a viszonteladói részesedésekhez');
define('_AFF_MEMBER_F5_1', 'E-Gold számlaszám a viszonteladói részesedésekhez');
define('_AFF_MEMBER_F6_1', 'Csekk a következõ névre kiállítandó');
define('_AFF_MEMBER_F7_1', 'SafePaySolutions cím a viszonteladói részesedésekhez');
define('_AFF_MEMBER_THANK_YOU', 'Köszönjük a regisztrációt!');
define('_AFF_MEMBER_REDIRECTING', 'Átirányítunk a viszonteladói adatok oldalra');
define('_AFF_DISABLED_MESSAGE', 'Viszonteladói program nincs élesítve. aMember CP -> Setup oldalon engedélyezheted');

define('_AFF_PAYOUT_TYPE', 'Viszonteladó kifizetésének típusa');
define('_AFF_SIGNUP_PLEASE_PAYOUT_TYPE', 'Kérlek, válassz kifizetési típust');

define('_MEMBER_VF_INTEGER', 'Egész számot írj be az [%s] ûrlapmezõbe');
define('_MEMBER_VF_NUMERIC', 'Számot írj be [%s] az ûrlapmezõbe');
define('_MEMBER_VF_REQUIRE', 'Ne hadd üresen az [%s] ûrlapmezõt');
define('_MEMBER_VF_EMAIL', 'Érvényes email címet adj meg az [%s] ûrlapmezõbe');

define('_MEMBER_ERROR_1', 'Email címed nincs megerõsítve, ezért belépésed egyelõre nem%sengedélyezett. Ellenõrizd email fiókod, és a visszaigazoló üzenetben, %kattints a linkre, a megerõsítéshez. Ha nem kaptad meg az emailt, kérlek %skattints %serre a linkre%s és újra küldjük.');
define('_MEMBER_REDIRECTING', 'Átirányítunk a viszonteladói információ oldalra');
define('_MEMBER_ONLY4_PAID', 'Ez a termék kizárólag kifizetés után hozzáférhetõ elõfizetõinknek');
define('_MEMBER_ONLY4_NEW', 'Ez a termék kizárólag új elõfizetõk számára hozzáférhetõ');
define('_MEMBER_NOT4_ORDER', 'Ez a termék jelenleg nem megrendelhetõ');
define('_MEMBER_SELECT_PRODUCT', 'Válassz egy terméket (elõfizetési típust) felújításra');
define('_MEMBER_SELECT_PAYMENT', 'Válassz fizetési módot');
define('_MEMBER_ID_NOT_MATCH', 'member_id nem egyezik a kifizetésnél');
define('_MEMBER_SUBSCR_CANCELLED', 'Elõfizetés törölve');
define('_MEMBER_RSUB_CANCELLED', 'Ismétlõdõ elõfizetések törölve.');
define('_MEMBER_MAIL_ADMIN', 'Ismétlõdõ elõfizetések törölve: Felhasználónév: %s Fizetmény szám: %d');
define('_MEMBER_MAIL_THEME', '*** Elõfizetés törölve');
define('_MEMBER_ERROR', 'El kell fogadnod a felhasználási feltételeket a folytatáshoz');

define('_MEMBER_PROFILE_CORRECTLOG', 'A felhasználónévnek legalább %d karakter hosszúságunak kell lennie, csak kis betûket, számokat, és aláhúzás jelet \'_\' tartalmazhat');
define('_MEMBER_PROFILE_NAMEEXISTS', 'Felhasználónév %s foglalt. Válassz másikat.');
define('_MEMBER_PROFILE_ERROR1', 'Írj be érvényes felhasználónevet: %s');
define('_MEMBER_PROFILE_ERROR2', 'Írj be érvényes email címet');
define('_MEMBER_PROFILE_ERROR3', 'Ez az email cím már foglalt');
define('_MEMBER_PROFILE_ERROR4', 'Írd be a keresztneved');
define('_MEMBER_PROFILE_ERROR5', 'Írd be a vezetékneved');
define('_MEMBER_PROFILE_ERROR6', 'A jelszó minimum %d karakter kell, hogy legyen');
define('_MEMBER_PROFILE_ERROR7', 'A jelszó maximum %d karakter kell, hogy legyen');
define('_MEMBER_PROFILE_ERROR8', 'A jelszó és megerõsítõ jelszó nem egyezik. Kérlek, ismételd meg');
define('_MEMBER_PROFILE_ERROR9', 'Ismeretlen ûrlapmezõ típus: %s : %s');

define('_CRON_ERROR', 'Kívülrõl elérheto cron a beállításokban nincs élesítve');

define('_COMMON_LANGUAGE', 'Nyelv');
define('_COMMON_LIFETIME', 'VÉGTELEN');
define('_COMMON_RECURRING', 'ISMÉTLõDõ');

define('_INDEX_ERROR', 'aMember még nincs beállítva. Menj a %skonfigurációs oldalra%s.');

define('_LOGIN_REDIRECT', 'Átirányítás a levédett felületre');

define('_RESEND_ERROR', 'Az email címed már megerõsítve');
define('_RESEND_ERROR2', 'Új email megerõsítése nem lehetséges, próbálj újra %sregisztrálni%s vagy fordulj segítségért a honlap adminisztrátorához');
define('_RESEND_ERROR3', 'Belsõ hiba #1265.');

define('_NEWSLETTER_SUBSCRIPTION', 'Hírlevél feliratkozás');
define('_NEWSLETTER_NO_GUEST_THREADS', 'Elnézést, jelenleg nincs olyan hírlevél, ami látogatók számára nyilvános lenne');

define('_SETUP_ERROR', 'Az aMember mûködtetéséhez magasabb PHP verzió %s szükséges. A Te PHP-Verziód: %s%s Frissítsd, vagy amennyiben nincs módodban, fordulj segítségért szolgáltatódhoz.');
define('_SETUP_ERROR2', 'A szerveren nincs MySQL támogatás %s, így az aMember nem kompatibilis! Lépj kapcsolatba a %sszolgáltató adminisztrátorával a hiba kiküszöbölésére.');
define('_SETUP_FATAL_ERROR', 'Fatális hiba: %s');
define('_SETUP_HEADER', 'aMember telepítés');
define('_SETUP_CONF_EXISTS', 'Fájl: %s már létezik, és nem üres. Törlése esetén indítható csak újra konfigurálás.');
define('_SETUP_AFTER_FIX', 'A hibák kiküszöbölését követõen, kattints %side%s az oldal frissítéséhez.');
define('_SETUP_CONF_CHMOD', 'Fájl: %s már létezik, és nem írható. Kérlek, %sjavítsd ezt ki%s');
define('_SETUP_DIRECTORY_CHMOD', 'Könyvtár: %s nem írható. Konfigurációs fájlt kell bemásolni %s. Kérlek, %sjavítsd ezt ki%s');
define('_SETUP_ENTER_PARAM', 'Írd be a konfigurációs paramétereket');
define('_SETUP_MODIFY_LATER', 'Ezek az értékek nem véglegesek, késõbb is módosíthatóak az aMember vezérlõpultból');
define('_SETUP_ROOT_URL', 'Gyökér URL a program fájlhoz');
define('_SETUP_TRAILING_SLASH', '%sNe tegyél%s követõ perjelet ( %s/%s ) a végére!');
define('_SETUP_LICENSE_NOTE', 'Figyelem: az URL azonosnak kell lennie a licensszel.');
define('_SETUP_HTTPS_URL', 'Biztonságos (HTTPS) gyökér URL a fájlhoz');
define('_SETUP_KEEP_DEFAULT', 'Kérlek, tartsd meg alapértelmezétt értéket, ha nem vagy biztos benne (nem biztonságos).');
define('_SETUP_NO_TRSLASH', 'Ne tegyél követõ perjelet ( %s/%s )!');
define('_SETUP_ADMIN_EMAIL', 'Adminisztrátor email');
define('_SETUP_SENT_TO', 'Az email cím, ahova fontos értesítések és egyéb üzenetek küldendõk');
define('_SETUP_ADMIN_LOGIN', 'Adminisztrátor belépés');
define('_SETUP_USERNAME', 'Felhasználónév az adminisztrációs felületre való belépéshez');
define('_SETUP_ADMIN_PASS', 'Adminisztrátor jelszó');
define('_SETUP_PASS', 'Jelszó az adminisztrációs felületre való belépéshez');
define('_SETUP_LICENSE_HEAD', 'Licensz');
define('_SETUP_LICENSE', 'Illeszd be a %sTeljes%s licenszkulcsot, a szaggatott vonalakkal ( == ) együtt alul és felül!');
define('_SETUP_NEXT_BUT', 'Következõ');
define('_SETUP_ERROR3', 'Írd be a program fájl gyökér URL-ét');
define('_SETUP_ERROR4', 'Írd be a program fájl biztonsági gyökér URL-ét (vagy hagyd meg az alapértelmezett értéket - megegyezve a nem biztonsági URL-vel)');
define('_SETUP_ERROR5', 'Írd be az adminisztrátor emailt');
define('_SETUP_ERROR6', 'Írd be az adminisztrátor felhasználónevet');
define('_SETUP_ERROR7', 'Írd be az adminisztrátor jelszót');
define('_SETUP_ERROR8', 'Írd be a licenszkulcsot');
define('_SETUP_ERROR9', 'Illeszd be a teljes licenszkulcsot, a szaggatott vonalakkal ( == ) együtt alul és felül!');
define('_SETUP_ERROR10', 'Gyökér URL %s nem egyezik a licenszben szereplõvel');
define('_SETUP_ERROR11', 'Biztonsági gyökér URL %s nem egyezik a licenszben szereplõvel');
define('_SETUP_RETURN', 'Kérlek, %slépj vissza%s és javítsd ki ezeket a hibákat.');
define('_SETUP_MYSQL_PARAM', 'Írd be a MySQL konfigurációs paramétereit');
define('_SETUP_CONF_EDIT', 'Szerkeszthetõ a %sconfig.inc.php%s fájl is, amennyiben módosításra szorul valamilyen paraméter');
define('_SETUP_MYSQL_HOST', 'MySQL Host');
define('_SETUP_LOCALHOST', 'nagyon gyakran: \'localhost\'');
define('_SETUP_MYSQL_DB', 'MySQL Adatbázis');
define('_SETUP_MYSQL_NOTE', 'Figyelem: a felállítási folyamat adatbázist nem hoz létre.');
define('_SETUP_USE_DEFAULT', 'Használd az alapértelmezett adatbázist, melyet a szolgáltatód biztosított, vagy %sállíts fel egy új adatbázist magad, pl. \'amember\' néven');
define('_SETUP_MYSQL_USER', 'MySQL felhasználónév');
define('_SETUP_MYSQL_PWD', 'MySQL jelszó');
define('_SETUP_TABLE_PREFIX', 'MySQL táblázat elõtag (pl. am_ elõtag minden táblazat neve elõtt)');
define('_SETUP_UNSURE', 'Ha ebben nem vagy biztos, használd az alapértelmezett értéket: %samember_%s');
define('_SETUP_MYSQL_ERROR1', 'Írd be a MySQL adatbázis nevét');
define('_SETUP_MYSQL_ERROR2', 'Írd be a MySQL felhasználónevet');
define('_SETUP_MYSQL_ERROR3', 'Írd be a MySQL hostnevet');
define('_SETUP_MYSQL_ERROR4', 'Írd be a MySQL jelszót');
define('_SETUP_MYSQL_ERROR5', 'Nem tud kapcsolatot teremteni a MySQL szerverrel (%s)');
define('_SETUP_MYSQL_ERROR6', 'Nem találja az adatbázist \'%s\' ( %s )');
define('_SETUP_MYSQL_INSTALL', 'Telepítsük az aMembert ehhez a MySQL adatbázishoz?');
define('_SETUP_MYSQL_CREATE_TABLES', 'aMember adatbázis táblázatok elkészítése');
define('_SETUP_MYSQL_INSTALL2', 'Az aMember táblázatok elkészítéséhez jelöld be a négyzetet és kattints a \'Következõ\' gombra a megjelölt MySQL adatbázisban.%s Ha az aMember azonos helyen van telepítve, akkor a telepítési folyamat semmit nem fog törölni%s, csak felülírja a táblázatok szerkezetét');
define('_SETUP_MYSQL_ERROR7', 'Adatbázist nem található \' %s \' ( %s )');
define('_SETUP_MYSQL_FIX_ERROR', 'Javítsd ki ezeket a hibákat és %sfrissítsd%s ezt az oldalt.');
define('_SETUP_ERROR12', ' %s nem nyitható. Töltsd fel ezt a fájlt');
define('_SETUP_ERROR13', 'Nem menthetõk a konfigurációs fájlok');
define('_SETUP_ERROR14', 'Nem menthetõ a fájl %s%s%s');
define('_SETUP_NEW_CONFIG', 'A teljes program felállításhoz töltsd le az új konfigurációs fájlokat a számítógépedre, majd töltsd fel a tárhelyedre.');
define('_SETUP_UPLOAD_CONFIG', 'Fájl: %sconfig.inc.php%s. Töltsd fel:');
define('_SETUP_DOWNLOAD_BUT', 'Töltsd le: config.inc.php');
define('_SETUP_IE_RENAME', 'A böngészõ átnevezheti a %sfájlokat mentéskor. Pl. átnevezi a %sconfig.inc.php%s%s-t %sconfig[1].inc.php%s-re. Feltöltés csakis config.inc.php néven lehetséges!');
define('_SETUP_THANK_YOU1', 'Köszönjük, hogy az aMember Pro mellett döntöttél. A használati utasítást %sitt találod%s.');
define('_SETUP_THANK_YOU2', 'Lépj velünk kapcsolatba, ha bármiféle problémát tapasztalsz a programmal.');
define('_SETUP_THANK_YOU3', 'Nézd át a következõket:');
define('_SETUP_THANK_YOU4', '(Javasolt az oldalt a kedvencek közé helyezned)');
define('_SETUP_THANK_YOU_LINK1', 'Adminisztrátor oldal (aMember Vezérlõpult)');
define('_SETUP_THANK_YOU_LINK2', 'Regisztrációs oldal');
define('_SETUP_THANK_YOU_LINK3', 'Regisztrált tag oldal');
define('_SETUP_THANK_YOU_LINK4', 'Belépõ oldal (átirányít a zárt felületre)');
define('_SETUP_THANK_YOU_BEFOREUSE', 'Az aMember használata elõtt a következõk is szükségesek:)');
define('_SETUP_THANK_YOU_GOTOCP', 'Menj az %sAdminisztrációs oldalra%s és jelentkezz be. A fõmenü bal oldalon válaszd ki a: %sSzolgáltatások>Telepítés/Konfiguráció%s menüpontot. Ezek a beállítások a telepítés finombeállítására szolgálnak. Engedélyezz minden fizetési plug-int, amire szükséged lesz, majd a konfigurációs szakaszban végezd el a többi beállítást.');
define('_SETUP_THANK_YOU_ADDPRODUCTS', 'Menj az %sAdminisztrátor oldalakra%s és adj hozzá termékeket vagy elõfizetési típusokat.%s%sNevezheted õket \'Termékek\'-nek vagy \'Elõfizetési típusok\'-nak attól függõen, hogy mivel foglalkozol. Pl. egy hírlevélre való feliratkozást valószínüleg \'Elõfiztés,\'-nek neveznél el, miközben mondjuk számítógépes alkatrészeket \'Termék\'-nek. Tõled függ, hogy nevezed el ezeket az aMember adatbázis rekordokat.');
define('_SETUP_THANK_YOU_REMEMBER', 'Fontos tudni, hogy a \'Termék\' vagy \'Elõfizetési típus\' csak megnevezésben különböznek, mindkettõ tulajdonképpen egy sor az aMember adatbázisában.');
define('_SETUP_THANK_YOU_SUBSCRTYPE', 'Megnevezhetsz elõfizetési típusokat (ingyenes, fizetõs, stb...) ahogy a termékeket beírod.%sFontos, hogy minimum 1 terméket írj be!%s');
define('_SETUP_THANK_YOU_PAYCONF', 'Gyõzõdj meg arról, hogy a megfizettetés igényel-e valamiféle speciális beállítást. Ha igen, a %sTelepítési utasításokban%s keress további lehetõségeket, vagy lépj kapcsolatba a CGI-Central ügyfélszolglatával további konfigurációs szolgáltatásért.');
define('_SETUP_THANK_YOU_PROTECTION', 'Állítsd be a szükséges felületek védelmét. Használhatsz .htaccess vagy PHP included fájlokat. Ha cookie keresztüli védelemre van szükség, minden védendõ fájlnak PHP fájlnak kell lennie! ');
define('_SETUP_THANK_YOU_CHECKINSTL', 'A %s%sRegisztrációs%oldalak segítségével teszteld a telepítést.%sHa minden jól mûködik, néhány HTML minta fájl testreszabására is van lehetoség, amelyek:');
define('_SETUP_THANK_YOU_READMORE', 'További információt a sablonok testreszabásáról %sitt%s találsz.%sTipp:%s 90%a az aMember felület külsojének módosítása a CSS stylesheet fájlok szerkesztésével lehetséges, ami a %sheader.html%s fájlban található meg');
define('_SETUP_THANK_YOU_FEELFREE', 'Egyéb módosítási igény esetén kérlek, lépj kapcsolatba a %sCGI-Central ügyfélszolgálattal%s.');
define('_SETUP_THANK_YOU_INFO', 'További hasznos információk olvashatóak a %stagsági fórumon%s.');
define('_SETUP_HEADER1', 'aMember beállítások: 6-dik lépés %d');

define('_UNSUBSCRIBE_ERROR', 'Hibásan megadott URL! Kérlek, lépj kapcsolatba a honlap adminisztrátorával');

define('_PLUG_PAY_REDIRECT_WAIT', 'Egy kis türelmet kérek... Köszönöm!');
define('_PLUG_PAY_REDIRECT_REDIRECT', 'Átirányítás a zárt tagsági oldalra');

define('_TPL_CC_INFO_TITLE', 'Hitelkártya Információ');
define('_TPL_CC_INFO_CCTYPE', 'Hitelkártya Típus');
define('_TPL_CC_INFO_SELECT1', 'válassz egyet');
define('_TPL_CC_INFO_CHOOSE', '*** Válassz ***');
define('_TPL_CC_INFO_HOLDERNAME', 'Kártyatulajdonos neve');
define('_TPL_CC_INFO_ASONCARD', 'kártyatulajdonos neve megegyezõen, ahogyan a kártyán van feltüntetve');
define('_TPL_CC_INFO_HOLDERNAME2', 'Kártyatulajdonos neve');
define('_TPL_CC_INFO_FLNAME', 'kártyatulajdonos kereszt és vezetékneve megegyezõen, ahogyan%sa kártyán van feltüntetve');
define('_TPL_CC_INFO_CNAME', 'Cégnév');
define('_TPL_CC_INFO_COMPNAME', 'tranzakció keretében megadott cégnév társítása a %sszámlán levõ címhez');
define('_TPL_CC_INFO_CCNUM', 'Hitelkártya szám');
define('_TPL_CC_INFO_EXAMPLE', 'például: 1111-2222-3333-4444');
define('_TPL_CC_INFO_EXPIRE', 'Kártya lejárati ideje');
define('_TPL_CC_INFO_EXPDATE', 'Válaszd ki a lejárati dátumot - hónap és év');
define('_TPL_CC_INFO_CCCODE', 'Hitelkártya kód');
define('_TPL_CC_INFO_CCCODEDESC', 'A "Hitelkártya kód" egy 3 vagy 4 jegyû biztonsági kód%sami a kártya hátoldalán az %saláírás mezõ végén található (American Express kártyáknál az elsõ oldalon).');
define('_TPL_CC_INFO_ADDRINFO', 'Cím információ');
define('_TPL_CC_INFO_STRADDR', 'Utca');
define('_TPL_CC_INFO_HNUMB', 'Házszám');
define('_TPL_CC_INFO_CITY', 'Település');
define('_TPL_CC_INFO_STATE', 'Állam vagy megye');
define('_TPL_CC_INFO_ZIP', 'Irányítószám');
define('_TPL_CC_INFO_COUNTRY', 'Ország');
define('_TPL_CC_INFO_PHONE', 'Telefonszám');
define('_TPL_CC_INFO_PHONENUM', 'a telefonszámot a következõ formátumban javasolt %smegadni: %s999-999-9999%s');
define('_TPL_CC_INFO_MUSTMATCH', '(A hitelkártyás számláján levõ címmel egyeznie kell)');
define('_TPL_CC_INFO_SUBMIT_BUT', 'Információ frissítése');
define('_TPL_CC_INFO_BACK_BUT', 'Vissza');
define('_TPL_CC_INFO_SUBMIT_BUT2', 'Elõfizetés indítása');
define('_TPL_CC_INFO_SUBMIT_BUT_3', 'Elõfizetés befejezése');

define('_TPL_CC_DECLINED_TITLE', 'Hiba a fizetési muveletben');
define('_TPL_CC_DECLINED_TRYAGAIN', 'Próbáld újra');



define('_TPL_CC_INFO_BANK_IDENTIFICATION', 'Bank Azonosítás');
define('_TPL_CC_INFO_BIN_NAME', 'Bank neve');
define('_TPL_CC_INFO_BIN_NAME_MORE', 'a bank neve, mely a hitelkártyát kiadta');
define('_TPL_CC_INFO_BIN_PHONE', 'Bank telefonszáma');
define('_TPL_CC_INFO_BIN_PHONE_MORE', 'Vevõszogálat telefonszám a hitelkártya hátulján');

define('_TPL_CC_VERIFY_CODE', 'Telefonszám azonosító ûrlapmezõ');
define('_TPL_CC_INFO_CALLING', 'Hívjuk a beírt telefonszámot');
define('_TPL_CC_INFO_VERIFY_CODE', 'Azonosító kód');
define('_TPL_CC_INFO_VERIFY_CODE_MORE', 'írd be az azonosító kódot, amit a robotic rendszertõl kaptál');
define('_TPL_CC_INFO_SUBMIT_VERIFY', 'Tovább');

define('_TPL_WRONG_VERIFY_CODE', 'Hibás azonosító kód! Kérlek, próbáld újra.');

define('_TPL_CC_ERROR_TNI', 'Hiba történt a telefonszám azonosítása közben');
define('_TPL_CC_ERROR_TV',  'Hiba történt a telefonszám azonosítása közben');
define('_TPL_CC_ERROR_CARDEREMAIL', 'Hiba. Email cím az adatbázisban a gyanús emailek között szerepel');
define('_TPL_CC_ERROR_COUNTRYNOTMATCH', 'Hiba. Az IP cím szerinti ország nem egyezik a számlázás szerinti országgal');
define('_TPL_CC_ERROR_HIGHRISKCOUNTRY', 'Hiba. IP cím vagy számlázási cím szerinti ország a nem elfogadott országok listáján szerepel');
define('_TPL_CC_ERROR_ANONYMOUSPROXY', 'Hiba. Anonymous proxy nem engedélyezett');
define('_TPL_CC_ERROR_FREEMAIL', 'Hiba. Ingyenes email szolgáltató nem engedélyezett');

define('_TPL_CC_ERROR_BIN', 'Hiba. A számlázási cím szerint megadott ország nem egyezik a bankazonosító (BIN) alapján kiállított ország nevével');
define('_TPL_CC_ERROR_BIN_NAME', 'Hiba. A kiállító bank megnevezése nem egyezik a bankazonosító (BIN-Name) alapján kiállított bank megnevezésével');
define('_TPL_CC_ERROR_BIN_PHONE', 'Hiba. Az ügyfélszolgálat telefonszáma nem egyezik a bankazonosító (BIN-Phone) alapján megadott telefonszámmal');

define('_TPL_CC_DECLINED', 'Érvénytelen Hitelkártya adatok. Tranzakció elutasítva');


define('_TPL_JSVAL_ERR_FORM', 'Írj be/válassz értékeket a következõ ûrlapmezõnek:');
define('_TPL_JSVAL_ERR_SELECT', 'Válassz érvényes [%FIELDNAME%]');
define('_TPL_JSVAL_ERR_ENTER', 'Írj be érvényes [%FIELDNAME%]');

define('_TPL_COMMON_SELECT_STATE', '[Válassz államot / megyét]');
define('_TPL_COMMON_SELECT_COUNTRY', '[Válassz országot]');






define('_PLUG_PAY_ANYLINK_REDIR_ERROR', '"AnyLink URL" üres a termékhez#%d. Lépj kapcsolatba a honlap adminisztrátorával');
define('_PLUG_PAY_ANYLINK_TITLE', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_ANYLINK_CCACCEPTED', 'Minden elismert és érvényes hitelkártya elfogadott');





define('_PLUG_PAY_AUTHORIZE_TITLE', 'Authorize.Net online fizetési rendszer segítségével történõ fizetés');
define('_PLUG_PAY_AUTHORIZE_DESCR', 'Hitelkártya az %sauthorize.net%s rendszeren keresztül');
define('_PLUG_PAY_AUTHORIZE_ERROR', 'hitelesítési HIBA: %s (Részletek: PNREF:%s, számla:%s)%s%s');
define('_PLUG_PAY_AUTHORIZE_ERR_ARR', 'Fizetési mûvelet kezelése sikertelen:');
define('_PLUG_PAY_AUTHORIZE_ERR_ARR2', 'Lépj vissza és próbálkozz újra.');
define('_PLUG_PAY_AUTHORIZE_USER_ERR', 'Összeg nulla vagy üresen hagyott');
define('_PLUG_PAY_AUTHORIZE_ERROR2', 'Hibás MD5 hash kód');
define('_PLUG_PAY_AUTHORIZE_ERROR3', 'Teszt tranzakciói kísérlet, az aMember beélesített tranzakciók konfigurálása ellenére');
define('_PLUG_PAY_AUTHORIZE_ERROR4', 'Fizetési mûvelet véglegesítési hiba: %s');





define('_PLUG_PAY_AUTHORIZE_AIM_TITLE', 'Authorize AIM');
define('_PLUG_PAY_AUTHORIZE_AIM_DESC', 'Hitelkártya fizetõ rendszer');












define('_PLUG_PAY_ESOLUTIONS_TITLE', 'Merchant e-Solutions');
define('_PLUG_PAY_ESOLUTIONS_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_BEANSTREAM_TITLE', 'BeanStream');
define('_PLUG_PAY_BEANSTREAM_DESC', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_BEANSTREAM_PFAILED', 'Sikertelen fizetési kísérlet: ');





define('_PLUG_PAY_BEANSTREAM_REM_ERROR', 'beanstream távoli elérési hiba: %s (Részletek: PNREF:%s, számla:%d)%s%s');
define('_PLUG_PAY_BEANSTREAM_REM_DEBUG', 'beanstream távoli elérési DEBUG: ');
define('_PLUG_PAY_BEANSTREAM_REM_TITLE', 'BeanStream');
define('_PLUG_PAY_BEANSTREAM_REM_DESC', 'Hitelkártya fizetõ rendszer');

define('_PLUG_PAY_BEANSTREAM_REM_HTML_TITLE', 'Hitelkártya fizetõ rendszer oldala');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CNAME', 'Név a kártyán');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CNAME2', '%spontosan%s ahogyan a hitelkártyán');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CCNUM', 'Hitelkártya szám');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CCEXP', 'Hitelkártya lejár');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JAN', 'Január');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_FEB', 'Február');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_MAR', 'Március');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_APR', 'Április');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_MAY', 'Május');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JUN', 'Június');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JUL', 'Július');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_AUG', 'Augusztus');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_SEP', 'Szeptember');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_OCT', 'Október');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_NOV', 'November');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_DEC', 'December');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ADDR', 'Cím');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ADDR2', 'a hitelkártya tulajdonos %spontos%s címe');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CITY', 'Település');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CITY2', 'a hitelkártya tulajdonos településének %spontos%s megnevezése');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_COUNTRY', 'Ország');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_COUNTRY2', 'a hitelkártya tulajdonos országának %spontos%s megnevezése');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_STATE', 'Állam vagy megye');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_STATE2', 'a hitelkártya tulajdonos %spontos%s állam vagy megye megnevezése');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ZIP', 'Irányítószám');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_PHONE', 'Telefonszám');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_PROCEED', 'Tovább');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_FSUMB', 'ezek az adatok biztonsági szerverre lesznek továbbítva');





define('_PLUG_PAY_PAYCOM_FERROR', 'PayCom IPN Hiba: %s (Részletek: számla:%d)%s');
define('_PLUG_PAY_PAYCOM_ERROR', 'Hiba a fizetési mûvelet adatfeldolgozása alatt: %s');
define('_PLUG_PAY_PAYCOM_ERROR2', '%s Menj vissza és próbálkozz újra.');
define('_PLUG_PAY_PAYCOM_ERROR3', 'Visszaigazolt jelszó hibás: ');
define('_PLUG_PAY_PAYCOM_ERROR4', 'Paycom IPN: Sikertelen fizetési kísérlet (Részletek: számla:%d)%s');
define('_PLUG_PAY_PAYCOM_ERROR5', 'Tesztmód érvénytelenítve, folyamat megszakítva');
define('_PLUG_PAY_PAYCOM_ERROR6', 'Rossz termék kód: [%d] [%d] helyett');
define('_PLUG_PAY_PAYCOM_ERROR7', 'Hibás IP cím: %s , engedélyezett IP mask: ');
define('_PLUG_PAY_PAYCOM_ERROR8', 'Hibás co_code');

define('_PLUG_PAY_PAYCOM_TITLE', 'PayCom');
define('_PLUG_PAY_PAYCOM_DESC', 'PayCom Hitelkártya Adatfeldolgozás');

define('_PLUG_PAY_PAYCOM_ERROR9', 'paycom Hiba: %s');
define('_PLUG_PAY_PAYCOM_ERROR10', 'Tesztmód érvénytelenítve');

define('_PLUG_PAY_PAYCOM_HTML_TITLE', 'Paycom Fizetmény');
define('_PLUG_PAY_PAYCOM_HTML_TEXT1', 'Kattints a "Tovább" gombra, a %sPaycom.net%s keresztüli fizetési mûvelet folytatásához.');
define('_PLUG_PAY_PAYCOM_HTML_SUBMBUT', 'Tovább');





define('_PLUG_PAY_CC_CORE_FERROR1', '\'v\' érvénytelen értéke van');
define('_PLUG_PAY_CC_CORE_FERROR2', 'Tag azonosítószám üres');
define('_PLUG_PAY_CC_CORE_FERROR3', 'Payment_id üres');
define('_PLUG_PAY_CC_CORE_FERROR4', 'Fizetési mûvelethez tartozó személy nem létezik');
define('_PLUG_PAY_CC_CORE_FERROR5', 'Fizetési mûvelet folyamatban! Kérlek, menj a %stagsági oldalra%s');
define('_PLUG_PAY_CC_CORE_FERROR6', 'Erre a próba elõfizetésre már feliratkoztál  - Lépj vissza a <a href=\'{%s}/signup.php\'>regisztrációs oldalra</a> és válassz más terméket');
define('_PLUG_PAY_CC_CORE_SBSCNCL', 'Elõfizetés törölve');
define('_PLUG_PAY_CC_CORE_SBSCNCL2', 'Ismétlõdõ elõfizetés megszüntetve.');
define('_PLUG_PAY_CC_CORE_CCINFOCHNG', 'Hitelkártya információ megváltoztatva');
define('_PLUG_PAY_CC_CORE_REDIR', 'Átirányítás a fizetõi rendszerhez');
define('_PLUG_PAY_CC_CORE_FERROR7', 'Érvénytelen mûvelet');

define('_TPL_CC_INFO_PROVINCE', 'Külföldön lévõ megye számlázása');
define('_TPL_CC_INFO_PROVINCE_DESC', ' USA-n és Kanadán kívüli megye esetén írd a megye nevét ide');
define('_TPL_CC_INFO_ISSUENUM', 'Kártya kiállítási száma');
define('_TPL_CC_INFO_ISSUENUM_DESC', 'Maestro/Solo/Switch Hitelkártyáknál kötelezõ csak');
define('_TPL_CC_INFO_STARTDATE', 'Kártya kezdeti dátuma');
define('_TPL_CC_INFO_STARTDATE_DESC', 'Csak Maestro/Solo/Switch hitelkártyáknál kötelezõ');


define('_PLUG_PAY_CC_CORE_REDIR', 'Átirányítás a fizetõi rendszerhez');
define('_PLUG_PAY_CC_CORE_REDIRDESC', 'Automatikus átirányítás a biztonságos fizetõi oldalra nehány másodperc múlva...');
define('_PLUG_PAY_CC_CORE_ERROR1', 'Beírandó: Hitelkártya szám');
define('_PLUG_PAY_CC_CORE_ERROR2', 'Érvénytelen Hitelkártya szám');
define('_PLUG_PAY_CC_CORE_ERROR3', 'Hitelkártya szám érvénytelen: ');
define('_PLUG_PAY_CC_CORE_ERROR4', 'Érvénytelen lejárt dátum - hónap');
define('_PLUG_PAY_CC_CORE_ERROR5', 'Érvénytelen lejárt dátum - év');
define('_PLUG_PAY_CC_CORE_ERROR6', 'Válaszd ki a hitelkártya típusát');
define('_PLUG_PAY_CC_CORE_ERROR7', 'Beírandó: Hitelkártya kód');
define('_PLUG_PAY_CC_CORE_ERROR8', 'Beírandó: Hitelkártya tulajdonosának neve');
define('_PLUG_PAY_CC_CORE_ERROR9', 'Beírandó: Hitelkártya tulajdonosának keresztneve');
define('_PLUG_PAY_CC_CORE_ERROR10', 'Beírandó: Hitelkártya tulajdonosának vezetékneve');
define('_PLUG_PAY_CC_CORE_ERROR11', 'Beírandó: Hitelkártyán szereplõ cég');
define('_PLUG_PAY_CC_CORE_ERROR12', 'Beírandó: Telefonszám');
define('_PLUG_PAY_CC_CORE_ERROR13', 'Beírandó: Házszám');
define('_PLUG_PAY_CC_CORE_ERROR14', 'Beírandó: Utca');
define('_PLUG_PAY_CC_CORE_ERROR15', 'Beírandó: Település');
define('_PLUG_PAY_CC_CORE_ERROR16', 'Válassz államot vagy megyét');
define('_PLUG_PAY_CC_CORE_ERROR17', 'Beírandó: Irányítószám');
define('_PLUG_PAY_CC_CORE_ERROR18', 'Kiválasztandó: Ország');

define('_PLUG_PAY_CC_CORE_ERROR19', 'Érvénytelen kezdeti dátum - Hónap');
define('_PLUG_PAY_CC_CORE_ERROR20', 'Érvénytelen kezdeti dátum - Év');





define('_PLUG_PAY_CC_BILL_TITLE', 'Hitelkártya');
define('_PLUG_PAY_CC_BILL_DESCR', 'Fizetési mód: Mastercard, Checkcards, Discover, JCB, vagy www.ccbill.com átutalás');
define('_PLUG_PAY_CC_BILL_CHECK_DESCR', 'Online Check fizetés www.ccbill.com segítségével');
define('_PLUG_PAY_CC_BILL_TEL_DESCR', 'Telefonos fizetség www.ccbill.com segítségével');
define('_PLUG_PAY_CC_BILL_ERROR', 'Felhasználónév nem egyezhet a jelszóval,  válassz másik jelszót');





define('_PLUG_PAY_CDG_TITLE', 'CDG');
define('_PLUG_PAY_CDG_DESCR', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_CENTIP_TITLE', 'Centipaid ');
define('_PLUG_PAY_CENTIP_DESC', '%sDigitálisan megõrzött érték kártyák%s');
define('_PLUG_PAY_CENTIP_FERROR', 'centipaid hiba: %s (Részletek: PNREF:%s, számla:%s)%s');
define('_PLUG_PAY_CENTIP_ERROR', 'Hiba a fizetési mûvelet adatfeldolgozása alatt: ');
define('_PLUG_PAY_CENTIP_ERROR2', ' Menj vissza és próbákozz újra');
define('_PLUG_PAY_CENTIP_ERROR3', 'a visszaigazolt összeg vagy üresen hagyott vagy nulla');
define('_PLUG_PAY_CENTIP_ERROR4', 'Teszt tranzakció kísérlet, miközben az aMember éles adatfeldolgozásra van beállítva');
define('_PLUG_PAY_CENTIP_ERROR5', 'Fizetési mûvelet véglegesítési hiba: %s');





define('_PLUG_PAY_CLICKBANK_TITLE', 'Clickbank');
define('_PLUG_PAY_CLICKBANK_DESC', 'Leírásért menj a %swww.clickbank.com%s oldalra');
define('_PLUG_PAY_CLICKBANK_INCORRECT', 'Hibás beterjesztés #%d. Értesítsd a programozót');
define('_PLUG_PAY_CLICKBANK_ERROR', 'Fizetési mûvelet véglegesítési hiba: ');





define('_PLUG_PAY_DIRECTONE_TITLE', 'DirectOne');
define('_PLUG_PAY_DIRECTONE_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_DIRECTONEREM_TITLE', 'Hitelkártya fizetõ rendszer (DirectOne)');
define('_PLUG_PAY_DIRECTONEREM_DESC', 'Leírásért a %swww.directone_remote.com%s oldlára menj');
define('_PLUG_PAY_DIRECTONEREM_RETLNK', 'Térj vissza a tagsági információs oldalra');
define('_PLUG_PAY_DIRECTONEREM_ERROR', 'directone hiba: %s (Részletek: PNREF:%s, számla:%d)%s');





define('_PLUG_PAY_PAYMENOW_TITLE', 'PayMeNow');
define('_PLUG_PAY_PAYMENOW_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_PAYMONDE_TITLE', 'PayMonde');
define('_PLUG_PAY_PAYMONDE_DESC', 'Menj a %swww.paymonde.com%s oldlra leírásért');

define('_PLUG_PAY_PAYMONDE_FERROR', 'paymonde hiba: %s (Részletek: payment_id:%d, számla:%d)');
define('_PLUG_PAY_PAYMONDE_ERROR', 'Érvénytelen válasz a PayMonde serverrõl. Külsõ beavatkozás gyanúja.');





define('_PLUG_PAY_CC_DEMO_TITLE', 'Hitelkártya demó fizetés');
define('_PLUG_PAY_CC_DEMO_DESCR', 'Demó hitelkártya fizetés alkalmazása - használd a 4111-1111-1111-1111 számot a hitelkártya számaként #');
define('_PLUG_PAY_CC_DEMO_CCNUM', 'A következõ számot írd be, hogy a tranzakció sikeresen átmenjen: 4111-1111-1111-1111');





define('_PLUG_PAY_ECHO_TITLE', 'ECHO');
define('_PLUG_PAY_ECHO_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_EFSNET_TITLE', 'EFSNet');
define('_PLUG_PAY_EFSNET_DESC', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_EFSNET_ERROR', 'Fizetési mûvelet nem található: #%d');
define('_PLUG_PAY_EFSNET_ERROR2', 'Fizetés sikeresen lebonyolítva: #%d');
define('_PLUG_PAY_EFSNET_ERROR3 ', 'Fizetési mûvelet teljesítése egy másik fizetõrendszeren keresztül történik: %d (#%d)');
define('_PLUG_PAY_EFSNET_ERROR4', 'Fizetési mûvelet egy másik tag számára létrehozott: #%d');
define('_PLUG_PAY_EFSNET_ERROR5', 'A tag nem található: #%d');
define('_PLUG_PAY_EFSNET_ERROR6', 'aMember: Nincs válasz a mûvelet végrehajtó egységtõl! Fizetési mûvelet sikertelen');





define('_PLUG_PAY_EGOLD_TITLE', 'E-Gold');
define('_PLUG_PAY_EGOLD_DESC', 'Fizess e-goldon keresztül (lasd: %swww.e-gold.com%s leírásért)');
define('_PLUG_PAY_EGOLD_ERROR', 'EGOLD hiba: %s (Részletek: PAYMENT_BATCH_NUM:%d, számla:%d)%s');
define('_PLUG_PAY_EGOLD_ERROR2', 'Kifizetést fogadó személy %s helyettem: ');
define('_PLUG_PAY_EGOLD_ERROR3', 'Kifizetés egy másik rendszerben van: %s az elfogadott helyett %s');
define('_PLUG_PAY_EGOLD_ERROR4', 'V2_HASH hiba %s a következõ helyett: %s');





define('_PLUG_PAY_EMATTERS_TITLE', 'eMatters.com.au');
define('_PLUG_PAY_EMATTERS_DESC', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_EMATTERS_ERROR', 'Tranzakció elutasítva%s. próbálkozz újra');
define('_PLUG_PAY_EMATTERS_CODE0', 'Jóváhagyott tranzakció.');
define('_PLUG_PAY_EMATTERS_CODE1', 'Tranzakció elutasítva. Keresd fel a kártya kiállítóját.');
define('_PLUG_PAY_EMATTERS_CODE2', 'Tranzakció elutasítva. Hívd fel az engedélyezõ hivatalt.');
define('_PLUG_PAY_EMATTERS_CODE3', 'Tranzakció elfogadva. Írd alá a számlát.');
define('_PLUG_PAY_EMATTERS_CODE4', 'Tranzakció elutasítva. Érvénytelen tranzakció típus.');
define('_PLUG_PAY_EMATTERS_CODE5', 'Tranzakció elutasítva. Keresd fel a kártya kiállítóját.');
define('_PLUG_PAY_EMATTERS_CODE6', 'Tranzakció elutasítva. Nincs ilyen hitelszámla.');
define('_PLUG_PAY_EMATTERS_CODE7', 'Tranzakció elutasítva. Nincs fedezet.');
define('_PLUG_PAY_EMATTERS_CODE8', 'Tranzakció elutasítva. Maximum fedezet feletti összeg.');
define('_PLUG_PAY_EMATTERS_CODE9', 'Tranzakció elutasítva. A kiállító nem elérhetõ.');
define('_PLUG_PAY_EMATTERS_CODE10', 'Nem egyedi UID (felhasználó azonosító) - elfogadva');
define('_PLUG_PAY_EMATTERS_CODE11', 'Tranzakció visszautasítva - Nem megfelelõ kártyatípus');
define('_PLUG_PAY_EMATTERS_CODE12', 'Érvénytelen vásárlási összeg');
define('_PLUG_PAY_EMATTERS_CODE13', 'Helytelen kártyaszám');
define('_PLUG_PAY_EMATTERS_CODE14', 'Érvénytelen lejárati dátum formátum');
define('_PLUG_PAY_EMATTERS_CODE15', 'Kártya lejár');
define('_PLUG_PAY_EMATTERS_CODE16', 'Host nem található, az adott bankrendszer pillanatnyilag üzemképtelen');
define('_PLUG_PAY_EMATTERS_CODE17', 'Szolgáltatóval a kapcsolat megszakadt, a bank vonala nem mûködik');
define('_PLUG_PAY_EMATTERS_ERROR', 'Tranzakció elutasítva%s. próbálkozz újra');

define('_PLUG_PAY_EMATTERS_HTML_TITLE', 'Fizetési mûvelet megerõsítése');
define('_PLUG_PAY_EMATTERS_HTML_SELECTC', 'válassz kártyát');
define('_PLUG_PAY_EMATTERS_HTML_CCNUM', 'Hitelkártya száma');
define('_PLUG_PAY_EMATTERS_HTML_CCEXP', 'Hitelkártya lejár');
define('_PLUG_PAY_EMATTERS_HTML_CCHNAME', 'Hitelkártya tulajdonosának neve');
define('_PLUG_PAY_EMATTERS_HTML_GOTOSITE', 'Menj a a levédett felületre');
define('_PLUG_PAY_EMATTERS_HTML_FORMSUBM', 'ezek az adatok biztonsági szerverre lesznek továbbítva');
define('_PLUG_PAY_EMATTERS_HTML_CCTYPE', 'Hitelkártya típus');





define('_PLUG_PAY_EPASSPORT_TITLE', 'Epassporte');
define('_PLUG_PAY_EPASSPORT_DESC', 'Epassporte fizetési mûvelet adatfeldolgozása');
define('_PLUG_PAY_EPASSPORT_HTML_TITLE', 'Paycom fizetõ rendszer');
define('_PLUG_PAY_EPASSPORT_HTML_CLICKPAY', 'Kattints a "Fizess ePassporte által" gombra a fizetési mûvelet kezdeményezéséhez!');
define('_PLUG_PAY_EPASSPORT_ERROR', 'epassporte hiba:');
define('_PLUG_PAY_EPASSPORT_ERROR2', 'Hiba a fizetési mûvelet adatfeldolgozása közben:');
define('_PLUG_PAY_EPASSPORT_ERROR3', ' Menj vissza és próbákozz újra.');

define('_PLUG_PAY_EPASSPORT_ERROR4', 'Epassporte IPN hiba: %s (Részletek: számla:%d)%s');
define('_PLUG_PAY_EPASSPORT_ERROR5', 'Epassporte IPN: Sikertelen fizetési kísérlet (Részletek: számla:%d)%s');
define('_PLUG_PAY_EPASSPORT_ERROR6', 'Hibás hitelkártyaszám');
define('_PLUG_PAY_EPASSPORT_ERROR7', 'Hibás IP cím: %s , engedélyezett IP maszk: ');
define('_PLUG_PAY_EPASSPORT_ERROR8', 'Visszaigazolt jelszó hibás: %s');
define('_PLUG_PAY_EPASSPORT_ERROR9', 'A következõ tranzakció elutasítva: ');
define('_PLUG_PAY_EPASSPORT_ERROR10', 'Köszönjük a vásárlást!');
define('_PLUG_PAY_EPASSPORT_ERROR11', 'Tranzakció ellenõrzési procedúra (TVP) Hiba: ');
define('_PLUG_PAY_EPASSPORT_ERROR12', 'ePassporte IPN: tranzakció %d ellenõrizve és elfogadva');





define('_PLUG_PAY_EPROCESSING_TITLE', 'eProcessingNetwork');
define('_PLUG_PAY_EPROCESSING_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_EWAY_TITLE', 'E-Way');
define('_PLUG_PAY_EWAY_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_FREE_ID', 'ingyenes');
define('_PLUG_PAY_FREE_TITLE', 'Ingyenes regisztráció');
define('_PLUG_PAY_FREE_DESC', 'Teljesen ingyenes');
define('_PLUG_PAY_FREE_NOTFORFREE', 'Az INGYENES Regisztráció plugin nem használható olyan terméknél, melynek ára 0.0-nál több');
define('_PLUG_PAY_FREE_ERROR', 'Azonosító kód helytelen. A hibaelhárításért, lépj kapcsolatba a honlap adminisztrátorával.');
define('_PLUG_PAY_FREE_MAILSENT', 'Email elküldve az adminisztrátornak. A jóváhagyás némi türelmet igényel! Köszönjük.');
define('_PLUG_PAY_FREE_SIGNEDUP', 'Már regisztráltál. %sLépj be%s itt');





define('_PLUG_PAY_GLOBILL_ID', 'globill');
define('_PLUG_PAY_GLOBILL_TITLE', 'Glo-Bill Hitelkártya');
define('_PLUG_PAY_GLOBILL_DESC', 'Fizetési mód: Visa, Mastercard, Checkcards, Discover, Eurocard, JCB, Diners kártyák, vagy elektronikus fizetés %swww.globill.com%s segítségével.');

define('_PLUG_PAY_GLOBILL_PH_ID', 'globill_phone');
define('_PLUG_PAY_GLOBILL_PH_TITLE', 'Glo-Bill Phone');
define('_PLUG_PAY_GLOBILL_PH_DESC', 'Fizess egyszerûen telefonon keresztül %swww.globill.com%s-nál');

define('_PLUG_PAY_GLOBILL_CH_ID', 'globill_check');
define('_PLUG_PAY_GLOBILL_CH_TITLE', 'Glo-Bill Check');
define('_PLUG_PAY_GLOBILL_CH_DESC', 'Fizess online csekkel %swww.globill.com%s-on keresztül');

define('_PLUG_PAY_GLOBILL_CANNOTORDER', 'Ez a termék nem megrendelhetõ GloBill hitelkártyával');
define('_PLUG_PAY_GLOBILL_CANNOTORDER2', 'Ez a termék nem megrendelhetõ GloBill telefonos számlázással');
define('_PLUG_PAY_GLOBILL_CANNOTORDER3', 'Ez a termék nem megrendelhetõ GloBill online csekkel');
define('_PLUG_PAY_GLOBILL_ERROR', 'Belsõ Hiba: ismeretlen paysys_id: %d');
define('_PLUG_PAY_GLOBILL_FERROR', 'GLOBILL hiba: %s (Részletek: PNREF:%s, számla:%d)%s');
define('_PLUG_PAY_GLOBILL_ERROR2', 'Hibás webmaster felhasználónév lett átküldve: %s!');





define('_PLUG_PAY_IKOBO_TITLE', 'ikobo');
define('_PLUG_PAY_IKOBO_DESC', 'Biztonságos hitelkártya fizetõ rendszer');
define('_PLUG_PAY_IKOBO_ERROR', 'Visszaigazolt jelszó hibás');





define('_PLUG_PAY_INTERSEC_TITLE', 'InternetSecure');
define('_PLUG_PAY_INTERSEC_DESC', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_INTERSEC_ERROR', 'Hibás beküldés. Lépj kapcsolatba az adminisztrátorral');





define('_PLUG_PAY_IPAYMENT_TITLE', 'IPayment.DE');
define('_PLUG_PAY_IPAYMENT_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_LINKPOINT_TITLE', 'LinkPoint');
define('_PLUG_PAY_LINKPOINT_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_MANCC_FERROR', 'E mûvelet kezdeményezésére nem rendelkezel elegendõ joggal');
define('_PLUG_PAY_MANCC_FERROR2', 'Fizetési rendszer azonosítószám nincs meghatározva');
define('_PLUG_PAY_MANCC_FERROR3', 'Nem töltõdnek a tag adatai #%d (%d)');
define('_PLUG_PAY_MANCC_ERROR', 'Érvénytelen Hitelkártyaszám');
define('_PLUG_PAY_MANCC_ERROR2', 'Érvénytelen lejárati dátum - hónap');
define('_PLUG_PAY_MANCC_ERROR3', 'Érvénytelen lejárati dátum - év');
define('_PLUG_PAY_MANCC_ERROR4', 'Beírandó: Utca');
define('_PLUG_PAY_MANCC_ERROR5', 'Beírandó: Település');
define('_PLUG_PAY_MANCC_ERROR6', 'Kiválasztandó: állam vagy megye');
define('_PLUG_PAY_MANCC_ERROR7', 'Beírandó: Irányítószám');
define('_PLUG_PAY_MANCC_ERROR8', 'Kiválasztandó: Ország');
define('_PLUG_PAY_MANCC_ID', 'manual_cc');
define('_PLUG_PAY_MANCC_TITLE', 'Hitelkártya');
define('_PLUG_PAY_MANCC_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_LOGICCOM_TITLE', 'LogicCommerce');
define('_PLUG_PAY_LOGICCOM_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_MONEYBOOK_ERROR', 'MD5 hash kód hibás: a mi eredményünk %s, a kiszámolt: %s (a %s-ból)');
define('_PLUG_PAY_MONEYBOOK_ERROR2', 'moneybookers hiba: %s (Részletek: txn_id:%d, számla:%d)%s');
define('_PLUG_PAY_MONEYBOOK_ERROR3', 'Ez az oldal megjelenítése nem engedélyezett a böngészõben');
define('_PLUG_PAY_MONEYBOOK_ERROR4', 'Kifizetést fogadó ügyfél: %s az üzletem helyett: ');
define('_PLUG_PAY_MONEYBOOK_ERROR5', 'Fizetési mûvelet nincs lebonyolítva. Státusz: ');

define('_PLUG_PAY_MONEYBOOK_TITLE', 'MoneyBookers');
define('_PLUG_PAY_MONEYBOOK_DESC', 'Lásd %swww.moneybookers.com%s a leírásért');





define('_PLUG_PAY_MULTICARD_ERROR', 'multicards hiba: %s (Részletek: PNREF:%s, számla:%d)%s');
define('_PLUG_PAY_MULTICARD_ERROR2', 'Hiba a fizetési mûvelet adatfeldolgozása alatt:');
define('_PLUG_PAY_MULTICARD_ERROR3', 'Menj vissza és próbákozz újra.');
define('_PLUG_PAY_MULTICARD_ERROR4', 'Fizetési mûvelet sikertelen');
define('_PLUG_PAY_MULTICARD_ERROR5', 'a visszaigazolt összeg vagy üresen hagyott vagy nulla');
define('_PLUG_PAY_MULTICARD_ERROR6', 'Hibás IP cím');
define('_PLUG_PAY_MULTICARD_ERROR7', 'Hibás kereskedelmi azonosítószám');

define('_PLUG_PAY_MULTICARD_TITLE', 'Multi-Cards');
define('_PLUG_PAY_MULTICARD_DESCR', 'Multi-Cards hitelkártya adatfeldolgozás');

define('_PLUG_PAY_MULTICARD_HTML_TITLE', 'MultiCards fizetõ rendszer oldala');
define('_PLUG_PAY_MULTICARD_HTML_CNAME', 'Név a kártyán');
define('_PLUG_PAY_MULTICARD_HTML_4CONT', 'a kapcsolattartóhoz');
define('_PLUG_PAY_MULTICARD_HTML_EMAIL', 'Kapcsolattartó email');
define('_PLUG_PAY_MULTICARD_HTML_4CONTE', 'a kapcsolattartóhoz');
define('_PLUG_PAY_MULTICARD_HTML_CNAME', 'Név a kártyán');
define('_PLUG_PAY_MULTICARD_HTML_ASONCC', '%spontosan%s ahogy a hitelkártyán szerepel');
define('_PLUG_PAY_MULTICARD_HTML_ADDRESS', 'Cím');
define('_PLUG_PAY_MULTICARD_HTML_ADDOFCC', '%spontos%s cím, a hitelkártya szerinti');
define('_PLUG_PAY_MULTICARD_HTML_CITY', 'Település');
define('_PLUG_PAY_MULTICARD_HTML_EXCITY', '%spontos%s város és irányítószám, ami a hitelkártya%stulajdonos települése (kivételt képez az USA; pl. %sLondon E12 6HB%s)');
define('_PLUG_PAY_MULTICARD_HTML_COUNTRY', 'Ország');
define('_PLUG_PAY_MULTICARD_HTML_EXCOUNTRY', 'a hitelkártya tulajdonos országának %spontos%s megnevezése');
define('_PLUG_PAY_MULTICARD_HTML_STATE', 'Állam vagy megye');
define('_PLUG_PAY_MULTICARD_HTML_EXSTATE', 'a hitelkártya tulajdonos %spontos%s állam vagy megye megnevezése');
define('_PLUG_PAY_MULTICARD_HTML_ZIP', 'Irányítószám');
define('_PLUG_PAY_MULTICARD_HTML_EXZIP', '%spontos%s irányítószám, ahol a hitelkártya %stulajdonosa él az USA-ban ');
define('_PLUG_PAY_MULTICARD_HTML_IFNOTUSA', '(ha nem az USA-ban, írd be: %s99999%s)');
define('_PLUG_PAY_MULTICARD_HTML_SUB_BUT', 'Végrehajt');





define('_PLUG_PAY_NETBILLING_FERROR', 'Tagsági azonosító nem meghatározott');
define('_PLUG_PAY_NETBILLING_FERROR2', 'A jogosultságod nem terjed ki e mûvelet kezdeményezésére');
define('_PLUG_PAY_NETBILLING_FERROR3', 'Fizetés mûveleti azonosító nem meghatározott');
define('_PLUG_PAY_NETBILLING_FERROR4', 'Nem tölthetõk be a tagságod adatai #%d (%d)');
define('_PLUG_PAY_NETBILLING_ERROR', 'Érvénytelen Hitelkártyaszám');
define('_PLUG_PAY_NETBILLING_ERROR2', 'Érvénytelen Lejárati dátum - hónap');
define('_PLUG_PAY_NETBILLING_ERROR3', 'Érvénytelen Lejárati dátum - év');
define('_PLUG_PAY_NETBILLING_ERROR4', 'Beírandó: Hitelkártya kód');
define('_PLUG_PAY_NETBILLING_ERROR5', 'Beírandó: Utca');
define('_PLUG_PAY_NETBILLING_ERROR6', 'Beírandó: Település');
define('_PLUG_PAY_NETBILLING_ERROR7', 'Kiválasztandó: Állam vagy megye');
define('_PLUG_PAY_NETBILLING_ERROR8', 'Beírandó: Irányítószám');
define('_PLUG_PAY_NETBILLING_ERROR9', 'Kiválasztandó: Ország');

define('_PLUG_PAY_NETBILLING_TITLE', 'NetBilling');
define('_PLUG_PAY_NETBILLING_CC_PAYMENT', 'Hitelkártya fizetõ rendszer');

define('_PLUG_PAY_NETBILLING_FERROR5', 'Nincs felhasználónév konfigurálva a NetBilling-hez');
define('_PLUG_PAY_NETBILLING_PNOTFOUND', 'Fizetési mûvelet nem létezik: #%d');
define('_PLUG_PAY_NETBILLING_PCOMPLETED', 'Fizetési mûvelet lebonyolítva: #%d');
define('_PLUG_PAY_NETBILLING_ANOTHERPSYS', 'Fizetési mûvelet egy másik fizetõrendszerhez hozzárendelve:');
define('_PLUG_PAY_NETBILLING_ANOTHERMEMBER', 'Fizetési mûvelet egy másik tagsági személyhez #%d hozzárendelve');
define('_PLUG_PAY_NETBILLING_MEMNOTFOUND', 'Nem található tagsági személy: #%d');
define('_PLUG_PAY_NETBILLING_EMPTYRES', 'aMember: mûveleti egység eredmémye nem értelmezhetõ, fizetési mûvelet végrehajtása sikertelen');





define('_PLUG_PAY_NOCHEX_FERROR', 'nochex hiba: %s (Részletek: txn_id:%d, számla:%d)%s');
define('_PLUG_PAY_NOCHEX_ERROR', 'IPN oldal kizárólag a nochex rendszer által kezelt felület, felhasználók nem jogosultak a kezelésére');
define('_PLUG_PAY_NOCHEX_ERROR2', 'Kifizetést fogadó ügyfél: %s az üzletem helyett:');
define('_PLUG_PAY_NOCHEX_ERROR3', 'Nochex szerver válasz ELUTASITVA! Erõszakos beavatkozási kísérlet gyanuja (%s)');
define('_PLUG_PAY_NOCHEX_ERROR4', 'A válasz nem tartalmaz hitelesített vagy érvenytelen parancssort (%s)');

define('_PLUG_PAY_NOCHEX_TITLE', 'NoChex');
define('_PLUG_PAY_NOCHEX_DESC', 'Biztonságos hitelkártya fizetõ rendszer');





define('_PLUG_PAY_OFFLINE_TITLE', 'Offline fizetõ rendszer');
define('_PLUG_PAY_OFFLINE_DESC', 'Offline fizetõ rendszer');

define('_PLUG_PAY_OFFLINE_HTML_HEAD', 'Módosítsd ezt a fájlt');
define('_PLUG_PAY_OFFLINE_HTML_HEAD2', 'offline fizetési módszer, azaz hitelkártya mentes fizetés teljesítése');
define('_PLUG_PAY_OFFLINE_HTML_PUSR', 'Fizetési mûvelet#/felhasználónév: ');
define('_PLUG_PAY_OFFLINE_HTML_PRICE', 'Ár:     ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT1', 'Add meg a leírást a fizetés lebonyolítására vonatkozólag.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT2', 'Gyõzödj meg, hogy az elõfizetõ a következõket megadja: felhasználónév és fizetési mûvelet száma');
define('_PLUG_PAY_OFFLINE_HTML_TEXT3', 'a fizetési mûvelet leírashoz. Ily módon az azonosítás egyszeruvé és egyértelmûvé tehetõ.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT4', 'rendelj késõbb.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT5', 'A fizetési mûvelet sikeresen lezárása után, adható meg a folyamat "Teljesített"-nek ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT6', 'az aMember vezérlõpultjában. A felhasználó emailben értesül a belépési információkról,');
define('_PLUG_PAY_OFFLINE_HTML_TEXT7', 'majd beléphet az oldalra.');





define('_PLUG_PAY_OGONE_TITLE', 'Ogone');
define('_PLUG_PAY_OGONE_DESC', 'biztonságos hitelkártya fizetõ rendszer');
define('_PLUG_PAY_OGONE_ERROR', 'Ismeretlen STÁTUSZ kód: [%s]');
define('_PLUG_PAY_OGONE_ERROR2', 'a visszaigazolt összeg üresen hagyott vagy nullával egyenlo');





define('_PLUG_PAY_PSWDCALL_FERROR', 'passwordcall hiba: %s (Részletek: txn_id:%d, számla:%d)%s');
define('_PLUG_PAY_PSWDCALL_ERROR', 'Téves webmester azonosító: %d');
define('_PLUG_PAY_PSWDCALL_TITLE', 'PasswordCall');
define('_PLUG_PAY_PSWDCALL_DESC', 'Lásd %swww.passwordcall.de%s a leírásért');





define('_PLUG_PAY_BLUEPAY_TITLE', 'BluePay');
define('_PLUG_PAY_BLUEPAY_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_PAYFLINK_FERROR', 'PAYFLOW Hiba: %s (Részletek: PNREF:%s, számla:%d)%s');
define('_PLUG_PAY_PAYFLINK_ERROR', 'a visszaigazolt összeg üresen hagyott vagy nullával egyenlo');

define('_PLUG_PAY_PAYFLINK_TITLE', 'PayFlow Link');
define('_PLUG_PAY_PAYFLINK_DESC', 'Lásd %swww.verisign.com%s a leírásért');





define('_PLUG_PAY_PAYFLPRO_TITLE', 'PayFlow Pro');
define('_PLUG_PAY_PAYFLPRO_DESC', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_PAYFLPRO_ERROR', 'PayFlow plugin konfigurációs hiba: fájl %s%s%s nem létezik');
define('_PLUG_PAY_PAYFLPRO_ERROR2', 'PayFlow plugin konfigurációs hiba: fájl %s%s%s nem végrehajtható. chmod utasítást adj a fájlnak 755-re');
define('_PLUG_PAY_PAYFLPRO_FERROR', 'A fizetõ rendszer programja nem hajtható végre');
define('_PLUG_PAY_PAYFLPRO_ERROR3', 'Hiba a pfpro program futtatásában, a visszatérési érték: %s');
define('_PLUG_PAY_PAYFLPRO_CCDECL', 'Kártya visszautasítva. Gyõzõdj meg róla, hogy a beírt cím azonos a hitelkártyaszámlán szereplõ címmel');





define('_PLUG_PAY_PYMGTWAY_TITLE', 'PaymentsGateway');
define('_PLUG_PAY_PYMGTWAY_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_EGSPAY_TITLE', 'AC Pay');
define('_PLUG_PAY_EGSPAY_DESC', 'Lásd <a href="http://www.egspay.com" target=_blank>www.egspay.com</a> leírásért');
define('_PLUG_PAY_EGSPAY_ERROR', 'egspay hiba: %s (Részletek: számla:%d)%s');





define('_PLUG_PAY_PAYPALR_INVEMAIL', 'Érvénytelen email: $email, átugorva');
define('_PLUG_PAY_PAYPALR_IDEMPTY', 'Elõfizetõi azonosítószám üres a %s -hez');
define('_PLUG_PAY_PAYPALR_NOPAYMENTS', 'Fizetés mûveleti sor nem található a következõre:');
define('_PLUG_PAY_PAYPALR_2MUCHREC', 'A javasoltnál több (>1) fizetés mûveleti sor található a következõre:');

define('_PLUG_PAY_PAYPALR_TITLE', 'PayPal');
define('_PLUG_PAY_PAYPALR_DESC', 'biztonságos hitelkártya fizetõ rendszer');
define('_PLUG_PAY_PAYPALR_FERROR', 'Idõtartam 1-5 év kell, hogy legyen');
define('_PLUG_PAY_PAYPALR_FERROR2', 'Idõtartam 1-24 hónap kell, hogy legyen');
define('_PLUG_PAY_PAYPALR_FERROR3', 'Idõtartam 1-52 hét kell, hogy legyen');
define('_PLUG_PAY_PAYPALR_FERROR4', 'Idõtartam 1-90 nap kell, hogy legyen');
define('_PLUG_PAY_PAYPALR_FERROR5', 'Ismeretlen idõtartam egység: %s');
define('_PLUG_PAY_PAYPALR_FERROR6', 'Lejárat napját meghatározó érték hibás: ');
define('_PLUG_PAY_PAYPALR_FERROR7', 'Egy felújuló és egyszeri termék rendelésének megbízása nem kezdeményezhetõ együttesen. Rendeld meg az elsõ terméket, késõbb a tagságnak fentartott oldalakon megrendelheted a másik termékeket');
define('_PLUG_PAY_PAYPALR_FERROR8', 'Az alábbi termékek együttesen nem rendelhetõek meg. Rendeld meg az elsõ terméket, késõbb a tagságnak fentartott oldalakon megrendelheted a másik terméket.');
define('_PLUG_PAY_PAYPALR_FERROR9', 'Különbözõ fizetõnemben megadott termékeket választottál. Ez a megrendelés így nem teljesithetõ - válassz más termékeket');
define('_PLUG_PAY_PAYPALR_ERROR', 'Nem megerõsített PayPal IPN válasz: FOPEN [%s] eredménye: [%s (%s)]');
define('_PLUG_PAY_PAYPALR_ERROR2', 'Paypal által érvénytelennek ítélt IPN tranzakció: [%s]');
define('_PLUG_PAY_PAYPALR_ERROR3', 'IPN érvényesítése révén adódó hiba: %s');
define('_PLUG_PAY_PAYPALR_ERROR4', 'Fizetési mûvelet email címe [{%s}] ismeretlen, ennek következtében a folyamat elutasítva.<br />');
define('_PLUG_PAY_PAYPALR_ERROR5', 'Ha nem értesz egyet, add meg az email címet {%s} az aMember vezérlõpultban -> Setup (Beállítások) -> PayPal');
define('_PLUG_PAY_PAYPALR_ERROR6', 'Paypal fizetés mûveleti státusz: [%s], IPN üzenet elutasítva <br />');
define('_PLUG_PAY_PAYPALR_ERROR7', 'Ez nem egy hiba üzenet, csak egy tájékoztató üzenet a státuszra vonatkozólag');
define('_PLUG_PAY_PAYPALR_ERROR8', 'Paypal fizetési mûvelet pénzneme: [%s] az elvártal szemben, ami: [%s]');
define('_PLUG_PAY_PAYPALR_ERROR9', 'az összeg: [%d], pedig ennyi kellene, hogy legyen: [%d]');
define('_PLUG_PAY_PAYPALR_ERROR11', 'Nem található megfelelõ aMember fizetés mûveleti sor ehhez a folyamathoz');
define('_PLUG_PAY_PAYPALR_ERROR12', 'Kuponok használata nem engedélyezett PayPal teszt elõfizetésekre, lépj kapcsolatba az adminisztrátorral');





define('_PLUG_PAY_PAYRDY_FERROR', 'A jogosultságod nem terjed ki e mûvelet kezdeményezésére');
define('_PLUG_PAY_PAYRDY_FERROR2', 'Fizetési mûvelet azonosító nincs meghatározva');
define('_PLUG_PAY_PAYRDY_FERROR3', 'Nem töltõdik be a tagság adatsora #%d (%d)');
define('_PLUG_PAY_PAYRDY_ERROR', 'Válassz hitelkártya típust');
define('_PLUG_PAY_PAYRDY_ERROR2', 'Érvénytelen Hitelkártyaszám');
define('_PLUG_PAY_PAYRDY_ERROR3', 'Érvénytelen Lejárati dátum - hónap');
define('_PLUG_PAY_PAYRDY_ERROR4', 'Érvénytelen Lejárati dátum - év');
define('_PLUG_PAY_PAYRDY_ERROR5', 'Beírandó: Utca');
define('_PLUG_PAY_PAYRDY_ERROR6', 'Beírandó: Település');
define('_PLUG_PAY_PAYRDY_ERROR7', 'Válassz államot vagy megyét');
define('_PLUG_PAY_PAYRDY_ERROR8', 'Beírandó: Irányítószám');
define('_PLUG_PAY_PAYRDY_ERROR9', 'Válassz országot');

define('_PLUG_PAY_PAYRDY_ERROR10', 'Fizetési mûvelet nem található: #%d');
define('_PLUG_PAY_PAYRDY_ERROR11', 'Fizetési mûvelet lebonyolítva: #%d');
define('_PLUG_PAY_PAYRDY_ERROR12', 'Fizetési mûvelet egy másik fizetõ rendszerhez hozzárendelve: ');
define('_PLUG_PAY_PAYRDY_ERROR13', 'aMember: Üresen hagyott visszajelzés a processzortól, fizetmény kezelése sikertelen');
define('_PLUG_PAY_PAYRDY_ERROR14', 'Fizetést végrehajtó mûveleti egység hiba: ');

define('_PLUG_PAY_PAYRDY_TITLE', 'PayReady');
define('_PLUG_PAY_PAYRDY_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_PAYZIP_TITLE', 'PayZIP');
define('_PLUG_PAY_PAYZIP_DESC', 'biztonságos hitelkártya fizetõ rendszer');
define('_PLUG_PAY_PAYZIP_ERROR', 'Hibás kapcsolat');
define('_PLUG_PAY_PAYZIP_FERROR', 'Nincs válasz a PayZIP-tõl - tranzakció megszakítva Próbálkozz késõbb.');





define('_PLUG_PAY_PLUGNPAY_FERROR', 'Tagsági azonosítószám nem meghatározott');
define('_PLUG_PAY_PLUGNPAY_FERROR2', 'A jogosultságod nem terjed ki e mûvelet kezdeményezésére');
define('_PLUG_PAY_PLUGNPAY_FERROR3', 'Fizetési mûvelet azonosító szám nem meghatározott');
define('_PLUG_PAY_PLUGNPAY_FERROR4', 'Tagsági adatsor betöltése sikertelen #%d (%d)');
define('_PLUG_PAY_PLUGNPAY_ERROR', 'Nincs visszatérési érték a plugnpay rendszertõl, Fizetési mûvelet #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR2', 'Érvénytelen lejárat dátum - hónap');
define('_PLUG_PAY_PLUGNPAY_ERROR3', 'Érvénytelen lejárat dátum - év');
define('_PLUG_PAY_PLUGNPAY_ERROR4', 'Beírandó: Hitelkártya kód');
define('_PLUG_PAY_PLUGNPAY_ERROR5', 'Beírandó: Utca');
define('_PLUG_PAY_PLUGNPAY_ERROR6', 'Beírandó: Település');
define('_PLUG_PAY_PLUGNPAY_ERROR7', 'Válassz államot vagy megyét');
define('_PLUG_PAY_PLUGNPAY_ERROR8', 'Beírandó: Irányítószám');
define('_PLUG_PAY_PLUGNPAY_ERROR9', 'Válassz országot');
define('_PLUG_PAY_PLUGNPAY_ERROR10', 'Fizetési mûvelet nem található: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR11', 'Fizetési mûvelet lebonyolítva: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR12', 'Fizetési mûvelet egy másik fizetõrendszerhez hozzárendelve');
define('_PLUG_PAY_PLUGNPAY_ERROR13', 'Tagsági személy nem található: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR14', 'Visszatérési érték nem értelmezhetõ, fizetési mûvelet kezelése sikertelen #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR15', 'aMember: Visszatérési érték a mûveleti egység által nem értelmezhetõ, fizetési mûvelet kezelése sikertelen');

define('_PLUG_PAY_PLUGNPAY_TITLE', 'PlugNPay');
define('_PLUG_PAY_PLUGNPAY_DESC', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_PLUGNPAY_ERROR', 'Nincs visszatérési érték a plugnpay rendszertõl, Fizetési mûvelet #%d');





define('_PLUG_PAY_PROBILLING_FERROR', 'PROBILLING hiba: %s (Részletek: PNREF:%s, számla:%d)<br />');
define('_PLUG_PAY_PROBILLING_ERROR', 'A státusz nem ÚJ vagy FIZETETT');
define('_PLUG_PAY_PROBILLING_TITLE', 'ProBilling');
define('_PLUG_PAY_PROBILLING_DESC', 'Hitelkártyas, elektronikus csekkeket fogad el, és 900-as számlázást is támogat');





define('_PLUG_PAY_PROTX_TITLE', 'Protx');
define('_PLUG_PAY_PROTX_DESC', 'Hitelkártyával/Terhelési kártyával fizethetsz - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');

define('_PLUG_PAY_PROTX_HTML_TITLE', 'Folytatás a biztonságos fizetõ rendszer oldalán');





define('_PLUG_PAY_PSIGATE_TITLE', 'PsiGate');
define('_PLUG_PAY_PSIGATE_DESC', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_PSIGATE_ERROR', 'Belsõ Hiba');

define('_PLUG_PAY_PSIGATE_HTML_TITLE', 'Hitelkártya fizetõ rendszer oldala');
define('_PLUG_PAY_PSIGATE_HTML_CNAME', 'Név a kártyán');
define('_PLUG_PAY_PSIGATE_HTML_ASONCC', '%spontosan%s ahogy a Hitelkártyán');
define('_PLUG_PAY_PSIGATE_HTML_CCNUM', 'Hitelkártyaszám');
define('_PLUG_PAY_PSIGATE_HTML_CCEXP', 'Hitelkártya lejárata');
define('_PLUG_PAY_PSIGATE_HTML_JAN', 'Január');
define('_PLUG_PAY_PSIGATE_HTML_FEB', 'Február');
define('_PLUG_PAY_PSIGATE_HTML_MAR', 'Március');
define('_PLUG_PAY_PSIGATE_HTML_APR', 'Április');
define('_PLUG_PAY_PSIGATE_HTML_MAY', 'Május');
define('_PLUG_PAY_PSIGATE_HTML_JUN', 'Június');
define('_PLUG_PAY_PSIGATE_HTML_JUL', 'Július');
define('_PLUG_PAY_PSIGATE_HTML_AUG', 'Augusztus');
define('_PLUG_PAY_PSIGATE_HTML_SEP', 'Szeptember');
define('_PLUG_PAY_PSIGATE_HTML_OCT', 'Október');
define('_PLUG_PAY_PSIGATE_HTML_NOV', 'November');
define('_PLUG_PAY_PSIGATE_HTML_DEC', 'December');
define('_PLUG_PAY_PSIGATE_HTML_ADDR', 'Cím');
define('_PLUG_PAY_PSIGATE_HTML_ADOFCC', '%spontos%s Cím a hitelkártyán');
define('_PLUG_PAY_PSIGATE_HTML_CITY', 'Település');
define('_PLUG_PAY_PSIGATE_HTML_CTOFCC', 'a hitelkártya tulajdonos településének %spontos%s megnevezése');
define('_PLUG_PAY_PSIGATE_HTML_COUNTRY', 'Ország');
define('_PLUG_PAY_PSIGATE_HTML_CNOFCC', 'a hitelkártya tulajdonos országának %spontos%s megnevezése');
define('_PLUG_PAY_PSIGATE_HTML_STATE', 'állam vagy megye');
define('_PLUG_PAY_PSIGATE_HTML_STOFCC', 'a hitelkártya tulajdonos %spontos%s állam vagy megye megnevezése');
define('_PLUG_PAY_PSIGATE_HTML_ZIP', 'Irányítószám');
define('_PLUG_PAY_PSIGATE_HTML_SUBBUT', 'Végrehajt');
define('_PLUG_PAY_PSIGATE_HTML_DESCR', 'ezek az adatok biztonsági szerverre lesznek továbbítva');





define('_PLUG_PAY_QCHEX_TITLE', 'QChex');
define('_PLUG_PAY_QCHEX_DESC', 'Fizess csekkel (lásd %swww.qchex.com%s leírásért)');





define('_PLUG_PAY_SECURTRD_FERROR', 'securetrading hiba: %s (Részletek: txn_id:%d, számla:%d)%s');
define('_PLUG_PAY_SECURTRD_TITLE', 'SecureTrading');
define('_PLUG_PAY_SECURTRD_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_STORMPAY_FERROR', 'StormPay hiba: %s (Részletek: txn_id:%d, számla:%d)%s');
define('_PLUG_PAY_STORMPAY_ERROR', 'Hibás titkos kód: %s');
define('_PLUG_PAY_STORMPAY_ERROR2', 'Kifizetést fogadó ügyfél: %s az üzletem helyett:');
define('_PLUG_PAY_STORMPAY_ERROR3', 'Fizetési mûvelet sikertelen! Státusz: %s');

define('_PLUG_PAY_STORMPAY_TITLE', 'StormPay');
define('_PLUG_PAY_STORMPAY_DESC', 'Lásd %swww.stormpay.com%s leírásért');





define('_PLUG_PAY_INETCOM_FERROR', 'Tagsági azonosító szám nem meghatározott');
define('_PLUG_PAY_INETCOM_FERROR2', 'A jogosultságod nem terjed ki e mûvelet kezdeményezésére');
define('_PLUG_PAY_INETCOM_FERROR3', 'Fizetési mûvelet azonosító szám nem meghatározott');
define('_PLUG_PAY_INETCOM_FERROR4', 'A tagsági adatsor betöltése sikertelen #%d (%d)');
define('_PLUG_PAY_INETCOM_ERROR', 'Érvénytelen Hitelkártyaszám');
define('_PLUG_PAY_INETCOM_ERROR2', 'Érvénytelen Lejárati dátum - hónap');
define('_PLUG_PAY_INETCOM_ERROR3', 'Érvénytelen Lejárati dátum - év');
define('_PLUG_PAY_INETCOM_ERROR4', 'Beírandó: Hitelkártya kód');
define('_PLUG_PAY_INETCOM_ERROR5', 'Beírandó: Utca');
define('_PLUG_PAY_INETCOM_ERROR6', 'Beírandó: Település');
define('_PLUG_PAY_INETCOM_ERROR7', 'Válassz államot vagy megyét');
define('_PLUG_PAY_INETCOM_ERROR8', 'Beírandó: Irányítószám');
define('_PLUG_PAY_INETCOM_ERROR9', 'Válassz országot');
define('_PLUG_PAY_INETCOM_ERROR10', 'Fizetési mûvelet nem található: #%d');
define('_PLUG_PAY_INETCOM_ERROR11', 'Fizetési mûvelet lebonyolítva: #%d');
define('_PLUG_PAY_INETCOM_ERROR12', 'Fizetési mûvelet egy másik fizetõrendszerhez hozzárendelve: %s (#%d)');
define('_PLUG_PAY_INETCOM_ERROR13', 'Tag nem található: #%d');

define('_PLUG_PAY_INETCOM_TITLE', 'TheInternetCommerce');
define('_PLUG_PAY_INETCOM_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_24eKOUT_TITLE', '2Checkout');
define('_PLUG_PAY_24eKOUT_DESC', 'vásárlás 2Checkout-tól');
define('_PLUG_PAY_24eKOUT_ERROR', 'Demó mód indításának kezdeményezése, az érvényesítéstõl függetlenül');
define('_PLUG_PAY_24eKOUT_ERROR2', 'Hitelkártya érvényesítési mûvelete sikertelen');
define('_PLUG_PAY_24eKOUT_ERROR3', 'Hitelkártya érvényesítési mûvelete sikertelen. Kérlek, lépj kapcsolatba a webmesterrel');





define('_PLUG_PAY_WORLDPAY_FERROR', 'WORLDPAY Hiba: %s (Részletek: PNREF:%s, számla:%d)%s');
define('_PLUG_PAY_WORLDPAY_ERROR', 'Hibás IP cím a WorldPay adat beterjesztéshez');
define('_PLUG_PAY_WORLDPAY_ERROR2', 'Tranzakció elutasítva (%s)');
define('_PLUG_PAY_WORLDPAY_ERROR3', 'Teszt mód érvénytelenítve');
define('_PLUG_PAY_WORLDPAY_ERROR4', 'Hibás telepítési azonosító: ez a fizetési mûvelet nem ide tartozik');
define('_PLUG_PAY_WORLDPAY_ERROR5', 'a visszaigazolt összeg üresen hagyott vagy nulla');
define('_PLUG_PAY_WORLDPAY_ERROR6', 'Fizetési mûvelet sikeresen végrehajtódott (worldpay számla#: %d) Fizetési mûvelet #%d');

define('_PLUG_PAY_WORLDPAY_TITLE', 'WorldPay');
define('_PLUG_PAY_WORLDPAY_DESC', 'Fizess Hitelkártyával/Terheléses számlával - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');
define('_PLUG_PAY_WORLDPAY_FERROR2', 'Ismeretlen egység a lejárat megadására. A következõk elfogadottak: d|m|w|y (nap|hónap|hét|év)');
define('_PLUG_PAY_WORLDPAY_FERROR3', 'Hibás érték $s: %s');
define('_PLUG_PAY_WORLDPAY_FERROR4', 'Hibás érték %s a következõ termékszámnál');





define('_PLUG_PAY_VEROTEL_FERROR', 'VEROTEL hiba: %s (Részletek: számla:%d)%s');

define('_PLUG_PAY_VEROTEL_TITLE', 'VeroTel');
define('_PLUG_PAY_VEROTEL_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_PAYPALPRO_TITLE', 'Fizess PayPal-al');
define('_PLUG_PAY_PAYPALPRO_DESC', 'Gyors, biztonságos pénztár a PayPal-nál.<br />Takarítsd meg idõt. Fizess biztonságos módon. Fizess anélkül, hogy<br />információdat mások is láthatnák.');
define('_PLUG_PAY_PAYPALPRO_FERROR', 'Különbözõ pénznemben kiválasztott termékek kifizetése nem teljesíthetõ. Válassz újra termékeket');
define('_PLUG_PAY_PAYPALPRO_FERROR2', 'Belsõ végrehajtási hiba (get_caller): ');
define('_PLUG_PAY_PAYPALPRO_FERROR3', 'Üresen visszaigazolt token');
define('_PLUG_PAY_PAYPALPRO_REDIRECT', 'Átirányítunk a PayPal web oldalára');
define('_PLUG_PAY_PAYPALPRO_REDIRECT2', 'Átirányítás a PayPal weboldalára, ahol fizetés kezdeményezhetõ');
define('_PLUG_PAY_PAYPALPRO_FERROR4', 'Belsõ végrehajtási hiba : ');
define('_PLUG_PAY_PAYPALPRO_FERROR5', 'Belsõ hiba: ');
define('_PLUG_PAY_PAYPALPRO_FERROR6', 'Fizetés mûveleti státusz: befejezetlen. Lépj kapcsolatba a honlap ügyfélszolgálatával');
define('_PLUG_PAY_PAYPALPRO_FERROR7', 'Kérjük, %skövesd újra a regisztrációs lépéseket%s');
define('_PLUG_PAY_PAYPALPRO_ERROR', 'Üresen visszaadott token');
define('_PLUG_PAY_PAYPALPRO_ERROR2', 'Fizetési mûvelet #%d nem található');
define('_PLUG_PAY_PAYPALPRO_FERROR8', 'Üres txn_id visszaigazolás');
define('_PLUG_PAY_PAYPALPRO_TITLE2', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_PAYPALPRO_DESC2', 'Válassz hitelkártyát a következõk közül: Visa, MC, Discover vagy Amex');

define('_PLUG_PAY_PAYPALPRO_HTML_TITLE', 'Erõsítsd meg a fizetési mûveletet');
define('_PLUG_PAY_PAYPALPRO_HTML_SPTITLE', 'Elõfizetés/Termék megnevezés');
define('_PLUG_PAY_PAYPALPRO_HTML_PRICE', 'Ár');
define('_PLUG_PAY_PAYPALPRO_HTML_SUBTOTAL', 'Összeg');
define('_PLUG_PAY_PAYPALPRO_HTML_CPDSC', 'Kupon kedvezmény');
define('_PLUG_PAY_PAYPALPRO_HTML_TAXAM', 'Adó');
define('_PLUG_PAY_PAYPALPRO_HTML_TOTAL', 'Totál');
define('_PLUG_PAY_PAYPALPRO_HTML_SBBUT', 'Erõsítsd meg a fizetési mûveletet');





define('_PLUG_PAY_FIRSTPAY_TITLE', 'FirstPay.Net');
define('_PLUG_PAY_FIRSTPAY_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_MERCANYW_TITLE', 'MerchantAnyWhere');
define('_PLUG_PAY_MERCANYW_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_SECPAY_TITLE', 'SecPay');
define('_PLUG_PAY_SECPAY_DESC', 'Hitelkártya fizetõ rendszer');
define('_PLUG_PAY_SECPAY_ERROR', 'Konsztruktor hiba: %s');
define('_PLUG_PAY_SECPAY_ERROR2', 'SOAP hívas hiba: ');
define('_PLUG_PAY_SECPAY_ERROR3', 'SOAP hiba: %s');





define('_PLUG_PAY_PROTXDIR_TITLE', 'Protx');
define('_PLUG_PAY_PROTXDIR_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_SAFEPAY_TITLE', 'SafePay');
define('_PLUG_PAY_SAFEPAY_DESC', 'Lásd %swww.safepaysolutions.com%s leírásért');
define('_PLUG_PAY_SAFEPAY_ERROR', 'titkos ellenõrzõ szöveg hiba');
define('_PLUG_PAY_SAFEPAY_ERROR2', 'Összeg hiba (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR3', 'Termék mennyiség hiba (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR4', 'Tranzakció azonosító hiba (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR5', 'Tranzakció nem igazolt, nincs pénz az SPS számládon');
define('_PLUG_PAY_SAFEPAY_ERROR6', 'Eredmény kód %s: Fizetési mûvelet hiba');





define('_PLUG_PAY_SECUREPAY_TITLE', 'SecurePay');
define('_PLUG_PAY_SECUREPAY_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_GOOGLE_CHECKOUT_TITLE', 'Google Checkout');
define('_PLUG_PAY_GOOGLE_CHECKOUT_DESC', 'Hitelkártya fizetõ rendszer');





define('_PLUG_PAY_MANUAL_TITLE', 'Manuális fizetõ rendszer');





define('_PLUG_PAY_ALERTPAY_TITLE', 'AlertPay');
define('_PLUG_PAY_ALERTPAY_DESC', 'Fizess hitelkártyával');
define('_PLUG_PAY_ALERTPAY_FERROR2', 'Ismeretlen egység a lejárat megadására. A következõk elfogadottak: d|m|w|y (nap|hónap|hét|év)');
define('_PLUG_PAY_ALERTPAY_FERROR3', 'Hibás érték $s: %s');
define('_PLUG_PAY_ALERTPAY_FERROR4', 'Hibás érték %s a követkeõ termékszámnál:');
define('_PLUG_PAY_ALERTPAY_ERROR', 'Hibás titkos kód');
define('_PLUG_PAY_ALERTPAY_FERROR', 'ALERTPAY Hiba: %s (Részletek: PNREF:%s, számla:%d)%s');
define('_PLUG_PAY_ALERTPAY_ERROR2', 'Tranzakció elutasítva (%s)');
define('_PLUG_PAY_ALERTPAY_ERROR3', 'Tesztmód érvénytelenítve');
define('_PLUG_PAY_ALERTPAY_ERROR4', 'Hibás kereskedõi számla: Ez a fizetési mûvelet nem ide tartozik');
define('_PLUG_PAY_ALERTPAY_ERROR5', 'a visszaigazolt összeg üresen hagyott vagy nulla');
define('_PLUG_PAY_ALERTPAY_ERROR6', 'Fizetési mûvelet sikeresen befejezõdött (alertpay számla#: %d) Fizetési mûvelet #%d');







define('_PLUG_PAY_METACHARGE_TITLE', 'Metacharge');
define('_PLUG_PAY_METACHARGE_DESC', 'Fizess hitelkártyával/terheléses kártyával - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');

define('_PLUG_PAY_METACHARGE_FERROR', 'METACHARGE Hiba: %s (Részletek: PNREF:%s, számla:%d)%s');

define('_PLUG_PAY_METACHARGE_ERROR2', 'Tranzakció elutasítva (%s)');
define('_PLUG_PAY_METACHARGE_ERROR3', 'Tesztmód érvénytelenítve');
define('_PLUG_PAY_METACHARGE_ERROR4', 'Hibás telepítõ azonosító: nem idetartozó fizetési mûvelet');
define('_PLUG_PAY_METACHARGE_ERROR5', 'a visszaigazolt összeg üresen hagyott vagy nulla');
define('_PLUG_PAY_METACHARGE_ERROR6', 'Sikeres fizetési mûvelet (metacharge számla#: %d) Fizetési mûvelet #%d');

define('_PLUG_PAY_METACHARGE_FERROR2', 'Ismeretlen egység a lejárat megadására. A következõk elfogadottak: d|m|w|y (nap|hónap|hét|év)');
define('_PLUG_PAY_METACHARGE_FERROR3', 'Hibás érték $s: %s');
define('_PLUG_PAY_METACHARGE_HTML_SUB_BUT', 'Kattints ide, ha a böngészõd nem irányított át automatikusan');
define('_PLUG_PAY_METACHARGE_HTML_TITLE', 'Metacharge fizetési mûvelet');













//missed rows
define ('_TPL_EMAIL_VER_TITLE_PROFILE', 'Email verification required');
define ('_TPL_EMAIL_VER_TEXT_PROFILE', 'Please check your email - verification email message has been just emailed to you. Once you receive this message, read it and follow instructions in this email to complete your email verification.');
define ('_TPL_MEMBER_MAIN_PAGE', 'Main Page');
define ('_TPL_PROFILE_EMAIL_NOT_VERIFIED', 'Email address is not verified!');
define ('_TPL_PROFILE_EMAIL_RESEND_VERIFICATION_EMAIL', 'Resend verification email');
define ('_TPL_NEWSLETTER_ARCHIVE_DATE', 'Date');
define ('_TPL_NEWSLETTER_ARCHIVE_SUBJECT', 'Subject');
define ('_TPL_NEWSLETTER_ARCHIVE_NO_ARCHIVE', 'You have no archive messages');
define('_PLUG_PAY_AUTHORIZE_CIM_TITLE', 'Authorize CIM');
define('_PLUG_PAY_AUTHORIZE_CIM_DESC', 'Credit card payment');
define('_TPL_SKYPAY_ADDRESS_TITLE', 'Billing address');
define('_TPL_SKYPAY_ADDRESS_CHOOSE', '*** Please choose ***');
define('_TPL_SKYPAY_ADDRESS_HOLDERNAME', 'Cardholder Name');
define('_TPL_SKYPAY_ADDRESS_ASONCARD', 'cardholder name, exactly as on the card');
define('_TPL_SKYPAY_ADDRESS_FLNAME', 'cardholder first and last name, exactly as%son the card');
define('_TPL_SKYPAY_ADDRESS_ADDRINFO', 'Please specify your billing address details');
define('_TPL_SKYPAY_ADDRESS_STRADDR', 'Address');
define('_TPL_SKYPAY_ADDRESS_STRADDR2', 'Address (2)');
define('_TPL_SKYPAY_ADDRESS_CITY', 'City');
define('_TPL_SKYPAY_ADDRESS_ZIP', 'Postal code / Zip code');
define('_TPL_SKYPAY_ADDRESS_COUNTRY', 'Country');
define('_TPL_SKYPAY_ADDRESS_PHONE', 'Phone');
define('_TPL_SKYPAY_ADDRESS_MUSTMATCH', '(must match your credit card statement delivery address)');
define('_TPL_SKYPAY_ADDRESS_BACK_BUT', 'Back');
define('_TPL_SKYPAY_ADDRESS_SUBMIT_BUT', 'Continue');
define('_TPL_SKYPAY_ADDRESS_SUBMIT_BUT_3', 'Subscribe and Pay');
define('_TPL_SKYPAY_PAY_TITLE', 'Confirm payment details');
define('_TPL_SKYPAY_PAY_SUBMIT', 'Continue to the Skypay Payment page');
define('_TPL_SKYPAY_ADDRESS_BILLING', 'Billing address details:');
define('_TPL_SKYPAY_PRODUCT_BILLING', 'Product details:');
define('_PLUG_PAY_SKYPAY_FERROR1', 'skypay ERROR: %s (Details: txn_id:%d, invoice:%d)%s');
define('_PLUG_PAY_SKYPAY_FERROR2', 'You are not logged in.');
define('_PLUG_PAY_SKYPAY_FERROR3', 'It seems to be not your payment, please go back and try again.');
define('_PLUG_PAY_SKYPAY_TITLE', 'Skypay');
define('_PLUG_PAY_SKYPAY_DESC', 'Pay by credit card/debit card');
define ('_TPL_SKYPAY_CANCEL_TITLE', 'Payment Cancelled');
define ('_TPL_SKYPAY_CANCEL_ERROR', 'Your payment has been cancelled.');
define ('_TPL_SKYPAY_CANCEL_GOTO', 'To see your subscription details please go to %sMembership page%s.');
?>