<?php
/**
 * se.php
 * Swedish Lanuage file
 * @author   Alex Scott <alex@cgi-central.net>
 * @package  aMember_Core
 * @translated by Peter Gustafsson - peter@infocanarias.nu
 * @version  $Id: se.php 5320 2010-09-15 06:04:44Z barfly $
 * @license  http://www.amember.com/p/Main/License
 * @copyright Copyright &copy; 2006, Alex Scott
 * DO NOT EDIT THIS FILE FOR CUSTOMIZATION, READ readme.txt for details
 */

defined( 'INCLUDED_AMEMBER_CONFIG' ) or die( 'Direkt access är inte tillåtet' );

define ('_TPL_POWEREDBY', 'Utvecklat av %saMember Pro%s medlemsskapsprogram');

define('_TPL_INDEX_IF_YOU_ARE_REGISTERED', 'Om du är registrerad medlem, vänligen %sLogga In%s');
define('_TPL_INDEX_IF_YOU_ARE_NOT_REGISTERED', 'Om du inte är registrerad medlem, vänligen %sRegistrera Dig%s');
define('_TPL_LOGIN_PLEASE_LOGIN', 'Vänligen Logga In');
define('_TPL_LOGIN_USERNAME', 'Användarnamn');
define('_TPL_LOGIN_PASSWORD', 'Lösenord');
define('_TPL_LOGIN_REMEMBER_MY_PASSWORD', 'Kom ihåg mitt lösenord?');
define('_TPL_LOGIN_NOT_REGISTERED_YET', 'Inte registrerad ännu?');
define('_TPL_LOGIN_SIGNUP_HERE', 'Registrera dig här');
define('_TPL_LOGIN_LOST_PASSWORD', 'Glömt Lösenordet?');
define('_TPL_LOGIN_ENTER_YOUR_EMAIL_OR_USERNAME', 'Skriv din <b>E-Post Adress</b> eller ditt<b>Användarnamn</b>');
define('_TPL_LOGIN_BTN_LOGIN', 'Logga In');
define('_TPL_LOGIN_BTN_BACK', 'Tillbaka');
define('_TPL_LOGIN_BTN_GET_PASSWORD', 'Skicka Lösenordet');

define ('_TPL_SIGNUP_MEM_TYPE', 'Välj typ av medlemsskap');
define ('_TPL_SIGNUP_TITLE', 'Registrera');
define ('_TPL_AFF_SIGNUP_TITLE', 'Registrering Återförsäljare');
define ('_TPL_SIGNUP_MEMB_TYPE', 'Typ av medlemsskap');
define ('_TPL_SIGNUP_FREE', 'gratis');
define ('_TPL_SIGNUP_SELECT_PSYS', 'Välj betalningsmetod');
define ('_TPL_SIGNUP_PAYSYS', 'Betalningsmetod');
define ('_TPL_SIGNUP_NAME', 'Ditt Namn');
define ('_TPL_SIGNUP_NAME_1', 'Ditt Förnamn &amp; Efternamn');
define ('_TPL_SIGNUP_EMAIL', 'Din E-Post adress');
define ('_TPL_SIGNUP_EMAIL_1', 'Ett konfirmerings meddelande kommer att skickas');
define ('_TPL_SIGNUP_EMAIL_2', 'till dig på denna E-Post adress');
define ('_TPL_SIGNUP_LOGIN', 'Välj Användarnamn (Användar ID)');
define ('_TPL_SIGNUP_LOGIN_1', 'Det måste bestå av %d tecken eller flera och kan ');
define ('_TPL_SIGNUP_LOGIN_2', 'endast innehålla små bokstäver, siffror, och');
define ('_TPL_SIGNUP_LOGIN_3', 'understräck \'_\'');
define ('_TPL_SIGNUP_CHECK_UNIQ', 'kontrollera unikhet');
define ('_TPL_SIGNUP_PSWD', 'Välj ett Lösenord');
define ('_TPL_SIGNUP_PSWD_1', 'Måste bestå av %d tecken eller flera');
define ('_TPL_SIGNUP_CONF_PSWD', 'Konfirmera ditt Lösenord');
define ('_TPL_SIGNUP_CONF_PSWD_1', 'Skriv Lösenord igen');
define ('_TPL_SIGNUP_NEWSLETTERS_SUBSCRIBE', 'Prenumerera på vårt Nyhetsbrev');
define ('_TPL_SIGNUP_NEWSLETTERS_SUBSCRIBE_1', '');
define ('_TPL_SIGNUP_ADDR', 'ADRESS INFO');
define ('_TPL_SIGNUP_STREET', 'Gata');
define ('_TPL_SIGNUP_CITY', 'Stad');
define ('_TPL_SIGNUP_STATE', 'Län');
define ('_TPL_SIGNUP_ZIP', 'Postnummer');
define ('_TPL_SIGNUP_COUNTRY', 'Land');
define ('_TPL_SIGNUP_COUPONS', 'Rabattkupong');
define ('_TPL_SIGNUP_COUPON_CODE', 'Skriv rabattkupongens kod');
define ('_TPL_SIGNUP_COUPON_1', 'om du fått någon rabattkupong genom annonsering,');
define ('_TPL_SIGNUP_COUPON_2', ' skriv då koden här');
define ('_TPL_SIGNUP_SUBMIT_CONTINUE', 'Fortsätt');

define ('_TPL_AFFILIATE_TITLE', 'Info Återförsäljare');
define ('_TPL_AFFILIATE_TXT_LINKS', 'Du kan använda följande textlänkar för att göra reklam för vår sida och samtidigt tjäna pengar:');
define ('_TPL_AFFILIATE_HTML_CODE', 'HTML kod:');
define ('_TPL_AFFILIATE_BANNERS', 'Du kan använda följande Banners för att göra reklam för vår sida och samtidigt tjäna pengar:');
define ('_TPL_AFFILIATE_BACK2_INFO', 'Tillbaka till Medlemssidan');

define ('_TPL_AFF_PAYOUT_TITLE', 'Ändra utbetalnings info');
define ('_TPL_AFF_PAYOUT_METHOD', 'UTBETALNINGSMETOD');
define ('_TPL_AFF_PAYOUT_NOT_SELECTED', 'Inte Vald');
define ('_TPL_AFF_PAYOUT_PP_EMAIL', 'Din PayPal E-Post adress');
define ('_TPL_AFF_PAYOUT_STORM_EMAIL', 'Din StormPay E-Post adress');
define ('_TPL_AFF_PAYOUT_IKOBO_EMAIL', 'Din iKobo E-Post adress');
define ('_TPL_AFF_PAYOUT_MBKRS_ID', 'Ditt MoneyBookers Konto ID');
define ('_TPL_AFF_PAYOUT_EGOLD_ACC', 'Ditt E-Gold konto#');
define ('_TPL_AFF_PAYOUT_CHECK_PTO', 'Check Betalbar Till');

define ('_TPL_AFF_PAYOUT_STREET', 'Gata');
define ('_TPL_AFF_PAYOUT_CITY', 'Stad');
define ('_TPL_AFF_PAYOUT_STATE', 'Län');
define ('_TPL_AFF_PAYOUT_ZIP', 'Postnummer');
define ('_TPL_AFF_PAYOUT_COUNTRY', 'Land');
define ('_TPL_AFF_PAYOUT_SAVE_BUT', 'Spara');
define ('_TPL_AFF_PAYOUT_BACK_BUT', 'Tillbaka');

define ('_TPL_AFF_STATS_TITLE', 'Statistik Återförsäljare');
define ('_TPL_AFF_STATS_DISPLAY_BUT', 'Visa');
define ('_TPL_AFF_STATS_PERIOD', 'Statistik för period');
define ('_TPL_AFF_STATS_CLICKS', 'Klick');
define ('_TPL_AFF_STATS_COMMISS', 'KOMMISSIONER');
define ('_TPL_AFF_STATS_DATE', 'Datum');
define ('_TPL_AFF_STATS_RAW', 'Stoff');
define ('_TPL_AFF_STATS_UNIQUE', 'Unik');
define ('_TPL_AFF_STATS_TRANS', 'Transaktioner');
define ('_TPL_AFF_STATS_CREDIT', 'Kredit');
define ('_TPL_AFF_STATS_DEBIT', 'Debet');
define ('_TPL_AFF_STATS_TOTAL', 'Totalt');
define ('_TPL_AFF_STATS_TOTAL_H', 'TOTAL');
define ('_TPL_AFF_STATS_TOP20', '20 främsta hänvisare');
define ('_TPL_AFF_STATS_REFERRER', 'HÄNVISARE');
define ('_TPL_AFF_STATS_BACK', 'Tillbaka till Medlemssidan');

define ('_TPL_AGREEMENT_TITLE', 'Användaravtal');
define ('_TPL_AGREEMENT_REED_AGREE', 'Vänligen läs och godkänn följande avtal:');
define ('_TPL_AGREEMENT_AGREE', 'Jag Godkänner');
define ('_TPL_AGREEMENT_CONTINUE_BUT', 'Fortsätt');

define ('_TPL_CANCEL_TITLE', 'Betalning Misslyckades');
define ('_TPL_CANCEL_ERROR', 'Ett fel uppstod vid betalningen.');
define ('_TPL_CANCEL_GOTO', 'Vänligen gå tillbaka till %sregistreringssidan%s och försök igen.');

define ('_TPL_EMAIL_VER_TITLE', 'Registrering - epost verifikation');
define ('_TPL_EMAIL_VER_TEXT', 'Vänligen kontrollera din E-Post - en epost verifikation har skickats till dig. När du får detta, läs det och följ instruktionerna för att slutföra din registrering.');
define ('_TPL_EMAIL_VER_POWEREDBY', 'Utvecklat av %saMember Pro%s medlemsskapsprogram');

define ('_TPL_FATAL_ERROR_TITLE', 'Ett fel har inträffat');
define ('_TPL_FATAL_ERROR_CONTACT', 'Vänligen kontakta sidans Administrator: ');

define ('_TPL_MEMBER_TITLE', 'Info om ditt Medlemsskap');
define ('_TPL_MEMBER_SUBSCR', 'Dina abonnemang');
define ('_TPL_MEMBER_NO_SUBSCR', 'Du har inga aktiva abonnemang');
define ('_TPL_MEMBER_ADD_RENEW', 'Lägg till/Förnya abonnemang');
define ('_TPL_MEMBER_USE', 'Vänligen använd %sformuläret Lägg till/Förnya abonnemang');
define ('_TPL_MEMBER_ORDER_SUBSCR', 'för att beställa eller förnya abonnemang.');
define ('_TPL_MEMBER_USEFUL_LINKS', 'Länkar');
define ('_TPL_MEMBER_LOGOUT', 'Logga Ut');
define ('_TPL_MEMBER_CH_PSWD', 'Ändra Lösenord/Redigera Profil');
define ('_TPL_MEMBER_SELECT', '** Välj Produkt **');
define ('_TPL_MEMBER_SELECT2', '** Välj Betalningsmetod **');
define ('_TPL_MEMBER_ORDER_BUT', 'Beställ');
define ('_TPL_MEMBER_PYMNT_HIST', 'Din Betalningshistoria');
define ('_TPL_MEMBER_PRODUCT', 'Produkt');
define ('_TPL_MEMBER_PERIOD', 'Period');
define ('_TPL_MEMBER_PAYSYS', 'Betalningssätt');
define ('_TPL_MEMBER_AMOUNT', 'Belopp');
define ('_TPL_MEMBER_CANCEL_SUBSCR', 'Vill du verkligen säga upp ditt abonnemang?');
define ('_TPL_MEMBER_CANCEL', 'Säg Upp');
define ('_TPL_MEMBER_CANCELLED', 'UPPSAGD');
define ('_TPL_MEMBER_PDF_INVOICE', 'PDF Fakturan');
define ('_TPL_MEMBER_INVOICE', 'Fakturan');

define ('_TPL_MULT_MEMBER_TITLE', 'Info om ditt Medlemsskap');
define ('_TPL_MULT_MEMBER_SUBSCR', 'Dina Abonnemang');
define ('_TPL_MULT_MEMBER_NOACTSUB', 'Du har inga aktiva abonnemang');
define ('_TPL_MULT_MEMBER_ADDREN', 'Vänligen använd %sLägg till/Förnya abonnemang%s formuläret%s.');
define ('_TPL_MULT_MEMBER_LOGOUT', 'Logga Ut');
define ('_TPL_MULT_MEMBER_CHPWD', 'Ändra Lösenord/Redigera Profil');
define ('_TPL_MULT_MEMBER_ADDRSUBSCR', 'Lägg till/Förnya abonnemang');
define ('_TPL_MULT_MEMBER_SELECTPM', '** Välj betalningsmetod **');
define ('_TPL_MULT_MEMBER_PHIST', 'Din Betalningshistoria');
define ('_TPL_MULT_MEMBER_PRODUCT', 'Produkt');
define ('_TPL_MULT_MEMBER_PERIOD', 'Period');
define ('_TPL_MULT_MEMBER_PSYS', 'Betalningsmetod');
define ('_TPL_MULT_MEMBER_AMOUNT', 'Belopp');
define ('_TPL_MULT_MEMBER_CANCEL', 'Säg Upp');
define ('_TPL_MULT_MEMBER_CANCELLED', 'UPPSAGD');
define ('_TPL_MULT_MEMBER_ORDERBUT', 'Beställ');

define ('_TPL_MSGCLOSE_CLOSE', 'Stäng fönstret');

define ('_TPL_PROFILE_TITLE', 'Redigera Profil');
define ('_TPL_PROFILE_USERNAME', 'Användarnamn');
define ('_TPL_PROFILE_ANOTHERUSRNM', 'du kan byta användarnamn här');
define ('_TPL_PROFILE_FLNAME', 'Förnamn & Efternamn');
define ('_TPL_PROFILE_EMAIL', 'E-Post Adress');
define ('_TPL_PROFILE_CHPWD', 'Byt Lösenord');
define ('_TPL_PROFILE_BLANK', 'Lämna tomt för att behålla det gamla');
define ('_TPL_PROFILE_CONFPWD', 'Konfirmera lösenord');
define ('_TPL_PROFILE_STREET', 'Gata');
define ('_TPL_PROFILE_CITY', 'Stad');
define ('_TPL_PROFILE_STATE', 'Län');
define ('_TPL_PROFILE_ZIP', 'Postnummer');
define ('_TPL_PROFILE_COUNTRY', 'Land');
define ('_TPL_PROFILE_UNSUBSCR', 'Säg Upp');
define ('_TPL_PROFILE_NOEMAIL', 'ta bort mig från nyhetslistan');
define ('_TPL_PROFILE_CHECKBOX', 'markera denna ruta för att säga upp');
define ('_TPL_PROFILE_SAVEBUT', 'Spara Profil');
define ('_TPL_PROFILE_BACKBUT', 'Tillbaka');

define ('_TPL_PROFILE_SAVED_TITLE', 'Redigera Profil');
define ('_TPL_PROFILE_SAVED_SUCCESS', 'Din medlemsprofil har sparats.');
define ('_TPL_PROFILE_SAVED_GOBACK', 'Vänligen gå tillbaka till %sInfo om ditt Medlemsskap%s.');

define ('_TPL_CHANGEPASSWORD_TITLE', 'Byt Lösenord');
define ('_TPL_CHANGEPASSWORD_USERNAME', 'Användarnamn');
define ('_TPL_CHANGEPASSWORD_SAVEBUT', 'Byt');
define ('_TPL_CHANGEPASSWORD_BACKBUT', 'Logga In');
define ('_TPL_CHANGEPASSWORD_CHPWD', 'Nytt Lösenord');
define ('_TPL_CHANGEPASSWORD_CONFPWD', 'Konfirmera Lösenord');

define ('_TPL_CHANGEPASSWORD_FAILED_TITLE', 'Fel vid byta av Lösenord');
define ('_TPL_CHANGEPASSWORD_FAILED_INCINFO', 'Informationen du skickade innehåller fel');
define ('_TPL_CHANGEPASSWORD_FAILED_USRNOTFOUND', 'Användare finns inte i vår databas.');
define ('_TPL_CHANGEPASSWORD_FAILED_EXPIRED', 'Säkerhetskoden har utgått.');
define ('_TPL_CHANGEPASSWORD_FAILED_WRONGPASS', 'Lösenorden är inte identiska eller har för få tecken.');
define ('_TPL_CHANGEPASSWORD_FAILED_RETURN', 'Gå tillbaka och försök igen');

define ('_TPL_REDIRECT_CLICKHERE', 'Klicka här om du inte gillar att vänta (eller om du inte automatiskt slussas vidare).');

define ('_SENDPWD_OK_TITLE', 'Det glömda Lösenordet har skickats');
define ('_SENDPWD_OK_TEXT', 'Ditt Lösenord har skickats till dig');
define ('_SENDPWD_OK_TEXT_1', 'Kontrollera din E-Post');

define ('_SENDPWD_FAILED_TITLE', 'Fel vid sändning av Lösenord');
define ('_SENDPWD_FAILED_TEXT', 'Informationen du uppgav innehåller fel');
define ('_SENDPWD_FAILED_TEXT_1', 'Användarnamnet [%s] finns inte i vår databas');
define ('_TPL_SENDPWD_RETURN', 'Gå Tillbaka');

define ('_TPL_NEWGUEST_FAILED_TITLE', 'Fel vid Konfirmation');
define ('_TPL_NEWGUEST_FAILED_INCINFO', 'Informationen du uppgav innehåller fel');
define ('_TPL_NEWGUEST_FAILED_RETURN', 'Gå tillbaka och försök igen');


define ('_TPL_NEWGUEST_FAILED_EMAIL_TITLE', 'Fel vid Konfirmation');
define ('_TPL_NEWGUEST_FAILED_EMAIL_INFO', 'E-Post adressen du skrev används redan av en annan registrerad medlem.');
define ('_TPL_NEWGUEST_FAILED_EMAIL_LINK', 'Följ denna länk för att Logga In och anmäla dig till vårt Nyhetsbrev');


define ('_TPL_NEWGUEST_OK_TITLE', 'Konfirmationen har skickats');
define ('_TPL_NEWGUEST_OK_PWDOK', 'Ett nytt konfirmationsbrev anmälan gäst har skickats till dig');
define ('_TPL_NEWGUEST_OK_CHECKEM', 'Kontrollera din E-Post');
define ('_TPL_NEWGUEST_OK_RETURN', 'Tillbaka');

define ('_TPL_NEWGUEST_COMPLETE_TITLE', 'Anmälan lades till');
define ('_TPL_NEWGUEST_COMPLETE', 'Din E-Postadress har lagts till i vår databas för vårt Nyhetsbrev');


define ('_TPL_NEWSLETTER_SUBSCRIPTIONS', 'Anmälan Nyhetsbrev');
define ('_TPL_NEWSLETTER_ARCHIVE', 'Nyhetsbrev Arkiv');
define ('_TPL_NEWSLETTER_SUBSCRIBE', 'Nyhetsbrev Anmälan');
define ('_TPL_NEWSLETTER_MEMBER_AREA', 'Medlemmsdel');
define ('_TPL_NEWSLETTER_SUBSCRIBE_TO_NEWSLETTERS', 'Välj Nyhetsbrev');
define ('_TPL_NEWSLETTER_NAME', 'Namn');
define ('_TPL_NEWSLETTER_EMAIL', 'E-Post');
define ('_TPL_NEWSLETTER_DO_SUBSCRIBE', 'Anmäl');
define ('_TPL_NEWSLETTER_BACK', 'Tillbaka');

define ('_TPL_NEWSLETTER_UPDATE_SUBSCRIPTIONS', 'Uppdatera Anmälan');
define ('_TPL_NEWSLETTER_INFO_SAVED', 'Informationen har sparats');
define ('_TPL_NEWSLETTER_INFO_UPDATED', 'Informationen har uppdaterats om anmälan till Nyhetsbrev');

define ('_TPL_NEWSLETTER_REQUIRED_NAME', 'Du måste skriva ditt Namn');
define ('_TPL_NEWSLETTER_REQUIRED_EMAIL', 'Du måste skriva din E-Post Adress');
define ('_TPL_NEWSLETTER_REQUIRED_THREAD', 'Du måste välja Nyhetsbrev');

define ('_TPL_NEWSLETTER_UNSUBSCRIBE', 'Avanmälan från alla Nyhetsbrev');

define ('_TPL_NEWSLETTER_DATE', 'Datum');
define ('_TPL_NEWSLETTER_SUBJECT', 'Ämne');
define ('_TPL_NEWSLETTER_MESSAGE', 'Meddelande');
define ('_TPL_NEWSLETTER_THREADS', 'Tråd(ar)');

define ('_TPL_SIGNUP_MULT_TITLE', 'Registrera');
define ('_TPL_SIGNUP_MULT_SELECTTYPE', 'Välj typ av Medlemsskap');
define ('_TPL_SIGNUP_MULT_MEMTYPE', 'Typ av Medlemsskap');
define ('_TPL_SIGNUP_MULT_SELPAYSYS', 'Välj betalningsmetod');
define ('_TPL_SIGNUP_MULT_PAYSYS', 'Betalningsmetod');
define ('_TPL_SIGNUP_MULT_NAME', 'Ditt Namn');
define ('_TPL_SIGNUP_MULT_FLNAME', 'förnamn & efternamn');
define ('_TPL_SIGNUP_MULT_EMAIL', 'Din E-Post Adress');
define ('_TPL_SIGNUP_MULT_CONFIRM', 'kommer att användas till konfirmering');
define ('_TPL_SIGNUP_MULT_LOGIN', 'Välj Användarnamn (Användar ID)');
define ('_TPL_SIGNUP_MULT_ENTER', 'välj önskat användar id%s- det kommer att användas efter betalning %sför att Logga In på ditt konto.%s Måste innehålla %d tecken eller fler %soch kan innehålla endast små bokstäver, siffror och understräck _');
define ('_TPL_SIGNUP_MULT_CHECK', 'kontrollera unikhet');
define ('_TPL_SIGNUP_MULT_CHPWD', 'Välj Lösenord');
define ('_TPL_SIGNUP_MULT_MUSTBE', 'Måste innehålla minst %d tecken');
define ('_TPL_SIGNUP_MULT_CONFPWD', 'Konfirmera ditt Lösenord');
define ('_TPL_SIGNUP_MULT_PWDAGAIN', 'skriv ditt Lösenord igen');
define ('_TPL_SIGNUP_MULT_ADDRESS', 'ADRESS INFO');
define ('_TPL_SIGNUP_MULT_STREET', 'Gata');
define ('_TPL_SIGNUP_MULT_CITY', 'Stad');
define ('_TPL_SIGNUP_MULT_STATE', 'Län');
define ('_TPL_SIGNUP_MULT_ZIP', 'Postnummer');
define ('_TPL_SIGNUP_MULT_COUNTRY', 'Land');
define ('_TPL_SIGNUP_MULT_COUPONS', 'Rabattkupong');
define ('_TPL_SIGNUP_MULT_CCODE', 'Skriv Rabattkupongens kod');
define ('_TPL_SIGNUP_MULT_GETCOUP', 'om du fått någon rabattkupong genom annonsering,%s skriv då koden här');
define ('_TPL_SIGNUP_MULT_CONT', 'Fortsätt');

define ('_TPL_THX_TITLE', 'Tack för din registrering');
define ('_TPL_THX_ENJOY', 'Du kommer att få mycket nöje med dett Medlemsskap. Logga In genom att klicka på %sLogga In%s');
define ('_TPL_THX_PAYPROC', 'Din betalning har tagits emot.');
define ('_TPL_THX_ORDERREF', 'Order referens: %d / %s');
define ('_TPL_THX_DATETIME', 'Datum och tid för betalning: %s');
define ('_TPL_THX_PRDTITLE', 'Anmälan/Produkt Titel');
define ('_TPL_THX_PRICE', 'Pris');
define ('_TPL_THX_SUBTOTAL', 'Delsumma');
define ('_TPL_THX_DISCOUNT', 'Rabatt');
define ('_TPL_THX_TAX', 'Skatt');
define ('_TPL_THX_TOTAL', 'Totalt');
define ('_TPL_THX_YOUR_INVOICE', 'Ditt Fakturanummer');
define ('_TPL_THX_FROM', 'från');

define ('_TPL_THX_ERROR_TITLE', 'Fel vid Registrering');
define ('_TPL_THX_ERROR_ERROR', 'Ett fel uppstod vid Registreringen');
define ('_TPL_THX_ERROR_CONTACT', 'Vänligen kontakta sidans Administrator');

define ('_TPL_UNSUBSCRIBE_TITLE', 'Konfirmation Avanmälan');
define ('_TPL_UNSUBSCRIBE_CONFIRM', 'Vill du verkligen säga upp anmälan för E-Postadressen  %s%s%s från %s nyhetsbrev?');
define ('_TPL_UNSUBSCRIBE_UNSUB_BUT', 'Ja, jag vill säga upp den');
define ('_TPL_UNSUBSCRIBE_NO_UNSUB_BUT', 'Nej, jag vill fortsätta vara anmäld');

define ('_TPL_UNSUBSCRIBED_TITLE', 'E-Postadressen är avanmäld');
define ('_TPL_UNSUBSCRIBED_SUCCESS1', 'Din E-Post adress %s har tagits bort.');
define ('_TPL_UNSUBSCRIBED_SUCCESS2', 'Du kommer inte att få vårt Nyhetsbrev längre.');
define ('_TPL_UNSUBSCRIBED_SUCCESS3', 'OBS, att du kommer fortfarande att få meddelande om nya betalningar, och ev om du glömt ditt Lösenord etc.');

define ('_UNIQ_LOGIN_EMPTY_TITLE', 'Inget Användarnamn');
define ('_UNIQ_LOGIN_EMPTY_TEXT', 'Vänligen skriv ditt Användarnamn först.');
define ('_UNIQ_LOGIN_EXSTS_TITLE', 'Användarnamnet är upptaget');
define ('_UNIQ_LOGIN_EXSTS_TEXT', 'Användarnamnet %s är upptaget av en annan medlem');
define ('_UNIQ_LOGIN_EXSTS_TEXT_1', 'Vänligen välj ett annat');
define ('_UNIQ_LOGIN_EXSTS_TEXT_2', 'Om det är ditt Användarnamn och konto, vänligen gå till %sdin medlemssida%s för att Logga In.');
define ('_UNIQ_LOGIN_FREE_TITLE', 'Användarnamnet är tillgängligt');
define ('_UNIQ_LOGIN_FREE_TEXT', 'Användarnamnet %s har inte registrerats ännu');
define ('_UNIQ_LOGIN_FREE_TEXT_1', 'Grattis, det är tillgängligt!');
define ('_TPL_UNIQ_LOGIN_CLOSE', 'Stäng');

define('_LOGIN_WAIT_BEFORE_NEXT_ATTEMPT', 'Vänligen vänta %d minuter innan nästa inloggnings försök');
define('_LOGIN_SESSION_EXPIRED', 'Sessionen har stängts, vänligen skriv ditt Användarnamn och Lösenord igen');
define('_LOGIN_ACCESS_NOT_ALLOWED', 'Access till avdelningen för medlemmar är inte tillåten. Vänligen gå till %s"Medlemssidan"%s för att förnya eller anmäla');
define('_LOGIN_INCORRECT', "Användarnamn eller Lösenord är fel");
define('_LOGIN_ACCOUNT_DISABLED', 'Ditt konto har stängts. Kontakta sidans Administratör för detaljer');
define('_LOGIN_MANUAL_VERIFICATION_PENDING', 'Ditt konto är ännu inte tillgängligt. Du kommer att få ett meddelande när verifieringen är klar');
define('_LOGIN_USERNAME_WRONG_CASE', 'Skriv Användarnamnet rätt. Du skrev "%s", vänligen skriv "%s" istället');
define('_LOGIN_PLEASE_LOGIN', 'Vänligen Logga In');

define('_SIGNUP_PLEASE_SELECT_MEMT', 'Vänligen välj Typ av Medlemsskap');
define('_SIGNUP_PLEASE_SELECT_PAYSYS', 'Vänligen välj Betalningsmetod');
define('_SIGNUP_PLEASE_ENTER_FNAME', 'Vänligen skriv ditt Förnamn');
define('_SIGNUP_PLEASE_ENTER_LNAME', 'Vänligen skriv ditt Efternamn');
define('_SIGNUP_INVALID_USERNAME', 'Användarnamnet innehåller felaktiga tecken - vänligen använd siffror, bokstäver och mellanrum');
define('_SIGNUP_INVALID_USERNAME_W_SPACES', 'Användarnamnet innehåller felaktiga tecken - vänligen använd siffror, bokstäver');
define('_SIGNUP_INVALID_USERNAME_2', 'Vänligen skriv ett annat Användarnamn. Det måste innehålla minst %d tecken');
define('_SIGNUP_INVALID_USERNAME_3', 'Användarnamnet  %s är upptaget. Vänligen välj ett annat.');
define('_SIGNUP_PLEASE_ENTER_EMAIL', 'Vänligen skriv en riktig E-Post adress');
define('_SIGNUP_INVALID_EMAIL_1', 'Ett konto med samma E-Post adress finns redan.');
define('_SIGNUP_INVALID_EMAIL_2', 'Vänligen %slogga in%s på detta konto.%sOm du inte har gjort klart med betalningen, kan du göra detta efter inloggningen');
define('_SIGNUP_PLEASE_ENTER_PSWD', 'Vänligen skriv ditt Lösenord');
define('_SIGNUP_INVALID_PASS_1', 'Lösenordet måste innehålla minst %d bokstäver eller siffror');
define('_SIGNUP_INVALID_PASS_2', 'Lösenordet och Konfirmeringen av Lösenordet är inte identiska. Vänligen försök igen');
define('_SIGNUP_SCRIPT_ERROR', 'Fel i Script Konfigurationen - du måste lägga in minst en Produkt (Medlemsskapstyp) från aMember Kontroll Panel');
define('_SIGNUP_PAYMENT_NOT_FOUND', 'Betalningen %d hittades inte');
define('_SIGNUP_PAYMENT_COMPLETED', 'Betalningen %d är redan klar, vänligen Logga In på ditt konto ');
define('_SIGNUP_PAYMENT_COMPLETED_1', 'här');
define('_SIGNUP_INCORRECT_LINK', 'Felaktig länk - försäkra dig om att den är riktig');
define('_SIGNUP_USER_AGREEMENT', 'Du måste godkänna vårt avtal innan du kan fortsätta');
define('_SIGNUP_INCORRECT_PRODID', 'Produk ID är felaktigt för registreringssidan');
define('_SIGNUP_LOGIN_EXISTS', 'Inloggningen existerar. Internt fel');
define('_SIGNUP_ENTER_STREET', 'Vänligen skriv din gatuadress');
define('_SIGNUP_ENTER_CITY', 'Vänligen skriv din hemstad');
define('_SIGNUP_ENTER_STATE', 'Vänligen skriv ditt hemlän');
define('_SIGNUP_ENTER_ZIP', 'Vänligen skriv ditt postnummer');
define('_SIGNUP_ENTER_COUNTRY', 'Vänligen skriv ditt hemland');

define('_AFF_MEMBER_TITLE', 'Information Återförsäljare');
define('_AFF_INTERNAL_ERROR', 'Internt Fel - medlems_id är tomt');
define('_AFF_ERROR_1', 'Vänligen skriv en E-Post adress för Utbetalningar');
define('_AFF_ERROR_2', 'Vänligen skriv Namn på checkmottagare');
define('_AFF_ERROR_3', 'Vänligen skriv StormPay konto e-post');
define('_AFF_ERROR_4', 'Vänligen skriv iKobo konto e-post');
define('_AFF_ERROR_5', 'Vänligen skriv MoneyBookers konto ID');
define('_AFF_ERROR_6', 'Vänligen skriv E-Gold konto#');
define('_AFF_ERROR_7', 'Okänd utbetalnings typ');
define('_AFF_ERROR_8', 'Okänd handling: %s');
define('_AFF_AFFILIATES', 'Återförsäljare');
define('_AFF_PROGR_CONF', 'konfiguration återförsäljarprogram');
define('_AFF_PAYOUT_MTHDS', 'Accepterade utbetalningsmetoder');
define('_AFF_MTHD4_PAYOUT', 'återförsäljare kan välja metod för utbetalning av kommision.');
define('_AFF_NOTHING_SELECTED', 'Om ingenting väljs, kommer kommisionen inte att inkluderas automatiskt');
define('_AFF_REPORT', 'utbetalningsrapport.');
define('_AFF_CONFIG_F1_1', 'Kommision Återförsäljare för första betalning');
define('_AFF_CONFIG_F1_2', 'kommision Återförsäljare för första betalning, ex.: 1.5 eller 2.5%');
define('_AFF_CONFIG_F2_1', 'Kommision Återförsäljare för följande betalningar');
define('_AFF_CONFIG_F2_2', 'kommision Återförsäljare för följande betalningar, ex.: 1.5 eller 2.5%');
define('_AFF_CONFIG_F3_1', 'Återförsäljare cookie livstid');
define('_AFF_CONFIG_F3_2', 'hur länge (räknat i dagar) ska cookien sparas ang återförsäljaren.');
define('_AFF_CONFIG_F3_3', 'Om en kund återkommer till sidan senare, kommer kommisionen att bli');
define('_AFF_CONFIG_F3_4', 'utbetald till återförsäljaren.');
define('_AFF_CONFIG_F4_1', 'Betala endast kommision för första betalningen');
define('_AFF_CONFIG_F4_2', 'återförsäljare betalas endast för första betalningen från medlem.');
define('_AFF_CONFIG_F4_3', 'Om medlem förnyar sitt medlemsskap, kommer inte återförsäljaren att erhålla kommision');
define('_AFF_CONFIG_F4_4', 'från detta.');
define('_AFF_CONFIG_F5_1', 'Ge inte kommision för gratis anmälningar');
define('_AFF_CONFIG_F5_2', 'sälj kommision kommer inte att krediteras till återförsäljares konto');
define('_AFF_CONFIG_F5_3', 'om medlem anmäler sig till gratis anmälan, det inverkar naturligtvis endast på');
define('_AFF_CONFIG_F5_4', '\'fast\' kommision.');
define('_AFF_ARRAY_1ELEM', 'Ge kommision även för gratis anmälan');
define('_AFF_ARRAY_2ELEM', 'Ge inte kommision för gratis anmälningar');
define('_AFF_CONFIG_F6_1', 'Registreringstyp Återförsäljare');
define('_AFF_CONFIG_F6_2', 'återförsäljare får kommision endast för första betalningen.');
define('_AFF_CONFIG_F6_3', 'Om medlem förnyar sitt medlemsskap, kommer inte återförsäljaren att erhålla kommision');
define('_AFF_CONFIG_F6_4', 'för detta.');
define('_AFF_ARRAY_2_ELEM_1', 'Startvärde - medlem måste klicka för att bli återförsäljare');
define('_AFF_ARRAY_2_ELEM_2', 'Alla nya medlemmar blir automatiskt återförsäljare');
define('_AFF_ARRAY_2_ELEM_3', 'Endast Admin kan göra en medlem till återförsäljare');
define('_AFF_CONFIG_F7_1', 'E-Posta kommision till Administratorn');
define('_AFF_CONFIG_F7_2', 'när ny försäljnings kommision läggs till återförsäljares konto');
define('_AFF_CONFIG_F7_3', 'skicka då ett meddelande till admin');
define('_AFF_CONFIG_F8_1', 'E-Posta kommision till återförsäljare');
define('_AFF_CONFIG_F8_2', 'när ny försäljnings kommision läggs till återförsäljares konto');
define('_AFF_CONFIG_F8_3', 'skicka då ett meddelande till återförsäljaren');
define('_AFF_ADVERTISE_SITE', 'Gör reklam för vår sida och/eller på annat sätt och tjäna pengar på detta');
define('_AFF_MEMBER_AREA', 'Område för Återförsäljare');
define('_AFF_GET_BANS_LINKS', 'Hämta Banners och Länkar som Återförsäljare');
define('_AFF_REVIEW_STAT', 'Statistik för Återförsäljare');
define('_AFF_UPDATE_PAYOUT', 'Uppdatera info om utbetalning av kommision<br><br>');
define('_AFF_MEMBER_F1_1', 'Paypal adress för utbetalning');
define('_AFF_MEMBER_F2_1', 'StormPay adress för utbetalning');
define('_AFF_MEMBER_F3_1', 'iKobo adress för utbetalning');
define('_AFF_MEMBER_F4_1', 'MoneyBookers konto ID för utbetalning');
define('_AFF_MEMBER_F5_1', 'E-Gold konto# för utbetalning');
define('_AFF_MEMBER_F6_1', 'Check betalningsbar till');
define('_AFF_MEMBER_THANK_YOU', 'Tack för din registrering');
define('_AFF_MEMBER_REDIRECTING', 'Du slussas vidare till din profil sida');
define('_AFF_DISABLED_MESSAGE', 'Programmet för återförsäljare är inte tillgängligt. Gör det tillgängligt i aMember CP -> Setup');

define('_AFF_PAYOUT_TYPE', 'Utbetalningstyp Återförsäljare');
define('_AFF_SIGNUP_PLEASE_PAYOUT_TYPE', 'Vänligen välj utbetalningstyp');

define('_MEMBER_VF_INTEGER', 'Vänligen skriv endast heltal för värdet på [%s]');
define('_MEMBER_VF_NUMERIC', 'Vänligen skriv endast nummer för värdet på [%s]');
define('_MEMBER_VF_REQUIRE', 'Vänligen skriv ett värde för fältet [%s]');
define('_MEMBER_VF_EMAIL', 'Vänligen skriv en riktig E-Post adress för fältet [%s] ');

define('_MEMBER_ERROR_1', 'Du har inte verifierat din E-Post adress, så inloggning är inte%stillåtet. Kontrollera din E-Post efter ett meddelande om verifiering och%sklicka på länken för att bli verifierad. Har du inte fått detta meddelande,%svänligen klicka på %sdenna länk%s så skickar vi meddelandet igen.');
define('_MEMBER_REDIRECTING', 'Du slussas nu vidare till medlemssidan');
define('_MEMBER_ONLY4_PAID', 'Denna produkt är endast tillgänglig för betalande medlemmar');
define('_MEMBER_ONLY4_NEW', 'Denna produkt är endast tillgänglig för nya medlemmar');
define('_MEMBER_NOT4_ORDER', 'Denna produkt är inte tillgänglig för beställning');
define('_MEMBER_SELECT_PRODUCT', 'Vänligen välj produkt (typ av anmälan) för att förnya');
define('_MEMBER_SELECT_PAYMENT', 'Vänligen välj betalningsmetod');
define('_MEMBER_ID_NOT_MATCH', 'medlems_id matchar inte till betalningen');
define('_MEMBER_SUBSCR_CANCELLED', 'Avanmälan gjord');
define('_MEMBER_RSUB_CANCELLED', 'Den återkommande anmälan har tagits bort.');
define('_MEMBER_MAIL_ADMIN', 'Återkommande anmälan som tagits bort: Användare: %s Betalning#: %d');
define('_MEMBER_MAIL_THEME', '*** Anmälan Raderad');
define('_MEMBER_ERROR', 'Du måste godkänna vårt avtal för att gå vidare');

define('_MEMBER_PROFILE_CORRECTLOG', 'Vänligen skriv riktiga inloggnings uppgifter. Det måste innehålla minst %d bokstäver, siffror eller  _');
define('_MEMBER_PROFILE_NAMEEXISTS', 'Användarnamnet %s är upptaget. Välj ett annat.');
define('_MEMBER_PROFILE_ERROR1', 'Skriv ett riktigt Användarnamn: %s');
define('_MEMBER_PROFILE_ERROR2', 'Skriv en riktig E-Post adress');
define('_MEMBER_PROFILE_ERROR3', 'E-Post adressen används redan');
define('_MEMBER_PROFILE_ERROR4', 'Skriv ett Förnamn');
define('_MEMBER_PROFILE_ERROR5', 'Skriv ett Efternamn');
define('_MEMBER_PROFILE_ERROR6', 'Lösenordet måste innehålla minst %d tecken');
define('_MEMBER_PROFILE_ERROR7', 'Lösenordet måste innehålla mindre än %d tecken');
define('_MEMBER_PROFILE_ERROR8', 'Lösenordet måste skrivas exakt lika 2 gånger. Försök igen');
define('_MEMBER_PROFILE_ERROR9', 'Okänd fälttyp för %s : %s');

define('_CRON_ERROR', 'Extern cron inte möjliggjord i setup');

define('_COMMON_LANGUAGE', 'Språk');
define('_COMMON_LIFETIME', 'LIVSLÄNGD');
define('_COMMON_RECURRING', 'PERIODIK');

define('_INDEX_ERROR', 'aMember är inte konfigurerad ännu. Gå till %skonfigureringen%s.');

define('_LOGIN_REDIRECT', 'Du slussas vidare till skyddadt område');

define('_RESEND_ERROR', 'Din E-Post adress är redan verifierad');
define('_RESEND_ERROR2', 'Du kan inte begära e-post verifikation mer,  %sanmäl dig%s igen eller kontakta supporten för hjälp');
define('_RESEND_ERROR3', 'Internt Fel #1265.');

define('_NEWSLETTER_SUBSCRIPTION', 'Anmälan Nyhetsbrev');
define('_NEWSLETTER_NO_GUEST_THREADS', 'Tyvärr, det finns inga Nyhetsbrev just nu för besökare');

define('_SETUP_ERROR', 'PHP version %s eller högre är ett måste för att använda aMember. Din PHP-Version är : %s%sVänligen uppgradera eller kontakta din server leverantör om detta. PHP före %s var ostabil och dåligt fungerande.');
define('_SETUP_ERROR2', 'PHP på din server har ingen MySQL support.%sso aMember kan inte installeras utan detta, kontakta din server leverantör angående detta.');
define('_SETUP_FATAL_ERROR', 'Ödestigert Fel: %s');
define('_SETUP_HEADER', 'aMember Installation');
define('_SETUP_CONF_EXISTS', 'Filen %s finns redan och är inte tom. Ta bort den eller töm den på innehåll');
define('_SETUP_AFTER_FIX', 'När du löst dessa problem, klicka %shär%s för att ladda om sidan.');
define('_SETUP_CONF_CHMOD', 'Filen %s finns redan och är inte skrivbar. Vänligen %sordna detta%s');
define('_SETUP_DIRECTORY_CHMOD', 'Foldern %s är inte skrivbar. Den måste vara skrivbar för att kunna skriva konfigurerings filen %s. Vänligen %sordna detta%s');
define('_SETUP_ENTER_PARAM', 'Skriv Parametrarna för Konfigureringen');
define('_SETUP_MODIFY_LATER', 'Du kan senare modifiera dessa värden i aMember Kontroll Panel');
define('_SETUP_ROOT_URL', 'Root URL av scriptet');
define('_SETUP_TRAILING_SLASH', '%sSkriv INTE%s ett avslutande snedstreck ( %s/%s ) på slutet!');
define('_SETUP_LICENSE_NOTE', 'Vänligen notera att din URL måste macha den i din licens.');
define('_SETUP_HTTPS_URL', 'Säker (HTTPS) Root URL av scriptet');
define('_SETUP_KEEP_DEFAULT', 'Är du osäker, skriv då samma som på Root URL.');
define('_SETUP_NO_TRSLASH', 'UTAN avslutande snedstreck ( %s/%s ) tack!');
define('_SETUP_ADMIN_EMAIL', 'Admin E-Post');
define('_SETUP_SENT_TO', 'Adressen som ska användas för meddelande etc');
define('_SETUP_ADMIN_LOGIN', 'Admin Inloggning');
define('_SETUP_USERNAME', 'Användarnamn för Inloggning på Administreringsdelen');
define('_SETUP_ADMIN_PASS', 'Admin Lösenord');
define('_SETUP_PASS', 'Lösenord för Inloggning på Administreringsdelen');
define('_SETUP_LICENSE_HEAD', 'Licens');
define('_SETUP_LICENSE', 'Skriv %sHela%s licens koden, inkludera även linjer ( == ) över och under!');
define('_SETUP_NEXT_BUT', 'Nästa');
define('_SETUP_ERROR3', 'Vänligen skriv in root url av scriptet');
define('_SETUP_ERROR4', 'Vänligen skriv in säker root url av scriptet (eller skriv samma som på Root URL - det vill fungera i alla fall)');
define('_SETUP_ERROR5', 'Vänligen skriv in admin e-post');
define('_SETUP_ERROR6', 'Vänligen skriv in admin inloggning');
define('_SETUP_ERROR7', 'Vänligen skriv in admin lösenord');
define('_SETUP_ERROR8', 'Vänligen skriv in licenskoden');
define('_SETUP_ERROR9', 'Vänligen skriv in hela licenskoden (den startar och slutar med ======)');
define('_SETUP_ERROR10', 'Root URL %s matchar inte domainen för licensen');
define('_SETUP_ERROR11', 'Säker Root URL %s matchar inte domainen för licensen');
define('_SETUP_RETURN', 'Vänligen %sgå tillbaka%s och försök igen.');
define('_SETUP_MYSQL_PARAM', 'Vänligen skriv in parametrar för MySQL konfigurationen');
define('_SETUP_CONF_EDIT', 'Du kan redigera %sconfig.inc.php%s senare om du vill göra ändringar');
define('_SETUP_MYSQL_HOST', 'MySQL Host');
define('_SETUP_LOCALHOST', 'Oftast \'localhost\'');
define('_SETUP_MYSQL_DB', 'MySQL Databas');
define('_SETUP_MYSQL_NOTE', 'OBS: Innstalleringsprogrammet skapar inte databasen åt dig.');
define('_SETUP_USE_DEFAULT', 'Använd en databas du redan har eller %sskapa en ny, till exempel \'amember\'');
define('_SETUP_MYSQL_USER', 'MySQL Användarnamn');
define('_SETUP_MYSQL_PWD', 'MySQL Lösenord');
define('_SETUP_TABLE_PREFIX', 'MySQL Prefix för Tabeller');
define('_SETUP_UNSURE', 'Om du är osäker, använd dom förinlagda värdena %samember_%s');
define('_SETUP_MYSQL_ERROR1', 'Vänligen skriv in mysql databas namn');
define('_SETUP_MYSQL_ERROR2', 'Vänligen skriv in mysql användarnamn');
define('_SETUP_MYSQL_ERROR3', 'Vänligen skriv in mysql hostnamn');
define('_SETUP_MYSQL_ERROR4', 'Vänligen skriv in mysql lösenord');
define('_SETUP_MYSQL_ERROR5', 'Jag kan inte kontakta mysql (%s)');
define('_SETUP_MYSQL_ERROR6', 'Jag kan inte välja databas \'%s\' ( %s )');
define('_SETUP_MYSQL_INSTALL', 'Installera aMember på denna MySQL databasen?');
define('_SETUP_MYSQL_CREATE_TABLES', 'Skapa aMember databas tabeller');
define('_SETUP_MYSQL_INSTALL2', 'Markera rutan och klicka på \'Nästa\' för att skapa aMember tabeller i den valda MySQL databasen%sOm du har aMember redan installerad på denna databas, kommer ingenting att tas bort utan bara en uppdatering att ske i tabellernas struktur');
define('_SETUP_MYSQL_ERROR7', 'Jag kan inte välja databas \' %s \' ( %s )');
define('_SETUP_MYSQL_FIX_ERROR', 'Fixa dessa fel och  %sladda om%s sidan.');
define('_SETUP_ERROR12', 'Jag kan inte öppna %s . Vänligen ladda upp denna fil');
define('_SETUP_ERROR13', 'Jag kan inte spara konfigurerings filer');
define('_SETUP_ERROR14', 'Jag kan inte spara filen %s%s%s');
define('_SETUP_NEW_CONFIG', 'För att komplettera installationen kan du ladda ner den nya konfigurations filen och sedan ladda upp den igen till servern.');
define('_SETUP_UPLOAD_CONFIG', 'Filen %sconfig.inc.php%s. Ladda upp den till:');
define('_SETUP_DOWNLOAD_BUT', 'Ladda ner config.inc.php');
define('_SETUP_IE_RENAME', 'Internet Expolorer döper ibland om %sfiler när dom sparas. Exempel, den kan döpa om %sconfig.inc.php%s%still %sconfig[1].inc.php%s. Glöm inte att kontrollera detta innan du laddar upp filen igen!');
define('_SETUP_THANK_YOU1', 'Tack för att du har valt aMember Pro. Du kan hitta aMember Pro Användar manual Guide %shär%s.');
define('_SETUP_THANK_YOU2', 'Kontakta gärna %sCGI-Central%s om du har problem eller frågor om denna produkt.');
define('_SETUP_THANK_YOU3', 'Vänligen kontyrollera följande:');
define('_SETUP_THANK_YOU4', '(Du kanske vill lägga in denna sida i dina favoriter)');
define('_SETUP_THANK_YOU_LINK1', 'Adminsida (aMember Kontroll Panel)');
define('_SETUP_THANK_YOU_LINK2', 'Registrerings sida');
define('_SETUP_THANK_YOU_LINK3', 'Medlemssida');
define('_SETUP_THANK_YOU_LINK4', 'Inloggnings sida (sluss till säker avdelning)');
define('_SETUP_THANK_YOU_BEFOREUSE', 'Innan aMember är klar för att användas måste du även göra följande:)');
define('_SETUP_THANK_YOU_GOTOCP', 'Gå till %sAdmin sidan%s och Logga In. Från huvudmenyn till vänster, välj  %sUtilities>Setup/Configuration%s Dessa inställningar kan användas för att finjustera din installation. Möjliggör ev betalningsmetoder som du vill använda, gå sedan till konfigurationssidan för dessa plugins och redigera inställningarna.');
define('_SETUP_THANK_YOU_ADDPRODUCTS', 'Gå till %sAdmin sidan%s och skapa produkter och anmälningstyper. %s%sYDu kan kalla dom för \'Produkter\' eller \'Anmälningstyper\' beroende på din typ av sida. Till exempel, till ditt nyhetsbrev kan du säga \'Anmälan,\' medan du kan kalla program eller hårdvara för \'Produkter.\' Det är helt upp till dig.');
define('_SETUP_THANK_YOU_REMEMBER', 'Kom ihåg, en \'Produkt\' eller \'Anmälningstyp\' är bara ett sätt att relatera till samma sak , nämligen ett värde i din aMember databas.');
define('_SETUP_THANK_YOU_SUBSCRTYPE', 'Du kan specifisera Anmälningstyp (gratis eller betald, etc.) när du lägger till varje produkt.%sDet är viktigt att du lägger im minst en produkt!%s');
define('_SETUP_THANK_YOU_PAYCONF', 'Fastställ om ditt valda betalningssystem kräver extra konfigurering. Om den gör det kan du titta i %sInstallation Manualen%s för mer information, eller kontakta CGI-Central för kundanpassningar.');
define('_SETUP_THANK_YOU_PROTECTION', 'Fastställ säkerheten för dina säkrade mappar. Du kan använda .htaccess eller PHP inkluderade filer. För att använda Cookie-Baserade inloggningskontroller måste alla dina filer vara i formatet .php! ');
define('_SETUP_THANK_YOU_CHECKINSTL', 'Kontrollera din installation genom att testa din %s%sRegistrerings Sida%s.%sNär allt är konfigurerat och fungerande vill du kanske ändra lite i HTML mallarna. Du bör tänka på att åtminstone ändra följande mallar:');
define('_SETUP_THANK_YOU_READMORE', 'Du kan läsa mer om ändringar i mallarna %shär%s.%sTips:%s 90% av aMember\'s utseende och känsla kan ändras genom att redigera CSS filen i  %sheader.html%s');
define('_SETUP_THANK_YOU_FEELFREE', 'Kontakta gärna %sCGI-Central Support%s om du behöver hjälp med modifiering av scriptet.');
define('_SETUP_THANK_YOU_INFO', 'Du kan även hitta mycket användbar hjälp i  %saMember Forum%s.');
define('_SETUP_HEADER1', 'aMember Setup: Step %d of 6');

define('_UNSUBSCRIBE_ERROR', 'Fel Licens URL, vänligen kontakta sidans administrator');

define('_PLUG_PAY_REDIRECT_WAIT', 'Vänligen vänta...');
define('_PLUG_PAY_REDIRECT_REDIRECT', 'Redirecting you to secure payment page');

define('_TPL_CC_INFO_TITLE', 'Kreditkorts Info');
define('_TPL_CC_INFO_CCTYPE', 'Kreditkorts Typ');
define('_TPL_CC_INFO_SELECT1', 'vänligen välj ett');
define('_TPL_CC_INFO_CHOOSE', '*** Vänligen välj ***');
define('_TPL_CC_INFO_HOLDERNAME', 'Namn på kortet');
define('_TPL_CC_INFO_ASONCARD', 'namn på kortet exakt som det står');
define('_TPL_CC_INFO_HOLDERNAME2', 'Namn på Kortet');
define('_TPL_CC_INFO_FLNAME', 'förnamn och efternamn på kortet exakt som det står');
define('_TPL_CC_INFO_CNAME', 'Företagsnamn');
define('_TPL_CC_INFO_COMPNAME', 'företaget assosierat med fakturaadressen för köpet');
define('_TPL_CC_INFO_CCNUM', 'Kreditkorts Nummer');
define('_TPL_CC_INFO_EXAMPLE', 'exempel: 1111-2222-3333-4444');
define('_TPL_CC_INFO_EXPIRE', 'Utgångsdatum');
define('_TPL_CC_INFO_EXPDATE', 'Välj kortets utgångsdatum - månad och år');
define('_TPL_CC_INFO_CCCODE', 'Säkerhetskod');
define('_TPL_CC_INFO_CCCODEDESC', '"Säkerhetskoden" är tre eller fyra siffror oftast på baksidan av kortet.');
define('_TPL_CC_INFO_ADDRINFO', 'Adress Info');
define('_TPL_CC_INFO_STRADDR', 'Gatuadress');
define('_TPL_CC_INFO_HNUMB', 'Nummer');
define('_TPL_CC_INFO_CITY', 'Stad');
define('_TPL_CC_INFO_STATE', 'Län');
define('_TPL_CC_INFO_ZIP', 'Postnummer');
define('_TPL_CC_INFO_COUNTRY', 'Land');
define('_TPL_CC_INFO_PHONE', 'Tel');
define('_TPL_CC_INFO_PHONENUM', 'skriv telefonnummret i formatet: %s999-999-9999%s');
define('_TPL_CC_INFO_MUSTMATCH', '(måste vara lika som adressen för ditt kreditkort)');
define('_TPL_CC_INFO_SUBMIT_BUT', 'Uppdatera Info');
define('_TPL_CC_INFO_BACK_BUT', 'Tillbaka');
define('_TPL_CC_INFO_SUBMIT_BUT2', 'Anmälan');
define('_TPL_CC_INFO_SUBMIT_BUT_3', 'Anmälan och Betalning');

define('_TPL_CC_DECLINED_TITLE', 'Fel vid betalning');
define('_TPL_CC_DECLINED_TRYAGAIN', 'Försök igen');



define('_TPL_CC_INFO_BANK_IDENTIFICATION', 'Bank Identifieringen');
define('_TPL_CC_INFO_BIN_NAME', 'Bank Namn');
define('_TPL_CC_INFO_BIN_NAME_MORE', 'name om bank vilken komat ut tilltron kort');
define('_TPL_CC_INFO_BIN_PHONE', 'Bank Telefonerna');
define('_TPL_CC_INFO_BIN_PHONE_MORE', 'customer tjanst telefonerna antal katalogiserat pa rygg av din kredit kort');

define('_TPL_CC_VERIFY_CODE', 'Telephone Bekraftande Form');
define('_TPL_CC_INFO_CALLING', 'We inkallar den telefonerna antal du anklagade');
define('_TPL_CC_INFO_VERIFY_CODE', 'Verification Koden');
define('_TPL_CC_INFO_VERIFY_CODE_MORE', 'enter koden givit till du vid den roboten system');
define('_TPL_CC_INFO_SUBMIT_VERIFY', 'Fortsatta');

define('_TPL_WRONG_VERIFY_CODE', 'Wrong bekraftande koden. Behaga forsok');

define('_TPL_CC_ERROR_TNI', 'Error fordriva tiden gor telefon antalen identifieringen');
define('_TPL_CC_ERROR_TV',  'Error fordriva tiden gor telefonera till bekraftande');
define('_TPL_CC_ERROR_CARDEREMAIL', 'Error. Email is in database of high risk e-mails');
define('_TPL_CC_ERROR_COUNTRYNOTMATCH', 'Error. Country of IP address not matches billing address country');
define('_TPL_CC_ERROR_HIGHRISKCOUNTRY', 'Error. IP address or billing address country is in high risk countries list');
define('_TPL_CC_ERROR_ANONYMOUSPROXY', 'Error. Anonymous proxy are not allowed');
define('_TPL_CC_ERROR_FREEMAIL', 'Error. E-mail from free e-mail provider are not allowed');

define('_TPL_CC_ERROR_BIN', 'Error. Country of issuing bank based on BIN number not matches billing address country');
define('_TPL_CC_ERROR_BIN_NAME', 'Error. Name of issuing bank not matches inputted binName');
define('_TPL_CC_ERROR_BIN_PHONE', 'Error. Customer service phone number not matches inputed binPhone');

define('_TPL_CC_DECLINED', 'Invalid kontokorten meddela. Din kontokorten sluttat nedat');


define('_TPL_JSVAL_ERR_FORM', 'Vänligen Skriv/Välj värden för följande fält:');
define('_TPL_JSVAL_ERR_SELECT', 'Vänligen välj ett riktigt värde för fält [%FIELDNAME%]');
define('_TPL_JSVAL_ERR_ENTER', 'Vänligen skriv ett riktigt värde för fält [%FIELDNAME%]');

define('_TPL_COMMON_SELECT_STATE', '[Select state]');
define('_TPL_COMMON_SELECT_COUNTRY', '[Select country]');






define('_PLUG_PAY_ANYLINK_REDIR_ERROR', '"AnyLink URL" är inte användbar för produkt#%d. Vänligen kontakta sidans Administratör');
define('_PLUG_PAY_ANYLINK_TITLE', 'Betalning med Kreditkort');
define('_PLUG_PAY_ANYLINK_CCACCEPTED', 'alla vanliga kreditkort accepteras');





define('_PLUG_PAY_AUTHORIZE_TITLE', 'Authorize.Net Web Betalning');
define('_PLUG_PAY_AUTHORIZE_DESCR', 'kreditkort via %sauthorize.net%s');
define('_PLUG_PAY_AUTHORIZE_ERROR', 'authorize ERROR: %s (Detaljer: PNREF:%s, faktura:%s)%s%s');
define('_PLUG_PAY_AUTHORIZE_ERR_ARR', 'Fel vid betalning:');
define('_PLUG_PAY_AUTHORIZE_ERR_ARR2', 'Vänligen gå tillbaka och försök igen.');
define('_PLUG_PAY_AUTHORIZE_USER_ERR', 'skickatt belopp är tomt eller = 0');
define('_PLUG_PAY_AUTHORIZE_ERROR2', 'MD5 hash felaktigt');
define('_PLUG_PAY_AUTHORIZE_ERROR3', 'Test transaktion skickad, när aMember är konfigurerad för online process');
define('_PLUG_PAY_AUTHORIZE_ERROR4', 'fel vid avslut_väntan_betalning: %s');





define('_PLUG_PAY_AUTHORIZE_AIM_TITLE', 'Authorize AIM');
define('_PLUG_PAY_AUTHORIZE_AIM_DESC', 'Betalning med Kreditkort');

















define('_PLUG_PAY_BEANSTREAM_TITLE', 'BeanStream');
define('_PLUG_PAY_BEANSTREAM_DESC', 'Betalning med Kreditkort');
define('_PLUG_PAY_BEANSTREAM_PFAILED', 'Betalningen Misslyckades: ');





define('_PLUG_PAY_BEANSTREAM_REM_ERROR', 'beanstream_remote Fel: %s (Detaljer: PNREF:%s, faktura:%d)%s%s');
define('_PLUG_PAY_BEANSTREAM_REM_DEBUG', 'beanstream_remote Felsökning: ');
define('_PLUG_PAY_BEANSTREAM_REM_TITLE', 'BeanStream');
define('_PLUG_PAY_BEANSTREAM_REM_DESC', 'Betalning med Kreditkort');

define('_PLUG_PAY_BEANSTREAM_REM_HTML_TITLE', 'Sida för Betalning med Kreditkort');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CNAME', 'Namn på kortet');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CNAME2', '%sexakt%s som det står på kortet');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CCNUM', 'Kreditkortets Nummer');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CCEXP', 'Kreditkortets Utgångsdatum');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JAN', 'Januari');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_FEB', 'Februari');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_MAR', 'Mars');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_APR', 'April');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_MAY', 'Maj');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JUN', 'Juni');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_JUL', 'Juli');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_AUG', 'Augusti');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_SEP', 'September');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_OCT', 'Oktober');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_NOV', 'November');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_DEC', 'December');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ADDR', 'Adress');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ADDR2', '%sexakt%s adress för kreditkortet');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CITY', 'Stad');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_CITY2', '%sexakt%s stad för kreditkortets ägare');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_COUNTRY', 'Land');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_COUNTRY2', '%sexakt%s för kreditkortets ägare');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_STATE', 'Län');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_STATE2', '%sexakt%s län för kreditkortets ägare');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_ZIP', 'Postnummer');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_PHONE', 'Telefonnummer');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_PROCEED', 'Fortsätt');
define('_PLUG_PAY_BEANSTREAM_REM_HTML_FSUMB', 'detta formulär skickas till en säker server');





define('_PLUG_PAY_PAYCOM_FERROR', 'PayCom IPN ERROR: %s (Detaljer: faktura:%d)%s');
define('_PLUG_PAY_PAYCOM_ERROR', 'Fel vid betalning: %s');
define('_PLUG_PAY_PAYCOM_ERROR2', '%s Vänligen gå tillbaka och försök igen.');
define('_PLUG_PAY_PAYCOM_ERROR3', 'Lösenordet felaktigt: ');
define('_PLUG_PAY_PAYCOM_ERROR4', 'Paycom IPN: betalningen misslyckades (Detaljer: faktura:%d)%s');
define('_PLUG_PAY_PAYCOM_ERROR5', 'Test är inte tillåtet, avslutar');
define('_PLUG_PAY_PAYCOM_ERROR6', 'Felaktig produkt kod: [%d] istället för [%d]');
define('_PLUG_PAY_PAYCOM_ERROR7', 'Felaktig IP adress: %s , Tillåtna IP är: ');
define('_PLUG_PAY_PAYCOM_ERROR8', 'Felaktig co_kod');

define('_PLUG_PAY_PAYCOM_TITLE', 'PayCom');
define('_PLUG_PAY_PAYCOM_DESC', 'PayCom Betalning med Kreditkort');

define('_PLUG_PAY_PAYCOM_ERROR9', 'paycom FEL: %s');
define('_PLUG_PAY_PAYCOM_ERROR10', 'Test är inte tillåtet');

define('_PLUG_PAY_PAYCOM_HTML_TITLE', 'Paycom Payment');
define('_PLUG_PAY_PAYCOM_HTML_TEXT1', 'Vänligen klicka på "Fortsätt" för att betala med %sPaycom.net%s, vår auktoriserade betalnings agent.');
define('_PLUG_PAY_PAYCOM_HTML_SUBMBUT', 'Fortsätt');





define('_PLUG_PAY_CC_CORE_FERROR1', '\'v\' har ogiltigt värde');
define('_PLUG_PAY_CC_CORE_FERROR2', 'Medlems id är tomt');
define('_PLUG_PAY_CC_CORE_FERROR3', 'Betalnings_id är tomt');
define('_PLUG_PAY_CC_CORE_FERROR4', 'Felaktigt Namn på betalare');
define('_PLUG_PAY_CC_CORE_FERROR5', 'Betalningen är redan genomförd, vänligen gå till  %sMedlems Sidan%s');
define('_PLUG_PAY_CC_CORE_FERROR6', 'Du har redan anmält dig för en testperiod  - vänligen gå tillbaka till  <a href=\'%s/signup.php\'>Registrerings Sidan</a> och välj en annan produkt');
define('_PLUG_PAY_CC_CORE_SBSCNCL', 'Anmälan avbruten');
define('_PLUG_PAY_CC_CORE_SBSCNCL2', 'Den återkommande anmälan har avbrutits.');
define('_PLUG_PAY_CC_CORE_CCINFOCHNG', 'Info om Kreditkort ändrat');
define('_PLUG_PAY_CC_CORE_REDIR', 'Du slussas vidare till Betalningssystem');
define('_PLUG_PAY_CC_CORE_FERROR7', 'Handlingen är tom');

define('_TPL_CC_INFO_PROVINCE', 'Billing International Province');
define('_TPL_CC_INFO_PROVINCE_DESC', 'for international provinces outside of US & Canada include the province name here');
define('_TPL_CC_INFO_ISSUENUM', 'Card Issue #');
define('_TPL_CC_INFO_ISSUENUM_DESC', 'is required for Maestro/Solo/Switch credit cards only');
define('_TPL_CC_INFO_STARTDATE', 'Card Start Date');
define('_TPL_CC_INFO_STARTDATE_DESC', 'is required for Maestro/Solo/Switch credit cards only');


define('_PLUG_PAY_CC_CORE_REDIR', 'Du slussas vidare till Betalningssystem');
define('_PLUG_PAY_CC_CORE_REDIRDESC', 'Du slussas vidare till en säker sida för betalning om cirka 2 sekunder');
define('_PLUG_PAY_CC_CORE_ERROR1', 'Vänligen uppge Kreditkorts Nummer');
define('_PLUG_PAY_CC_CORE_ERROR2', 'Ogilltigt Kreditkorts Nummer');
define('_PLUG_PAY_CC_CORE_ERROR3', 'Kreditkorts Nummret är ogiltigt: ');
define('_PLUG_PAY_CC_CORE_ERROR4', 'Ogilltigt utgångsdatum - Månad');
define('_PLUG_PAY_CC_CORE_ERROR5', 'Ogilltigt utgångsdatum - År');
define('_PLUG_PAY_CC_CORE_ERROR6', 'Vänligen välj typ av kreditkort');
define('_PLUG_PAY_CC_CORE_ERROR7', 'Vänligen uppge Kreditkorts Koden');
define('_PLUG_PAY_CC_CORE_ERROR8', 'Vänligen uppge Kreditkortets Ägare');
define('_PLUG_PAY_CC_CORE_ERROR9', 'Vänligen uppge förnamnet på Kreditkortets ägare');
define('_PLUG_PAY_CC_CORE_ERROR10', 'Vänligen uppge efternamnet på Kreditkortets ägare');
define('_PLUG_PAY_CC_CORE_ERROR11', 'Vänligen uppge Företaget på Kreditkortet');
define('_PLUG_PAY_CC_CORE_ERROR12', 'Vänligen uppge Telefonnummer');
define('_PLUG_PAY_CC_CORE_ERROR13', 'Vänligen uppge Gatunummer');
define('_PLUG_PAY_CC_CORE_ERROR14', 'Vänligen uppge Gatuadress');
define('_PLUG_PAY_CC_CORE_ERROR15', 'Vänligen uppge Stad');
define('_PLUG_PAY_CC_CORE_ERROR16', 'Vänligen uppge Län');
define('_PLUG_PAY_CC_CORE_ERROR17', 'Vänligen uppge Postnummer');
define('_PLUG_PAY_CC_CORE_ERROR18', 'Vänligen uppge Land');

define('_PLUG_PAY_CC_CORE_ERROR19', 'Invalid Start Date - Month');
define('_PLUG_PAY_CC_CORE_ERROR20', 'Invalid Start Date - Year');





define('_PLUG_PAY_CC_BILL_TITLE', 'Kreditkort');
define('_PLUG_PAY_CC_BILL_DESCR', 'Betala med Mastercard, Checkcards, Discover, JCB, Electronic via www.ccbill.com');
define('_PLUG_PAY_CC_BILL_CHECK_DESCR', 'Online Check betalning via www.ccbill.com');
define('_PLUG_PAY_CC_BILL_TEL_DESCR', 'Telefonräkning via www.ccbill.com');
define('_PLUG_PAY_CC_BILL_ERROR', 'Användarnamn och lösenord kan inte vara samma, välj ett annat lösenord');





define('_PLUG_PAY_CDG_TITLE', 'CDG');
define('_PLUG_PAY_CDG_DESCR', 'Betalning med Kreditkort');





define('_PLUG_PAY_CENTIP_TITLE', 'Centipaid ');
define('_PLUG_PAY_CENTIP_DESC', '%sDigital Stored Value Cards%s');
define('_PLUG_PAY_CENTIP_FERROR', 'centipaid FEL: %s (Detaljer: PNREF:%s, faktura:%s)%s');
define('_PLUG_PAY_CENTIP_ERROR', 'Fel vid betalning: ');
define('_PLUG_PAY_CENTIP_ERROR2', ' Vänligen gå tillbaka och försök igen');
define('_PLUG_PAY_CENTIP_ERROR3', 'skickatt belopp är tomt eller = 0');
define('_PLUG_PAY_CENTIP_ERROR4', 'Test transaktion skickad, när aMember är konfigurerad för online process');
define('_PLUG_PAY_CENTIP_ERROR5', 'fel vid avslut_väntan_betalning: %s');





define('_PLUG_PAY_CLICKBANK_TITLE', 'Clickbank');
define('_PLUG_PAY_CLICKBANK_DESC', 'Se %swww.clickbank.com%s för beskrivning');
define('_PLUG_PAY_CLICKBANK_INCORRECT', 'Fel vid sändning #%d. Kontakta webmastern');
define('_PLUG_PAY_CLICKBANK_ERROR', 'fel vid avslut_väntan_betalning: ');





define('_PLUG_PAY_DIRECTONE_TITLE', 'DirectOne');
define('_PLUG_PAY_DIRECTONE_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_DIRECTONEREM_TITLE', 'Betalning med Kreditkort (DirectOne)');
define('_PLUG_PAY_DIRECTONEREM_DESC', 'Se %swww.directone_remote.com%s för beskrivning');
define('_PLUG_PAY_DIRECTONEREM_RETLNK', 'Tillbaka till Medlems Sidan');
define('_PLUG_PAY_DIRECTONEREM_ERROR', 'directone FEL: %s (Detaljer: PNREF:%s, faktura:%d)%s');





define('_PLUG_PAY_PAYMENOW_TITLE', 'PayMeNow');
define('_PLUG_PAY_PAYMENOW_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_PAYMONDE_TITLE', 'PayMonde');
define('_PLUG_PAY_PAYMONDE_DESC', 'Se %swww.paymonde.com%s för beskrivning');

define('_PLUG_PAY_PAYMONDE_FERROR', 'paymonde FEL: %s (Detaljer: betalnings_id:%d, faktura:%d)');
define('_PLUG_PAY_PAYMONDE_ERROR', 'OGILTIGT svar från PayMonde server.  Möjligt hack försök.');





define('_PLUG_PAY_CC_DEMO_TITLE', 'CCProv');
define('_PLUG_PAY_CC_DEMO_DESCR', 'Prov Kreditkorts Betalning - använd  4111-1111-1111-1111 som kreditkorts nummer #');
define('_PLUG_PAY_CC_DEMO_CCNUM', 'Vänligen uppge kreditkorts nummer# 4111-1111-1111-1111 för att göra ett fullständigt test');





define('_PLUG_PAY_ECHO_TITLE', 'ECHO');
define('_PLUG_PAY_ECHO_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_EFSNET_TITLE', 'EFSNet');
define('_PLUG_PAY_EFSNET_DESC', 'Betalning med Kreditkort');
define('_PLUG_PAY_EFSNET_ERROR', 'Betalningen hittades inte: #%d');
define('_PLUG_PAY_EFSNET_ERROR2', 'Betalningen är redan gjord: #%d');
define('_PLUG_PAY_EFSNET_ERROR3 ', 'Betalningen är gjord för annat betalsystem: %d (#%d)');
define('_PLUG_PAY_EFSNET_ERROR4', 'Betalningen är gjord för en annan medlem: #%d');
define('_PLUG_PAY_EFSNET_ERROR5', 'Medlemmen hittades inte: #%d');
define('_PLUG_PAY_EFSNET_ERROR6', 'aMember: Tomt resultat från prosessen, betalningen misslyckades');





define('_PLUG_PAY_EGOLD_TITLE', 'E-Gold');
define('_PLUG_PAY_EGOLD_DESC', 'Betala med e-gold (see %swww.e-gold.com%s for description)');
define('_PLUG_PAY_EGOLD_ERROR', 'EGOLD ERROR: %s (Detaljer: PAYMENT_BATCH_NUM:%d, faktura:%d)%s');
define('_PLUG_PAY_EGOLD_ERROR2', 'Betalningsmottagare är  %s istället för mig: ');
define('_PLUG_PAY_EGOLD_ERROR3', 'Betalningen är i en annan enhet: %s istället för tillåtna %s');
define('_PLUG_PAY_EGOLD_ERROR4', 'V2_HASH fel %s istället för: %s');





define('_PLUG_PAY_EMATTERS_TITLE', 'eMatters.com.au');
define('_PLUG_PAY_EMATTERS_DESC', 'Betalning med Kreditkort');
define('_PLUG_PAY_EMATTERS_ERROR', 'Transaktionen nekades%s. Vänligen försök igen');
define('_PLUG_PAY_EMATTERS_CODE0', 'Transaktionen godtogs.');
define('_PLUG_PAY_EMATTERS_CODE1', 'Transaktionen nekades. Rådfråga kortets utfärdare.');
define('_PLUG_PAY_EMATTERS_CODE2', 'Transaktionen nekades. Kontakta auktorisations Centret.');
define('_PLUG_PAY_EMATTERS_CODE3', 'Transaktionen godtogs. Vänligen signera kvittot.');
define('_PLUG_PAY_EMATTERS_CODE4', 'Transaktionen nekades. Ogiltig typ av transaktion.');
define('_PLUG_PAY_EMATTERS_CODE5', 'Transaktionen nekades. Rådfråga kortets utfärdare.');
define('_PLUG_PAY_EMATTERS_CODE6', 'Transaktionen nekades. Inget KREDIT konto.');
define('_PLUG_PAY_EMATTERS_CODE7', 'Transaktionen nekades. Otillräckligt med medel.');
define('_PLUG_PAY_EMATTERS_CODE8', 'Transaktionen nekades. Över kortets limit.');
define('_PLUG_PAY_EMATTERS_CODE9', 'Transaktionen nekades. Utfärdare inte disponibel.');
define('_PLUG_PAY_EMATTERS_CODE10', 'Icke-Unik UID - Redan accepterad');
define('_PLUG_PAY_EMATTERS_CODE11', 'Transaktionen godtogs - Felaktig korttyp');
define('_PLUG_PAY_EMATTERS_CODE12', 'Felaktig Köpsumma');
define('_PLUG_PAY_EMATTERS_CODE13', 'Ogiltigt Kortnummer');
define('_PLUG_PAY_EMATTERS_CODE14', 'Ogiltigt format på Utgångsdatum');
define('_PLUG_PAY_EMATTERS_CODE15', 'Kortet har Gått Ut');
define('_PLUG_PAY_EMATTERS_CODE16', 'Host Hittades Inte, Banksystemet ur funktion');
define('_PLUG_PAY_EMATTERS_CODE17', 'Transaktionen misslyckades, Banksystemet ur funktion');
define('_PLUG_PAY_EMATTERS_ERROR', 'Transaktionen nekades%s. Vänligen försök igen');

define('_PLUG_PAY_EMATTERS_HTML_TITLE', 'Konfirmation av Betalning');
define('_PLUG_PAY_EMATTERS_HTML_SELECTC', 'välj kort');
define('_PLUG_PAY_EMATTERS_HTML_CCNUM', 'Kreditkorts Nummer');
define('_PLUG_PAY_EMATTERS_HTML_CCEXP', 'Kreditkortets Utgångsdatum');
define('_PLUG_PAY_EMATTERS_HTML_CCHNAME', 'Kreditkortets Ägare, Namn på kortet');
define('_PLUG_PAY_EMATTERS_HTML_GOTOSITE', 'Gå till säker sida');
define('_PLUG_PAY_EMATTERS_HTML_FORMSUBM', 'Detta formulär skickas till en säkrad server.');
define('_PLUG_PAY_EMATTERS_HTML_CCTYPE', 'Typ av Kreditkort');





define('_PLUG_PAY_EPASSPORT_TITLE', 'Epassporte');
define('_PLUG_PAY_EPASSPORT_DESC', 'Epassporte Betalnings System');
define('_PLUG_PAY_EPASSPORT_HTML_TITLE', 'Paycom Betalning');
define('_PLUG_PAY_EPASSPORT_HTML_CLICKPAY', 'Vänligen klicka på "Pay by ePassporte" knappen för att betala med ePassporte, vår auktoriserade betalningsagent.');
define('_PLUG_PAY_EPASSPORT_ERROR', 'epassporte FEL:');
define('_PLUG_PAY_EPASSPORT_ERROR2', 'Fel vid betalning: ');
define('_PLUG_PAY_EPASSPORT_ERROR3', ' Vänligen gå tillbaka och försök igen.');

define('_PLUG_PAY_EPASSPORT_ERROR4', 'Epassporte IPN FEL: %s (Detaljer: faktura:%d)%s');
define('_PLUG_PAY_EPASSPORT_ERROR5', 'Epassporte IPN: betalningen misslyckades (Detaljer: faktura:%d)%s');
define('_PLUG_PAY_EPASSPORT_ERROR6', 'Felaktigt kontonummer');
define('_PLUG_PAY_EPASSPORT_ERROR7', 'Felaktig IP adress: %s , tillåtna IP mask är: ');
define('_PLUG_PAY_EPASSPORT_ERROR8', 'Felaktigt Lösenord: %s');
define('_PLUG_PAY_EPASSPORT_ERROR9', 'Denna transaktion avslogs: ');
define('_PLUG_PAY_EPASSPORT_ERROR10', 'Tack för din betalning!');
define('_PLUG_PAY_EPASSPORT_ERROR11', 'Fel vid Verifiering av Transaktion: ');
define('_PLUG_PAY_EPASSPORT_ERROR12', 'ePassporte IPN: Transaktionen för betalning %d var accepterad och verifierad');





define('_PLUG_PAY_EPROCESSING_TITLE', 'eProcessingNetwork');
define('_PLUG_PAY_EPROCESSING_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_EWAY_TITLE', 'E-Way');
define('_PLUG_PAY_EWAY_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_FREE_ID', 'fritt');
define('_PLUG_PAY_FREE_TITLE', 'Fri Registrering');
define('_PLUG_PAY_FREE_DESC', 'Helt fritt');
define('_PLUG_PAY_FREE_NOTFORFREE', 'Fri registrering kan inte användas när produkten kostar mer än 0.00');
define('_PLUG_PAY_FREE_ERROR', 'Felaktig registrerings kod. Vänligen kontakta sidans Administratör.');
define('_PLUG_PAY_FREE_MAILSENT', 'Mailet har redan skickats till Admin. Vänligen vänta på svaret.');
define('_PLUG_PAY_FREE_SIGNEDUP', 'Du är redan Registrerad. Vänligen %slogga in%s här');





define('_PLUG_PAY_GLOBILL_ID', 'globill');
define('_PLUG_PAY_GLOBILL_TITLE', 'Glo-Bill Kreditkort');
define('_PLUG_PAY_GLOBILL_DESC', 'Betala med Visa, Mastercard, Checkcards, Discover, Eurocard, JCB, Diners cards, Electronic  via  %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_PH_ID', 'globill_phone');
define('_PLUG_PAY_GLOBILL_PH_TITLE', 'Glo-Bill Phone');
define('_PLUG_PAY_GLOBILL_PH_DESC', 'Betala enkelt med telefon betalning #900 via  %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_CH_ID', 'globill_check');
define('_PLUG_PAY_GLOBILL_CH_TITLE', 'Glo-Bill Check');
define('_PLUG_PAY_GLOBILL_CH_DESC', 'Betala med online check via %swww.globill.com%s');

define('_PLUG_PAY_GLOBILL_CANNOTORDER', 'Denna produkt kan inte beställas med GloBill Kreditkort');
define('_PLUG_PAY_GLOBILL_CANNOTORDER2', 'Denna produkt kan inte beställas med GloBill Telefon betalning');
define('_PLUG_PAY_GLOBILL_CANNOTORDER3', 'Denna produkt kan inte beställas med GloBill Online Check');
define('_PLUG_PAY_GLOBILL_ERROR', 'Internt Fel: okänt paysys_id: %d');
define('_PLUG_PAY_GLOBILL_FERROR', 'GLOBILL FEL: %s (Detaljer: PNREF:%s, faktura:%d)%s');
define('_PLUG_PAY_GLOBILL_ERROR2', 'Felaktigt webmaster användarnamn : %s!');





define('_PLUG_PAY_IKOBO_TITLE', 'ikobo');
define('_PLUG_PAY_IKOBO_DESC', 'säker betalning med kreditkort');
define('_PLUG_PAY_IKOBO_ERROR', 'Felaktigt lösenord');





define('_PLUG_PAY_INTERSEC_TITLE', 'InternetSecure');
define('_PLUG_PAY_INTERSEC_DESC', 'Betalning med Kreditkort');
define('_PLUG_PAY_INTERSEC_ERROR', 'Felaktig Sändning. Vänligen kontakta webmastern');





define('_PLUG_PAY_IPAYMENT_TITLE', 'IPayment.DE');
define('_PLUG_PAY_IPAYMENT_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_LINKPOINT_TITLE', 'LinkPoint');
define('_PLUG_PAY_LINKPOINT_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_MANCC_FERROR', 'Du måste vara behörig för att göra det');
define('_PLUG_PAY_MANCC_FERROR2', 'Betalnings ID är inte specifierat');
define('_PLUG_PAY_MANCC_FERROR3', 'Kan inte ladda medlems info #%d (%d)');
define('_PLUG_PAY_MANCC_ERROR', 'Ogiltigt Kreditkorts Nummer');
define('_PLUG_PAY_MANCC_ERROR2', 'Ogiltigt Utgångsdatum - Månad');
define('_PLUG_PAY_MANCC_ERROR3', 'Ogiltigt Utgångsdatum - År');
define('_PLUG_PAY_MANCC_ERROR4', 'Vänligen skriv gatuadress');
define('_PLUG_PAY_MANCC_ERROR5', 'Vänligen skriv stad');
define('_PLUG_PAY_MANCC_ERROR6', 'Vänligen skriv län');
define('_PLUG_PAY_MANCC_ERROR7', 'Vänligen skriv postnummer');
define('_PLUG_PAY_MANCC_ERROR8', 'Vänligen välj land');
define('_PLUG_PAY_MANCC_ID', 'manual_cc');
define('_PLUG_PAY_MANCC_TITLE', 'Kreditkort');
define('_PLUG_PAY_MANCC_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_LOGICCOM_TITLE', 'LogicCommerce');
define('_PLUG_PAY_LOGICCOM_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_MONEYBOOK_ERROR', 'MD5 har fel: vi har %s, men kalkulerat är %s (från %s)');
define('_PLUG_PAY_MONEYBOOK_ERROR2', 'moneybookers FEL: %s (Detaljer: txn_id:%d, faktura:%d)%s');
define('_PLUG_PAY_MONEYBOOK_ERROR3', 'Denna sida ska inte hämtas av webläsare');
define('_PLUG_PAY_MONEYBOOK_ERROR4', 'Betalningsmottagare är %s istället för mitt företag: ');
define('_PLUG_PAY_MONEYBOOK_ERROR5', 'Betalningen är inte genomförd, status: ');

define('_PLUG_PAY_MONEYBOOK_TITLE', 'MoneyBookers');
define('_PLUG_PAY_MONEYBOOK_DESC', 'Se %swww.moneybookers.com%s för beskrivning');





define('_PLUG_PAY_MULTICARD_ERROR', 'multicards FEL: %s (Detaljer: PNREF:%s, faktura:%d)%s');
define('_PLUG_PAY_MULTICARD_ERROR2', 'Fel vid behandling av betalning: ');
define('_PLUG_PAY_MULTICARD_ERROR3', 'Vänligen gå tillbaka och försök igen.');
define('_PLUG_PAY_MULTICARD_ERROR4', 'Betalningen misslyckades');
define('_PLUG_PAY_MULTICARD_ERROR5', 'beloppet som kom tillbaka är tomet eller = 0');
define('_PLUG_PAY_MULTICARD_ERROR6', 'Felaktig IP adress');
define('_PLUG_PAY_MULTICARD_ERROR7', 'Felaktigt säljar id');

define('_PLUG_PAY_MULTICARD_TITLE', 'Multi-Cards');
define('_PLUG_PAY_MULTICARD_DESCR', 'Multi-Cards Kreditkorts Betalning');

define('_PLUG_PAY_MULTICARD_HTML_TITLE', 'MultiCards Betalnings Sida');
define('_PLUG_PAY_MULTICARD_HTML_CNAME', 'Namn på Kortet');
define('_PLUG_PAY_MULTICARD_HTML_4CONT', 'för kontakt');
define('_PLUG_PAY_MULTICARD_HTML_EMAIL', 'Kontakt E-Post');
define('_PLUG_PAY_MULTICARD_HTML_4CONTE', 'för kontakt');
define('_PLUG_PAY_MULTICARD_HTML_CNAME', 'Namn på Kortet');
define('_PLUG_PAY_MULTICARD_HTML_ASONCC', '%sexakt%s som det står på kortet');
define('_PLUG_PAY_MULTICARD_HTML_ADDRESS', 'Adress');
define('_PLUG_PAY_MULTICARD_HTML_ADDOFCC', '%sexakt%s adress för kreditkortet');
define('_PLUG_PAY_MULTICARD_HTML_CITY', 'Stad');
define('_PLUG_PAY_MULTICARD_HTML_EXCITY', '%sexakt%s stad + Postnummer (exkl USA) för kreditkortets %sägare, ex. %sLondon E12 6HB%s');
define('_PLUG_PAY_MULTICARD_HTML_COUNTRY', 'Land');
define('_PLUG_PAY_MULTICARD_HTML_EXCOUNTRY', '%sexakt%s land för kreditkortets ägare');
define('_PLUG_PAY_MULTICARD_HTML_STATE', 'Län');
define('_PLUG_PAY_MULTICARD_HTML_EXSTATE', '%sexakt%s län för kreditkortets ägare');
define('_PLUG_PAY_MULTICARD_HTML_ZIP', 'Postnummer');
define('_PLUG_PAY_MULTICARD_HTML_EXZIP', '%sexakt%s Postnummer för kreditkortets ägare  %skreditkortets ägare i USA');
define('_PLUG_PAY_MULTICARD_HTML_IFNOTUSA', '(om inte i USA, skriv %s99999%s)');
define('_PLUG_PAY_MULTICARD_HTML_SUB_BUT', 'Fortsätt');





define('_PLUG_PAY_NETBILLING_FERROR', 'Medlems ID är inte specifiserat');
define('_PLUG_PAY_NETBILLING_FERROR2', 'Du måste vara behörig för att göra det');
define('_PLUG_PAY_NETBILLING_FERROR3', 'Betalnings ID är inte specifiserat');
define('_PLUG_PAY_NETBILLING_FERROR4', 'Kan inte ladda medlems info #%d (%d)');
define('_PLUG_PAY_NETBILLING_ERROR', 'Ogiltigt Kreditkorts nummer');
define('_PLUG_PAY_NETBILLING_ERROR2', 'Ogiltigt utgångsdatum - Månad');
define('_PLUG_PAY_NETBILLING_ERROR3', 'Ogiltigt utgångsdatum - År');
define('_PLUG_PAY_NETBILLING_ERROR4', 'Vänligen skriv in kreditkortets kod');
define('_PLUG_PAY_NETBILLING_ERROR5', 'Vänligen uppge gatuadress');
define('_PLUG_PAY_NETBILLING_ERROR6', 'Vänligen uppge stad');
define('_PLUG_PAY_NETBILLING_ERROR7', 'Vänligen uppge län');
define('_PLUG_PAY_NETBILLING_ERROR8', 'Vänligen uppge Postnummer');
define('_PLUG_PAY_NETBILLING_ERROR9', 'Vänligen uppge land');

define('_PLUG_PAY_NETBILLING_TITLE', 'NetBilling');
define('_PLUG_PAY_NETBILLING_CC_PAYMENT', 'Betalning med Kreditkort');

define('_PLUG_PAY_NETBILLING_FERROR5', 'Inget Användarnamn är konfigurerat för NetBilling');
define('_PLUG_PAY_NETBILLING_PNOTFOUND', 'Betalningen hittades inte: #%d');
define('_PLUG_PAY_NETBILLING_PCOMPLETED', 'Betalningen är redan genomförd: #%d');
define('_PLUG_PAY_NETBILLING_ANOTHERPSYS', 'Betalningen skapades för ett annat betalningssystem:');
define('_PLUG_PAY_NETBILLING_ANOTHERMEMBER', 'Betalningen skapades för en annan medlem: #%d');
define('_PLUG_PAY_NETBILLING_MEMNOTFOUND', 'Medlemen hittades inte: #%d');
define('_PLUG_PAY_NETBILLING_EMPTYRES', 'aMember: Tomt resultat från systemet, betalningen misslyckades');





define('_PLUG_PAY_NOCHEX_FERROR', 'nochex FEL: %s (Detaljer: txn_id:%d, faktura:%d)%s');
define('_PLUG_PAY_NOCHEX_ERROR', 'IPN sidan måste tillträdas endast av nochex, inte av kunder');
define('_PLUG_PAY_NOCHEX_ERROR2', 'Betalningsmottagare är %s istället för mitt företag: ');
define('_PLUG_PAY_NOCHEX_ERROR3', 'AVSLÅENDE svar från nochex server. Möjligt försök till hacking (%s)');
define('_PLUG_PAY_NOCHEX_ERROR4', 'Inte några VERIFIERADE eller OGILTIGA ord hittades i svaret (%s)');

define('_PLUG_PAY_NOCHEX_TITLE', 'NoChex');
define('_PLUG_PAY_NOCHEX_DESC', 'Säker Betalning med Kreditkort');





define('_PLUG_PAY_OFFLINE_TITLE', 'Offline Betalning');
define('_PLUG_PAY_OFFLINE_DESC', 'Offline Betalning');

define('_PLUG_PAY_OFFLINE_HTML_HEAD', 'Ändra denna fil');
define('_PLUG_PAY_OFFLINE_HTML_HEAD2', 'för att måta dina behov för offline betalning.');
define('_PLUG_PAY_OFFLINE_HTML_PUSR', 'Betalning#/Användarnamn: ');
define('_PLUG_PAY_OFFLINE_HTML_PRICE', 'Pris:     ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT1', 'Infoga instruktioner här för kunder hur dom ska betala.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT2', 'Försäkra dig om att dina kunder uppger sitt Användarnamn (inloggningsnamn) och betalning#');
define('_PLUG_PAY_OFFLINE_HTML_TEXT3', 'för betalningarna i beskrivningen. Det blir då lättare för dig att hitta dessa ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT4', 'order senare.');
define('_PLUG_PAY_OFFLINE_HTML_TEXT5', 'När du mottagit betalning, markera betalningen som "Slutförd"');
define('_PLUG_PAY_OFFLINE_HTML_TEXT6', 'i aMember kontroll panel. Användaren får ett meddelande med inloggnings info ');
define('_PLUG_PAY_OFFLINE_HTML_TEXT7', 'och kan då logga in på medlemssidorna.');





define('_PLUG_PAY_OGONE_TITLE', 'Ogone');
define('_PLUG_PAY_OGONE_DESC', 'säker Betalning med Kreditkort');
define('_PLUG_PAY_OGONE_ERROR', 'Okänd kod för STATUS: [%s]');
define('_PLUG_PAY_OGONE_ERROR2', 'mottaget belopp är tomt eller = 0');





define('_PLUG_PAY_PSWDCALL_FERROR', 'passwordcall FEL: %s (Detaljer: txn_id:%d, faktura:%d)%s');
define('_PLUG_PAY_PSWDCALL_ERROR', 'Falskt webmaster id: %d');
define('_PLUG_PAY_PSWDCALL_TITLE', 'PasswordCall');
define('_PLUG_PAY_PSWDCALL_DESC', 'Se %swww.passwordcall.de%s för beskrivning');





define('_PLUG_PAY_BLUEPAY_TITLE', 'BluePay');
define('_PLUG_PAY_BLUEPAY_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_PAYFLINK_FERROR', 'PAYFLOW FEL: %s (Detaljer: PNREF:%s, faktura:%d)%s');
define('_PLUG_PAY_PAYFLINK_ERROR', 'mottaget belopp är tomt eller = 0');

define('_PLUG_PAY_PAYFLINK_TITLE', 'PayFlow Link');
define('_PLUG_PAY_PAYFLINK_DESC', 'Se %swww.verisign.com%s för beskrivning');





define('_PLUG_PAY_PAYFLPRO_TITLE', 'PayFlow Pro');
define('_PLUG_PAY_PAYFLPRO_DESC', 'Betalning med Kreditkort');
define('_PLUG_PAY_PAYFLPRO_ERROR', 'PayFlow plugin konfigurations fel: filen %s%s%s finns inte');
define('_PLUG_PAY_PAYFLPRO_ERROR2', 'PayFlow plugin konfigurations fel: filen %s%s%s är inte skrivbar. Vänligen ändra rättigheter (chmod) denna fil till 755');
define('_PLUG_PAY_PAYFLPRO_FERROR', 'Kan inte köra betalnings scriptet');
define('_PLUG_PAY_PAYFLPRO_ERROR3', 'Fel vid körning av pfpro script, resultatet som gavs: %s');
define('_PLUG_PAY_PAYFLPRO_CCDECL', 'Kortet nekades. Försäkra dig om att adressen som uppgavs är samma som på kreditkortets saldobesked');





define('_PLUG_PAY_PYMGTWAY_TITLE', 'PaymentsGateway');
define('_PLUG_PAY_PYMGTWAY_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_EGSPAY_TITLE', 'AC Pay');
define('_PLUG_PAY_EGSPAY_DESC', 'Se <a href="http://www.egspay.com" target=_blank>www.egspay.com</a> för beskrivning');
define('_PLUG_PAY_EGSPAY_ERROR', 'egspay FEL: %s (Detaljer: faktura:%d)%s');





define('_PLUG_PAY_PAYPALR_INVEMAIL', 'Ogiltig E-Post: $email, skickades');
define('_PLUG_PAY_PAYPALR_IDEMPTY', 'Anmälnings id är tomt för %s');
define('_PLUG_PAY_PAYPALR_NOPAYMENTS', 'Ingen betalnings info hittades för');
define('_PLUG_PAY_PAYPALR_2MUCHREC', 'För många (>1) betalnings informationer hittades för');

define('_PLUG_PAY_PAYPALR_TITLE', 'PayPal');
define('_PLUG_PAY_PAYPALR_DESC', 'säker Betalning med Kreditkort');
define('_PLUG_PAY_PAYPALR_FERROR', 'Period måste vara i intervall 1-5 år');
define('_PLUG_PAY_PAYPALR_FERROR2', 'Period måste vara i intervall 1-24 månader');
define('_PLUG_PAY_PAYPALR_FERROR3', 'Period måste vara i intervall 1-52 veckor');
define('_PLUG_PAY_PAYPALR_FERROR4', 'Period måste vara i intervall 1-90 dagar');
define('_PLUG_PAY_PAYPALR_FERROR5', 'Okänd enhet för period: %s');
define('_PLUG_PAY_PAYPALR_FERROR6', 'Ogiltigt värde för utgångsdagar: ');
define('_PLUG_PAY_PAYPALR_FERROR7', 'Följande kombination av produkter (engångs och återkommande) kan inte beställas samtidigt. Vänligen börja med den ena produkten, gå sedan tillbaka för att beställa dom andra i tur och ordning');
define('_PLUG_PAY_PAYPALR_FERROR8', 'Följande kombination av produkter kan inte beställas samtidigt. Vänligen börja med den ena produkten, gå sedan tillbaka för att beställa dom andra i tur och ordning');
define('_PLUG_PAY_PAYPALR_FERROR9', 'Det finns produkter med olika betalnings valutor. Det går inte att genomföra denna order - vänligen ändra detta');
define('_PLUG_PAY_PAYPALR_ERROR', 'Kan inte validera PayPal IPN post: FOPEN [%s] resultat till [%s (%s)]');
define('_PLUG_PAY_PAYPALR_ERROR2', 'Paypal säger att detta inte är en giltig IPN transaktion: [%s]');
define('_PLUG_PAY_PAYPALR_ERROR3', 'FEL vid IPN: %s');
define('_PLUG_PAY_PAYPALR_ERROR4', 'Betalningsmottagarens E-post [%s] är okänd, betalningen ignorerades.<br />');
define('_PLUG_PAY_PAYPALR_ERROR5', 'Om detta är fel, vänligen lägg till e-post adressen  %s at aMember CP -> Setup -> PayPal');
define('_PLUG_PAY_PAYPALR_ERROR6', 'Paypal betalnings status är [%s], IPN meddelande kommer att ignoreras<br />');
define('_PLUG_PAY_PAYPALR_ERROR7', 'Det är inte ett fel eller problem, endast ett status meddelande för din information');
define('_PLUG_PAY_PAYPALR_ERROR8', 'Paypal betalningsvaluta är [%s] istället för väntad [%s]');
define('_PLUG_PAY_PAYPALR_ERROR9', 'belopp som skickats är [%d], ska vara [%d]');
define('_PLUG_PAY_PAYPALR_ERROR11', 'Kan inte hitta motsvarande aMember betalning för denna betalning');
define('_PLUG_PAY_PAYPALR_ERROR12', 'Coupons kunde inte bli brukat med PayPal provningen , behaga komma i kontakt med administratoren');





define('_PLUG_PAY_PAYRDY_FERROR', 'Du måste vara behörig för att göra det');
define('_PLUG_PAY_PAYRDY_FERROR2', 'Betalnings ID är inte specifiserad');
define('_PLUG_PAY_PAYRDY_FERROR3', 'Kan inte ladda medlems info #%d (%d)');
define('_PLUG_PAY_PAYRDY_ERROR', 'Vänligen välj typ av kreditkort');
define('_PLUG_PAY_PAYRDY_ERROR2', 'Ogiltigt kreditkorts nummer');
define('_PLUG_PAY_PAYRDY_ERROR3', 'Ogiltigt utgångsdatum - Månad');
define('_PLUG_PAY_PAYRDY_ERROR4', 'Ogiltigt utgångsdatum - År');
define('_PLUG_PAY_PAYRDY_ERROR5', 'Vänligen uppge gatuadress');
define('_PLUG_PAY_PAYRDY_ERROR6', 'Vänligen uppge stad');
define('_PLUG_PAY_PAYRDY_ERROR7', 'Vänligen uppge län');
define('_PLUG_PAY_PAYRDY_ERROR8', 'Vänligen uppge postnummer');
define('_PLUG_PAY_PAYRDY_ERROR9', 'Vänligen uppge land');

define('_PLUG_PAY_PAYRDY_ERROR10', 'Betalningen hittades inte: #%d');
define('_PLUG_PAY_PAYRDY_ERROR11', 'Betalningen är redan genomförd: #%d');
define('_PLUG_PAY_PAYRDY_ERROR12', 'Betalningen är skapad för ett annat betalningssystem: ');
define('_PLUG_PAY_PAYRDY_ERROR13', 'aMember: Tomt resultat från betalningssystemet, betalningen misslyckades');
define('_PLUG_PAY_PAYRDY_ERROR14', 'Fel vid betalning: ');

define('_PLUG_PAY_PAYRDY_TITLE', 'PayReady');
define('_PLUG_PAY_PAYRDY_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_PAYZIP_TITLE', 'PayZIP');
define('_PLUG_PAY_PAYZIP_DESC', 'säker Betalning med Kreditkort');
define('_PLUG_PAY_PAYZIP_ERROR', 'Dålig anslutning ');
define('_PLUG_PAY_PAYZIP_FERROR', 'Ingen kontakt med PayZIP - transaktion avslutad. Vänligen försök senare.');





define('_PLUG_PAY_PLUGNPAY_FERROR', 'Medlems ID är inte specifiserat');
define('_PLUG_PAY_PLUGNPAY_FERROR2', 'Du måste vara behörig för att göra det');
define('_PLUG_PAY_PLUGNPAY_FERROR3', 'Betalnings ID är inte specifiserat');
define('_PLUG_PAY_PLUGNPAY_FERROR4', 'Kan inte ladda medlems info #%d (%d)');
define('_PLUG_PAY_PLUGNPAY_ERROR', 'inget svar från plugnpay, betalning #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR2', 'Ogiltigt utgångsdatum - Månad');
define('_PLUG_PAY_PLUGNPAY_ERROR3', 'Ogiltigt utgångsdatum - År');
define('_PLUG_PAY_PLUGNPAY_ERROR4', 'Vänligen uppge kreditkortets kod');
define('_PLUG_PAY_PLUGNPAY_ERROR5', 'Vänligen uppge gatuadress');
define('_PLUG_PAY_PLUGNPAY_ERROR6', 'Vänligen uppge stad');
define('_PLUG_PAY_PLUGNPAY_ERROR7', 'Vänligen uppge län');
define('_PLUG_PAY_PLUGNPAY_ERROR8', 'Vänligen uppge postnummer');
define('_PLUG_PAY_PLUGNPAY_ERROR9', 'Vänligen uppge land');
define('_PLUG_PAY_PLUGNPAY_ERROR10', 'Betalningen hittades inte: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR11', 'Betalningen är redan genomförd: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR12', 'Betalningen skapades för ett annat betalnings system');
define('_PLUG_PAY_PLUGNPAY_ERROR13', 'Medlemen hittades inte: #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR14', 'Tomt resultat, betalningen misslyckades #%d');
define('_PLUG_PAY_PLUGNPAY_ERROR15', 'aMember: Tomt resultat mottogs, betalningen misslyckades');

define('_PLUG_PAY_PLUGNPAY_TITLE', 'PlugNPay');
define('_PLUG_PAY_PLUGNPAY_DESC', 'Betalning med Kreditkort');
define('_PLUG_PAY_PLUGNPAY_ERROR', 'inget svar från plugnpay, betalning #%d');





define('_PLUG_PAY_PROBILLING_FERROR', 'PROBILLING FEL: %s (Detaljer: PNREF:%s, faktura:%d)<br />');
define('_PLUG_PAY_PROBILLING_ERROR', 'Status är inte NY eller BETALD');
define('_PLUG_PAY_PROBILLING_TITLE', 'ProBilling');
define('_PLUG_PAY_PROBILLING_DESC', 'Acceptera kreditkort, e-checkar och kan handha telefonbetalning med 900 nummer');





define('_PLUG_PAY_PROTX_TITLE', 'Protx');
define('_PLUG_PAY_PROTX_DESC', 'Betala med kreditkort/debetkort - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');

define('_PLUG_PAY_PROTX_HTML_TITLE', 'Fortsätt till säker betalnings sida');





define('_PLUG_PAY_PSIGATE_TITLE', 'PsiGate');
define('_PLUG_PAY_PSIGATE_DESC', 'Betalning med Kreditkort');
define('_PLUG_PAY_PSIGATE_ERROR', 'Internt Fel');

define('_PLUG_PAY_PSIGATE_HTML_TITLE', 'Betalning med Kreditkort Page');
define('_PLUG_PAY_PSIGATE_HTML_CNAME', 'Namn på kortet');
define('_PLUG_PAY_PSIGATE_HTML_ASONCC', '%sexakt%s som det står på kortet');
define('_PLUG_PAY_PSIGATE_HTML_CCNUM', 'Kreditkorts Nummer');
define('_PLUG_PAY_PSIGATE_HTML_CCEXP', 'Kreditkortets Utgångsdatum');
define('_PLUG_PAY_PSIGATE_HTML_JAN', 'Januari');
define('_PLUG_PAY_PSIGATE_HTML_FEB', 'Februari');
define('_PLUG_PAY_PSIGATE_HTML_MAR', 'Mars');
define('_PLUG_PAY_PSIGATE_HTML_APR', 'April');
define('_PLUG_PAY_PSIGATE_HTML_MAY', 'Maj');
define('_PLUG_PAY_PSIGATE_HTML_JUN', 'Juni');
define('_PLUG_PAY_PSIGATE_HTML_JUL', 'Juli');
define('_PLUG_PAY_PSIGATE_HTML_AUG', 'Augusti');
define('_PLUG_PAY_PSIGATE_HTML_SEP', 'September');
define('_PLUG_PAY_PSIGATE_HTML_OCT', 'Oktober');
define('_PLUG_PAY_PSIGATE_HTML_NOV', 'November');
define('_PLUG_PAY_PSIGATE_HTML_DEC', 'December');
define('_PLUG_PAY_PSIGATE_HTML_ADDR', 'Adress');
define('_PLUG_PAY_PSIGATE_HTML_ADOFCC', '%sexakt%s adress som kreditkortets');
define('_PLUG_PAY_PSIGATE_HTML_CITY', 'Stad');
define('_PLUG_PAY_PSIGATE_HTML_CTOFCC', '%sexakt%s stad för kreditkortets %sägare');
define('_PLUG_PAY_PSIGATE_HTML_COUNTRY', 'Land');
define('_PLUG_PAY_PSIGATE_HTML_CNOFCC', '%sexakt%s land för kreditkortets ägare');
define('_PLUG_PAY_PSIGATE_HTML_STATE', 'Län');
define('_PLUG_PAY_PSIGATE_HTML_STOFCC', '%sexakt%s län för kreditkortets ägare');
define('_PLUG_PAY_PSIGATE_HTML_ZIP', 'Postnummer');
define('_PLUG_PAY_PSIGATE_HTML_SUBBUT', 'Fortsätt');
define('_PLUG_PAY_PSIGATE_HTML_DESCR', 'detta formulär skickas till en säker server');





define('_PLUG_PAY_QCHEX_TITLE', 'QChex');
define('_PLUG_PAY_QCHEX_DESC', 'Betala med check (se %swww.qchex.com%s för beskrivning)');





define('_PLUG_PAY_SECURTRD_FERROR', 'securetrading FEL: %s (Detaljer: txn_id:%d, faktura:%d)%s');
define('_PLUG_PAY_SECURTRD_TITLE', 'SecureTrading');
define('_PLUG_PAY_SECURTRD_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_STORMPAY_FERROR', 'StormPay FEL: %s (Detaljer: txn_id:%d, faktura:%d)%s');
define('_PLUG_PAY_STORMPAY_ERROR', 'Falsk säkerhets kod: %s');
define('_PLUG_PAY_STORMPAY_ERROR2', 'Betalningsmottagare är %s istället för mitt företag: ');
define('_PLUG_PAY_STORMPAY_ERROR3', 'Betalningen är inte genomförd, status: %s');

define('_PLUG_PAY_STORMPAY_TITLE', 'StormPay');
define('_PLUG_PAY_STORMPAY_DESC', 'Se %swww.stormpay.com%s för beskrivning');





define('_PLUG_PAY_INETCOM_FERROR', 'Medlems ID är inte specifiserat');
define('_PLUG_PAY_INETCOM_FERROR2', 'Du måste vara behörig för att göra det');
define('_PLUG_PAY_INETCOM_FERROR3', 'Betalnings ID är inte specifiserat');
define('_PLUG_PAY_INETCOM_FERROR4', 'Kan inte ladda medlems info #%d (%d)');
define('_PLUG_PAY_INETCOM_ERROR', 'Ogiltigt Kreditkorts Nummer');
define('_PLUG_PAY_INETCOM_ERROR2', 'Ogiltigt utgångsdatum - Månad');
define('_PLUG_PAY_INETCOM_ERROR3', 'Ogiltigt utgångsdatum - År');
define('_PLUG_PAY_INETCOM_ERROR4', 'Vänligen uppge kreditkortets kod');
define('_PLUG_PAY_INETCOM_ERROR5', 'Vänligen uppge gatuadress');
define('_PLUG_PAY_INETCOM_ERROR6', 'Vänligen uppge stad');
define('_PLUG_PAY_INETCOM_ERROR7', 'Vänligen uppge län');
define('_PLUG_PAY_INETCOM_ERROR8', 'Vänligen uppge postnummer');
define('_PLUG_PAY_INETCOM_ERROR9', 'Vänligen uppge land');
define('_PLUG_PAY_INETCOM_ERROR10', 'Betalningen hittades inte: #%d');
define('_PLUG_PAY_INETCOM_ERROR11', 'Betalningen är redan genomförd: #%d');
define('_PLUG_PAY_INETCOM_ERROR12', 'Betalningen är skapad för ett annat betalnings system: %s (#%d)');
define('_PLUG_PAY_INETCOM_ERROR13', 'Medlemen hittades inte: #%d');

define('_PLUG_PAY_INETCOM_TITLE', 'TheInternetCommerce');
define('_PLUG_PAY_INETCOM_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_24eKOUT_TITLE', '2Checkout');
define('_PLUG_PAY_24eKOUT_DESC', 'betala via 2Checkout');
define('_PLUG_PAY_24eKOUT_ERROR', 'Försökte använda testscript, men denna är inte användbar');
define('_PLUG_PAY_24eKOUT_ERROR2', 'Kreditkortet kunde inte behandlas');
define('_PLUG_PAY_24eKOUT_ERROR3', 'Kan inte validera din betalning, vänligen kontakta webmastern');





define('_PLUG_PAY_WORLDPAY_FERROR', 'WORLDPAY FEL: %s (Detaljer: PNREF:%s, faktura:%d)%s');
define('_PLUG_PAY_WORLDPAY_ERROR', 'Felaktig IP adress för WorldPay betalningsubmission');
define('_PLUG_PAY_WORLDPAY_ERROR2', 'Transaktionen nekades (%s)');
define('_PLUG_PAY_WORLDPAY_ERROR3', 'Test kan inte göras');
define('_PLUG_PAY_WORLDPAY_ERROR4', 'Felaktigt Installations ID: det är inte vår betalning');
define('_PLUG_PAY_WORLDPAY_ERROR5', 'mottaget belopp är tomt eller = 0');
define('_PLUG_PAY_WORLDPAY_ERROR6', 'Betalningen är redan genomförd (worldpay faktura#: %d) för betalning #%d');

define('_PLUG_PAY_WORLDPAY_TITLE', 'WorldPay');
define('_PLUG_PAY_WORLDPAY_DESC', 'Betala med kreditkort/debetkort - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');
define('_PLUG_PAY_WORLDPAY_FERROR2', 'Okänd enhet i utgångsdatum. Måste vara d|m|v|å');
define('_PLUG_PAY_WORLDPAY_FERROR3', 'Ogiltigt värde för $s: %s');
define('_PLUG_PAY_WORLDPAY_FERROR4', 'Ogiltigt värde för %s i produkt #');





define('_PLUG_PAY_VEROTEL_FERROR', 'VEROTEL FEL: %s (Detaljer: faktura:%d)%s');

define('_PLUG_PAY_VEROTEL_TITLE', 'VeroTel');
define('_PLUG_PAY_VEROTEL_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_PAYPALPRO_TITLE', 'Betala med PayPal');
define('_PLUG_PAY_PAYPALPRO_DESC', 'Snabb, Säker betalning med PayPal.<br />Spar tid. Betala säkert. <br />Betala utan att dela din känsliga finansiella information.');
define('_PLUG_PAY_PAYPALPRO_FERROR', 'Det finns produkter med pris i olika valutor. Det går inte att slutföra denna order - vänligen ändra detta');
define('_PLUG_PAY_PAYPALPRO_FERROR2', 'Internt FEL (get_caller): ');
define('_PLUG_PAY_PAYPALPRO_FERROR3', 'Mottog tomt värde');
define('_PLUG_PAY_PAYPALPRO_REDIRECT', 'Du slussas nu vidare till PayPal');
define('_PLUG_PAY_PAYPALPRO_REDIRECT2', 'Du slussas nu vidare till PayPal för inloggning och betalning');
define('_PLUG_PAY_PAYPALPRO_FERROR4', 'Internt FEL : ');
define('_PLUG_PAY_PAYPALPRO_FERROR5', 'Internt fel: ');
define('_PLUG_PAY_PAYPALPRO_FERROR6', 'Betalningens status är inte komplett, vänligen kontakta suporten');
define('_PLUG_PAY_PAYPALPRO_FERROR7', 'Vänligen %sregistrerings proseduren igen%s');
define('_PLUG_PAY_PAYPALPRO_ERROR', 'Tomt värde mottogs');
define('_PLUG_PAY_PAYPALPRO_ERROR2', 'Betalningen #%d hittades inte');
define('_PLUG_PAY_PAYPALPRO_FERROR8', 'Tomt txn_id mottogs');
define('_PLUG_PAY_PAYPALPRO_TITLE2', 'Betalning med Kreditkort');
define('_PLUG_PAY_PAYPALPRO_DESC2', 'Betala med Visa, MC, Discover eller Amex kreditkort');

define('_PLUG_PAY_PAYPALPRO_HTML_TITLE', 'Konfirmera din betalning');
define('_PLUG_PAY_PAYPALPRO_HTML_SPTITLE', 'Anmälan/Produkt Titel');
define('_PLUG_PAY_PAYPALPRO_HTML_PRICE', 'Pris');
define('_PLUG_PAY_PAYPALPRO_HTML_SUBTOTAL', 'Subtotal');
define('_PLUG_PAY_PAYPALPRO_HTML_CPDSC', 'Rabattkupong Värde');
define('_PLUG_PAY_PAYPALPRO_HTML_TAXAM', 'Skattebelopp');
define('_PLUG_PAY_PAYPALPRO_HTML_TOTAL', 'Totalt');
define('_PLUG_PAY_PAYPALPRO_HTML_SBBUT', 'Konfirmera Betalningen ');





define('_PLUG_PAY_FIRSTPAY_TITLE', 'FirstPay.Net');
define('_PLUG_PAY_FIRSTPAY_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_MERCANYW_TITLE', 'MerchantAnyWhere');
define('_PLUG_PAY_MERCANYW_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_SECPAY_TITLE', 'SecPay');
define('_PLUG_PAY_SECPAY_DESC', 'Betalning med Kreditkort');
define('_PLUG_PAY_SECPAY_ERROR', 'FEL: %s');
define('_PLUG_PAY_SECPAY_ERROR2', 'SOAP anmärkning: ');
define('_PLUG_PAY_SECPAY_ERROR3', 'SOAP fel: %s');





define('_PLUG_PAY_PROTXDIR_TITLE', 'Protx');
define('_PLUG_PAY_PROTXDIR_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_SAFEPAY_TITLE', 'SafePay');
define('_PLUG_PAY_SAFEPAY_DESC', 'Se %swww.safepaysolutions.com%s för beskrivning');
define('_PLUG_PAY_SAFEPAY_ERROR', 'Hemligt lösenfras fel');
define('_PLUG_PAY_SAFEPAY_ERROR2', 'Fel belopp (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR3', 'Fel kvantitet (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR4', 'Fel Transaktions ID (%d)');
define('_PLUG_PAY_SAFEPAY_ERROR5', 'Transaktionen är inte konfirmerad, pengarna är inte på ditt SPS konto');
define('_PLUG_PAY_SAFEPAY_ERROR6', 'Resultat kod %s: Betalnings Fel');





define('_PLUG_PAY_SECUREPAY_TITLE', 'SecurePay');
define('_PLUG_PAY_SECUREPAY_DESC', 'Betalning med Kreditkort');





define('_PLUG_PAY_GOOGLE_CHECKOUT_TITLE', 'Google Checkout');
define('_PLUG_PAY_GOOGLE_CHECKOUT_DESC', 'Credit kort betalning');





define('_PLUG_PAY_MANUAL_TITLE', 'Manual payment');





define('_PLUG_PAY_ALERTPAY_TITLE', 'AlertPay');
define('_PLUG_PAY_ALERTPAY_DESC', 'Pay by credit card');
define('_PLUG_PAY_ALERTPAY_FERROR2', 'Unknown period unit in expire_days. Should be d|m|w|y');
define('_PLUG_PAY_ALERTPAY_FERROR3', 'Incorrect value for $s: %s');
define('_PLUG_PAY_ALERTPAY_FERROR4', 'Incorrect value for %s in product #');
define('_PLUG_PAY_ALERTPAY_ERROR', 'Incorrect secret code');
define('_PLUG_PAY_ALERTPAY_FERROR', 'ALERTPAY ERROR: %s (Details: PNREF:%s, invoice:%d)%s');
define('_PLUG_PAY_ALERTPAY_ERROR2', 'Transaction declined (%s)');
define('_PLUG_PAY_ALERTPAY_ERROR3', 'Test mode disabled');
define('_PLUG_PAY_ALERTPAY_ERROR4', 'Incorrect merchant account: it is not our payment');
define('_PLUG_PAY_ALERTPAY_ERROR5', 'returned amount empty or = 0');
define('_PLUG_PAY_ALERTPAY_ERROR6', 'Payment is already processed (alertpay invoice#: %d) in payment #%d');







define('_PLUG_PAY_METACHARGE_TITLE', 'Metacharge');
define('_PLUG_PAY_METACHARGE_DESC', 'Pay by credit card/debit card - Visa/Mastercard/Eurocard/Delta/Solo/Switch/JCB');

define('_PLUG_PAY_METACHARGE_FERROR', 'METACHARGE ERROR: %s (Details: PNREF:%s, invoice:%d)%s');

define('_PLUG_PAY_METACHARGE_ERROR2', 'Transaction declined (%s)');
define('_PLUG_PAY_METACHARGE_ERROR3', 'Test mode disabled');
define('_PLUG_PAY_METACHARGE_ERROR4', 'Incorrect Installation ID: it is not our payment');
define('_PLUG_PAY_METACHARGE_ERROR5', 'returned amount empty or = 0');
define('_PLUG_PAY_METACHARGE_ERROR6', 'Payment is already processed (metacharge invoice#: %d) in payment #%d');

define('_PLUG_PAY_METACHARGE_FERROR2', 'Unknown period unit in expire_days. Should be d|m|w|y');
define('_PLUG_PAY_METACHARGE_FERROR3', 'Incorrect value for $s: %s');
define('_PLUG_PAY_METACHARGE_HTML_SUB_BUT', 'Click here if your browser does not automatically forward you');
define('_PLUG_PAY_METACHARGE_HTML_TITLE', 'Metacharge Payment');













//missed rows
define ('_TPL_SIGNUP_CAPTCHA', 'Enter Verification Text');
define ('_TPL_SIGNUP_CAPTCHA_1', 'Please type text from image');
define ('_TPL_AFF_PAYOUT_SAFEPAY_EMAIL', 'Your SafePaySolutions E-Mail address');
define ('_TPL_EMAIL_VER_TITLE_PROFILE', 'Email verification required');
define ('_TPL_EMAIL_VER_TEXT_PROFILE', 'Please check your email - verification email message has been just emailed to you. Once you receive this message, read it and follow instructions in this email to complete your email verification.');
define ('_TPL_MEMBER_MAIN_PAGE', 'Main Page');
define ('_TPL_PROFILE_EMAIL_NOT_VERIFIED', 'Email address is not verified!');
define ('_TPL_PROFILE_EMAIL_RESEND_VERIFICATION_EMAIL', 'Resend verification email');
define ('_TPL_NEWSLETTER_ARCHIVE_DATE', 'Date');
define ('_TPL_NEWSLETTER_ARCHIVE_SUBJECT', 'Subject');
define ('_TPL_NEWSLETTER_ARCHIVE_NO_ARCHIVE', 'You have no archive messages');
define('_SIGNUP_CAPTCHA_ERROR', 'Verification image entered incorrectly, please re-enter it carefully');
define('_AFF_ERROR_9', 'Please enter an email address for payouts');
define('_AFF_MEMBER_F7_1', 'SafePaySolutions address for affiliate payout');
define('_PLUG_PAY_AUTHORIZE_CIM_TITLE', 'Authorize CIM');
define('_PLUG_PAY_AUTHORIZE_CIM_DESC', 'Credit card payment');
define('_PLUG_PAY_ESOLUTIONS_TITLE', 'Merchant e-Solutions');
define('_PLUG_PAY_ESOLUTIONS_DESC', 'Credit card payment');
define('_TPL_SKYPAY_ADDRESS_TITLE', 'Billing address');
define('_TPL_SKYPAY_ADDRESS_CHOOSE', '*** Please choose ***');
define('_TPL_SKYPAY_ADDRESS_HOLDERNAME', 'Cardholder Name');
define('_TPL_SKYPAY_ADDRESS_ASONCARD', 'cardholder name, exactly as on the card');
define('_TPL_SKYPAY_ADDRESS_FLNAME', 'cardholder first and last name, exactly as%son the card');
define('_TPL_SKYPAY_ADDRESS_ADDRINFO', 'Please specify your billing address details');
define('_TPL_SKYPAY_ADDRESS_STRADDR', 'Address');
define('_TPL_SKYPAY_ADDRESS_STRADDR2', 'Address (2)');
define('_TPL_SKYPAY_ADDRESS_CITY', 'City');
define('_TPL_SKYPAY_ADDRESS_ZIP', 'Postal code / Zip code');
define('_TPL_SKYPAY_ADDRESS_COUNTRY', 'Country');
define('_TPL_SKYPAY_ADDRESS_PHONE', 'Phone');
define('_TPL_SKYPAY_ADDRESS_MUSTMATCH', '(must match your credit card statement delivery address)');
define('_TPL_SKYPAY_ADDRESS_BACK_BUT', 'Back');
define('_TPL_SKYPAY_ADDRESS_SUBMIT_BUT', 'Continue');
define('_TPL_SKYPAY_ADDRESS_SUBMIT_BUT_3', 'Subscribe and Pay');
define('_TPL_SKYPAY_PAY_TITLE', 'Confirm payment details');
define('_TPL_SKYPAY_PAY_SUBMIT', 'Continue to the Skypay Payment page');
define('_TPL_SKYPAY_ADDRESS_BILLING', 'Billing address details:');
define('_TPL_SKYPAY_PRODUCT_BILLING', 'Product details:');
define('_PLUG_PAY_SKYPAY_FERROR1', 'skypay ERROR: %s (Details: txn_id:%d, invoice:%d)%s');
define('_PLUG_PAY_SKYPAY_FERROR2', 'You are not logged in.');
define('_PLUG_PAY_SKYPAY_FERROR3', 'It seems to be not your payment, please go back and try again.');
define('_PLUG_PAY_SKYPAY_TITLE', 'Skypay');
define('_PLUG_PAY_SKYPAY_DESC', 'Pay by credit card/debit card');
define ('_TPL_SKYPAY_CANCEL_TITLE', 'Payment Cancelled');
define ('_TPL_SKYPAY_CANCEL_ERROR', 'Your payment has been cancelled.');
define ('_TPL_SKYPAY_CANCEL_GOTO', 'To see your subscription details please go to %sMembership page%s.');
?>