<!-- login box on signup page widget -->

<!-- Optimizely code begin -->
<script src="//cdn.optimizely.com/js/41368195.js"></script>
<!-- Optimizely code end -->

<?php if (!Am_Di::getInstance()->auth->getUserId()) : ?>
    <link type="text/css" href="/application/default/themes/getaudiofromvideo/public/css/main.css" rel="stylesheet" />
    <link type="text/css" href="/application/default/themes/getaudiofromvideo/public/css/style_3.css" rel="stylesheet" />
    <!-- SIGNUP PAGE UPPER AREA - START -->
    <style type="text/css">
        #form_hide3,#form_hide4{display:none;}
        #form_hide3{margin-top: 12px;}
    </style>
    <div style="width:945px; margin-left:-75px;">
        <!-- <div class="main_left1">
            <div class="mem_benefit_tbl">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <th width="100%" class="frst">Why register to become a member?</th>
                    </tr>
                    <tr class="bg_blu">
                        <td class="frst"><div class="member_tic"></div> <strong>UNLIMITED</strong> number of conversions and downloads</td>
                    </tr>
                    <tr>
                        <td class="frst"><div class="member_tic"></div> Advertisement-free downloading with no annoying popups</td>
                    </tr>
                    <tr class="bg_blu">
                        <td class="frst"><div class="member_tic"></div> Instant downloads, no waiting for conversions to start</td>
                    </tr>
                    <tr>
                        <td class="frst"><div class="member_tic"></div> 1st priority in conversion queue over guest visitors</td>
                    </tr>
                    <tr class="bg_blu">
                        <td class="frst"><div class="member_tic"></div> Upload your own videos to convert</td>
                    </tr>
                    <tr>
                        <td class="frst"><div class="member_tic"></div> Expedited customer support via email/Facebook/Twitter</td>
                    </tr>
                    <tr class="bg_blu">
                        <td class="frst"><div class="member_tic"></div> Secure 256-bit encryption conversions &AMP; downloads</td>
                    </tr>
                    <tr>
                        <td class="frst"><div class="member_tic"></div> Upgrade/downgrade your membship plan at anytime</td>
                    </tr>
                </table>
            </div>
        </div> -->
        <h2 class="title_black24">Why pay $0.99 cents per song on iTunes?</h2>
        <p class="text_black21">Get unlimited downloads here for just $6 per month!</p>
        <div class="prime_feature_main mt20">
            <div class="prime_feature">
                <h2><span class="pf_1"></span>Compatible on any version iPhone, iPad, iPod or any other MP3 player!</h2>
            </div>
            <div class="prime_feature ml50">
                <h2><span class="pf_2"></span>Convert to all types of formats including MP3, MP4, AAC, M4R, FLV, AVI, WMV and more!</h2>
            </div>
            <div class="prime_feature">
                <h2><span class="pf_4"></span>No software to install!  All conversions are 100% online with our web based converter!</h2>
            </div>
            <div class="prime_feature ml50">
                <h2><span class="pf_3"></span>Browse and convert videos from Youtube and over +10 additional sites!</h2>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear10"></div>
        <div class="mem_benefit_tbl" style="width:594px; margin: 0 auto; padding: 0;">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <th width="100%" class="frst">Why register to become a member?</th>
                </tr>
                <tr>
                    <td class="frst"><div class="member_tic"></div> <span>UNLIMITED</span> number of conversions and downloads</td>
                </tr>
                <tr>
                    <td class="frst"><div class="member_tic"></div> All advertisements removed</td>
                </tr>
                <tr>
                    <td class="frst"><div class="member_tic"></div> Instant downloads, no delay for conversions to start</td>
                </tr>
                <tr>
                    <td class="frst"><div class="member_tic"></div> 1st priority in conversion queue above guest visitors</td>
                </tr>
                <tr>
                    <td class="frst"><div class="member_tic"></div> Expedited customer support via email, Facebook, Twitter</td>
                </tr>
                <tr>
                    <td class="frst"><div class="member_tic"></div> Upgrade/downgrade your membership at any time</td>
                </tr>
            </table>
        </div>
        <div class="clear22"></div>
        <br />
        <!-- code for trust guard seals - START -->
        <div class="trust_guide">
            <table width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center"><a name="trustlink" href="http://secure.trust-guard.com/certificates/3785" target="_blank" onclick="var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; window.open(this.href.replace('http', 'https'),'welcome','location='+nonwin+',scrollbars=yes,width=517,height='+screen.availHeight+',menubar=no,toolbar=no'); return false;" oncontextmenu="var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by trust-guard \251 '+d.getFullYear()+'.'); return false;"><img name="trustseal" alt="Security Verified Seal" style="border: 0;" src="https://c674753.ssl.cf2.rackcdn.com/security-3785-large-gray.gif" /></a></td>
                    <td align="center"><a name="trustlink" href="http://secure.trust-guard.com/certificates/3785" target="_blank" onclick="var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; window.open(this.href.replace('http', 'https'),'welcome','location='+nonwin+',scrollbars=yes,width=517,height='+screen.availHeight+',menubar=no,toolbar=no'); return false;" oncontextmenu="var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by trust-guard \251 '+d.getFullYear()+'.'); return false;"><img name="trustseal" alt="Trust Guard Certified" style="border: 0;" src="https://c674753.ssl.cf2.rackcdn.com/certified-3785-large-gray.gif" /></a></td>
                    <td align="center"><a name="trustlink" href="http://secure.trust-guard.com/certificates/3785" target="_blank" onclick="var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; window.open(this.href.replace('http', 'https'),'welcome','location='+nonwin+',scrollbars=yes,width=517,height='+screen.availHeight+',menubar=no,toolbar=no'); return false;" oncontextmenu="var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by trust-guard \251 '+d.getFullYear()+'.'); return false;"><img name="trustseal" alt="Privacy Seal" style="border: 0;" src="https://c674753.ssl.cf2.rackcdn.com/privacy-3785-large-gray.gif" /></a></td>
                    <td align="center"><a name="trustlink" href="http://secure.trust-guard.com/certificates/3785" target="_blank" onclick="var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; window.open(this.href.replace('http', 'https'),'welcome','location='+nonwin+',scrollbars=yes,width=517,height='+screen.availHeight+',menubar=no,toolbar=no'); return false;" oncontextmenu="var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by trust-guard \251 '+d.getFullYear()+'.'); return false;"><img name="trustseal" alt="Business Verified" style="border: 0;" src="https://c674753.ssl.cf2.rackcdn.com/business-3785-large-gray.gif" /></a></td></tr></table>            
        </div>
        <!-- code for trust guard seals - END -->
        <div class="ptable_up">
            <h2>1 day free trial on all plans!</h2>
            <p>No contracts, start &AMP; stop your membership at anytime!</p>
        </div>
        <div class="clear38"></div>
        <!-- pricing table -->
        <div class="p_table">
            <div class="frame_border radius5">
                <!-- caption column -->
                <div class="caption_column">
                    <ul>
                        <!-- column header -->
                        <li class="header_row_1 align_center"></li>
                        <li class="decor_line"></li>
                        <li class="header_row_2"><h1 class="caption">Membership<span>Plans</span></h1></li>
                        <!-- data rows -->
                        <!-- <li class="row_style_1"><span>1 month cost</span></li> -->
                        <li class="row_style_2"><span>Conversions per day</span></li>
                        <li class="row_style_1"><span>Maximum length of video possible to convert</span></li>
                        <li class="row_style_2"><span>Maximum size of file possible to convert</span></li>
                        <li class="row_style_1"><span>Conversion formats</span></li>
                        <li class="row_style_2"><span>Free memberships to give to friends</span></li>
                        <li class="row_style_1"><span>Video sites</span></li>
                        <!-- <li class="row_style_2"><span>Payment system</span></li> -->
                        <!-- column footer -->
                        <li class="footer_row"></li>
                    </ul>
                </div>
                <!-- column style 2 -->
                <div class="column_2">
                    <!-- ribbon (optional) -->
                    <!-- <div class="column_ribbon ribbon_style1_hot"></div> -->
                    <!-- /ribbon -->				
                    <ul>
                        <!-- column header -->
                        <li class="header_row_1 align_center"><h2>Basic</h2></li>
                        <li class="decor_line"></li>
                        <li class="header_row_2 align_center"><h1>$6</h1><h3>per month</h3></li>
                        <!-- data rows -->
                        <!-- <li class="row_style_1 align_center"><span>$6</span></li> -->
                        <li class="row_style_3 align_center"><span>unlimited</span></li>
                        <li class="row_style_1 align_center"><span>3 minutes</span></li>
                        <li class="row_style_3 align_center"><span>3 mb</span></li>
                        <li class="row_style_1 align_center"><span>MP4</span></li>
                        <li class="row_style_3 align_center"><span>0</span></li>
                        <li class="row_style_1 align_center"><span class="stream_site_logo1">Youtube</span></li>
                        <!-- <li class="row_style_3 align_center"><span class="paypal_icon"></span></li>-->
                        <!-- column footer -->
                        <li class="footer_row"><a href="#register_form" class="button_2 radius5" onclick="switchproduct(0);">Sign Up</a></li>
                    </ul>
                </div>
                <!-- column style 3 -->
                <div class="column_3">
                    <!-- ribbon (optional) -->
                    <div class="column_ribbon ribbon_style1_hot"></div>
                    <!-- /ribbon -->
                    <ul>
                        <!-- column header -->
                        <li class="header_row_1 align_center"><h2>Plus</h2></li>
                        <li class="decor_line"></li>
                        <li class="header_row_2 align_center"><h1>$9</h1><h3>per month</h3></li>
                        <!-- data rows -->
                        <!-- <li class="row_style_1 align_center"><span>$9</span></li> -->
                        <li class="row_style_2 align_center"><span>unlimited</span></li>
                        <li class="row_style_1 align_center"><span>10 minutes</span></li>
                        <li class="row_style_2 align_center"><span>15 mb</span></li>
                        <li class="row_style_1 align_center"><span>MP3, MP4, M4R</span></li>
                        <li class="row_style_2 align_center"><span>1</span></li>
                        <li class="row_style_1 align_center"><span class="stream_site_logo2">Youtube, Vimeo, Dailymotion</span></li>
                        <!--  <li class="row_style_2 align_center"><span class="paypal_icon"></span></li> -->
                        <!-- column footer -->
                        <li class="footer_row"><a href="#register_form" class="button_3 radius5" onclick="switchproduct(3);">Sign Up</a></li>
                    </ul>
                </div>
                <!-- column style 4 -->
                <div class="column_4">
                    <!-- ribbon (optional) -->
                    <!--<div class="column_ribbon ribbon_style1_best"></div>-->
                    <!-- /ribbon -->
                    <ul>
                        <!-- column header -->
                        <li class="header_row_1 align_center radius5_topright"><h2>Pro</h2></li>
                        <li class="decor_line"></li>
                        <li class="header_row_2 align_center radius5_bottomright"><h1>$11</h1><h3>per month</h3></li>
                        <!-- data rows -->
                        <!-- <li class="row_style_1 align_center"><span>$11</span></li> -->
                        <li class="row_style_3 align_center"><span>unlimited</span></li>
                        <li class="row_style_1 align_center"><span>60 minutes</span></li>
                        <li class="row_style_3 align_center"><span>100 mb</span></li>
                        <li class="row_style_1 align_center" style="padding:3px 0 !important;"><span style="padding:0!important;">MP3, MP4, M4R,<br />AAC, AVI, FLV, WMV</span></li>
                        <li class="row_style_3 align_center"><span>2</span></li>
                        <li class="row_style_1 align_center"><span class="stream_site_logo3">Youtube, Vimeo, Dailymotion, Veoh, Metacafe, Viddler, Myspace, Clipfish, Break, Blip</span></li>
                        <!-- <li class="row_style_3 align_center"><span class="paypal_icon"></span></li> -->
                        <!-- column footer -->
                        <li class="footer_row"><a href="#register_form" class="button_4 radius5" onclick="switchproduct(6);" >Sign Up</a></li>
                    </ul>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <!-- pricing table end -->
        <div class="ptable2">
            <div class="ptable2_inr clearfix">
                <div class="col1">Save 10% - 3 months plan</div>
                <div class="col2"><span>$16</span> per 3 months</div>
                <div class="col3"><span>$24</span> per 3 months</div>
                <div class="col4"><span>$30</span> per 3 months</div>
                <div class="clear"></div>
                <div class="col1">&nbsp;</div>
                <div class="col2"><a href="#register_form" class="smal_signup2 sp_radius5" onclick="switchproduct(1);">Sign Up</a></div>
                <div class="col3"><a href="#register_form" class="smal_signup3 sp_radius5" onclick="switchproduct(4);">Sign Up</a></div>
                <div class="col4"><a href="#register_form" class="smal_signup4 sp_radius5" onclick="switchproduct(7);">Sign Up</a></div>
                <div class="clear"></div>
            </div>
            <div class="clear10"></div>
            <div class="ptable2_inr clearfix">
                <div class="col1">Save 25% - 1 year plan</div>
                <div class="col2"><span>$54</span> per 1 year</div>
                <div class="col3"><span>$81</span> per 1 year</div>
                <div class="col4"><span>$99</span> per 1 year</div>
                <div class="clear"></div>
                <div class="col1">&nbsp;</div>
                <div class="col2"><a href="#register_form" class="smal_signup2 sp_radius5" onclick="switchproduct(2);">Sign Up</a></div>
                <div class="col3"><a href="#register_form" class="smal_signup3 sp_radius5" onclick="switchproduct(5);">Sign Up</a></div>
                <div class="col4"><a href="#register_form" class="smal_signup4 sp_radius5" onclick="switchproduct(8);">Sign Up</a></div>
                <div class="clear"></div>
            </div>
        </div>
    </div>

    <a name="register_form">&nbsp;</a>
    <div class="title_gray box_shadow fl" style="display:none; margin-left: -75px;"><?php echo $title ?></div>
    <div class="am-login-text" id="form_hide2" style="display:none; margin-top: 60px;"><?php __e("If you already have an account on our website, please %slogin%s to continue", '<a href="javascript:" id="show-login-box-on-signup">', '</a>') ?></div>
    <div class="am-signup-login-form-container" style="display:none">
        <div style="font-size: xx-small; text-align: right; width: 100%;">
            <a href="javascript:" id="hide-login-box-on-signup">
                <img src="<?php echo $this->_scriptImg('modal-close.png') ?>" alt="<?php __e('Close') ?>" title="<?php __e('Close') ?>"/>
            </a>
        </div>
        <br />
        <div class="am-layout-two-coll">
            <div class="am-layout-two-coll-top"></div>
            <div class="am-coll-left">
                <div class="am-coll-content">

                    <div class="am-form am-login-form am-signup-login-form">
                        <form name="login" method="post" action="<?php echo REL_ROOT_URL ?>/login">
                            <fieldset>
                                <legend>&nbsp;&nbsp;<?php __e('Member Login') ?></legend>
                                <div class="row">
                                    <div class="element-title">
                                        <label class="element-title" for="login"><?php __e('E-Mail Address or Username') ?></label>
                                    </div>
                                    <div class="element">
                                        <input type="text" id="login" name="amember_login" size="15" value="<?php p(@$_REQUEST['amember_login']) ?>" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="element-title">
                                        <label class="element-title" for="pass"><?php __e('Password') ?></label>
                                    </div>
                                    <div class="element">
                                        <input type="password" id="pass" name="amember_pass" size="15" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="element-title"></div>
                                    <div class="element" style="vertical-align: baseline">
                                        <input type="submit" value="&nbsp;&nbsp;&nbsp;<?php __e('Login') ?>&nbsp;&nbsp;&nbsp;" />
                                    </div>
                                </div>
                            </fieldset>
                            <input type="hidden" name="login_attempt_id" value="<?php print time() ?>" />
                            <input type="hidden" name="amember_redirect_url" value="<?php p($_SERVER['REQUEST_URI']) ?>" />
                        </form>
                    </div>
                </div>
            </div>
            <div class="am-coll-right">
                <div class="am-coll-content">
                    <div class="am-form am-sendpass-form">
                        <form name="sendpass" method="post" action="<?php echo REL_ROOT_URL ?>/sendpass">
                            <fieldset>
                                <legend>&nbsp;&nbsp;<?php __e('Lost password') ?></legend>
                                <div class="row">
                                    <div class="element-title">
                                        <label class="element-title" for="sendpass"><?php __e('Enter your <b>E-Mail Address</b> or <b>Username</b>') ?></label>
                                    </div>
                                    <div class="element"><input type="text" name="login" id="sendpass" size="15" /></div>
                                </div>
                                <div class="row">
                                    <div class="element-title"></div>
                                    <div class="element">
                                        <input type="submit" value="<?php __e('Get Password') ?>" />
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
            <div class="am-layout-two-coll-bottom"></div>
        </div>
    </div>

    <script type="text/javascript">

        //custom js to make the form magic happen

        var switchproduct = function(id){
            console.log(id);
            $('#form_hide2,#form_hide3,#form_hide4').fadeIn(800);
            var current = $("#product_id---" + id);
            current[0].checked = true;
            //  current.siblings().find("br").each(function(){$(this)[0].style.display="none";})
            current.siblings().each(function(index){
                console.log(index);
                if ( ($(this).attr("id") == "product_id---" + id) || ($(this).attr("for") == "product_id---" + id) ) {
                    console.log($(this));
                    $(this)[0].style.display = "";
                } else {
                    $(this)[0].style.display = "none";
                }
                        
            });
            current[0].style.display = "";
            $("#row-paysys_id").find("span")[0].style.display="none";
        };

        jQuery(document).ready(function($) {

            var cpbox = $("#coupon-0");
            cpbox.parent()[0].innerHTML = cpbox.parent()[0].innerHTML + '<div class="btn_red2"><a href="Javascript:ju_loadiframe();">&nbsp; Click here for Coupon &nbsp;</a></a>';
        });
    </script>



    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $("#show-login-box-on-signup").click(function(){
                $("body").append("<div id='mask'></div>");
                $(".am-signup-login-form-container").show(100);
            });
            $("#hide-login-box-on-signup").click(function(){
                $("#mask").remove();
                $(".am-signup-login-form-container").hide(100);
            });
            $(".am-signup-login-form form").amAjaxLoginForm({
                success: function() { window.location.reload(true); }
            });// from user.js
        });
    </script>

    <script type="text/javascript" charset="utf-8">
        var ju_num = "717039E2-1DDF-4B31-8274-DE3A8FBAECA5";
        var ju_color = "CC0000";
        var ju_placement = "left";
        var ju_hidebutton = false;
        var ju_style = "1";
        var ju_tab_text = "coupons";
        var is_ssl = ("https:" == document.location.protocol);
        var asset_host = is_ssl ? "https://s3.amazonaws.com/justuno/" : "http://s3.amazonaws.com/justuno/";
    </script>
    <script src='https://s3.amazonaws.com/justuno/coupon_code1.js' type='text/javascript'></script>

<?php else: // if logged-in  ?>
    <div class="am-login-text">
        <?php
        __e("You are logged-in as %s. %sLogout%s to signup as new user.", "<strong>" . Am_Di::getInstance()->auth->getUsername() . "</strong>", "<a href='" . REL_ROOT_URL . "/logout?amember_redirect_url=" . urlencode($_SERVER['REQUEST_URI']) . "'>", "</a>"
        );
        ?>
    </div>
<?php endif // if not logged-in ?>
<!-- login box on signup page widget end -->
