<?php 
if (empty($title)) $title=___('Sign-up');
$this->setLayout('layout.phtml'); 
include $this->_script('_error.phtml');

$this->headScript()
        ->appendFile(REL_ROOT_URL . '/application/default/views/public/js/jquery/jquery.validate.js');
?>
<div class="am-signup">
<?php echo $this->blocks('signup/login/before') ?>
<?php include $this->_script('signup/_login.phtml'); ?>    
<?php echo $this->blocks('signup/login/after') ?>
    
<?php echo $this->blocks('signup/form/before') ?>
<?php include $this->_script('_form.phtml'); ?>
<?php echo $this->blocks('signup/form/after') ?>

</div>
<?php include $this->_script('js.country_state.js'); ?>