<?php
/// that is layout for member.phtml - based pages - with tab menu on top
/// it is automatically inserted into your site layout:
if (empty($title)) $title = ___("Your Membership Information");
$this->setLayout('layout.phtml');

$this->headScript()
    ->prependFile(REL_ROOT_URL . '/application/default/views/public/js/jquery/jquery.validate.js')

?>
<?php $this->blocks('member/under-menu') ?>
<!-- member content starts here -->
<?php echo $content ?>
<!-- member content ends here -->
<?php $this->blocks('member/under-contents') ?>
