<?php 
/*
*
*
*     Author: Alex Scott
*      Email: alex@cgi-central.net
*        Web: http://www.cgi-central.net
*    Details: Admin Payments
*    FileName $RCSfile$
*    Release: 3.2.3PRO ($Revision: 4981 $)
*
* Please direct bug reports,suggestions or feedback to the cgi-central forums.
* http://www.cgi-central.net/forum/
*                                                                          
* aMember PRO is a commercial software. Any distribution is strictly prohibited.
*
*/

include "../config.inc.php";
$t = new_smarty();
include "login.inc.php";

$vars = get_input_vars();
admin_check_permissions('list_payments');
extract($vars, EXTR_OVERWRITE);

function get_payments_by_date($vars){
    global $db, $t;

    $count = 20;
    list($all_count, $all_amount,$all_tax) = $db->get_payments_c($vars['beg_date'], $vars['end_date'],
                intval($vars['only_completed']), $vars['list_by']); 
    $list = $db->get_payments($vars['beg_date'], $vars['end_date'], 
                intval($vars['only_completed']), $vars['start'], $count, $vars['list_by']); 

    return array($all_count, $all_amount, $list,$all_tax);
}


function get_payments_by_string($vars){
    global $db, $t;

    $count = 20;

    list($all_count, $all_amount,$all_tax) = $db->get_payments_c($vars['beg_date'], $vars['end_date'],
                intval($vars['only_completed']), $vars['list_by'], null, // lost parameter $prod_search, added 'null' (AseR)
                1, $vars['q'], $vars['q_where']); 
    $list = $db->get_payments($vars['beg_date'], $vars['end_date'], 
                intval($vars['only_completed']), $vars['start'], $count, $vars['list_by'],
                null, 1, $vars['q'], $vars['q_where']); 
    return array($all_count, $all_amount, $list,$all_tax);
}


if ($vars['beg_dateDay'])
   set_date_from_smarty('beg_date', $vars);
elseif ($vars['beg_date'] == '') 
   $vars['beg_date'] = date('Y-m-d');

if ($end_dateDay)
   set_date_from_smarty('end_date', $vars);
elseif ($vars['end_date'] == '') 
   $vars['end_date'] = date('Y-m-d');

if ($vars['beg_date'] > $vars['end_date']){
    $s = $vars['beg_date'];
    $vars['beg_date'] = $vars['end_date'];
    $vars['end_date'] = $s;
}
$t->assign('beg_date', $vars['beg_date']);
$t->assign('end_date', $vars['end_date']);

if ($vars['type'] == 'string'){
    list($all_count, $all_amount, $list,$all_tax) = get_payments_by_string($vars);
} else {
    list($all_count, $all_amount, $list,$all_tax) = get_payments_by_date($vars);
}

$t->assign('list', $list);
$t->assign('all_count', $all_count);
$t->assign('all_amount', $all_amount);
$t->assign('all_tax_amount', $all_tax);
///////////////////////////////////////////
$t->assign('list_by_options', array(
    '' =>         'Record change date',
    'add' =>      'Record insertion date',
    'complete' => 'Payment completion date'
));
$t->assign('q_where_options', array(
    ''           => 'Search entire payment record',
    'receipt_id' => 'Receipt# (returned by payment system)',
    'payment_id' => 'Payment# (generated by aMember)',
    'login'      => 'Username',
    'login_part' => 'Part of username',
    'amount'     => 'Payment amount',
    'remote_addr'=> 'Client IP',
    'product'    => 'Product Title',
));

switch ($vars['list_by']){
    case 'add':
        $list_by_field = 'tm_added';
        $list_by_title = 'Record<br />Added';
    break;
    case 'complete':
        $list_by_field = 'tm_completed';
        $list_by_title = 'Record<br />Completed';
    break;
    case '': default:
        $list_by_field = 'time';
        $list_by_title = 'Change Time';
}
$t->assign('list_by_field', $list_by_field);
$t->assign('list_by_title', $list_by_title);
$t->display('admin/payments.html');


?>
