<?php
/**
 * Class represents records from table product_upgrade
 * {autogenerated}
 * @property int $product_upgrade_id 
 * @property int $from_billing_plan_id 
 * @property int $to_billing_plan_id 
 * @property double $surcharge 
 * @see Am_Table
 */
class ProductUpgrade extends Am_Record 
{
    /** @return BillingPlan */
    function getFromPlan()
    {
        return $this->getDi()->billingPlanTable->load($this->from_billing_plan_id, false);
    }
    /** @return BillingPlan */
    function getToPlan()
    {
        return $this->getDi()->billingPlanTable->load($this->to_billing_plan_id, false);
    }
    /** @return Product */
    function getFromProduct()
    {
        $pr = $this->getDi()->productTable->load($this->getFromPlan()->product_id);
        return $pr;
    }
    /** @return Product */
    function getToProduct()
    {
        $pr = $this->getDi()->productTable->load($this->getToPlan()->product_id);
        return $pr;
    }
}

class ProductUpgradeTable extends Am_Table 
{
    protected $_key = 'product_upgrade_id';
    protected $_table = '?_product_upgrade';
    /**
     * @param Invoice $invoice
     * @return array of ProductUpgrade
     */
    function findUpgrades(Invoice $invoice)
    {
        $items = $invoice->getItems();
        if (!$items) return array();
        static $cache;
        if (empty($cache))
        {
            foreach ($this->_db->select("SELECT * FROM {$this->_table}") as $row)
                $cache[ $row['from_billing_plan_id'] ][] = $row;
        }
        $ret = array();
        foreach ((array)@$cache [ $items[0]->billing_plan_id ] as $row)
            $ret[] = $this->createRecord($row);
        return $ret;
    }
}