<?php // content of this file is displayed in popup box when user chooses to cancel subscription ?>
<div class="cancel-subscription-popup-text">
<?php __e("Do you really want to cancel subscription?") ?>
</div>

<div class="cancel-subscription-buttons">
    <input type="button" id="cancel-subscription-yes" value="<?php __e('Yes, I want to cancel subscription')?>" />
    &nbsp;&nbsp;
    <input type="button" id="cancel-subscription-no" value="<?php __e('No, please keep me subscribed')?>" />
</div>
