<?php if ($plugin->getFbUid()): ?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#appId=<?php echo $plugin->getConfig('app_id')?>&xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-send="true" data-href="<?php p($plugin->getConfig('likeurl', ROOT_URL))?>" data-width="450" data-show-faces="true"></div>
<?php endif ?>