<?php $title=___('Sign-up - email verification'); $this->setLayout('layout.phtml'); ?>
<?php include $this->_script('_error.phtml'); ?>

<?php __e('Please check your email - verification email message has been just emailed to you. Once you receive this message, read this and follow instructions in this email to complete your subscription.') ?>

<br /><br />
<p class="powered"><?php __e('Powered by %saMember Pro%s membership software','<a href="http://www.amember.com/">','</a>') ?></p>

</center>
