<?php $title=___('Thank you for Signing up'); $this->setLayout('layout.phtml'); ?>

<!-- display payment receipt -->
<?php if (empty($invoice) || !$invoice->tm_started): ?>

<strong><?php __e('Enjoy your membership. To Login please click here %sLogin%s','<a href="'.ROOT_SURL .'/login">','</a>') ?></strong>
<br />
<?php echo $this->blocks('thanks/unknown'); ?>

<?php elseif ($invoice->tm_started): ?>

<?php if ($invoice->first_total > 0): ?>
<?php __e('Your payment has been succesfully processed.') ?> 
<?php else: ?>
<?php __e('Your subscription has been succesfully processed.') ?> 
<?php endif ?>

<br />
<?php __e('Order reference: %s', $invoice->public_id . (@$payment->receipt_id ? (" / ".$payment->receipt_id) : null)) ?><br />
<?php if (!empty($payment->dattm)) __e('Date and time of payment: %s',amDatetime($payment->dattm)) ?><br />

<br /><br />

<?php include $this->_script('_receipt.phtml'); ?>

<strong><?php __e('Enjoy your membership. To Login please click here %sLogin%s','<a href="'.ROOT_SURL .'/login">','</a>') ?></strong>
<br />

<?php $this->blocks('thanks/success'); ?>

<?php elseif ($show_waiting): ?>
<div class="am-thanks-awaiting-payment">
    <?php __e("Your payment is not yet confirmed by payment system. It may take several minutes to get confirmation of the payment.") ?>
    <div class="am-thanks-awaiting-refresh">
    <?php __e("This page will be automatically refreshed within %s", $refreshTime) ?>
    </div>
</div>
<script type="text/javascript">
<?php echo $script ?>    
</script>
<?php echo $this->blocks('thanks/notstarted'); ?>
<?php endif // invoice->tm_started ?>
<!-- end of display payment receipt -->


