<?php $title=___("E-Mail Users"); $this->setLayout('admin/layout.phtml'); ?>
<?php include $this->_script('admin/_error.phtml'); 

$this->headStyle()->captureStart() ?>
<?php $this->headStyle()->captureEnd() ?>

<div class="filter-wrap">
<span style="float:left; text-align: left; padding: 5px;">
<?php __e('You have currently choosed the following users for e-mail to:')?><br />
<strong><?php echo @$filterCondition ?></strong><br />
<?php __e('%d user(s) matches your search', $users_found)?>.
<a href="javascript:loadBrowseUsers()" class="browse-users"><?php __e('browse...')?></a>
<?php if (@$filterConditionGuest): ?>
<br /><strong><?php echo $filterConditionGuest ?></strong><br />
<?php __e('%d guest(s) matches your search', $guests_found)?>.
<?php endif ?>
</span>
<br />

<?php echo $search ?>
</div>

    
<?php
echo $form;
?>        
    
<div id="email-history"></div>
        
<div id="browse-users" style="display:none"></div>
        
<script type="text/javascript">
function insertTag(sel){
    var v = $(sel).val();
    if (v == "") return;
    var txt = $('textarea[name="body"]');
    txt.val( txt.val() + " " + v);
    sel.selectedIndex = null;
}
$(function(){
    $("#email-history")
        .load(window.rootUrl + "/admin-email/history-rows?_h_wrap=1",
            function(){ $("#email-history .grid-wrap").ngrid(); });
            
    var editor = null;
    $("input[name='format']").change(function()
    {
        if (!this.checked) return;
        if (this.value == 'html')
        {
            if (!editor) {
                editor = initCkeditor('body-0', { placeholder_items: [
                    ['%user.name%'],
                    ['%user.email%'],
                    ['%user.login%'],
                    
                    ['%user.street%'],
                    ['%user.city%'],
                    ['%user.state%'],
                    ['%user.zip%'],
                    ['%user.country%'],
                ]});
            }
        } else {
            if (editor) {
                editor.destroy();
                editor = null;
            }
        }
    }).change();

});
    function loadBrowseUsers()
    {
        var vars = $("#am-form-email").serializeArray();
        $("#browse-users").empty().dialog({
            modal: true,
            bgiframe: true,
            autoOpen: true,
            height: 500,
            width: 730,
            draggable: true,
            resizeable: true,
            title: "<?php j(___('Browse Found Users'))?>",
        }).load(window.rootUrl + "/admin-email/browse-users", vars, function(){
            $("#browse-users").ngrid();
        });
    }
</script>
