<?php 
    $scriptId = "am-video-" . filterId($this->id); 
    $divId = "div-".$scriptId;
    $flowPlayerJs = ROOT_URL . "/application/default/themes/getaudiofromvideo/public/js/flowplayer/flowplayer.js";
    $flowPlayerSwf = ROOT_URL . "/application/default/themes/getaudiofromvideo/public/js/flowplayer/flowplayer.swf";
?>
<?php if (!empty($video)) : // user has access to video ?>
jQuery(document).ready(function($) {
    var runVideo = function()
    {
        var $a = $("<a id='<?php p($divId)?>'></a>");
        $a.attr("href","<?php p($video);?>");
        $a.css({
            width : '<?php p($width)?>',
            height : '<?php p($height)?>',
            display: 'block',
        });
        $("script#<?php echo $scriptId?>").after($a);
        flowplayer('<?php p($divId)?>', '<?php p($flowPlayerSwf)?>', <?php echo(empty($flowPlayerParams) ? '{}' : json_encode($flowPlayerParams)) ?>);
    }
    // if !flowplayer loaded, load it in async mode
    if (typeof flowplayer == 'function')
    {
        runVideo();
    } else {
        jQuery.getScript('<?php p($flowPlayerJs)?>', runVideo);
    }
});
<?php else: // no video ?>
jQuery(document).ready(function($) {
    var $a = $("<a id='<?php p($divId)?>'></a>");
    $a.attr("href","<?php p($link);?>");
    $a.css({
        width : '<?php p($width)?>',
        height : '<?php p($height)?>',
        display: 'block',
        'background-color' : '#aaa'
    });
    $a.text('<?php p($error)?>');
    $("script#<?php echo $scriptId?>").after($a);
});
<?php endif; ?>