<?php
$title = ___("Processing your Transaction");
$this->setLayout('layout.phtml');
?>
<br />
<div >
<form id="payment-system-redirect" method="post" action="<?php echo $this->escape($url); ?>" target="_top">
<noscript>
<h2><?php __e('Click button to continue') ?></h2>
</noscript>
<input type="submit" value="<?php __e('Continue')?>" />
    <?php if (!empty($vars)) echo Am_Controller::renderArrayAsInputHiddens($vars); ?>
</form>
<script>
    document.getElementById('payment-system-redirect').submit();
</script>
</div>