<div class="cart-product">
<div class="title">
   <a href="<?php p($this->pUrl(null, 'product', null, 'id', $product->pk())) ?>"><?php echo $product->title ?></a>
   <span class="terms">
   <?php 
   $plans = $product->getBillingOptions();
   if (count($plans)==1) echo current($plans);
   else
   echo "<select class='billing-plan-select' name='plan[{$product->product_id}]' size='1'>\n"
       . Am_Controller::renderOptions($plans, $product->default_billing_plan_id) 
       . "</select>\n";
   ?> 
   
   
   </span>
</div>
<div class="description"><?php echo $product->getDescription(); ?></div>
<input type="button" name="add" value="<?php __e('Add to Basket')?>" onclick="cart.add(<?php echo $product->product_id; ?>, 1)">
<input type="button" name="order" value="<?php __e('Quick Order')?>" onclick="cart.addAndCheckout(<?php echo $product->product_id; ?>); ">

<?php if (!empty($displayProductDetails)): // if called from the product page ?>

<?php endif ?>
</div>