<?php

if (!defined('INCLUDED_AMEMBER_CONFIG')) 
    die("Direct access to this location is not allowed");
 
$notebook_page = 'Authorize.Net SIM';
config_set_notebook_comment($notebook_page, 'Authorize.Net configuration');
if (file_exists($rm = dirname(__FILE__)."/readme.txt"))
    config_set_readme($notebook_page, $rm);

add_config_field('payment.authorize.login', 'Authorize.Net API Login',
    'text', "The API login is different from your Authorize.net username.<br />
    You can get at the same time as the Transaction Key",
    $notebook_page, 
    '');
add_config_field('payment.authorize.tkey', 'Transaction Key',
    'text', 
    "The transaction key is generated by the system <br />
    and can be obtained from Merchant Interface. <br />
    To obtain the transaction key from the Merchant <br />
    Interface<br />
1. Log into the Merchant Interface<br />
2. Select Settings from the Main Menu<br />
3. Click on Obtain Transaction Key in the Security section<br />
4. Type in the answer to the secret question configured on setup<br />
5. Click Submit<br />",
    $notebook_page, 
    '');
add_config_field('payment.authorize.secret', 'Secret Word',
    'text', "From authorize.net MD5 Hash menu. You have to create secret word",
    $notebook_page, 
    '','',''
    ); 
add_config_field('payment.authorize.testing', 'Test Mode Enabled',
    'select', "set to No after you complete testing",
    $notebook_page, 
    '','','',
    array('options' => array(0 => 'No', 1 => 'Yes')));
add_config_field('payment.authorize.title', 'Payment Method Title',
    'text', "displayed on signup page and on renewal page",
    $notebook_page, 
    '', '', '',
    array('default' => 'Authorize.Net Web Payment'));
add_config_field('payment.authorize.description', 'Payment Method Description',
    'text', "displayed on signup page",
    $notebook_page, 
    '', '', '',
    array('default' => 'Credit card payment'));
?>
